### ISSUE TITLE
Entity Visualization bugs

### ISSUE THREAD

**Issue by jpasila** [GetDKAN/dkan#1003]
See: CIVIC-1252
## Description

While QAing a client site release I came across 2 bugs related to Entity Visualizations. The first bug breaks the entity preview while creating a new chart. The second bug displays charts incorrectly when embedded in a datastory. 
## Steps to Reproduce

Navigate to the Add Chart page. Structure/Entity Types/Visualizations/chart/add chart
Give the chart a Title, Description, and load in the Madison Polling Places CSV. 
When defining variables set the Series to "Ward" and X-field to "Aldermanic District"
Pick this chart type
!broken_vis_preview_chart_select.jpg|thumbnail!
 The Chart should properly preview at first like so
!broken_vis_preview_working_temp.jpg|thumbnail!
 If you check any of the side options like "Show title" the preview will break and you will only see a blank white space. Once you create the chart by hitting the "Finish" button the visualization will display properly.

!Broken_Vis_display.jpg|thumbnail!
Go to Content/add content/news 
Fill in the Title, paste the chart embed link in the "Body" field. Click Save. 
You should now see a broken chart display

**Comment by janette** [comment]
@jpasila can you fix the screenshots so we can see what you are trying to do and the errors you are seeing.

The polling places data is not a good candidate for a chart as it does not have numerical data, can you use the gold pricing data instead?

**Comment by kimwdavidson** [comment]
Closing for lack of info. Can reopen later.
