### ISSUE TITLE
Site not properly rendering on initial load - Site not properly rendering on initial load

### ISSUE THREAD

**Issue by jpasila** [GetDKAN/dkan#1006]
See: NCS-26
## Description

 Site not properly rendering on initial load Upon initial display the main page of the site does not properly render, it is missing some graphics.

Marked as high as client is reporting site loading issues. 
## Instructions to reproduce

This has happened periodically during development and is difficult to reproduce. It seems to be happening again. Please note that typically, and at the time of logging this, the problem (see images A and B) is most prevalent when accessing the site through the proxy, but the page for the most part properly renders when directly accessing the site via http://live. though as shown in the attached C image the home icon is missing.

**Comment by dafeder** [comment]
There seem to be a couple different bugs going on here, and the site is on a fairly old codebase. Let's table this until it's been tested on a current version of DKAN.
