### ISSUE TITLE
DKAN Times Out When Installing on Pantheon

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#1081]
I get the following when installing DKAN on Pantheon at the last step:

<img width="795" alt="screen shot 2016-04-20 at 10 58 28 pm" src="https://cloud.githubusercontent.com/assets/512243/14712530/1810339e-07a3-11e6-8995-a97cf26d5746.png">

I'm not sure what could be done about this other than breaking up the final install into more discreet steps. It would be not to time consuming to test this. I create a ticket on Pantheon to ask for guidance: https://dashboard.pantheon.io/users/e92fe87e-f95d-4853-b66d-11cee3514864#support/ticket/60142

Another step could be to supply a default database like some other profiles do. This would make the pantheon installation a lot quicker as well as make it faster for our internal systems as well.  

The installation is successful after that step. So at the least I think this should get documented as an expected behavior: http://docs.getdkan.com/dkan-documentation/get-dkan/dkan-pantheon

**Comment by acouch** [comment]
A response from Pantheon:

> The operations seems to be arranged properly, but the memory expense of particular operations may be the issue. I would say that it should certainly be broken up as there are several cache flush operations happening within the dkan_additional_setup.

**Comment by SalahMessaoud** [comment]
@acouch I clicked on the link **the error page** and it took me here:

![selection_474](https://cloud.githubusercontent.com/assets/1775858/14716529/625a3566-07e5-11e6-8718-21ae0ea05cd8.png)

after that the installation is successful.

**Comment by dafeder** [comment]
I've updated the docs. The "DKAN final setup tasks" are already fairly broken up but I'll see if we can go further.

**Comment by kimwdavidson** [comment]
Seems to be working now. Closing.
