### ISSUE TITLE
Need DB clean up when visualization bundles are 'uninstalled'

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#1117]
## Description

 If you enable visualization_entity_choropleth_bundle, visualization_entity_geojson_bundle, and/or geo_file_entity_geojson_bundle, then disable and uninstall, the bundle information is left in the database.
## Steps to Reproduce
1. Enable: visualization_entity_choropleth_bundle, visualization_entity_geojson_bundle, and geo_file_entity_geojson_bundle
2. Optional: create a visualization of each type
3. Disable the modules
4. Uninstall the modules
5. View the database, you will see the bundle information is still in the following tables:
- eck_bundle
- eck_entity_type
- eck_geo_file
- eck_visualization
- field_config
- field_config_instance
- field_data_field_color_scale / field_revision_field_color_scale
- field_data_field_file / field_revision_field_file
- field_data_field_geojson / field_revision_field_geojson
- field_data_field_name_attribute / field_revision_field_name_attribute
- field_data_field_uuid_resource / field_revision_field_uuid_resource
- field_data_field_ve_geojson_key / field_revision_field_ve_geojson_key
- field_data_field_ve_geojson_label / field_revision_field_ve_geojson_label
- field_data_field_ve_map_column / field_revision_field_ve_map_column
- file_managed
- file_usage
## Acceptance Criteria

 When visualization entity modules are uninstalled, the corresponding content is removed from the database.
## Documentation Updates

N/A

**Comment by janette** [comment]
```

  if (!module_exists('visualization_entity_choropleth_bundle')) {
    // Remove choropleth bundle.
    db_delete('eck_bundle')
      ->condition('name', 'choropleth_visualization')
      ->execute();
    // Remove choropleth links.
    $query = db_select('menu_links', 'm');
    $query->fields('m', array('mlid'));
    $query->condition('link_path', '%' . db_like('choropleth') . '%', 'LIKE');
    $result = $query->execute();
    if ($result) {
      foreach ($result as $value) {
        db_delete('menu_links')
          ->condition('mlid', $value->mlid)
          ->execute();
        $messages[] = $value->mlid . ' choropleth link deleted';
      }
    }
  }

  if (!module_exists('visualization_entity_geojson_bundle')) {
    // Remove choropleth bundle.
    db_delete('eck_bundle')
      ->condition('name', 'geojson_visualization')
      ->execute();
    // Remove choropleth links.
    $query = db_select('menu_links', 'm');
    $query->fields('m', array('mlid'));
    $query->condition('link_path', '%' . db_like('geojson_visualization') . '%', 'LIKE');
    $result = $query->execute();
    if ($result) {
      foreach ($result as $value) {
        db_delete('menu_links')
          ->condition('mlid', $value->mlid)
          ->execute();
        $messages[] = $value->mlid . ' geojson link deleted';
      }
    }
  }

  if (!module_exists('geo_file_entity')) {
    // Remove geo_file residuals.
    db_delete('eck_bundle')
      ->condition('name', 'geojson')
      ->execute();
    db_delete('eck_entity_type')
      ->condition('name', 'geo_file')
      ->execute();
    db_drop_table('eck_geo_file');
    db_drop_table('field_data_field_ve_geojson_key');
    db_drop_table('field_data_field_ve_geojson_value');
    db_drop_table('field_revision_field_ve_geojson_key');
    db_drop_table('field_revision_field_ve_geojson_value');
    // Remove geo_file links.
    $query = db_select('menu_links', 'm');
    $query->fields('m', array('mlid'));
    $query->condition('link_path', '%' . db_like('geo_file') . '%', 'LIKE');
    $result = $query->execute();
    if ($result) {
      foreach ($result as $value) {
        db_delete('menu_links')
          ->condition('mlid', $value->mlid)
          ->execute();
        $messages[] = $value->mlid . ' geo_file link deleted';
      }
    }
  }
```

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
