### ISSUE TITLE
author DCAT field v filter by author

### ISSUE THREAD

**Issue by pmackay** [GetDKAN/dkan#113]
## Description

DKAN datasets currently have two different "author" fields. The first is Drupal's standard "authored by" field, which refers to the Drupal user who entered the information. The second is the "author" field specified by DCAT.

Having two fields with such similar names is inherently confusing and has been noted as an issue on multiple DKAN websites. In particular, it is confusing that the faceted search block on the dataset listing page filters by the Drupal "authored by" field, while 

We should use Drupal's stringoverrides module or some other approach to rename Drupal's standard "authored by" field to "entered by." We should also use a faceted search block on the dataset listing page that filters by the DKAT author field, not the Drupal user field.
## Steps to Reproduce
- Visit the datasets listing page on this test instance of DKAN: http://dev-dkan1-10.getnucivic.com/dataset
- You can see that the faceted search to "Filter by author" shows the names of the site's two Drupal users: "admin" and "Jane Editor": ![image](https://cloud.githubusercontent.com/assets/2838758/12765091/846e41e4-c9c2-11e5-863d-1f6bda1d027b.png)
- If you filter by author "Jane Editor," the search results will be filtered to the single dataset named "Test" that was created by Jane Editor. If you click to view that dataset, you will see that the "Dataset info" table displays "William Faulkner" as the author, and "Jane Editor" is not displayed anywhere on the page.
## Acceptance Criteria
- [ ] The faceted search box for authors should let users filter by field_author (the DCAT field), not by the Drupal "authored by" field.
- [ ] Editors who have access to see the "authored by" field should see a field label of "entered by," not "authored by."
## Ticket Reference

NCS-52

**Comment by sheldonrampton** [comment]
This issue was originally reported by Paul Mackay as follows:

> Should the "filter by author" facet on /dataset list filter on the DCAT author field,  rather than the Drupal user? What if the DCAT author is an organisation, but several people in that organisation are responsible for uploading datasets?

**Comment by dafeder** [comment]
This still seems worth doing. I'm not sure EITHER author field is really helpful on the search page. Agree that at minimum we should override the Drupal form. Interested in feedback from other adopters/users on usefulness of having the DCAT author field available as a facet.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
