### ISSUE TITLE
Cannot remove user from Groups from the profile page (UX fix)

### ISSUE THREAD

**Issue by mcdougs** [GetDKAN/dkan#1133]
## Description

As a Site Manager, I should be able to remove a user from a Group from the user profile page. Currently, users with the correct permissions can add a user to Groups from the profile page, but they cannot remove users from Groups. 

![screen shot 2016-05-17 at 2 17 55 pm](https://cloud.githubusercontent.com/assets/12161118/15334305/a1cf9a8c-1c3b-11e6-8c52-de9c4d220282.png)

A Site Manager must go to the specific Group, click the _Group_ button then the _People_ menu item to manage users. 
## Steps to Reproduce
1. Build or access existing demo site built with 7.x.1.x parameters
2. Create or login as site manager user. 
3. Access a user through the _People_ menu item and select a profile to edit. 
4. Click the _Edit_ button and scroll towards the end of the form to find the Groups section. 
5. Add an existing Group through the _Other groups_ UI and click the _Save_ button.  
6. Access the same user and attempt to remove the Group. 
## Acceptance Criteria
- [ ] Using the same UI, a Site Manager can both add and remove Groups from a user's profile directly from the user's profile page. 
## Test Updates

Unknown 
## Documentation Updates

Unknown
## NCS

CIVIC-2549

**Comment by janette** [comment]
A site manager is able to remove a group association from a user by command/control clicking the name of the group on the user profile page, however, if you are trying to ADD a user to a group, it only puts the user into a *pending* status. The site manager would need to go to the `group/node/[nid]/admin/people` page to update that user to **Active**

**Comment by kimwdavidson** [comment]
closing.
