### ISSUE TITLE
BACnet coordination

### ISSUE THREAD

**Issue by dbt102** [GetDKAN/dkan#1161]
Wanted to make note of this issue --> https://www.drupal.org/node/2345121#comment-11240321

to minimize duplication of efforts

**Comment by dbt102** [comment]
[The BACnet Interest Group - Drupal](http://www.bg-drupal.org) is also a good reference.

**Comment by dafeder** [comment]
Hi @dbt102! Interesting project. Do you have any specific proposals? If you're still investigating charting alternatives, I would recommend checking out our [React Dashboard](https://github.com/NuCivic/react-dashboard) project, which is a pure JS library for building charting applications with a minimal amount of coding (most development can be done in a simple JSON configuration object).

**Comment by kimwdavidson** [comment]
Hey @dbt102! Sorry for the delay here - we're combing through some older issues today. We think this is really interesting, and if you want to talk to us more about it, you should join our Slack instance at dkan.slack.com. @nerdstein would also be happy to chat with you about this - he was just looking into it himself! Thanks for sending this in.

- Kim
