### ISSUE TITLE
Datastore doesn't properly check UTF-8 characters in the header row

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#117]
Here is an example:

```
Pound in header! £,Organisation,Unit
Department for £,Environment Agency, £ in body
```

**Comment by dafeder** [comment]
todo: check to see if still an issue

**Comment by janette** [comment]
Yes, this is still an issue, and not just the header row.

`DKAN DATASTORE: There was a problem while importing the Resource - SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF1a' for column 'campo_2' at row 2`
[test.csv.zip](https://github.com/GetDKAN/dkan/files/3121638/test.csv.zip)

**Comment by jjalcolea** [comment]
Hi, any plans on fixing this any soon?
Thanks!

**Comment by erogray** [comment]
Closing this one in favor of https://github.com/GetDKAN/dkan/issues/2276
