### ISSUE TITLE
Undefined index: und in dkan_topics_views_pre_render() 

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#1213]
Getting a notice of `Undefined index: und in dkan_topics_views_pre_render() (line 113 of /modules/dkan/dkan_topics/dkan_topics.module`

``` php
if($row->_field_data['tid']['entity']->field_icon_type['und'][0]['value'] == 'font') {
```

The `$view->language` is maybe more reliably substituted for the language `'und'` and would fix the issue.

**Comment by kimwdavidson** [comment]
No longer seems to be an issue.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
