### ISSUE TITLE
Create notice for users that have default content enabled

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#1264]
The new default content is so awesome that it might confuse people about the purpose or context of the default content.

I think adding a message while the default content module is on would help make that more clear while not interfering with the default content. It could also encourage site users to turn off (thus removing) the default content when they start adding data and stories.

Something along the lines of:

``You are viewing DKAN with DKAN's default content. To remove the default content ask your administrator or turn it off here: (link to help instructions)."

**Comment by dafeder** [comment]
@acouch we were talking about the same thing. We'll come up with a proposal for this.
