### ISSUE TITLE
Viz entity can't use data with dollar signs ($) in Charts - can't make economic visualizations

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#1266]
As a site user with permission to create Charts, I want to view my economic data as a Chart.

Here is my data, containing dollar signs in four columns:

![screenshot 2016-07-19 21 01 20](https://cloud.githubusercontent.com/assets/9059428/16971711/012f6c5c-4df4-11e6-997e-8f78cc7864dc.png)

Unfortunately, the fact that the data contains dollar signs means that it cannot load properly in Charts. Charts cannot handle economic data.

![screenshot 2016-07-19 20 58 38](https://cloud.githubusercontent.com/assets/9059428/16971664/b050a576-4df3-11e6-8a5d-7c1f1462ced7.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
