### ISSUE TITLE
Resources with no group membership

### ISSUE THREAD

**Issue by SmallhillCZ** [GetDKAN/dkan#1267]
New groups membership management for resources causes problems with resources that were in catalog before upgrade - they are not in any group, therefore not editable by group members (if permissions set that way). And groups can't be set on a resource anymore.

Quick fix: Add the resource to a new parent dataset, it will force the resource to copy grou membership from dataset.

It would be good to have an option to reset resources' group memberships to those of datasets automatically for all resources.

DKAN Version 7.x-1.12

**Comment by dafeder** [comment]
Hi @SmallhillCZ - just wanted to let you know we'll be taking a look at this

**Comment by kimwdavidson** [comment]
Need to determine if this is still an issue

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
