### ISSUE TITLE
Range pagination Recline

### ISSUE THREAD

**Issue by samuburgueno** [GetDKAN/dkan#1335]
Hi! I cant change the range of de pagination to public user access. The limit es 100 but when the user was logged with administrator user has not limit. Whats is the permission to change this?

**Comment by dafeder** [comment]
@samuburgueno I don't know what you're referring to. The pagination on what?

**Comment by samuburgueno** [comment]
I'm Sorry, the pagination on a resource, for example on "Map" tab, you can see the paginator, but is you do not sign in with administrator role, then you can not see more than 100 registries.
Sorry for my english! :/

**Comment by mgottholsen** [comment]
Here is an [example](https://data.louisvilleky.gov/dataset/building-code-permit-enforcement-cases/resource/0c6c0037-50f9-4452-a855-2ba1965ad95a#{view-graph:{graphOptions:{hooks:{processOffset:{},bindEvents:{}}}},graphOptions:{hooks:{processOffset:{},bindEvents:{}}}}) of what I think @samuburgueno is talking about.

Just to hijack this issue a little, the pagination for the dataset preview in Recline, specifically the grid preview, caps items to 100. This isn't so much a problem in the grid view (although I think @samuburgueno would like to have the ability to customize that), but it's definitely a problem in the Leaflet.js view, as it's not immediately apparent that the points mapped are connected to pagination. I think it causes some confusion with end users, expecting more data to be presented. What may be a good solution is to use the Leaflet cluster plugin in conjunction to customization of the pagination amount.

**Comment by samuburgueno** [comment]
Thanks @mgottholsen! 

Your explanation is correct!

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
