### ISSUE TITLE
Dataset REST API performance issues

### ISSUE THREAD

**Issue by jakubklimek** [GetDKAN/dkan#1346]
Trying to load 50K datasets, some of which have up to 20K distributions is something that takes up to a week (or more) using the current Dataset REST API implementation. It takes 1 request per resource (distribution) and 1 request per dataset, each request results in the target URL to be resolved.

This is in contrast to the CKAN API, where it is just 1 request per dataset, including all resources (distributions) and no target file resolving. Using CKAN API, I can catalog this amout of datasets and resources in 8,5 hours.

This is related to https://github.com/NuCivic/dkan/issues/132, https://github.com/NuCivic/dkan/issues/1314, https://github.com/NuCivic/dkan/issues/1313 and https://github.com/NuCivic/dkan/issues/310 - I think this would qualify as a demand for the writable CKAN API

**Comment by dafeder** [comment]
@jakubklimek we could try to tweak the existing REST API to accept multiple node objects in a single request; that should be a much lighter lift than writing a completely new CRUD API to mimic CKAN's. However, I suspect that unfortunately the bottleneck is the entity write process in Drupal not the number of requests required; IE there's only so much optimization that can be done on the API level if Drupal takes a certain amount of time to save a node. CKAN has less going on in the metadata writing process and will probably always be faster. It's worth a shot though, and you might want to think about migrating loading these datasets using our harvester when that ships with DKAN 1.13

**Comment by dafeder** [comment]
BTW what is the connection between this and #1314?

**Comment by dafeder** [comment]
Sneak peak at that: https://github.com/NuCivic/dkan_harvest/tree/harvest_dkan_integration

**Comment by jakubklimek** [comment]
@dafeder The connection to #1314 is that I suspect that the biggest portion of time processing the request is actually spent trying to access the URL of the resource (therefore dependent on the server hosting the resource), which I think should not happen at all, or at least be optional.

**Comment by marciuz** [comment]
Me too I'm interested in this issue.
I'm working for a big national portal and the file download is not necessary the best option. Probably can be useful to have an optional behaviour, like the @jakubklimek  suggestion.

@dafeder what is the position of NuCivic about this? 
Are you already working on this? 
If I can improve this option are you interested about a co-planning and in the adoption?

**Comment by dafeder** [comment]
@marciuz yes we want to solve this issue but are only focused on critical bugs as we prepare for our next point release. It will be a few weeks before we can focus on this but it's definitely something we could fix in either a patch release on in the following point release. I would love to connect about collaborating though. Let's connect over email.

**Comment by dafeder** [comment]
The real challenge here I believe is that the remote file field is expecting a file object to get basic metadata like filesize and mimetype. I can see the benefit of skipping this optionally, but it will require a bit of hacking. We are having issues with the same code recognizing file types correctly and would probably address both these issues in the same round of work. Keeping this open.

**Comment by kimwdavidson** [comment]
Improvements were made in 1.15.3 that might improve this. @marciuz and @jakubklimek could you give it a try and reopen this if you're still experiencing these issues?
