### ISSUE TITLE
Write tests for visualization entity

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#137]
Tests should provide coverage for:

* Creating a chart with a resource
* Creating a chart with a remote file
* Creating a chart with a google spreadsheet
* Basic edit and delete functions on an entity

Main thing that needs testing is the creation form/workflow.

**Comment by dafeder** [comment]
Description updated. We have some basic tests in place but not testing the form: https://github.com/NuCivic/dkan/blob/7.x-1.x/test/features/vis_entity_embeds.feature.disabled

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
