### ISSUE TITLE
Blank page install last DKAN

### ISSUE THREAD

**Issue by datammdecin** [GetDKAN/dkan#1428]
Hello,
i want install last distro DKAN, but on  my hosting is blank page when i started install. I don´t know what is? PHP is (5.3, 5.4, 5.5, 7.0 (error)). Can you help me? Any idea?

http://datadecin.savana-hosting.cz

thank you very much

Martin

**Comment by janette** [comment]
Hi Martin, could you review the installation and requirements documentation:  http://dkan.readthedocs.io/en/latest/introduction/installation.html . We will need more details of any errors and hosting environment set up in order to help you.
