### ISSUE TITLE
"New harvest source" don't create a new migrate 

### ISSUE THREAD

**Issue by marciuz** [GetDKAN/dkan#1540]
I'm using the harvester from drush and normally I create via interface the new record in the harvester and I use the drush migrate commands (not the dkan-h* commands, because I need to use the --limit, --feedback and other flags).

When a new record is created in the harvester, the migration doens't exists yet.
In order to create the migration is necessary to open other pages, for example the "node/%node/harvest-events" page.

With a backtrace of the function, is possibile to see where the migration is created : 

dkan_harvest/includes/HarvestSource.php:378

` // Register the migration if it does not exist yet or
    // update the arguments if not.
    HarvestMigration::registerMigration(
      $this->type->migrationClass,
      $harvest_migration_machineName,
      $arguments
    );`

Probably this code or something similar should be launched also in the node_insert hook.

For example: in dkan_harvest.module 

```
/**
 * Implements hook_node_insert().
 */
function dkan_harvest_node_insert($node) {
  if($node->type == 'harvest_source') {
    $harvest_source = HarvestSource::getHarvestSourceFromNode($node);
    dkan_harvest_get_migration($harvest_source);
  }
}
```

**Comment by dafeder** [comment]
Thanks @marciuz - we should probably let people pass the migrate parameters you've mentioned through our dkan-harvest drush commands. But for now we'll take a look at this PR. Can you explain your use case a little more, why you need those migrate options?

**Comment by marciuz** [comment]
Yes, I think is very important. The migrata process seems very slow and all the migrate tools (like limit) is really useful. 
About the issue, simply when you create a new harvest source from the interface, the harvester don't create the migrate job. This is created only with other actions. 

I created a pull request about this: https://github.com/NuCivic/dkan/pull/1542

**Comment by rhabbachi** [comment]
@marciuz Suppor for '--limit' migrate drush option is implemented in the latest 7.x-1.x.

**Comment by janette** [comment]
The PR was merged
