### ISSUE TITLE
Fix or remove /rss.xml

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#1613]
Drupal by default has an /rss.xml that we should remove for DKAN.

**Comment by sidburgess** [comment]
Interested in hearing why? RSS can be useful for getting notifications when changes, say on a Resource page, happen.

**Comment by mgottholsen** [comment]
It doesn't seem to have any articles in it, at least on the Louisville DKAN site...

![image](https://cloud.githubusercontent.com/assets/11966842/24357964/7a04c6c4-12cd-11e7-83bd-1fff2be802aa.png)

**Comment by acouch** [comment]
I asked for it to be removed because it is a Drupal default which we aren't using and aren't supporting.  RSS is still heavily used but isn't often mentioned in an Open Data context.

@mgottholsen did you just notice this or are folks asking for an RSS feed of yr content?

**Comment by mgottholsen** [comment]
I just noticed this. If anyone asks for a feed, I point them to the data.json

**Comment by dafeder** [comment]
Converting this to a discovery ticket for adding a default RSS feed to DKAN. Let's look at what other open data portals do for reference.

**Comment by susisiman** [comment]
Closed due to inactivity. Feel free to open!
