### ISSUE TITLE
User Story: provide map-based preview of additional geodata file types: KML, SHP, others

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#17]
> Posted by drkloc on April 4, 2014 at 5:33pm
> We have a couple of problems to pull this.
> 
> First, the shp file is tricky in many ways because it needs the .dbf file as well (http://en.wikipedia.org/wiki/Shapefile#Shapefile_attribute_format_.28.db...). There are two options to solve this:
> - Upload the shape file zipped with all the layer files in (like https://recursos-data.buenosaires.gob.ar/ckan2/parcelas/parcelas.zip). We need to inspect the zip file content for .shp and .dbf files
> - Upload two files in field_upload (shp and dbf).
> 
> Another issue that arises from this is that all the recline view functionality circles around getting data from something that relates an index (check out existing backends http://okfnlabs.org/recline/docs/tutorial-backends.html). Neither shapefiles or kml files are in principle that. We need the functionality provided by the recline field (just the file upload really) but none of the actual recline functionality (we just need a leaflet map, no need to initialise a recline multiview for this). I don't know if we are adding confusion if we aggregate this to the recline module.
> 
> Maybe we need to restructure things a little bit here. Initial thoughts are:
> 
> > Show the grid/map/graph checkboxes only if the upload is a csv file (or something that relates an index)
> > Show another set of checkboxes if the file is a zip file (with shp and dbf inside), kml file or another format that acts as a map layer we present a 'Leaflet Map' checkbox
> > We only initialise the recline multiview if one of the recline's checkboxes are selected
> > We only initialise a Leaflet Map if one if the Leaflet checkbox is checked
> > For this, we need a lot (A LOT) of validation on the drupal side and a lot of hide/show behaviour on the client side.

**Comment by dafeder** [comment]
We've done some additional research more recently; there is a bunch of tooling these days around transforming shapefiles to geojson, which could then obviously be visualized with existing tools. We'd still like to do this and are considering bumping up the priority...

**Comment by akuckartz** [comment]
.shp still is a proprietary ESRI-specific format. And ArcGIS is proprietary software.

**Comment by dafeder** [comment]
@akuckartz the shapefile specification is [relatively open](https://support.esri.com/en/white-paper/279), and there are fully FOSS tools for parsing and visualizing them that we can leverage. We are certainly not talking about creating any ArcGIS dependencies for DKAN. What are you advocating for here?

**Comment by dharizza** [comment]
Security updates and bug fixes only in the D7 version of DKAN. Closing.
