### ISSUE TITLE
When I change the Topics label menu lost the icons in the dropdown

### ISSUE THREAD

**Issue by oriole9g** [GetDKAN/dkan#1714]
How to reproduce:

1. Create a Topics list with Icon Type Image: Go to admin/structure/taxonomy/dkan_topics and attach some PNGs to topic items.
2. Edit the main menu label: Go to admin/structure/menu/manage/main-menu and change "Topics" menú label to "Test" and Save.
3. See that the dropdown menu works but the icons have disapeared.

**Comment by dafeder** [comment]
@oriole9g I can reproduce. Adding to our bug list.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
