### ISSUE TITLE
datastore_active property missing from resource descriptor

### ISSUE THREAD

**Issue by adufilie** [GetDKAN/dkan#181]
"resource" JSON objects do not report "datastore_active":true like CKAN does.
Because of this, I cannot determine when I can use the datastore API without trying it and possibly receiving an error.

Example DKAN resource with datastore active (datastore/search works):
This resource should have a property datastore_active=true, but it doesn't.
    http://demo.getdkan.com/api/3/action/resource_show?id=abc12ce0-e5ac-4f73-b11d-f9348d99f829
    http://demo.getdkan.com/api/action/datastore/search.json?resource_id=abc12ce0-e5ac-4f73-b11d-f9348d99f829&query=api/datastore/search

Example DKAN resource with datastore inactive (datastore/search does not work):
    http://demo.getdkan.com/api/3/action/resource_show?id=a6096244-5069-440f-bd2c-dd751266eca0
    http://demo.getdkan.com/api/action/datastore/search.json?resource_id=a6096244-5069-440f-bd2c-dd751266eca0

Example CKAN resource with datastore active (result shows datastore_active=true):
    http://demo.ckan.org/api/3/action/resource_show?id=c22a36e0-8ca5-42aa-ad15-505ff5ee2d90
    http://demo.ckan.org/api/3/action/datastore_search?resource_id=c22a36e0-8ca5-42aa-ad15-505ff5ee2d90

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
