### ISSUE TITLE
request for adding a "DKAN" header or <meta>

### ISSUE THREAD

**Issue by seralf** [GetDKAN/dkan#1850]
Hi

it could be helpful for future versions to have an HTTP header (or a meta tag) tracing the fact that portal is published used specifically. This could help detecting its usage, and promote/recognize it in the Open Data community.
I tried some experiments with Wappalyzer (SEE: https://github.com/AliasIO/Wappalyzer/issues/1422), but in my experience it is correctly handled as Drupal, but there is no way to understand externally that an instance of Druapl is actually running DKAN.

For example the header value for 
```X-Generator:Drupal 7 (http://drupal.org)```
and the tag value for 
```<meta name="Generator" content="Drupal 7 (http://drupal.org)" />```
could contain information about DKAN itself.

Connects #33

**Comment by kimwdavidson** [comment]
@seralf, sorry for the delay in getting back to you! We have an outstanding task to add the metatags module and better address this generally. We'll prioritize this soon, but feel free to submit a pull request, as we agree this should be added to DKAN core. Thanks!

**Comment by susisiman** [comment]
To revisit

**Comment by kimwdavidson** [comment]
Because DKAN2 is now a module that can be served by any number of front end system, this would be difficult to apply consistently. May revisit in the future
