### ISSUE TITLE
request to give an option to download data in different formats.

### ISSUE THREAD

**Issue by kundanrock** [GetDKAN/dkan#1853]

**Comment by dafeder** [comment]
Not enough info. Please explain

**Comment by kundanrock** [comment]
Right now user can download data in only those they  have uploaded. There should be a facility to download data in multiple format e.g. json, csv, xmk, xls. Although i have implemented this functionality but i want the same with default dkan download.

**Comment by dafeder** [comment]
@kundanrock this is a pretty big feature request if I understand properly - you want to create exports from the Datastore in multiple formats and provide all on the fly. This is in our longterm roadmap but will require a significant refactor of the datastore to accomplish. Happy to review proposals or PRs in the meantime if you attempt yourself.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
