### ISSUE TITLE
Drush Install Does Not Work, Only Index Page Available

### ISSUE THREAD

**Issue by mohnjatthews** [GetDKAN/dkan#1861]
## Description
After installing DKAN-DROPS-7 using drush and navigating to 192.168.33.10 only the index page of DKAN is available. All other pages result in 404s.

## Steps To Reproduce
```
$ mkdir ~/dev/dkan-testing
$ cd !$
$ git clone --branch master https://github.com/nuams/dkan-drops-7.git .
$ vagrant init mohnjatthews/lamp
$ vim VagrantFile
	uncommented line 29
$ :wq
$ vagrant up
$ vagrant ssh
$ cd /vagrant
$ composer require drush/drush
$ vendor/bin/drush site-install dkan --db-url="mysql://root:rainbar@localhost/dkan"
	You are about to create a /vagrant/sites/default/settings.php file and CREATE the 'dkan' database. Do you want to continue? (y/n):
$ y
```

The vagrant box I'm using is just a standard LAMP stack I made myself. The exact steps used to create the VM [can be found here](https://vagrantcloud.com/mohnjatthews/boxes/lamp/versions/1.0.0).

Originally I thought that the issue may have something to do with cloning DKAN-DROPS-7 *before* building the vagrant machine, however switching things (running `vagrant up` before cloning the drop repo) around didn't fix the issue.

## Acceptance Criteria
Installing DKAN-DROPS-7 using drush results in no 404 errors.

**Comment by mohnjatthews** [comment]
Installing via the GUI works perfectly fine (while still running into the issues mentioned in #1840).

**Comment by dafeder** [comment]
Hi @mohnjatthews - can you confirm if you're still seeing this issue?

-dan

**Comment by poliveiraIPB** [comment]
I'm having the same problem after a clean installation using drush of DKAN 1.13.3.

Only index page is workin, ther other pages give errors of this type:

Not Found

The requested URL /dkan2017/about was not found on this server.

**Comment by janette** [comment]
sounds like a missing .htaccess file

**Comment by poliveiraIPB** [comment]
No, the htaccess file is on the directory.

**Comment by mohnjatthews** [comment]
@dafeder Unfortunately I am yes. I'm not sure if it does have anything to do with a .htaccess file. It may be that I set up my VM wrong. If I get some time this afternoon I'll try using Scotchbox (a tried and trusted vagrant box) and see if that works.

**Comment by poliveiraIPB** [comment]
With the htaccess file on the directory the error still occurs.

**Comment by mohnjatthews** [comment]
Just to check @poliveiraIPB, are you getting actual error messages or just 404s?

**Comment by poliveiraIPB** [comment]
No error messages.

The index page of DKAN is available. All other pages result in 404s.

**Comment by patjo82000** [comment]
I am having the same issue

**Comment by mohnjatthews** [comment]
Clean URLs is sometimes an issue with this. These are the steps I follow to turn them back on:

---

1\. SSH into the server.
2\. Run the following:

    sudo a2enmod rewrite
    sudo chmod 700 /etc/apache2/apache2.conf
    sudo vim /etc/apache2/apache2.conf

3\. Within `apache2.conf` find a section that looks simiar to this:

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require None
    </Directory>

Change it to this:

    <Directory /var/www/html>
		Options Indexes FollowSymLinks
		AllowOverride All
		Require all granted
	</Directory>

Exit the file.

4\. Run the following

    sudo chmod 600 /etc/apache2/apache2.conf
    sudo service apache2 restart

5\. Navigate to `/admin/config/search/clean-urls`
6\. Check **Enable clean URLs** and click **Save configuration**.
7\. You're done.

**Comment by dafeder** [comment]
Seems like all these are issues with turning on clean URLs, which is more of an environment issue than a bug in DKAN. See https://www.drupal.org/docs/7/configuring-clean-urls/enable-clean-urls if you're having trouble with this.
