### ISSUE TITLE
Dkan install on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by ryanvco34** [GetDKAN/dkan#1889]
I deploy the app from the UI. The install goes as expected (some 504 error warnings) but it successfully directs me to the home page. However, immediately when I enter the home page I get the DKAN logo, and typical interface, except for this huge error on every page: 
   
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).
Notice: Undefined offset: 1 in nuboot_radix_preprocess() (line 45 of /var/app/current/profiles/dkan/themes/nuboot_radix/includes/panel.inc).

#1770

**Comment by lamipaul** [comment]
Hi Ryan ! got the same problem here, did you find any solution yet ?

**Comment by janette** [comment]
Can you check your php configuration to see if the ctype extension is enabled?

**Comment by VolkerStolz** [comment]
Same issue here, @janette . How do I go about checking this?

**Comment by dafeder** [comment]
What version/repo are you deploying @VolkerStolz @lamipaul ?

**Comment by VolkerStolz** [comment]
https://github.com/nuams/dkan-drops-7.git / master

**Comment by janette** [comment]
@VolkerStolz try changing line 45 on profiles/dkan/themes/nuboot_radix/includes/panel.inc to
`if( $front[0]=='node' && is_numeric($front[1]) ) {`

**Comment by dafeder** [comment]
Hi @ryanvco34 @VolkerStolz - did you make any more progress on this?

**Comment by kimwdavidson** [comment]
We'll close this up. Let us know if you need more help here.

**Comment by ayushman2013** [comment]
Tried as mentioned by Janette "if( $front[0]=='node' && is_numeric($front[1]) ) {"
Still not working!

**Comment by janette** [comment]
@ayushman2013 are you using a page manager page for your front page?  Sounds like the function needs more logic to handle a front page that is not a node.

**Comment by gjackson12** [comment]
Bump. Any solution for this yet?

**Comment by eauc** [comment]
I suppressed the error by editing profiles/dkan/themes/nuboot_radix/includes/panel.inc:45

-  if ($front[0] == 'node' && ctype_digit($front[1])) {
+  if (count($front) > 1 && $front[0] == 'node' && ctype_digit($front[1])) {

Dirty but efficient ;)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
