### ISSUE TITLE
Dkan dataset/datastore API issues

### ISSUE THREAD

**Issue by XavierMoreau** [GetDKAN/dkan#1893]
Hello,

Im new to Drupal 7 and i have to set up DKAN data API module.
This is my configuration
- 7.53 Drupal core
- DB PostgreSQL 9.6
- Dkan dataset and datastore 7.x-1.x-dev

If i try to upload a file, i have this message : 
"Your file for this resource is not added to the datastore. Click "Manage Datastore" to import file into the datastore."

And in Manage Datastore : 
DKAN Datastore Link Importer: Status
No imported items.
The file type for this resource is not supported by the datastore. 

If i use an extrenal link to remote the exact same file, it works.
I tried with many files, always same issue.
I tried with a MySQL db, same issue.

Second Issue, how to get Recline View usable for remote files uloading part in the Add data part, i only get the form for upload local files.

May someone help me please ?  :)

**Comment by janette** [comment]
@XavierMoreau are you using the dkan distribution or are you trying to use the separate dkan_dataset and dkan_datastore modules in a regular drupal site? We have stopped development on the individual modules and consolidated the work into the distribution. 

If you are using the distribution, could you upgrade to the latest release, and confirm that the file you are uploading is a csv file.

**Comment by kimwdavidson** [comment]
@XavierMoreau, we're going to close this up. Let us know if you need any more help. Thanks!

**Comment by Cyntia182** [comment]
Hi @janette and @kimwdavidson 

I have a similar problem with the Datastore: "The file type for this resource is not supported by the datastore". I'm using the dkan-drops-7-master repository with Drupal 7.59, Ubuntu 18 64bits, Server version: Apache/2.4.29 (Ubuntu) and PHP 7.2.7

Do you have any suggestion?

Thank you in advance.

Cyntia.

**Comment by janette** [comment]
@Cyntia182 the datastore currently only supports importing .csv files, is your resource file a csv?

**Comment by Cyntia182** [comment]
@janette Yes, my resource is CSV.

**Comment by janette** [comment]
@Cyntia182 ok then my next question is have you upgraded the feeds module? If so you will need to restore the version that ships with dkan https://github.com/GetDKAN/dkan/blob/7.x-1.x/drupal-org.make#L103

**Comment by Cyntia182** [comment]
@janette I upgraded the feeds module to the version 7.x-2.0-beta4 but after that I downgraded it to 7.x-2.0-beta3 and the problem was the same. Now, I'm going to follow your suggestion.

Thank you!

**Comment by Cyntia182** [comment]
Hi @janette,

I have some questions… 

1) I’m working with dkan-drops-7-master repository with Drupal 7.59, but there is any problem if I restore the version that ships with dkan?  

2) I understand that is a different topic but I would like to ask if you knows if the Views TimelineJS integration (https://www.drupal.org/project/views_timelinejs) gets the information from the DKAN datasets? And if the integration has more visualizations or just charts? I would appreciate your help with this doubt.

Thank you in advance.
