### ISSUE TITLE
Table sort functionality for the grid preview of the file after importing into Datastore not working

### ISSUE THREAD

**Issue by cpatrone** [GetDKAN/dkan#1934]
Drupal 7.54
dkan-7.x-1.13.3

Description:
Having an item with a CSV file not imported into Datastore the grid preview of the file works as expected (you click in each column header and the data is sorted). But after importing into Datastore the items, then the sort functionality no longer functions and you receive a js error. See image for details:

![image_error](https://user-images.githubusercontent.com/10221083/26847953-2a523f68-4ad5-11e7-9741-db1e9545924d.png)

Steps to reproduce:
- Add new Resource (node/add/resource).
- In Upload section click Browse and select a CSV file with header values.
- Check Grid in Data Previews section.
- Check Embed.
- Fill in Title.
- Save
- Click in any header value and observe the sort functionality works as expected.
- Click "Manage Datastore" button.
- Click "Import" button.
- Check DKAN Datastore File: Status and observe the import was ok.
- Click "View" button.
- Observe the message "Your file for this resource has been added to the datastore." appears in the page.
- Click in any header value and observe the sort functionality now is not working. The "Loading" message remains in the page and the data is not sorted. See image for details:

![loading](https://user-images.githubusercontent.com/10221083/26848379-9cf8bb5e-4ad6-11e7-8fa8-2579e48ea941.png)

- If you inspect and check Console you will see a js error. See following image for details:

![js_error](https://user-images.githubusercontent.com/10221083/26848431-cd6db8b6-4ad6-11e7-8ea4-a7920388e63d.png)

Note: Tested in Chrome Version 59.0.3071.86 (Official Build) (64-bit) and Firefox 53.0.3 (64-bit).

Thanks,

**Comment by cpatrone** [comment]
Maybe this can help in the resolution of the bug.

After some time debugging I found datastore API call returns bad SQL query:

`http://massdocs.local/api/action/datastore/search.json?resource_id=a8a8453b-01ff-47a5-b054-e41b7ed2ae54&limit=100&offset=0&sort=Employer%20City%20asc`

This returns:

`{"sql":"SELECT t.*\nFROM \n{feeds_datastore_dkan_file_1084049} t\nORDER BY t.0 ASC\nLIMIT 100 OFFSET 0","error":{"message":"Caught exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't.0' in 'order clause'"}}`

Please observe image attached with the above:

<img width="1432" alt="screen shot 2017-07-26 at 13 25 09" src="https://user-images.githubusercontent.com/10221083/28643826-81c1c230-722d-11e7-9260-c4ff993a316f.png">

**Comment by dafeder** [comment]
Hi @cpatrone - sorry we never got back to you about this. We've been working on a new release but once it's out will get caught up on some outstanding bugs, including this one.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by datphamict** [comment]
Hi all,
I was installed Dkan 7.6 but still error sort. Please help me to fix it.

![image](https://user-images.githubusercontent.com/38518509/51424447-38cc4680-1c00-11e9-8410-8c386cd111ef.png)
