### ISSUE TITLE
Feature Request: Add 'sql' parameter option to DataStore API

### ISSUE THREAD

**Issue by schnuerle** [GetDKAN/dkan#1948]
Add a 'sql' or similarly named parameter to the DataStore API, to allow passing in a SQL query instead of a combination of parameters.

http://dkan.readthedocs.io/en/latest/apis/datastore-api.html#parameters

Suggestion to add more logic here:
https://github.com/NuCivic/dkan/blob/7.x-1.x/modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module#L568

Of course sanitizing the query would be paramount.  

Example in Carto: https://carto.com/docs/carto-engine/sql-api/making-calls
Example in Socrata: https://dev.socrata.com/docs/queries/
Example in CKAN: http://docs.ckan.org/en/latest/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_search_sql

[Edit from @dafeder]
Blocked by #2571

**Comment by dafeder** [comment]
We definitely want to do this. It is complicated however by the fact that DKAN currently stores datastore tables in the same DB as the rest of the CMS data which creates some real security concerns. Having an endpoint you can pass an arbitrary SQL string to obviously brings up a lot of issues. Requiring authentication will help but isolating it to a separate DB would be ideal.

**Comment by acouch** [comment]
We definitely want to do this and separating allowing for a separate datastore from the application database is a step in that direction. Closing for now until we get this on the near-term roadmap.

**Comment by schnuerle** [comment]
Could this be reopened now that the datastore is in a separate database?

**Comment by dafeder** [comment]
@schnuerle the datastore is not yet working from a separate DB. We've rearchitected the code in a way that makes that much more feasable, but that next step is not complete. Here is where that work is documented, and it is on our near-term roadmap: #2571

Building the SQL endpoint would be unblocked by that.

**Comment by fmizzell** [comment]
An SQL-like language is the main way to interact with stored data in 2.x.

Security updates and bug fixes only in the D7 version of DKAN. Closing.
