### ISSUE TITLE
Discovery: Establish a decoupled architecture between the standard DKAN dataset and custom fields

### ISSUE THREAD

**Issue by nerdstein** [GetDKAN/dkan#1954]
One common customization request is to add custom fields to a dataset. Many DKAN instances desire such a feature to decouple standard DKAN distribution features from specific customization needed for DKAN instances. These customizations may be one or more fields, e.g. a set of common metadata fields.

One approach could be to explore the use of paragraphs.

The datastore would have a new field linking to an unlimited number of attached paragraph instances. This allows for one or more paragraph bundles to be added to the data store.

Paragraph bundles would be used for a collection of custom fields. 

** Architectural Considerations **

1. Paragraph bundles would need to be exposed via the API with all of the open data standards in mind.

2. Paragraph bundles could be used for more cases outside of the bundles tied to the DKAN dataset. It might be worthwhile adding a checkbox/flag to classify a paragraph bundle for use in the DKAN dataset. This would mean the DKAN dataset field would restrict bundles in which that checkbox was set.

3. Update documentation on how to add custom fields and how to migrte any existing custom fields to the new architecture.

**Comment by nerdstein** [comment]
It may make sense to try this iteratively and work out the kinks.

**Comment by nerdstein** [comment]
Some existing DKAN customization may lead to API discrepancy with this approach.

I could see the implementation extending the API in a more automatic manner, in which there is an attribute for "custom fields" and each attached paragraph gets appended as nested attributes. 

For backwards compatibility, we would need to ensure there is a pre-render API that we can add the existing, customized attributes to preserve the old format in tact. This would allow for a mapping between the old API-based specification to the new paragraph data.

**Comment by dafeder** [comment]
Actually for public data APIs like data.json, as long as the values can be accessed via tokens, it shouldn't be a problem. It would be nice if the REST API for dataset CRUD didn't require a second request though to deal with the child entity. Maybe there is already a paragraphs-services integration that deals with this, or a best practice?

**Comment by nerdstein** [comment]
Can you elaborate? In your experience, how has DKAN been customized with respect to the APIs? In my opinion, if the APIs have been changed and paragraphs are implemented, the existing APIs would need to map to the new paragraph data structure for backwards compatibility.

**Comment by dafeder** [comment]
No, for the most part we just use the default Services REST server for nodes. SO maybe best to keep things standard and just address in documentation. I am assuming that no _existing_ fields would be moved into paragraph entities, just new and custom fields. So presumably we wouldn't break anything on that front. 

Another issue is the [Open Data Schema Map](https://github.com/NuCivic/open_data_schema_map) system where we map DKAN fields to arbitrary open data schemas like data.json, DCAT-AP and the public CKAN APIs. This is mostly outside of services and very custom - the mapping is done with Drupal tokens. So if the fields in paragraphs are accessible in a node context via tokens we can still support them if needed.

**Comment by acouch** [comment]
What advantage would paragraphs have over just using fields and features to export them? The field settings get a little tricky with field overrides but wouldn't creating a standardized and tested way of doing that be easier then adding another entity modeling and rendering engine?

Also important to note are the search facets with custom fields. Any solution should include those as well.

**Comment by nerdstein** [comment]
Paragraphs provides the structure and interface for consistent bundles of fields, where a user could select which bundle attaches to a dataset. The interface aspect is nice, because you can select which bundle(s) apply per dataset. Fixed field structures would not offer this.

I could see search facets being more challenging, as paragraphs are a separate entity outside of the dataset entity.

**Comment by nerdstein** [comment]
I also see this helping define a lot of best practices around customization. The only DKAN-sponsored functionality would be the dataset field linking to paragraphs. The paragraphs themselves all can be featurized and cleanly decoupled from DKAN proper. I could see this being useful for release management stability.

**Comment by acouch** [comment]
After discussing this briefly at the summit I still think the best approach is to add fields to DKAN Dataset and update the field form and display settings for the desired form and node settings. 

The reason we don't want to do this is that Features and Features Override doesn't handle this very well.  Adding a field is not a problem but editing the form or display or an existing field causes features that are hard to get out of an overridden state. I think we could solve this by looking more closely at Features and Features Override and determining exactly what configurations don't work well with those modules. If we started with a test module that attempts to override that dataset content type then we could pinpoint the way that these items break features.

Perhaps we could create a DKAN Overrides module that we use instead of Features Overrides that handles just the specific use cases. Use cases could include:

* Add new field to content type
* Change order of fields in content type form
* Change order of fields in display
* Edit existing DKAN field

Perhaps we could limit updates to a certain API we create that could be stored in ``config.yml``.

**Comment by kimwdavidson** [comment]
Current paragraphs work is covering this. Closing.
