### ISSUE TITLE
Fix syntax in dkan_dataset.module to support PHP 5.4

### ISSUE THREAD

**Issue by soonho2** [GetDKAN/dkan#1982]
When I install the DKAN in my server (Centos 6.9 and PHP 5.4.45 ), I got the following error:

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://dkan.bonnykoo.com/install.php?profile=dkan&locale=en&id=2&op=do StatusText: OK ResponseText: Fatal error: Can't use method return value in write context in /home/dkan/public_html/profiles/dkan/modules/dkan/dkan_dataset/dkan_dataset.module on line 1265

Could you kindly provide any tip to fix out? I roughly guess that it would link to the php version....

**Comment by dafeder** [comment]
Hi @soonho2 - looking. What version of DKAN did you install?

**Comment by dafeder** [comment]
Nevermind, I found it. Yes, it looks like some non-backward-compatible code snuck in there. If you can update to PHP 5.5 that would be the best, but will mark this for fixing as we should still support PHP 5.4.

**Comment by janette** [comment]
Fixed here https://github.com/GetDKAN/dkan/pull/2431
