### ISSUE TITLE
API to support automated notification of harvesting/data.json status

### ISSUE THREAD

**Issue by sheldonrampton** [GetDKAN/dkan#2008]
I have documented some incidents on Open Data websites powered by DKAN in which harvest sources do not get fully and correctly harvested via automated drush commands, or else the `drush odsm-filecache` command fails to correctly cache the data.json feed for the site, or else the site’s Solr search index does not get promptly updated following a harvest. When this happens, DKAN should support an automated notification so that developers can be made aware of the issue and can resolve it in a timely fashion.

On the Open Data sites that I manage, dataset harvests and data.json feed rebuilds are supposed to happen once nightly, so the automated checks only need to run once every 24 hours.

h2. Acceptance criteria
* All open data websites are checked nightly to confirm that their data harvests ran correctly.
* All open data websites are checked nightly to confirm that their data.json files are validating correctly according to the Project Open Data schema.
* All open data websites are checked nightly to confirm that their data.json files contain the correct number of datasets. On most websites, the "correct number" will be equal to the total number of published datasets. On one website that I manage, they have a customization that excludes datasets which they have harvested from state and local sources from their data.json feed, so the correct number should be calculated on that basis.
* All open data websites are checked nightly to confirm that their Solr search index is returning a correct number of datasets within 30 minutes after the harvest has completed. The "correct number" in this case should always be equal to the total number of published datasets.
* Whenever one of these conditions has failed within the past 24 hours and remains unfixed, the failure is reported via a "health check" API that returns the failure status in machine-readable form. For example, it might return a .json result such as the following:
`{"check_solr_index":{"status":"okay","message":"Dataset count: 3333 matches Search count: 3333."},"check_data_json_build":{"status":"failed","message":"The data.json cache has not been rebuilt in 27 hours."},"check_data_json_count":{"status":"failed","message":"The data.json cachefile reports 0 datasets, but the correct count is 3333."}}`

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
