### ISSUE TITLE
Harvester should use file format as resource title when no title is provided

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2027]
## User story
As a Site Manager, when I harvest data from a source that does not provide titles for resources/distributions, I should see the format of the file used as the title, rather than the URL, so that it is easier to read.

## Original Request

Datasets being harvested are being titled with relative link titles, which do not accurately reflect their content, request research into possible alternatives.

## Description

We think the client is referencing the behavior where if no title exists for a distribution in a data.json harvest, the url is used as the title in DKAN. We'd like to use the filename instead, or use the file type as the title if no file name can be isolated.

POD schema for distributions:
https://project-open-data.cio.gov/v1.1/schema/#distribution

## Steps to Reproduce

- create a resource with the attached data.json
- harvest using the resource download link
- review the resource titles

## Acceptance Criteria

- If a data.json distribution does not include a title, use the file name as the title
- If a title can't be determined use the file format as the title "{{file type}} File"

## Tests

We should add php unit tests to make sure all of this is happening correctly.

**Comment by kimwdavidson** [comment]
Blocked by PHP unit tests

**Comment by fmizzell** [comment]
The issues with the unit tests will be dealt in #2301
