### ISSUE TITLE
`drush dkan-hs` throws exception when harvest source content type is not visible to anon user

### ISSUE THREAD

**Issue by loziju** [GetDKAN/dkan#2030]
## Description
In this particular project, there is a need to prevent anon user from viewing harvest source nodes. By doing so, running `drush dkan-hs` returns error like below.

```
SJ:default sj$ drush dkan-hs
exception 'Exception' with message 'Harvest Source node with machine name <em class="placeholder">abc</em> not found.' in                  [error]
/Users/sj/docker/aaaportal/dkan/modules/dkan/dkan_harvest/includes/HarvestSource.php:67
Stack trace:
#0 /Users/sj/docker/aaaportal/dkan/modules/dkan/dkan_harvest/includes/HarvestSource.php(201): HarvestSource->__construct('abc')
#1 /Users/sj/docker/aaaportal/dkan/modules/dkan/dkan_harvest/dkan_harvest.module(486):
HarvestSource::getHarvestSourceFromNode(Object(stdClass))
#2 /Users/sj/docker/aaaportal/dkan/modules/dkan/dkan_harvest/dkan_harvest.drush.inc(225): dkan_harvest_sources_definition()
#3 [internal function]: dkan_harvest_drush_command_status()
#4 /Users/sj/.composer/vendor/drush/drush/includes/command.inc(422): call_user_func_array('dkan_harvest_dr...', Array)
#5 /Users/sj/.composer/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#6 [internal function]: drush_command()
#7 /Users/sj/.composer/vendor/drush/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#8 /Users/sj/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#9 /Users/sj/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#10 /Users/sj/.composer/vendor/drush/drush/drush.php(12): drush_main()
#11 {main}
```

The cause is that EntityFieldQuery does check user permission when executing the query. Read more:

-   https://www.drupal.org/node/2452993
-   https://www.drupal.org/docs/7/creating-custom-modules/howtos/how-to-use-entityfieldquery-for-drupal-7  --> search for "addMetaData"

## Steps to reproduce

1.  install dkan, any branch
2.  remove view harvest source node permission for anon user
3.  create harvest source, e.g. pods 1.1 pointing to http://demo.getdkan.com/data.json
4.  run `drush dkan-hs`

## Possible solutions

1.  Add the user context when running drush: `drush --user=1 dkan-hs`.
2.  Improve `HarvestSource::__construct()` to recognise that function is called from CLI. Reading the code, I don't see there's any other way before this function to prevent the anon user context from happening.

## Next steps

1.  Update documentation on `drush dkan-hs` either in the online documentation or in drush command help to include `--user=1` option, i.e. `drush dkan-hs --user=1`
2.  Update `HarvestSource::__construct()` to detect CLI call. Will submit pull request for this.

**Comment by susisiman** [comment]
Closed due to inactivity. Feel free to open!
