### ISSUE TITLE
Change MyISAM tables to InnoDB for datastore

### ISSUE THREAD

**Issue by sheldonrampton** [GetDKAN/dkan#2042]
DKAN currently uses MyISAM rather than InnoDB when creating datastore tables. This can create some performance issues including slow database cloning between environment on Acquia-hosted websites. The original decision to use MyISAM was motivated by a desire to enable full-text searches of datastore content, but InnoDB supports full-text search in MySQL 5.5 and later, so we should use InnoDB for datastore tables.

A MySQL query for converting MyISAM to InnoDB can be found here:

https://dba.stackexchange.com/questions/50028/mysql-command-querying-all-myisam-database/50030#50030

**Acceptance criteria**

* When DKAN creates a new datastore table, that table should be an InnoDB table.
* When upgrading from earlier releases of DKAN, this fix should include a hook_update function that converts any existing MyISAM tables to InnoDB.

**Comment by kimwdavidson** [comment]
Need to decide if we want to do the second acceptance criteria. Or if we just provide documentation for people who want to do this manually.

**Comment by erogray** [comment]
We tested with one client who had a lot of datastore tables and it didn't cause significant improvement; closing this as a won't do.
