### ISSUE TITLE
Move 'Install DKAN on Pantheon' to docs

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2043]
move this to docs: http://getdkan.com/pantheon/ and update/reference here: http://docs.getdkan.com/en/latest/introduction/get-dkan.html#pantheon

cc @stefaniefgray

**Comment by stefaniefgray** [comment]
Created new Pantheon.md page from the getdkan.com/pantheon site and removed Granicus reference from the get-dkan.html#pantheon page 

Not sure what else to update re: Pantheon on the new ReadTheDocs, though. Will have to return to this ticket to compare Pantheon notes and ensure everything is up-to-date.

**Comment by janette** [comment]
Existing documentation is here http://dkan.readthedocs.io/en/latest/introduction/get-dkan.html
