### ISSUE TITLE
Move 'DKAN sites' to docs

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2044]
- [x] Create a 'Sites' page in docs
- [x] Copy this markdown to the page: https://github.com/NuCivic/dkan-sites/blob/master/README.md
- [x] Update intro text (see copy below)
- [ ] Resolve issues: https://github.com/NuCivic/dkan-sites/issues
- [ ] Delete this repo: https://github.com/NuCivic/dkan-sites

New intro text:

A partial list of [DKAN](https://getdkan.org) sites around the world. 

[Submit an issue](https://github.com/getdkan/dkan) to add sites not on this list.

Note: Probably good to save this repo somewhere just in case we need it in the future, but don't want it accessible to the public.

cc @janette

**Comment by stefaniefgray** [comment]
Not sure how to copy the HTML page and all of its accompanying files to ReadTheDocs

**Comment by lukefretwell** [comment]
@janette note updates
