### ISSUE TITLE
Add 'Help' page to docs

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2046]
Add 'Help' page to docs with this information:

# Help

## Community

For developers and contributors:

* [Submit an issue at the official DKAN repo](https://github.com/NuCivic/dkan/issues/new)
* [Join the DKAN Slack community](https://dkansignup.herokuapp.com/)

## Professional

For professional DKAN development services and support:

* [CivicActions](https://civicactions.com/dkan)
* [Angry Cactus](http://www.angrycactus.biz/)
* [National Democratic Institute](https://www.nditech.org/project/dkan)
* [Annai](http://landing.dkan.annai.co.jp/)

cc @stefaniefgray

**Comment by janette** [comment]
This needs a link in the index.rst file
