### ISSUE TITLE
Issue with Dataset Rest API - Updating/Posting to the 'field_tags'

### ISSUE THREAD

**Issue by avrilpearl** [GetDKAN/dkan#2062]
Drupal 7.54
dkan-7.x-1.13.3
Added patch: https://www.drupal.org/node/2224803#comment-11477609

**Description**: Using the 'Dataset Rest API' I am unable to update the 'field_tags' of a dataset. Based on feedback from @dafeder we have added a patch to our repository that is meant to solve the issue with the Drupal Services Module around posting to autocomplete fields (see patch applied here: https://www.drupal.org/node/2224803#comment-11477609). However, even after applying this patch I am not able to post/update a dataset's field_tags using the dataset rest api. Not sure if this is a bug or I have not been able to determine the correct JSON format to post to the 'field_tags'. I have determined the appropriate payload for all other DKAN fields at the resource and dataset level, this seems to be the only form widget type that I cannot resolve.

**Steps to Reproduce**: 
1. Create a dataset in DKAN
2. Retrieve the dataset's Node ID
3. Using the Dataset Rest API, and posting to the node id above, post the following JSON payload to the dataset Rest API. Please note the tid is term id of a tag in your DKAN instance, make sure that value reflects the true value of a tag in your instance.: 
```
{
 "title": "Updated dataset",
    "field_tags": {
        "und": [
            {
                "tid": 9
            }
        ]
    }
}
```
4. Visit the dataset you just updated via the rest api, you will see that the title has change based on your payload but that the tags have not.

**Acceptance Criteria**:
* A json payload for the field_tags is provided in the documentation and this payload format works to update the 'field_tags' of a dataset using the Dataset Rest API.

**Comment by kimwdavidson** [comment]
Hi @avrilpearl! We'd like to take a look at this soon! I know you were looking into it as well - were you able to make any progress? Thanks! Kim

**Comment by usmanAB** [comment]
I'm also interested

**Comment by avrilpearl** [comment]
@kimwdavidson i installed the patch to the services module on our dkan instance that @dafeder had  mentioned on the DKAN slack channel, that, however, I have still not been able to use the rest API to post to the field_tags. (this is the patch we applied to our instance: [Possible patch for multi-value fields](https://www.drupal.org/node/2224803#comment-11477609))

**Comment by usmanAB** [comment]
@avrilpearl Can you give the procedure to install this patch please ? I tried with : 
git apply [name.patch].

Thanks

**Comment by dafeder** [comment]
@usmanAB I use `patch -p1 < [patchfile` from whatever the patch root dir is - (usually the module root)

**Comment by dafeder** [comment]
DKAN v1 issue, no longer relevant.
