### ISSUE TITLE
Escape special characters correctly in JSON endpoints like data.json

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2077]
CIVIC-6662

Drupal outputs the text fields we use for titles and bodies in ODSM output with special characters escaped for HTML. Escaping for JSON follows different rules and we should convert on output. For instance, apostrophes are escaped as `&#039;` and should not be escaped at all. Same for ampersands (`&amp;`). These are the most common we've seen but see the rules at json.org.

## Acceptance Criteria

* In JSON endpoints, decode all HTML entities/special characters in strings and escape following rules at http://www.json.org/

**Comment by kducharm** [comment]
Addressed in NuCivic/open_data_schema_map#104

**Comment by acouch** [comment]
The linked PR has been merged.
