### ISSUE TITLE
Lower the memory footprint for ODSM during endpoint generation

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2081]
CIVIC-6365

## Description

During the nightly job to [regenerate the cache file](https://dkan.readthedocs.io/en/7.x-1.13.4/components/open-data-schema.html#the-odsm-file-cache) for the /data.json endpoint, a site with ~3000 datasets ran into a memory exhaustion issue. The immediate fix was to bump the memory limit for Drush commands on the site by adding the following to settings.php:

```php
if (drupal_is_cli()) {
  ini_set('memory_limit', '1024M');
}
```

For a real fix a we need to rework the current ODSM code responsible for rendering the endpoints to consume less memory.

The ODSM module have three layers that work together during the endpoint generation:

1. Query construction layer
2. Query execution layer: This is where the data is fetching by looping thought all the Node ids assembled in the first phase and applying token translation on them as well ODSM hook alters.
3. Render layer: This phase uses the provided endpoint format (JSON, XML, CSV) and medium (Cache file, HTTP request) to render the query result and return it.

The memory exhaustion problems are happening on the 2ed layer during the result construction.

Originally reported by @rhabbachi

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
