### ISSUE TITLE
Document cache behavior for DKAN from user POV

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2084]
CIVIC-6292

Many users and customers run into confusion about how caching works in Drupal and DKAN specifically and what to expect. 

## Acceptance Criteria

(obviously needs more fleshing out)

* Documentation for DKAN specific cache configurations are in DKAN RTD
* Documentation for DKAN Starter specific cache configurations are in DKAN Starter RTD

**Comment by jvitello** [comment]
Found some additional info:

Dan:
> Currently the search page caches for anonymous users and only updates every 5 minutes.
>During times of heavy load or during site launches we might want to increase that. We need to document that for the client since they may think it is a bug that they create a dataset and might expect it see it in /search.
>We could alternatively clear the /search page cache on node creation so that the client could see the search page working but set a larger cache lifetime for the facets. This would be slightly deceptive since the cache results wouldn't show up right away for places searches using facets and arguments or searching for the keyword.
>This would be more ideal as we could clear the /search page right away and tell clients the actual search results won't be ready for X time. X hopefully being close to 30 mins or so. However this would need to be documented as well.

Dharizza:
>I've been reading about this and I think we should the improvement instead of just documenting the issue as this is a pain point for a lot of clients, I suggest the following:
>We need to add new variables in config.yml for next acquia purge config settings:
>$conf['acquia_purge_https']
>$conf['acquia_purge_http']
>and include those into the settings.php so acquia purge knows whether it should purge http or https.
>Also, in order to purge the cache when a node is created or updated, we could create rules to respond to those events and add the reaction "Clear pages on Acquia Cloud" to it, configuring it to purge specific pages instead of the whole site. We have to remember that wildcards are not supported so we should manually get all the urls that we want to purge (ideally, it would be everything on search/*) and add it to the rule settings one by one.
We can find some documentation here: https://docs.acquia.com/article/configuring-acquia-purge
>Here https://docs.acquia.com/cloud/performance/varnish/manually-purge we can see some info if we want to do the process manually but I think it would be best using rules.
