### ISSUE TITLE
Only run tests on DKAN starter

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2088]
Now that we have automatic builds running on DKAN starter, it's redundant to be running behavioral tests on both DKAN and DKAN starter, and ties up a lot of containers on circleCI. Let's just run them in one place.

## Acceptance Criteria

1. Both PHPUnit and Behat tests run only in DKAN starter
2. DKAN still has required "checks" on its pull requests, but they are looking at the DKAN starter tests, not tests directly on the DKAN repo. Best strategy TBD but a passing test on DKAN Starter should make DKAN pass, and the same with a fail.
3. If possible, keep running the linter on DKAN itself.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
