### ISSUE TITLE
failing to create a resources doesn't flag a harvest error

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2090]
CIVIC-6489

## Description
If a source data.json has file links that are formats that aren't allowed on the DKAN site, the resources won't be created. No errors are flagged when this happens.

If a file doesn't have a valid url, the resource is not created. No errors are flagged when this happens.

## Steps to Reproduce

Case: File Format Not Allowed
- harvest this source https://data.edd.ca.gov/data.json
- no errors will be flagged
- find "California Metropolitan Statistical Areas (MSA) and Metropolitan Divisions (MD)" in the source data.json and you will see .kml distributions
- find the same dataset on the site and there will be missing resources

Case: Invalid URL
- add the attached json to a resource and use it as a harvest pod source
- the harvest will successfully complete and flag no errors
- no resource will exist in the dataset

Test JSON
`{
  "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
  "@id": "http://example.com/error_data.json",
  "@type": "dcat:Catalog",
  "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
  "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
  "dataset": [{"accessLevel":"public","landingPage":"http://example.com","issued":"2017-06-08","@type":"dcat:Dataset","modified":"2017-06-08","keyword":["test","error"],"contactPoint":{"@type":"vcard:Contact","fn":"<Nobody>","hasEmail":"mailto:justin.vitello@granicus.com"},"publisher":{"@type":"org:Organization","name":"DKAN QA Team"},"identifier":"https://example.com/12345678","description":"This is a test dataset to see if an invalid url will be flagged as an error.","title": "Dataset With Improper Link","distribution":[{"@type":"dcat:Distribution","downloadURL":"https://asdf;lkj230987qweljhasdvopuh.com/file.csv","mediaType":"text/csv"}],"theme":["Industry Information "]}]
}`

## Acceptance Criteria

- If a resource cannot be created during a harvest, an error should be flagged

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
