### ISSUE TITLE
Remote file resources import very slowly into datastore

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2093]
## Description

When trying to import a remote file resource into the datastore it takes a very long time.  This is an unexpected behavior and is likely fixable by first downloading the remote file locally before attempting to import it.

This is partly the cause of CIVIC-5292 and CIVIC-5293
 
##  Steps to Reproduce

* Add the following remote file resource to a dataset https://gisdata.nd.gov/Metadata/CSV/NDHUB.Roads_County.csv
* Attempt to import the resource into the datastore
* Observe how slowly the import takes place
 
## Acceptance Criteria

* The datastore import of a remote file should be equivalent or very near in speed to the import if the resource where uploaded.
* There is a user defined limit for the size of a remote file to be imported
* Default for size limit of remote file import is set to a variable (Site Managers should edit the variable on the /admin/dkan/datastore page even when Fast Import module is disabled)
  * Help text that should say that remote files are only supported up to X. If the user needs a larger file, it should be uploaded to their DKAN site.
  * Show an error if a user tries to import a remote file that is too large
* Any temporary file is deleted after import operation

## Documentation

update RTD with changes 

## Test Updates
Unit test could be added to verify that remote files are handled slightly differently than non remote files.
 
## Documentation Updates
If not possible to increase the speed of these types of import it should be noted in the UI so that it does not come a surprise to the user.

**Comment by jasoneverettmiller** [comment]
An interim fix may include instructing the user on how to upload CSV resources to DKAN and import into the datastore from there instead. Explain why Remote Files aren't necessarily the best way to add some resources to the site.

**Comment by dafeder** [comment]
We'd like to try a different approach before merging the above PR, that leverages the changes we made to remote_stream_wrapper [here](https://github.com/NuCivic/remote_stream_wrapper/pull/1/files). This would be more consistent with our handling of remote files and not introduce additional points of failure. #1936 _does_ work and will be used if we can't make a solution leveraging remote_file_wrapper and the /tmp directory.

**Comment by kducharm** [comment]
Moving to blocked until @dafeder can review, not sure if new approach was attempted yet cc @kimwdavidson

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
