### ISSUE TITLE
100,000 format for chart axis labels not applied

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2098]
## Description

The comma formatting for axis labels in chart visualizations is not being applied. This was tested on multiple graphTypes for 1.12.11. It still exists in 1.13.6.

## Steps to Reproduce

- Find/Create a resource that has large numbers (file attached). Go to node/add/resource and create resource with the file attached.
- Go to admin/structure/entity-type/visualization/ve_chart/add. For the source, select the resource created, select line chart for the type.
- for the format option (Axis x or Axis y) use 100,000. 
- The chart will show 100000 format for the labels instead 100,000.

[comma_delimiter_large_raw_number_large_number_groups.csv.zip](https://github.com/NuCivic/dkan/files/1281600/comma_delimiter_large_raw_number_large_number_groups.csv.zip)

## Acceptance Criteria

- When I choose a format option for the X or Y axis to '100,000' or any another format on any chart
- Then I should see the numbers on the axis change to comma formatted

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
