### ISSUE TITLE
Add Featured Groups panel to IPE for site managers

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2101]
CIVIC-6166

## Description

In 1.12.x a Featured Groups view could be added to pages using the IPE. In 1.13.x that functionality was removed. The justification was that the panel would normally be created once on the homepage during initial implementation, so it was not necessary to include in the IPE for clients.

However, for organizations with large numbers of groups, the Featured Groups view can be used to break up the groups into different categories or highlight them in related stories. It would be useful if the Featured Groups could be added to the configuration options when editing page layout and content.

## Acceptance Criteria

- [ ] Log in as a Site Manager and click Customize This Page.
- [ ] Click the "+" button to add a panel object.
- [ ] Featured Groups should be one of the selections and should display the expected groups
- [ ] Hitting Save should display the Featured Groups panel widget as configured.

Originally reported by @jvitello

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
