### ISSUE TITLE
Permission to download data in resource content

### ISSUE THREAD

**Issue by Rkedemi** [GetDKAN/dkan#2104]
With DKAN can i restrict to download in resource content, just for download data, i upload jpg, pdf, doc, etc.. I want to give a restriction with the criteria

**Comment by kimwdavidson** [comment]
@Rkedemi! Thanks for submitting this issue! Can you tell me a bit more about the request you're making? Can you describe the behavior you're looking for in more detail?

Thanks! 
Kim

**Comment by Rkedemi** [comment]
I wish to have some uploaded documents only accessible by members of groups and not to the public. So just restrict a few of the resource documents.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
