### ISSUE TITLE
Preview Controls for Remote Files

### ISSUE THREAD

**Issue by jasoneverettmiller** [GetDKAN/dkan#2105]
## Description
When adding a Resource to DKAN using the Remote File option, there is no corresponding ability to toggle the Previews like there is on the Upload tab.

## Acceptance Criteria
When adding a Resource using the Remote File option, users should be given the ability to turn recline data previews on and off.

The Remote File tab should reflect the same functionality and layout as the Upload tab. See attached screenshots. 

## Subtasks
>Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [ ] do this first
- [ ] then do this

## Results
>When the work is complete, write the outcomes of the work. Was the acceptance criteria met? Any new documentation? Any follow up tickets created?

**Comment by jasoneverettmiller** [comment]
![remote-file.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59aed3f25beb920011384938/125516c66e82c728ace21e0d46fa91972c9686e489e0b346e611b2843b492d762a10e17132d0ba29eb172d5457594dff145c5e44fcfd8c7aaee338788b4e17ff933c0120996048e6edc00db513bb27814e80b6b98b48c5e93b2ce28a8c5d73.png)
![file-upload.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59aed3f25beb920011384938/125516c66e82c728ace21e0d46ee9d9626cf96b983e6be47e611b2843b492d762a10e17132d0ba29eb172d5457594dff145c5e44fcfd8c7aaee338788b4e17ff933c0120996048e6edc00db513bb28814e80b6b98b48c5e93b2ce383885d73.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
