### ISSUE TITLE
Display Truncated Legend Labels for Charts

### ISSUE THREAD

**Issue by jasoneverettmiller** [GetDKAN/dkan#2108]
## Description
For charts with legends displayed, allow the user to show the full title rather than the truncated display.

## Acceptance Criteria
For charts with legends set to display, give user an additional selection to show the full legend titles rather than the truncated text. 

## Subtasks
>Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [ ] do this first
- [ ] then do this

## Results
>When the work is complete, write the outcomes of the work. Was the acceptance criteria met? Any new documentation? Any follow up tickets created?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
