### ISSUE TITLE
UI: Unclear error message when Public Access Level left blank

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2110]
When the "Public Access Level" field is not filled in on a dataset the user receives an error message that says the "rights field is required," but it's unclear which fields that refers to. 

From client: There are several fields, (eg. License) that could fit into the category of "Rights field" on that page, and there is no actual field with this label. I recommend that the error message is changed from "Rights field required" to "Access level required."

**Comment by janette** [comment]
The **Rights** field only displays if the public access level is set to something other than 'Public'

![dkan](https://user-images.githubusercontent.com/314172/30351925-39e5bfe4-97e3-11e7-9691-0948396c66b0.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
