### ISSUE TITLE
Fix dkan tests failing for recline and vis_entity repos.

### ISSUE THREAD

**Issue by dkinzer** [GetDKAN/dkan#2114]
Description
====

Dkan tests for the nucivic/visualization_entity and nucivic/recline tests are failing on those repository. This is likely because of a build failure or a missing step in the build for those repositories.

Acceptance Criteria
==
- [ ] Dkan tests for recline repo pass.
- [ ] Dkan tests for visualization_entity repo pass.
- [ ] dkan tests get run for nucivic/open_data_schema_map repo and tests pass.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
