### ISSUE TITLE
Set dkan_version variable on installation and updates.

### ISSUE THREAD

**Issue by dkinzer** [GetDKAN/dkan#2115]
Description
===
We need an easy canonical way to determine the version of dkan we are currently running.  The easiest way to do this would be by setting a `dkan_version` variable that can be accessed via `variable_get`.

The use case for this feature is to allow other modules and entities to respond according to the version of dkan that is running.

This will be primarily useful in configuring what is enabled or disabled in different versions of dkan via dkan_starter settings.

AC
==
- [ ] running `drush vget dkan_setting` should return the version of dkan I am currently running.
- [ ] Add a `DKAN` subsection to `admin/system` that displays the information for regular users.

**Comment by kimwdavidson** [comment]
@janette: can you tell us a bit more about what the value of this ticket is? what can't we do currently that we need?

**Comment by janette** [comment]
@kimwdavidson dkan uses external modules/libraries and the versions of these modules and libraries will be different depending on the version of dkan you are trying to build. We need a way for the scripts that build dkan to know which versions to use, currently everything defaults to the versions specified in the 7.x-1.x branch of dkan.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
