### ISSUE TITLE
Convert the license field to a taxonomy field

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2123]
We need a better method of matching values that come in through harvesting and saving custom values that users may enter. The current method doesn't give the user a way to add a user-friendly name after a harvest pulls in a previously-unknown license URL.

![_mysql_5_5_42-log__dkan_drupal_field_data_field_license](https://user-images.githubusercontent.com/309671/30866945-9d188932-a2a8-11e7-9f78-db167f2d6ca1.png)

![wisconsin_polling_places___dkan](https://user-images.githubusercontent.com/309671/30866947-a08df480-a2a8-11e7-9d23-20d123d3fe54.png)

## User Stories

As a site manager, I want the license field to display the label text and link to the license definition when a url is given, even for harvested datasets.

**Comment by marctjones** [comment]
Have we checked to see if SPDX has coding for open data licenses?

**Comment by dafeder** [comment]
@marctjones what do you mean by coding? Looking quickly, they do have a list of open licenses generally (not specific to data) but it's pretty enormous:

**Comment by dafeder** [comment]
@marctjones what do you mean by coding? Looking quickly, they do have a list of open licenses generally (not specific to data) but it's pretty enormous:

https://github.com/spdx/license-list-data/blob/master/json/licenses.json

There are a number of resources we could use to create an updated set of out-of-the-box licenses, but I think we always need to let people add arbitrary ones.

**Comment by dafeder** [comment]
Security updates and bug fixes only in the D7 version of DKAN. Closing.
