### ISSUE TITLE
EPIC: DKAN Health Check

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2125]
There are common issues that can arise on DKAN sites that are difficult to be aware of unless someone manually checks different parts of the site. We need a nightly health check to flag any common issues.

The health check information may be useful to Site Administrators or Site Managers.

The included tickets are in the form of notification emails. It may be better to instead create an API so that it can be integrated into other things like Slack.

**Comment by acouch** [comment]
We've implemented a health check solution here: https://github.com/NuCivic/dkan_health_status and don't have near-term plans to do more.
