### ISSUE TITLE
Notification for Harvest Errors

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2126]
## User Story

As an Administrator
I need to know when a harvest encounters errors or does not complete
So that I can investigate issues as soon as they start to occur

## Description

Without manually checking the harvest dashboard, there is no way to be aware of harvests that encounter errors. We need a check at the end of the nightly harvests to see if any of the harvest sources flagged any errors, and send a notification to site Administrators if it did.

## Acceptance Criteria

- On a nightly basis, any errors flagged for Harvest Sources are emailed to site Administrators
- Notifications can be enabled/disabled independently for each harvest source (incase there are known errors that aren't going to be able to be fixed any time soon) *default is enabled*
- The email contains information similar to the following example:

## Example Email

<Site Name>

During an automated nightly site health check at <time>, errors were found to be flagged during the Harvest. The status of all Harvest Sources can be reviewed on the  <link>Harvest Dashboard</link>.

The following Harvest Sources encountered errors:

<source name with link to Harvest Source page>
<source name with link to Harvest Source page>
<source name with link to Harvest Source page>

**Comment by erogray** [comment]
Closing since this is pretty well solved for DKAN 1; needs a to-do for DKAN 2 still.
