### ISSUE TITLE
Notification when data.json is not 100% valid

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2127]
## User Story

As a site Administrator
I need to know on a nightly basis when the data.json feed is not valid
So that I can investigate issues as soon as they start to occur

## Description

Without manually checking the data.json validity, there is no way to be aware of new content that doesn't meet POD standards. This is so that we can see if there was a functional change that is affecting the data.json, or if communication with the organization responsible for the content should be notified. We need a nightly check that validates the data.json feed and sends an email to Administrators if it begins to fail validation.

## Acceptance Criteria

- data.json POD validation is checked every night
- an email notification is sent to Administrators if the data.json is not valid after the nightly check
- The email contains information similar to the following example:

<Site Name>

During a nightly automated check at <time>, the <link>data.json feed</link> was found not to be 100% valid. Please visit your site's <link>Project Open Data Validation page</link> for more details.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
