### ISSUE TITLE
Notification for Search index accuracy

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2128]
## User Story

As a site Administrator
I need to know when the search index isn't accurate on a nightly basis
So that I can quickly be aware of and start to fix search index issues when they start to appear

## Description

We have encountered a number of times, especially after harvests, when the search index doesn't contain all of the datasets on the site. We need a nightly check that flags when issues are occurring so that we can make sure all of the published data is available to users.

## Acceptance Criteria

- Every night the search index is check to make sure if it contains the same number of datasets as the total number of published datasets
- The notification email contains information similar to the following example:

## Example Notification Email

<site name>

The search index does not contain the same number of datasets as the total number of Published Datasets. Please review the <link>Dataset Search Index<link>.

Datasets in Dataset Search Index: 44
Published Datasets: 45

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
