### ISSUE TITLE
Notification for Harvest Accuracy

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2129]
## User Story

As a site Administrator
I need to know when a harvest didn't complete, but flagged no errors
So that I can quickly investigate issues that exist on the site, but weren't flagged by the harvester

## Description

Sometimes a harvest doesn't completely generate all of the datasets or resources, but an error isn't flagged. Site Administrators need to know when this happens so that they can investigate errors that weren't anticipated by the checks we have in place. 

## Acceptance Criteria

- On a nightly basis, the number of datasets and resources associated with a Harvest Source are compared to the number of datasets and resources in the cached data (check the cached data since there may be filters in place)
- An email similar to the following example is sent to site Administrators:

<site name>

During an automated nightly health check, we found potential issues with the DKAN Harvest. The status of Harvest Sources can be reviewed on the <link>DKAN Harvest Dashboard</link>.

The following Harvest Sources do not contain the same number of datasets or resources as are in the cached source data:

<source name with link to Harvest Source page>

- Number of harvested datasets: 44
- Number of cached datasets: 48

- Number of harvested resources: 98
- Number of cached resources: 116

<source name with link to Harvest Source page>

- Number of harvested datasets: 76
- Number of cached datasets: 76

- Number of harvested resources: 115
- Number of cached resources: 116

**Comment by dafeder** [comment]
@erogray have you observed this issue, do you know if it's still a problem?

**Comment by erogray** [comment]
Closing since this is pretty well solved in DKAN 1. Harvest error reporting still needs to be built for DKAN 2 though; but that'll be a new issue.
