### ISSUE TITLE
Scan resources for X-Y extent

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2131]
## Description
Provide an option to set the default Data Extent based on the X-Y coordinates of a dataset resource.

## Instructions to reproduce
 
In addition to manually setting the data extents via the map or GeoJSON boundary for displaying the coverage area, provide the ability to define the default X-Y extents of the dataset by allowing the editor to specify the resource to be scanned for determining the extents. As one option, this could be done by reading the ArcGIS Server REST of one of the dataset’s resources.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
