### ISSUE TITLE
Remove adminrole from DKAN

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2132]
## Description

DKAN uses the adminrole module to ensure that the "administrator" role gets every permission. This adds a bunch of overhead and, most annoyingly, results in messages of "The administrator role has been reset" being printed constantly in strange places. 

## Acceptance Criteria

* The adminrole module is gone from DKAN codebase
* Permissions are updated to make sure administrator does in fact have all permissions
* There is a test that checks if administrator actually has all permissions. (Think this already exists and works but double-check)

## Comments from original discussion

>Justin: We are thinking of removing the admin role since it really shouldn't be used by anyone. Do you know of any clients that routinely use this role? Do you use it for anything?
>
>We'll have the user1 for admin purposes, but we wanted to make sure removing the entire role wouldn't impact anyone's work.

>Sheldon: We use the admin role frequently to perform support tasks ranging from enabling modules to adding menu items to a host of other tasks. Moreover, the FedRamp security requirements for state that each person who accesses the website as a privileged user needs to do so through a separate user account so that we have a clear record of who performed what actions. The admin actions that we undertake on customer websites could in theory be performed by logging in as the root user, since the root user inherits permission to perform all performable tasks on the website. However, if we performed all admin actions by logging in as the root user, we would be in violation of the FedRamp requirement that I just described. For this exact reason, I recently created new admin user accounts for all our sites.
>
>Please DO NOT remove the administrator role from DKAN.

>Dan: In light of this, I would say replace admin role with our own custom code to ensure the administrator has all permissions.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
