### ISSUE TITLE
Add date widget to search page and improve UX

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2133]
##  User story

As a site visitor, I want to filter datasets by date using an intuitive interface, so I can easily filter out datasets outside my desired date range.

## Background

We currently have no way to filter by date on the main dataset page, but we do on the groups pages (Date Changed facet). Still, the UX of the widget there is not very good. Some possible existing solutions are:

https://www.drupal.org/project/date_facets
https://www.drupal.org/project/facetapi_slider
https://www.drupal.org/sandbox/uzlov/2160651

**Comment by erogray** [comment]
Closing since this hasn't been active lately, but please feel free to submit pull requests; this could also be a good feature to add to DKAN 2 in the future.
