### ISSUE TITLE
Create Explicit Permissions test

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2134]
## Description

David has created a couple of scripts that check permissions. We should make that into a behat test.

Given I am logged in as a user with the "administrator" role
I want to know permissions are the same as DKAN permissions.

This could go in Data Starter I think.

**Comment by kimwdavidson** [comment]
@jvitello Checking this isn't already done.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
