### ISSUE TITLE
Browser out of date message for react dash

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2136]
User Story:

As a site visitor, when I visit a react dashboard, if my older browser is not compatible with react dash, I should see a message informing me that my browser might be out of date, and I should update it, so that I know why I can't see dashboards.

**Comment by JayDarnell** [comment]
I'm putting an estimate of a day on this ticket as a bit of a blind guess. I've done some preliminary research into how we might figure out what browser versions are supported:

https://reactjs.org/docs/react-dom.html#browser-support

http://kangax.github.io/compat-table/es5/

There may be more research to be done but assuming these resources are a step in the right direction it should be a matter of checking the browser version against the compatibility table in the link above and updating the DOM with a notification if an unsupported browser is detected.

**Comment by JayDarnell** [comment]
https://github.com/NuCivic/dkan_dash/blob/master/js/package.json

**Comment by iris-i** [comment]
React component for browser detection: https://github.com/mbasso/react-browser-detection

**Comment by kimwdavidson** [comment]
This issue was moved to GetDKAN/dkan_dash#18
