### ISSUE TITLE
Collections support in DKAN

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2137]
## Description

POD (and maybe eventually DCAT) provide for dataset collections - groups of datasets within a single catalog grouped under a single parent. There is weak support for this in existing open data portal solutions, but data.gov has added some functionality around it. See these examples of collections on data.gov:

https://catalog.data.gov/dataset/usgs-national-geologic-map-database-collection
https://catalog.data.gov/dataset/fas-parent

Federal agencies are now beginning to require this functionality. We need to determine a plan to:

1. Either reproduce or improve upon the data.gov UX for collections
2. Deal with the existing isPartOf/collections support, which is to simply store the ID of the parent dataset which comes in from a Harvest. Presumably the native collection support will always be an entity reference, but could we still provide a fallback to just an ID string in the case of a Harvest?

## Additional Info

History:
https://github.com/project-open-data/project-open-data.github.io/issues/258

Here's an example of a source data.json feed with datasets that use the isPartOf field:
http://www.usda.gov/data.json

Parent of #2432
Parent of #2379

**Comment by susisiman** [comment]
Closed due to inactivity. Feel free to open! This work can be found at this repo: https://github.com/GetDKAN/dkan_dataset_collections
