### ISSUE TITLE
Datastore Import should handle type definitions / SCHEMA for column variables

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2139]
## Statement of problem
Because the API defaults to longtext (https://github.com/NuCivic/feeds_flatstore_processor/blob/master/feeds_flatstore_processor.module#L333) queries have the capacity to become very slow.  Currently, complex queries which we are using oin GBPW are taking between 4 and 6 seconds, which is too slow for the amount of data being presented (on order of 10-15,000 rows)

## Possible solutions
We need to create a means to define field types by column when importing data into the datastore (int, bool, varchar, etc). This could be done via a UI, or via more 'intelligent' typing by the import code, or both!

## Acceptance criteria
A complex real-world query with joins should take less than two seconds, preferable even faster!

**Comment by erogray** [comment]
Closing since this hasn't been active lately, and datastore is handled differently now
