### ISSUE TITLE
Update dkan_workflow to include data_stories and data_dashboards

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2140]
h2. Description
Currently only datasets and resources are enabled to use the dkan_workflow process. Add an install hook to also enable dkan_data_stories and dkan_data_dashboard content to follow the content moderation process when dkan_workflow is enabled.

h2. Steps to reproduce
1. Visit the demo site and enable dkan_workflow
2. Create a data story
3. Notice that it is published on save and does not show up in the My Workbench screens.

h2. Acceptance criteria
When dkan_workflow is enabled, data stories and data dashboard content is part of the content moderation process.
We may want to add the ability to choose which content types are added to workflow as part of this. Maybe at least as a configuration option to DKAN Starter.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
