### ISSUE TITLE
Print: (spike) investigate how printed stories pages should break appropriately

### ISSUE THREAD

**Issue by alexiscott** [GetDKAN/dkan#2142]
As a user, when I print a data stories page, I should see my printed version broken into pages in a logical way, so that they are easy to read and do not have large blank spaces when possible.

Connects https://github.com/GetDKAN/dkan/issues/2475

**Comment by alexiscott** [comment]
Description
===
Images are sometimes cut off when printing multiple pages.

Note. Kim suggested page break separation between sections.  Investigate how that might be achieved.

QA Steps
===
1. Go to file/print on a page where images are cut off. Example: https://gbpw.georgia.gov/physician-workforce-data

2. Make sure that the image are not being cut off.

**Comment by alexiscott** [comment]
Note. I think this could be treated as a spike ticket to find the best approach for a new ticket that would implement the changes.

 A couple of possible approaches are here:
https://stackoverflow.com/questions/1664049/can-i-force-a-page-jump-in-html-printing/1664058

Cross Operating system testing would be important.

**Comment by alexiscott** [comment]
Hi @eknapier , I introduced a fix in #2151 that I think might have fixed this, at least in the case of some charts. Anyhow, it would be good to know if you think anything else is still needed? This was the fix that I added:

Apoogies if I have stepped on your toes here. It just looked like the #2151 fix was for images but in fact SVGs were not getting treated as images so it needed .card-chart to fix it.

@media print {
 tr, img, .card-chart {
  page-break-inside: avoid;
  }
}

CC @kimwdavidson

**Comment by alexiscott** [comment]
@kimwdavidson could you supply some URL's  for dev and QA, please? I would like to make my QA notes more specific. Thanks!

**Comment by janette** [comment]
The pages respond nicely until a visualization is placed inside a panel. The inline style height added to charts is not dynamic and causes panels to overlap. As a short-term band-aid we could add a `panel-pane.pane-visualization-embed: padding-bottom: 5em;`to avoid the overlap until a better chart height solution is devised.

**Comment by janette** [comment]
@alexiscott any of the dkan default content (data stories & data dashboards -- not the react dashboards) should provide good examples. Improved print styles are definitely needed but I think the key problem for printing is the fixed height values on visualizations. See https://github.com/GetDKAN/dkan/issues/2172

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
