### ISSUE TITLE
Print: (spike, visual) need a print icon on the dashboard

### ISSUE THREAD

**Issue by alexiscott** [GetDKAN/dkan#2143]

**Comment by alexiscott** [comment]
Description
===
The print PDF icon will be removed. As that is being removed we will want a print icon on the dashboard so that users can print directly to the printer.

Decide what print icon to use and where to place it.

QA Steps
===
1. Expect to see a print icon on the page. 
2. When clicking it a print dialogue should open.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
