### ISSUE TITLE
Print: (spike) investigate removing pdf link and related code/ module

### ISSUE THREAD

**Issue by alexiscott** [GetDKAN/dkan#2144]

**Comment by alexiscott** [comment]
This is dependent on 2143.

**Comment by alexiscott** [comment]
@kimwdavidson could you let me know where the PDF link, which we need to remove, is showing? I had assumed it was on these pages: https://gbpw.georgia.gov/physician-workforce-data 
Or maybe it only shows up when signed in?

**Comment by kimwdavidson** [comment]
This only appears on GOSA, and we can do this ticket last, once we know printing pages works well. I'm moving to the icebox.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
