### ISSUE TITLE
Open Data leaders feature suggestions for long-term roadmap

### ISSUE THREAD

**Issue by aaronpava** [GetDKAN/dkan#2150]
Bill Ogilvie suggested we aggregate the areas where every open data leader in this article would like to see improvements - and understand if those are plugin solutions or things we should be looking at for DKAN. 

Consider this a bunch of roadmap/feature ideas...

 http://statescoop.com/monthly/open-gov-leaders-you-need-to-know

**Comment by kimwdavidson** [comment]
Needs to be broken into multiple cards

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
