### ISSUE TITLE
Print: Fix printing stories where charts and text overlap

### ISSUE THREAD

**Issue by alexiscott** [GetDKAN/dkan#2152]
As a user when I print a data stories page, I should see text and charts clearly with no overlapping, so that it is easy to read my print out.

Connects https://github.com/GetDKAN/dkan/issues/2475

**Comment by alexiscott** [comment]
Description 
====
Dashboard charts and text should not overlap.

**Comment by alexiscott** [comment]
@kimwdavidson - the scope of this ticket might be wider than I had Imagined, as I also see similar type issues when the site  width is responsively adjusted (Could affect tablets, mobiles etc). So a fix might affect the site as viewed in the browser as well.

It looks to me like the problem related to fixed pixel heights, such as 400, on graph elements in the panels for this page /state-workforce-and-retirement-statistics and possibly other dashboard pages. 

What is not clear to me is whey those fixed heights would have been added, and if we are to replace them with 100% specifications which seems to fix the issue then what pages might be affected. I am not sure if this warrants and after scrum meeting, at least so I can get a better sense of the context of this issue.

**Comment by dafeder** [comment]
@alexiscott we've had a lot of trouble getting charts to display consistently across browsers and for the legends to line up. @janette is more familiar with the specifics of why certain decisions were made, I think there are a couple different points where fixed heights are applied. One of them at least is supposed to be IE-specific (charts w/o heights displayed really squashed in IE). See:

* #1705 
* #2092 
* NuCivic/nuboot_radix#103 (nuboot_radix was later moved into main DKAN repo)

**Comment by alexiscott** [comment]
Thanks for giving me the extra context, @dafeder.  I am adding a screenshot showing where I was seeing the issue, though perhaps it's a complete red herring if no clients actually have this particular configuration!
![Screen Shot 2017-09-29 at 16.04.11.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c93eb84646dc0012d7caf9/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772a6456fa6b7191a379e90c2b55415e4fbe5d4a1f06a3a3dc78e2a436628f555ae9d46b5a7cc03e42f9bc831fbf05bf71831a81bebd9850d2aa6c7bb3d4d216744b470a83ed5c33aa984ec85ef042e54d53a7103165f43b.png)

**Comment by alexiscott** [comment]
@janette this is the proposed fix, for all similar panes.
<img width="1066" alt="panel-pane-height-fix" src="https://user-images.githubusercontent.com/5583342/31235683-67d2d9a2-a9f2-11e7-9432-17154c82bb96.png">

**Comment by janette** [comment]
@alexiscott you will get squished charts if you set the height to 100%

**Background:**
The original ticket was to fix the display of visualizations in IE: 
> Charts are displaying really small without css aggregation, and even worse with aggregation on.
We need to add specific height values to `svg` in IE specific css

![dashboard](https://user-images.githubusercontent.com/314172/31235368-fc3c0974-a9b6-11e7-84c4-21265949fdbc.png)

**Additional context:** https://github.com/NuCivic/recline.view.nvd3.js/pull/45
Some data will need a taller chart and the user should be able to make adjustments to the height until we can figure out a dynamic way for this to happen based on the data.

**Follow up:** We need to investigate how we can make the height of charts in IE dynamically change with the context while maintaining the responsive design. There isn't an obvious solution, but we said we'd see if we can do it with javascript.
Ideally we would want the fix in the ndv3 library or https://github.com/NuCivic/recline.view.nvd3.js/ otherwise we can make adjustments in the theme files

**Comment by alexiscott** [comment]
@janette thanks for the details relating to the requirement. Do you think that it would be worth me first looking into a short term fix such as adding the 400px height via CSS in an IE specific CSS statement?

**Comment by janette** [comment]
@alexiscott we already have a default chart height set. The issue on this ticket is now when the data stories are displayed on small screens the page panels are overlapping

**Comment by alexiscott** [comment]
@janette from my testing it was that very default height that was causing the problem in chrome. So it would seem that the fix for I.E. would have been what broke the chrome layout on small pages and also in print, where the width is also restricted. My proposed "quick" solution was therefore to limit the I.E fix so that it would not be seen in other browsers.

**Comment by iris-i** [comment]
@alexiscott I think this issue may have to do with the nvd3 library using svg's for the charts. There is an IE bug where IE9/10/11 does not respect `style = "height: " `attributes in svgs unless you add a viewbox attribute. 
https://stackoverflow.com/questions/27970520/svg-with-width-height-doesnt-scale-on-ie9-10-11

**Comment by kimwdavidson** [comment]
Janette to push work for overlap and create new ticket for chart height

**Comment by janette** [comment]
The data story pages respond nicely until a visualization is placed inside a panel. There is an  inline style height added to charts that is not dynamic. This causes panels to overlap. As a short-term band-aid we could add some css to avoid the overlap until a better chart height solution is devised.

**Comment by eknapier** [comment]
With the new pull request checked out locally (https://github.com/GetDKAN/dkan/pull/2187) I still get overlapping words and charts when printing via chrome.

**Comment by janette** [comment]
@eknapier 2187 is not fixing the print problems it is only addressing the display of stories on narrow screens. Additional work is needed for printing that is blocked until the chart height issue is fixed. #2172

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
