### ISSUE TITLE
Review non-developer install documentation

### ISSUE THREAD

**Issue by marctjones** [GetDKAN/dkan#2154]
All of the documentation for setting up an instance of DKAN now assume that you are also setting up a developer enviroment or rely on developers toolchains.

I tried to setup a pantheon instance today, because that seemed the most straightforward but that failed when Terminus did not install correctly. And even then I was asked to install drush (which apparently in the latest version will require you to install via composure).

Ideally we would have step by step instructions that you could follow to install on a vanilla install of Debian/Ubuntu/CentOS without having to rely on installing a entire development environment. Or even better offer RPM/Deb packages.

**Comment by kimwdavidson** [comment]
@marctjones You shouldn't have needed Terminus. Can you say more?

**Comment by dafeder** [comment]
@marctjones https://dashboard.getpantheon.com/products/dkan/spinup

**Comment by kimwdavidson** [comment]
https://dkan.readthedocs.io/en/latest/introduction/get-dkan.html

**Comment by stefaniefgray** [comment]
Ready for QA
