### ISSUE TITLE
iframe content doesn't resize

### ISSUE THREAD

**Issue by jvitello** [GetDKAN/dkan#2158]
connects #2534
## Description

There is an old item in our User QA Checklist that talks about how iframe content (youtube content) should resize with the browser. I tested this using a custom content block in a datastory, and the embedded content didn't respect the column widths of the layout I was using.

We should reconfirm how we will support iframe content, and make sure it is working as expected.

## Steps to Reproduce

- Create a Data Story.
- Add an iframes to a region and make sure there aren't height/width configurations. An easy example for this is using the embed code of a Youtube video.
- Remove the "width" and "height" values from the iframe element if any. 
- Save.
- Resize your browser and check the behavior as the regions change in size (they won't resize).

## Acceptance Criteria

- Iframes fit in different layouts and scale

## From Mariano

I've created this gist until we move this to the product: https://gist.github.com/topicus/c8ff538d32271077772f9ddee7d72f91

**Comment by erogray** [comment]
Can adjust embed code to size properly.

**Comment by janette** [comment]
After discussion this is changed to a **won't do**

Users can wrap the iframe content like this:

```
<span class="iframe-container"><iframe src="..."></iframe></span>
```
and it will be responsive if using the nuboot_radix theme

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
