### ISSUE TITLE
Spike: Review React-dash for implications of updating to v.16

### ISSUE THREAD

**Issue by iris-i** [GetDKAN/dkan#2162]
We need to update to React's v.16. 
Things to update: https://reactjs.org/blog/2017/09/26/react-v16.0.html#breaking-changes

Notable changes:
1. Deprecated React.createClass has been removed from the core package
2. Also React.PropTypes has been removed. Both are available as separate libraries.

**Comment by kimwdavidson** [comment]
@iris-i: How time sensitive is this? Thanks!

**Comment by iris-i** [comment]
@kimwdavidson I wouldn't consider it urgent but it is important enough to prioritize it within the next few weeks so we can upgrade to an MIT version of React.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
