### ISSUE TITLE
Reduce repo size by moving documentation images to S3

### ISSUE THREAD

**Issue by grugnog** [GetDKAN/dkan#2166]
The repo is 100MB, which while not huge is enough to slow down some operations. While there are local workarounds (such as using git clone with --reference) it would be nice to see if there is a more universal option.

Most of the volume is coming from the /docs directory, especially the images. We want to keep this as part of the project, so documentation can be tracked and reviewed in lockstep with code changes. The simplest method would be to replace the images with git-lfs (https://git-lfs.github.com/) which would avoid the repository bloat. To reduce repository size a script would need to replace the images with git-lfs references in the entire history, so this change would need to be done at some point when feature branches are all merged (or as close to that point as possible, to avoid disruption).

**Comment by dafeder** [comment]
We could also just keep the images in the cloud in the first place. Let's think through the level of effort for that.

**Comment by janette** [comment]
**conf.py**
``# Do not warn about external images (status badges in README.rst)
suppress_warnings = ['image.nonlocal_uri']``

**Comment by janette** [comment]
After discussing with Gerardo we've concluded that manually managing the files on an S3 bucket would be the better route as it is a small lift and keeps it simple, no need for additional tooling.

## Acceptance Criteria
- image files will be stored in version specific directories, we will maintain three versions: latest (dev) and the last two tags, once a new tag is created we will drop the oldest directory.
- doc files are updated with the external links to the images

## Process going forward
- any community submitted files can be moved by the code reviewer to S3
- added release tasks of image maintenance:  i.e. ``cp ~/s3/doc_images/latest`` to ``~/s3/doc_images/7.x-1.15``
