### ISSUE TITLE
Task: Update documentation on contributing code

### ISSUE THREAD

**Issue by nerdstein** [GetDKAN/dkan#2167]
Describing from beginning to end of how a first time contributor would submit a pull request successfully.

Articulate our objective of having a community of contributors

1. Forking of the repo, branching, and pull request model
2. Read the documentation we have provided (/docs)
3. Creating a build environment (references to docs, options like Pantheon one-click)
4. Identifying potential issues to work on (beginners issues, tagged)
5. Coding standards identification and linter (runs automatically when PR generated by CircleCI, PR will fail otherwise, https://github.com/NuCivic/dkan/blob/7.x-1.x/.ahoy/.scripts/dkan-lint.sh)
6. Acknowledgement of DCO and use of commit signoff
7. Every change goes through code review by the maintainers
8. If something is not accurate in this file or others, please submit a pull request

## To do:
- [ ] Remove OWNERS.md file
-

**Comment by nerdstein** [comment]
cc: @marctjones

**Comment by janette** [comment]
@nerdstein this is what exists already https://github.com/GetDKAN/dkan/blob/7.x-1.x/.github/CONTRIBUTING.md

**Comment by kimwdavidson** [comment]
https://github.com/GetDKAN/dkan/blob/develop/.github/CONTRIBUTING.md
https://github.com/GetDKAN/dkan/blob/develop/README.md

**Comment by kimwdavidson** [comment]
Updated text, making a new ticket for owners.md file
