### ISSUE TITLE
Task: Update documentation on contribution architecture

### ISSUE THREAD

**Issue by nerdstein** [GetDKAN/dkan#2168]
Adam's suggestions:

1. Core -- All stable features that are non-optional, all default install features, all APIs that extend DKAN. Expectations are that... 
- There is adequate documentation
- There is adequate automated testing
- There is parity with other DKAN core features

2. Whitelisted modules (optional) -- Stable features that have been vetted and are supportable that can extend DKAN for specific use cases.
- Documentation is desired, but not mandatory
- There is adequate automated testing 
- There is parity with DKAN core but not necessarily all other whitelisted modules

3. Experimental modules (optional) -- Features that may or may not be supported long term but provide an ability to extend DKAN. There is no expectation of documentation, automated testing or guarantees of future support.

4. Custom modules -- Implementation-specific extensions to DKAN and there is no expectation of community contribution.

Connects #2167

**Comment by kimwdavidson** [comment]
Let's use this text as MVP of our documentation

**Comment by fmizzell** [comment]
@nerdstein What are these guidelines in reference to? As I see it there are 3 thing in DKAN currently:

1. DKAN specific modules
2. Drupal contributed modules with DKAN specific integrations (features/config)
3. Other Drupal contributed modules

IMO expectations should be that we support only 1 and the integrations in 2. 3 could probably be removed from the profile all together.

If this representation of the codebase is correct, what does whitelisted or experimental mean in the given context?

**Comment by nerdstein** [comment]
Per @dafeder "there are modules we consider core that are optional"

Also, we should be clear that this impacts our community standards

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
