### ISSUE TITLE
Fast import tests fail locally

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#2176]
## Description
I am running dkan locally within the docker containers configured by the repo, yet the fast import tests fail due to the sql command "LOAD" not being allowed. I see the configuration in multiple places to make this work, but for some reason it isn't.

## Steps to Reproduce
1. Get dkan working with docker
2. ahoy dkan tests

## Acceptance Criteria
All the tests should pass

It would be great if other could confirm.

**Comment by fmizzell** [comment]
Somethings have changed in our docker configuration since these attempts, so they now seem to have no effect. We will have to revisit this again later.

**Comment by kimwdavidson** [comment]
Closing in favor of #2256
