### ISSUE TITLE
Non-feeds Datastore Importer

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#2179]
The datastore and the API driven by it are IMO the most valuable things in DKAN. 

Currently the datastore is highly coupled to Drupal, Feeds, etc, and it has plenty of leakage in all places it touches.
 
If we were to contain the leakage and properly isolate our interactions with Drupal, we could then have a better framework to experiment with other powerful technologies in this section of the code.

Feeds is a very powerful module but that power comes with complexity that is then complicating our maintenance of the Datastore codebase. 

Our other option is the fast import which is also highly coupled to feeds.

**Solution**
- [x] Create a datastore importer to replace the feeds importer
- [x]  Decouple the fast datastore importer from Feeds
- [x] Decouple any other parts of the system from Feeds (Datastore API, etc)

parent of #2568
parent of #2523
parent of #2482
parent of #2481
parent of #2487
parent of #2569
parent of #2619
parent of #2622
parent of #2665
parent of #2684
parent of #2705
parent of #2706
parent of #2735
parent of NuCivic/recline#102

**Comment by acouch** [comment]
This would be tremendous. 

FYI @topicus and I had started a version of this a couple of years ago. I can't find the repo on Github but it might be private. I could get @dafeder to help me look if it is still there. Anyway might help with some ideas. It looks like your approach is similar. We were going to rip out Feeds and use https://github.com/portphp/portphp for the import/extraction. Another important component we wanted to enable is to be able to use a separate database from the Drupal database. This would make the management of the datastore a lot easier from a sysadmin perspective.

**Comment by kimwdavidson** [comment]
Blocked by #2483

**Comment by kimwdavidson** [comment]
needs to get tests passing, then needs to be rebuilt, then ready for QA
