### ISSUE TITLE
Break up Add Content Page by types

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2200]
Currently, this is one long page in Read the Docs, should be broken up by content type for more readable, manageable chunks.

**Comment by stefaniefgray** [comment]
https://docs.google.com/presentation/u/1/d/10qo7XI8dQCfDwlMu2hWAErBVV1cV4kAn62oDwCI7Ew4/edit?usp=slides_home&ths=true

Closing ticket for now

**Comment by stefaniefgray** [comment]
http://dkan.readthedocs.io/en/latest/admin/data_and_content/adding_new_content.html

^^ Improved docs will go here

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
