### ISSUE TITLE
Help with importing a weather dataset daily into dkan drupal 7

### ISSUE THREAD

**Issue by sumanthkumarc** [GetDKAN/dkan#2204]
Hi All, I'm using dkan on drupal 7, i have a endpoint which directly gives xml weather data, i want this to be saved a dataset with resources and refreshed every day. i feel like i can't use harvest for this?? because harvest requires data to be in POD format or something and not the actual data directly??

**Comment by janette** [comment]
@sumanthkumarc you would need a custom harvest source **type**

There is a little documentation on that topic here http://dkan.readthedocs.io/en/latest/components/harvest.html#define-a-new-harvest-source-type

**Comment by kimwdavidson** [comment]
@sumanthkumarc, we're going to close this one up. Feel free to open a new ticket if you need more help!

**Comment by sumanthkumarc** [comment]
@janette @kimwdavidson  yes please close this. Thanks for the help. also i have written drupal 7 module for this, which i will ask my company to open source and will put in my github. will post link here once it is up.
