### ISSUE TITLE
Incorrect field mapping defaults in open_data_schema_map_dkan feature

### ISSUE THREAD

**Issue by kducharm** [GetDKAN/dkan#2213]
Three tokens in feature defaults for APIs are using underscores instead of dashes when using the [node:field_name:?] tokens:
- [node:field_harvest_source_issued:custom:Y-m-d]
-
 [node:field_harvest_source_modified:custom:Y-m-d]
- [node:field_landing_page:url]

They should be:
- [node:field-harvest-source-issued:custom:Y-m-d]
- [node:field-harvest-source-modified:custom:Y-m-d]
- [node:field-landing-page:url]

**Comment by dafeder** [comment]
This isn't fully resolved yet. Searching the feature file I still see more than 75 instances of `field_` that presumably should be `field-`. Also I would want to test an upgrade as ODSM features don't seem to revert reliably... so let's test an upgrade from the previous release and see if we need to give it an extra push via update hook or something.

**Comment by dafeder** [comment]
DKAN v1 issue, closing due to EOL.
