### ISSUE TITLE
Drupal 8 Spike: Explore web service APIs

### ISSUE THREAD

**Issue by nerdstein** [GetDKAN/dkan#2216]
Drupal 8 has made substantial progress, both with core and contrib, in it's web service API offering.

Off the top of my head, the following technologies could/should be explored:

1. What is Contenta / Reservoir doing that overlaps with DKAN objectives?

2. How could the following modules be used? JSON API, Open API, Rest WS, Services, Graph QL

3. Could Schemata be used to help support open data standards? https://www.lullabot.com/articles/decoupled-drupal-hard-problems-schemas

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
