### ISSUE TITLE
Move away from a single dataset centric view

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2219]
Per the Civic Analytics Network's '[An Open Letter to the Open Data Community](http://datasmart.ash.harvard.edu/news/article/an-open-letter-to-the-open-data-community-988)':

**2. Move away from a single dataset centric view.** Tying together related datasets is a key priority for our network. Most portals make it difficult to tie together related datasets either during the discovery process or via APIs. Since data portals generally only support flat data, this means that information from relational databases need to be broken into smaller datasets, and later recombined by a potential user of that data. Having a better ability to tie together and compare related data sets is important in regards to content, too; for example, current open data features do not make it easy for users to compare budgets or other city information. This relates to a greater need in general - that data portals need to do a better job of keeping pace with the data types that are most useful and/or needed by the public.

**Comment by dafeder** [comment]
The biggest thing we can do to move toward this is #2137. Datasets can be grouped into "collections," and with the right panelizer configuration, the main collection dataset could be customizable to provide more of a landing page feel. Beyond this, DKAN's "data stories" provide a way to better package data for the public, but these are just unstructured pieces of content and very labor-intensive to create.
