### ISSUE TITLE
Treat geospatial data as a first class data type

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2220]
Per the Civic Analytics Network's '[An Open Letter to the Open Data Community](http://datasmart.ash.harvard.edu/news/article/an-open-letter-to-the-open-data-community-988)':

**3. Treat geospatial data as a first class data type.** On most data portals, geospatial data is an underdeveloped and undervalued asset; going forward, it needs to be an integral part of any open data program. For the past several years, the general status quo for cities has been to post spreadsheets of data on the web for the public to consume. In this iteration, geospatial data largely serves as a secondary feature.

Having better and more easily navigable geospatial data is a priority among open data consumers that current data portals don’t meet in both the user interface and via the API. It’s why cities such as Chicago and Los Angeles have sought their own solutions to the issue, with Chicago creating OpenGrid, an open-source public geospatial awareness tool, and Los Angeles commissioning GeoHub, an online forum for the public to discover, explore, and download geospatial data.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
