### ISSUE TITLE
Decrease the cost and work required to publish data

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2222]
Per the Civic Analytics Network's '[An Open Letter to the Open Data Community](http://datasmart.ash.harvard.edu/news/article/an-open-letter-to-the-open-data-community-988)':

**5. Decrease the cost and work required to publish data.** Portals’ automation services are generally minimal, putting the onus on localities to manage this on their own. And the (non-monetary) cost of getting datasets up is generally too high for local governments. The amount of time and manpower it takes for cities to upload new datasets prohibits them from having larger volumes of wanted data available to the public. Automation services from open data portals need to keep up with demand. While many cities have been able to manage automation on their own, the capacity to do so may vary considerably from city to city, especially as smaller and/or resource-constrained cities seek to launch open data programs of their own.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
