### ISSUE TITLE
Introduce revision history

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2223]
Per the Civic Analytics Network's '[An Open Letter to the Open Data Community](http://datasmart.ash.harvard.edu/news/article/an-open-letter-to-the-open-data-community-988)':

**6. Introduce revision history.** Data quality is improved with revision history. To have a quality data portal, governments must be able to provide data that is timely and accurate. This means governments should (and do) update their data sets frequently. These updates are sometimes driven by users from the general public as well, who can note errors to be corrected. However, there is currently no easy way to track a data set’s revision history over time. This is something that GitHub, for instance, does well, which is immensely useful for users. Many cities have devised “workaround” solutions to this, such as posting snapshots of previous data versions onto their portal; however, in the long term, this is not an adequate solution.

We also believe steps can be taken to improve the context for data and data quality. For example, if versions of the same dataset for different time spans are provided, context can also be provided behind the reasoning for different versions. Such changes that incorporate context need to be less about including a note that says “x revision occurred on x date,” and more about explaining the reasoning.

**Comment by mgottholsen** [comment]
Revisions of the dataset as well as metadata revisions would be beneficial I think.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by acouch** [comment]
Just to be clear DKAN does have revision history out of the box.

![image](https://user-images.githubusercontent.com/512243/43783606-231b7e84-9a30-11e8-89e7-7ffa99b5995f.png)


There is a revision tab at the top of every page. The revision history for a dataset is updated any time a dataset is updated or a resource is added, removed, or updated.
