### ISSUE TITLE
Set clear transparent pricing based on memory, not number of datasets

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2225]
Per the Civic Analytics Network's '[An Open Letter to the Open Data Community](http://datasmart.ash.harvard.edu/news/article/an-open-letter-to-the-open-data-community-988)':

**8. Set clear transparent pricing based on memory, not number of datasets.** Data portal providers vary in how they price their services with varying levels of transparency. This makes it challenging for open data providers to budget and plan for their work. While we understand portal need to position their services competitively, we strongly discourage pricing strategies that are misaligned with the goals for open data. In particular, pricing models based on number of datasets published (versus memory, volume) disincent publishing open data and undermine the spirit and goals of the movement.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
