### ISSUE TITLE
Discovery: [POD Validation] Less data with better quality vs. More data with poor quality

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2228]
RE: https://github.com/GetDKAN/open_data_schema_map/blob/7.x-1.x/modules/open_data_schema_pod/open_data_schema_pod.module#L252

Currently we fill in missing POD values with dummy data with the above code when generating data.json. The reason is to keep low quality data available at a Federal level. Is this good practice or should we rethink how this should work. 

When you run the built in validator `/admin/config/services/odsm/validate/pod` it will never fail unless you enable ODFE, which will fail on program and bureau code fields if they are empty.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
