### ISSUE TITLE
UI bug: Can't perform bulk actions on content across pages

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2230]
**Context:**
While logged in as a Site Manager or admin, I can visit the Content page to perform bulk actions on multiple pieces of content at once. 

When I select the checkmark at the top of the page to select all, my site says that it's selected all 74 pieces of content across Page 1 and Page 2, as seen in this image:

<img width="1443" alt="screen shot 2017-11-07 at 9 51 03 pm" src="https://user-images.githubusercontent.com/9059428/32576090-e112a4de-c4a3-11e7-970a-ed9e101d8b89.png">

But if I try to perform the action on all 74 pieces of content, it really only modifies 50:

<img width="1022" alt="screen shot 2017-11-08 at 4 37 43 pm" src="https://user-images.githubusercontent.com/9059428/32576122-f408dc0c-c4a3-11e7-9c2e-98bbdb973d39.png">

Additionally, if I bulk-select all of the content on the Content page, I get the option to either select the 50 rows shown on the page, or “Select all 74 rows in this view.” 

But if I choose that option and then go to Page 2, nothing is checked off. The checkmarks should be persistent on the following pages if you’ve selected to view all rows.

**Acceptance criteria:** Bulk actions can be performed with multiple pieces of content across pages. Selections on the Content screen are persistent across pages.

**Comment by janette** [comment]
@stefaniefgray looking at your screen shot it says `selected 50 rows in this page`

When I tested, and clicked on the **select all 79 rows in this view**, it updated the text next to it to say `selected 79 rows in this view` and the button text changes as well

![content___7_x-1_x](https://user-images.githubusercontent.com/314172/32589049-fa08668e-c4d7-11e7-824c-f88a16447119.png)

When I ran an operation, I got the message `Performed Stick on 79 items.`

So try again and if you get the same buggy results let me know

**Comment by stefaniefgray** [comment]
Hmm, you're right - I didn't see the bug. Looks like everything is alright and that it was my mistake, sorry!
