### ISSUE TITLE
UX: Why are ArcGIS and ESRI Rest file previews not enabled by default?

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2231]
(From the Data Previews page at http://test.devy.nucivicdata.com/admin/dkan/dataset_preview )

Why are ArcGIS previews not enabled by default for the ArcGIS and ESRI rest file types? 

Mappability is the whole point of hosting those formats, and having them disabled by default is why people think the preview option is broken. :/ http://test.devy.nucivicdata.com/admin/dkan/dataset_preview

Additionally, GeoJSON and KML files should also have map previews enabled, as well as WMS files - which are hosted on DKAN but are not even given as an option on this screen.

One thing worth noting is that Carto is revoking access to its API as of 11/30, so we need an alternative map preview option that’s based on OpenStreetMap or other open source tools.

Excel and XLS files do not require the map preview option, so it should be removed from those file types.

<img width="912" alt="screen shot 2017-11-07 at 9 55 38 pm" src="https://user-images.githubusercontent.com/9059428/32576307-97e7e35e-c4a4-11e7-8e07-b2419f668e91.png">

**Comment by dafeder** [comment]
Agreed - we need to tighten up and unify the ArcGIS previewing generally.

It does make sense, I think, to keep CSV previews in CartoDB optional... that's really like a secondary preview type, a lot of sites will not have geospatial data in the majority of their CSV files.

**Comment by kimwdavidson** [comment]
Need to create new tickets to clean up this functionality

**Comment by dafeder** [comment]
DKAN v1 issue, no longer relevant.
