### ISSUE TITLE
Bug: 500 Internal Server Error While Trying to Install Workflow; Permissions Are Broken

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2232]
This is either a bug or an error with Devy -- cc: @dafeder 

As an admin, attempting to enable the Workbench/Workflow set of modules results in the following for each module:

<img width="1050" alt="screen shot 2017-11-07 at 10 05 38 pm" src="https://user-images.githubusercontent.com/9059428/32579172-f5c1bea6-c4ad-11e7-91e7-d83c9a635b67.png">

It appeared as if the modules had installed properly (the 'on' switch was green on the Modules page) because Workbench roles became enabled for each user.

In turn, I created 3 accounts with each of the 3 Workflow roles (Supervisor, Moderator and Contributor). None of the permissions for these roles were available when logged in, nor was the "My Workbench" button or Workflow menu options.

**Acceptance criteria:** If Workflow is enabled, Workflow Roles and Permissions work as expected.

**Comment by dafeder** [comment]
Could not reproduce on a bare install, assuming that this is due to a problem with the devy instance. Reopen if this issue appears on any production site.
