### ISSUE TITLE
Enhancement Request: Pre-set Colorizer Palettes Are Not 508 Compliant

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2233]
As a user choosing a color palette for my DKAN site, the preset DKAN color palettes do not meet the high-contrast color standards of 508 compliance under the Americans with Disabilities act.

See: 
- http://colorsafe.co/
- https://standards.usa.gov/components/colors/
- https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html

This screenshot displays the theme "Ice," which is very low-contrast and difficult even for users without color loss:

<img width="828" alt="screen shot 2017-11-07 at 10 09 42 pm" src="https://user-images.githubusercontent.com/9059428/32579470-12a50f9a-c4af-11e7-9ce5-2979e86375e6.png">

**Acceptance criteria** DKAN's pre-existing color palettes are subbed out for 508-compliant palettes.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
