### ISSUE TITLE
UX: DKAN "Global Settings" for Appearance Won't Let Me Change or Turn Off Default Logo

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2234]
As an admin editing Global Settings for Appearance, DKAN refused to allow me to turn off the default logo. It also refused to load or save the new logo.

These things worked under NuBoot settings, but it's very confusing for users to have two different locations for changing the logo -- especially when one works, and one doesn't.

Appearance options should be streamlined for better UX.

The last screenshot shows that the intended logo had been uploaded, but was not visible as a preview or recognized as an image.

<img width="720" alt="screen shot 2017-11-07 at 10 25 29 pm" src="https://user-images.githubusercontent.com/9059428/32579554-6c8e82e8-c4af-11e7-85f2-2dde0101a390.png">

<img width="855" alt="screen shot 2017-11-07 at 10 26 59 pm" src="https://user-images.githubusercontent.com/9059428/32579557-6f508044-c4af-11e7-81af-adcb5e1cf37f.png">

**Comment by janette** [comment]
@stefaniefgray the value you are using in the 'path to custom logo' field implies that you added the file to the root directory of nuboot_radix... if the file does not exist at the path you provide it can not display it. If that is a file that already exists on the site, provide the path relative to the theme directory.

**Comment by janette** [comment]
Can not reproduce, perhaps need additional documentation?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
