### ISSUE TITLE
Dataset form

### ISSUE THREAD

**Issue by kevindavis338** [GetDKAN/dkan#2238]
## Description
Disabling dkan_workflow does not disable workbench_moderation, causing confusion.

## User Story
Hi there, if you look at the following image, I'm seeing it different from what it should be. I disabled the workflow, however, I'm still seeing the same layout.  Is there something else that needs to be done? 

![dkan](https://user-images.githubusercontent.com/4030822/32788970-3d1144e0-c920-11e7-9e9d-ec7164c3bd39.png)

## Acceptance Criteria
- [ ] When dkan_workflow is disabled, the workbench_moderation module is also disabled.

**Comment by janette** [comment]
@kevindavis338 did you also disable Dkan Workflow Permissions? If not disable that, clear cache, rebuild permissions, if you still see the workflow buttons, try a features revert on dkan_dataset.

**Comment by kevindavis338** [comment]
Yes, I did.. How would I go about doing a features revert on dkan_dataset?

**Comment by janette** [comment]
Go to `admin/structure/features/dkan_sitewide_panels` if there are overrides, check the box and click Revert Components. 
If you will not be using dkan_workflow, uninstall it as well as dkan_workflow_permissions.
Clear cache.

**Comment by kevindavis338** [comment]
Ok, I reverted the sitewide panels, and I removed both workflow and I cleared the cache. Still seeing it.

**Comment by janette** [comment]
Sounds like things are not truly disabled, can you go to the modules admin screen and filter by 'work' and confirm that all workflow and workbench modules are disabled.

**Comment by kevindavis338** [comment]
![dkan-work](https://user-images.githubusercontent.com/4030822/32791943-c61a072a-c927-11e7-8f0f-b84dd99d66ca.png)

This is what I'm seeing.

**Comment by janette** [comment]
Ok that makes sense then, disable workbench_moderation and you should be back to the regular local task links.

**Comment by kevindavis338** [comment]
That did the trick. Thank you..
