### ISSUE TITLE
Fix data.json test in PHP 7

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2239]
From Owen's discovery on #1049 

According to https://docs.acquia.com/article/php-55-retirement-faq
"PHP.net will end support for PHP 5.5 in July 2016. As a result, Acquia is ending support for PHP 5.5 in favor of PHP 5.6 on Monday, 2 May 2016" - all of our sites are running on 5.6.

I ran a test with PHP 7.1 and we appear to have only a single error below, plus a bunch of identical warnings from devel_generate: https://circleci.com/gh/GetDKAN/dkan/8652?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

DataJsonTest::testDataJson
PHPUnit_Framework_Exception: Argument #2 (No Value) of PHPUnit_Framework_Assert::assertArrayHasKey() must be a array or ArrayAccess
It seems like fixing these would be a fairly easy task and worth getting ahead of so we can move hosted clients to PHP 7.1 and give the DKAN community time to adjust their hosting also.

We could then run tests on both PHP 5.6 and 7.1 (at least) for a period. I am not sure if we can do that on CircleCI (the 1.0 configs at least), but we have been considering a more generic Docker based test runner anyway, which should accommodate this easily.

**Comment by Pythagory** [comment]
The pile of warnings is resolved here: https://www.drupal.org/project/devel/issues/2879092

Unfortunately, Devel hasn't had a new release in about 3 years, so we'll either have to patch it, ignore it, or wait for a 1.6 release, which has been threatened recently: https://www.drupal.org/project/devel/issues/2851078

**Comment by kducharm** [comment]
Devel 7.x-1.x seems to hide warnings, branch: https://github.com/GetDKAN/dkan/tree/circleci-v2-test-php7-kd

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
