### ISSUE TITLE
Get PHP 7 tests running in Circle

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2240]
See if using CircleCI workflows is feasible to allow us to run PHP7 tests from CircleCI UI (https://circleci.com/docs/2.0/workflows/)

**Comment by kducharm** [comment]
![Add_PHP_7_1___5_6_Workflows_to_CircleCI_by_kducharm_·_Pull_Request__2252_·_GetDKAN_dkan.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59a6ea4146d8ae00164539b0/125516c66e82c728ace21e0d46c9909e1cb2ab99b0be80129b62cfc1161018442616a82d7c8af43b8056743e2c060cff1d0d2c3d93abc044fde27923d20d49b0be9fd81ba6784df0d7e04afe44ef63cf20eab4be8f4eaf1aba4a90decb3b456f7b77dda40c6bb28559881aa911b41e11b6192466ef273279419116732f383222aafcdf5282d468f1be182e44d4f1a6ab4846fe21818d5c33715f49ab2238b4075b886890427a59edbcc3fa0501.png)
