### ISSUE TITLE
Group Package Show API with valid UUID as 'id' parameter gives "Not Found" message

### ISSUE THREAD

**Issue by gouli** [GetDKAN/dkan#2245]
The Group Package Show API returns valid group details when 'id' parameter is provided with "name" attribute. But fails when 'id' parameter is provided with "uuid" attribute.

API with Name attribute returns correct results
https://abc.com/api/3/action/group_package_show?id=geospatial

API with UUID attribute returns "Not Found" message
https://abc.com/api/3/action/group_package_show?id=b315afd9-6a86-4f1e-bf65-b9a8d1f665e6

**Comment by gouli** [comment]
The issue is with "open_data_schema_ckan.module". I have fixed the issue and have the patch file, but it doesn't allow me to upload the patch, how do i upload ?

**Comment by gouli** [comment]
diff --git a/modules/open_data_schema_ckan/open_data_schema_ckan.module b/modules/open_data_schema_ckan/open_data_schema_ckan.module
index 97bb4ce..912ad39 100644
--- a/modules/open_data_schema_ckan/open_data_schema_ckan.module
+++ b/modules/open_data_schema_ckan/open_data_schema_ckan.module
@@ -179,7 +179,7 @@ function open_data_schema_map_nid_exists($nid) {
 function open_data_schema_map_normalize_id($content_type, $id) {
   if (open_data_schema_ckan_is_valid_guid($id)) {
     $uuid = $id;
-    $nid = reset(entity_get_id_by_uuid('node', array($nid), FALSE));
+    $nid = reset(entity_get_id_by_uuid('node', array($uuid), FALSE));
     return array('nid' => $nid, 'uuid' => $uuid);
   }
   else {

**Comment by janette** [comment]
@gouli can you create a pull request with your fix?

**Comment by gouli** [comment]
@janette 

I have created pull request. 
The pull request title is 
"Fix ckan package issue #109"

**Comment by janette** [comment]
Thanks @gouli will get this into review

**Comment by dafeder** [comment]
Merged this!

**Comment by dafeder** [comment]
Merged this, thanks @gouli !
