### ISSUE TITLE
Task: Implement new branching strategy

### ISSUE THREAD

**Issue by kducharm** [GetDKAN/dkan#2250]
### Most Important
- [x] Update zip and tar.gz for1.14.1
- [x] Release 1.14.2
- [x] Create a script that adds version information to the appropriate .info files (Gerardo has a script that removes the version info. Modifying that to add info should be simple)
- [x] Create a packaging script. For each release we should create a packaged version of DKAN with updates to the CHANGELOG, and version information
- [ ] Identify other necessary changes to point release workflows and possible automation
- [ ] Update DKAN docs to explain all of this
- [x] Create scripts that modifies the CHANGELOG from git information.

### Good to Have
- [ ] Revise/create a new script for patch releases (1. Merge develop into the production branch 2. Creates an integration branch from production 3. Creates a PR from the integration branch to be merged into develop)
- [ ] Enhance the package manager to not only add information but to create a fully functional DKAN with drupal (just like dkan_starter).  
- [ ] Connect all this scripting with more automation, either on a github hook, or through jenkins

### Done
- [x] Create a new `develop` branch on DKAN. This will now be the default branch in the repo.
- [x] Write ticket for point release automation 
- [x] Create 2.x releases for recline, open_data_schema_map, visualization_entity
- [x] PR/release of DKAN switching to fixed versions of EVERYTHING, no more branches in makefiles

**Comment by kimwdavidson** [comment]
Dan to rewrite this as implementing new branching strategy

**Comment by fmizzell** [comment]
I do not have the right permission to set default branches and other setting on the repo \cc @dafeder

**Comment by dafeder** [comment]
Try now

**Comment by fmizzell** [comment]
Update: The release script can now freeze the develop branch, and the release method can merge that branch into "master" (7.x-1.x) and develop. The only thing left is to create the tag on "master". There are quite a few extra things happening in that release method that I would like to look at and discuss with @dafeder before calling it done.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
