### ISSUE TITLE
Feeds issue

### ISSUE THREAD

**Issue by kevindavis338** [GetDKAN/dkan#2251]
Hi there,

Every time I save a resource when I attach it to a dataset or remove or add a group to a dataset, I seem to be getting the following issue:

Call to undefined function feeds_node_prepare() in dkan_datastore_node_update() (line 307 of /dkan/dkan/profiles/dkan/modules/dkan/dkan_datastore/dkan_datastore.module).

Is there a for me to revert to the original feeds module that is in the dkan profile?  It seems me that it is no longer recognizing it.

**Comment by janette** [comment]
@kevindavis338 it is important to stay with the Feeds version included with DKAN https://github.com/GetDKAN/dkan/blob/7.x-1.x/drupal-org.make#L98
It is a specific revision with a patch applied.

**Comment by kimwdavidson** [comment]
@kevindavis338: We're going to close this up. Let us know if you're still experiencing this issue. Thanks!

**Comment by kevindavis338** [comment]
I'm still getting the issue.. The Feeds module is in the following directory:

/profile/dkan/modules/contrib folder.

**Comment by kevindavis338** [comment]
I'm using version 7.x-2.0-beta4

**Comment by janette** [comment]
Currently DKAN only works with Feeds 7.x-2.0-beta3+36-dev (2017-Jun-07)
- revision: d312f4f66e98cc12b8462cd13874184589017f72
- patch: 1127696: https://www.drupal.org/files/issues/1127696-137.patch

you will need to down grade your version of Feeds

**Comment by kevindavis338** [comment]
Got it.. Thank you.

**Comment by kevindavis338** [comment]
Got it..
