### ISSUE TITLE
Audit existing automated tests

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2256]
List new PHPunit tests we need
List Behat tests we need
List Behat tests we no longer need
List Behat tests that should be ported to PHPunit
Review PHPunit tests for tests we no longer need
Create follow up tickets

#2269
#2270
#2271
#2272

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by kimwdavidson** [comment]
Won't do
