### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2258]
Just a placeholder for now, but let's start talking about adding two-factor authentication to DKAN out of the box.

## Acceptance Criteria
- Create a 'How-to' recipe in the docs under 'Development'

**Comment by acouch** [comment]
This can be implemented quite easily with: https://www.drupal.org/project/tfa

We aren't adding this to DKAN for now.

**Comment by erogray** [comment]
There's some user demand for this. Reopening.

**Comment by erogray** [comment]
Required by ATO for at least one federal agency. What's the best way to address that? Add to product or as a client customization? @acouch

**Comment by acouch** [comment]
Both options make sense. @dafeder ?

**Comment by kimwdavidson** [comment]
Maybe a recipe, not a modification
