### ISSUE TITLE
Workflow Moderators who do not belong to a group do not see Needs Review content

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2262]
## Description
If a workflow contributor and workflow moderator belong to a group, everything works as expected. However, if neither the contributor nor the moderator belong to a group, content that is submitted for review is not visible to the moderator under 'needs review'

## Steps to Reproduce
1. Workflow Contributor, does not belong to any groups, creates dataset or resource content, submits for review
2. Workflow Moderator, does not belong to any groups, navigates to `admin/workbench/needs-review-active`, the contributor content flagged as needs review will NOT be visible to the moderator under 'Needs Review'

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
