### ISSUE TITLE
Dataset not publish

### ISSUE THREAD

**Issue by kevindavis338** [GetDKAN/dkan#2264]
Hi there,

For some reason when I create a dataset, I can't seem to set the item to publish. Is there a reason why I can't publish the dataset after I create the dataset? 

![screen shot dataset](https://user-images.githubusercontent.com/4030822/33440434-90b7ba7e-d5b5-11e7-9bb5-2733a121300c.png)

**Comment by janette** [comment]
@kevindavis338 
- Do you have dkan_workflow, workbench_moderation enabled?
- What role does your user have?
- What do you see when you click on 'Publishing options'?
- Can you publish it from the `admin/content` screen?

**Comment by kevindavis338** [comment]
- Yes
-  administrator
- Nothing happens when I click on publishing options
- As for admin/content for some reason, it has been blocked out

**Comment by janette** [comment]
Can you rebuild permissions here `admin/reports/status/rebuild`

**Comment by kevindavis338** [comment]
I did a rebuild and still can't get into admin/content

**Comment by kevindavis338** [comment]
issue resovled.
