### ISSUE TITLE
datastore_fast_import.feature tests failing locally

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#2269]
Running `ahoy dkan test /var/www/dkan/test/features/datastore_fast_import.feature` locally fails with:

`
--- Failed scenarios:

    features/datastore_fast_import.feature:36
    features/datastore_fast_import.feature:53
    features/datastore_fast_import.feature:83

5 scenarios (2 passed, 3 failed)
110 steps (107 passed, 3 failed)
7m12.80s (177.07Mb)

`

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by kimwdavidson** [comment]
No longer needed.
