### ISSUE TITLE
dkan_harvest.feature tests failing locally

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#2270]
Running `ahoy dkan test /var/www/dkan/test/features/dkan_harvest.feature` locally fails with:

`
--- Failed scenarios:

    features/dkan_harvest.feature:67
    features/dkan_harvest.feature:145
    features/dkan_harvest.feature:159

19 scenarios (16 passed, 3 failed)
209 steps (199 passed, 3 failed, 7 skipped)
9m17.80s (135.10Mb)
`

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
