### ISSUE TITLE
group.admin.feature tests failing locally

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#2271]
Running `ahoy dkan test /var/www/dkan/test/features/group.admin.feature` locally fails with:

`
--- Failed scenarios:

    features/group.admin.feature:61

17 scenarios (16 passed, 1 failed)
263 steps (259 passed, 1 failed, 3 skipped)
4m38.99s (132.26Mb)
`

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
