### ISSUE TITLE
panels.feature tests failing locally

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#2272]
Running `ahoy dkan test /var/www/dkan/test/features/panels.feature` locally fails with:

`[WebDriver\Exception\UnexpectedAlertOpen]                                                                                                                 
  unexpected alert open: {Alert text : This will discard all unsaved changes. Are you sure?}                                                                
    (Session info: chrome=53.0.2785.143)                                                                                                                    
    (Driver info: chromedriver=2.24.417424 (c5c5ea873213ee72e3d0929b47482681555340c3),platform=Linux 4.13.0-17-generic x86_64) (WARNING: The server did no  
  t provide any stacktrace information)                                                                                                                     
  Command duration or timeout: 8 milliseconds: null                                                                                                         
  Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'                                                                           
  System info: host: 'browser', ip: '172.19.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '4.13.0-17-generic', java.version: '1.8.0_91'             
  Driver info: org.openqa.selenium.chrome.ChromeDriver                                                                                                      
  Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion  
  =2.24.417424 (c5c5ea873213ee72e3d0929b47482681555340c3), userDataDir=/tmp/.org.chromium.Chromium.Vvan4G}, takesHeapSnapshot=true, pageLoadStrategy=norma  
  l, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=53.0.2785.143, platform=LINUX, browserConnectionEnabled=false, nativeEvents=  
  true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSel  
  ectorsEnabled=true}]                                                                                                                                      
  Session ID: 19a77be6fe6784cf522cf522c6a3af06`

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
