### ISSUE TITLE
UTF8 header names in datastore import cause error

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2276]
Hello,

when i tried to import a csv in the datastore with Greek column titles i got the error SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name ''

When i change the header names to English, the import process completes.

**Comment by kimwdavidson** [comment]
Thanks for reporting this, @chrodos. We'll take a look!

**Comment by janette** [comment]
@chrodos can you attach the csv file with Greek column titles to this issue

**Comment by chrodos** [comment]
@janette Sure. This one gives an error.
[problematic.zip](https://github.com/GetDKAN/dkan/files/1583933/problematic.zip)

**Comment by chrodos** [comment]
Now that i give it a better look, It might not be the greek characters the problem, but possible some special characters (e.g., #).

**Comment by chrodos** [comment]
Did you manage to replicate the problem?

**Comment by erogray** [comment]
@stefaniefgray can you replicate this?

**Comment by kimwdavidson** [comment]
@fmizzell: is this ready to re-test?

**Comment by kimwdavidson** [comment]
@fmizzell: is this the same issue as #117?

**Comment by jjalcolea** [comment]
Hi, I'm experiencing a similar issue with UTF8 spanish characters in data fields.  Please find attached the error and a CSV file to reproduce it.
![error](https://user-images.githubusercontent.com/7276480/56948635-0c926100-6b31-11e9-8e59-73850d823c2c.png)


[test.zip](https://github.com/GetDKAN/dkan/files/3130400/test.zip)

**Comment by erogray** [comment]
See also https://github.com/GetDKAN/dkan/issues/117

**Comment by janette** [comment]
Also an issue on DKAN2, fails silently.

**Comment by janette** [comment]
![valid-chars](https://user-images.githubusercontent.com/314172/58737564-bb8fba00-83c7-11e9-8a84-8581acf3a27a.png)

**Comment by janette** [comment]
@chrodos after further testing I think the issue you were running into was having a mysql reserved word/symbol in the header column.

@jjalcolea the file you provided was using the iso-8859-1 encoding, once I converted it to UTF8 it did display the special characters properly.

I will be updating our documentation and closing this issue, let me know if the solutions above do not solve your errors.

**Comment by jjalcolea** [comment]
@janette, you are right, the issue is solved now (or better: there was no issue). Thanks a lot for looking into this!

Best,

Juanje.
