### ISSUE TITLE
Rdf View of content broken in 1.14

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2277]
When you try to view the rdf view of the dataset then you get a 404 error. After checking the logs, this happens because there are some parsing errors in: profiles/dkan/libraries/symfonyserializer/Normalizer/AbstractObjectNormalizer.php

More specifically in lines 235 and 346 there is a ? in front of string in function declaration.

ParseError: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /profiles/dkan/libraries/symfonyserializer/Normalizer/AbstractObjectNormalizer.php).

If you remove this then it works fine.

**Comment by kimwdavidson** [comment]
Hi @chrodos! Thanks for reporting this. We'll get to work on it. Thanks again!

**Comment by janette** [comment]
The fix should be applied to the upstream repo, I sent chrodos to https://github.com/symfony/serializer to create the PR (https://github.com/symfony/serializer/pull/11) but it looks like the PR should actually be against https://github.com/symfony/symfony instead

**Comment by chrodos** [comment]
The **RDF API** is also broken in the demo.getdkan.com. Check http://demo.getdkan.com/dataset/london-deprivation-index.xml .

Error:
`<b>Fatal error</b>:  Default value for parameters with a class type hint can only be NULL in <b>/var/www/dkan_demo/dkan/libraries/symfonyserializer/Encoder/XmlEncoder.php</b> on line <b>47</b><br />`

**Comment by janette** [comment]
I've created a PR on the symfony repo https://github.com/symfony/symfony/pull/25611

**Comment by chrodos** [comment]
Hi @janette Please read my comments here: https://github.com/GetDKAN/dkan-drops-7/pull/62 
I submitted the PR to the symphony repo, but they correctly responded that the questionmarks are valid in PHP 7.1 (this is the minimum version for symphony 4.0). If you read the link above you will understand what is the problem.

**Comment by janette** [comment]
@chrodos thank you for looking into this issue and providing the details, we now have a fix on the board, most likely will be in the next patch release.
