### ISSUE TITLE
DKAN Dataset Search API

### ISSUE THREAD

**Issue by kevindavis338** [GetDKAN/dkan#2285]
Hi there, 

I have at least 440 datasets in the database, however, the search api only gets at least 139.  Not the total amount. 

Is there a reason why it is doing that?

**Comment by janette** [comment]
Have you tried re-indexing? `admin/config/search/search_api/index/datasets`

**Comment by kimwdavidson** [comment]
@kevindavis338: Looks like reindexing fixed your issue, so I'm closing this, but let us know if you're still experiencing a problem.
