### ISSUE TITLE
Add sites to DKAN sites

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2292]
Add these sites to https://docs.getdkan.com/en/latest/introduction/dkan-sites.html: 

* https://dadesobertes.diba.cat/
* http://data.edostate.gov.ng/Home/index.html
* https://opendata.duesseldorf.de/

**Comment by janette** [comment]
| url | notes |
|----|-----|
| https://dadesobertes.diba.cat/ | Already there |
| http://data.edostate.gov.ng/Home/index.html | CKAN site |
| https://opendata.duesseldorf.de/ | Added |
