### ISSUE TITLE
Subtheme functions missing

### ISSUE THREAD

**Issue by alexburrows** [GetDKAN/dkan#2295]
This appears to be subtheme related, however running the drush commands stated it still encounters the following:

`Fatal error: Call to undefined function insight_site_information_theme_settings_form_submit() in includes/form.inc on line 1520`

So searching the code the function is only declared in `nuboot_radix` therefore as its reliant off `  $form['#submit'][] = $theme . '_site_information_theme_settings_form_submit';`

this is set inside `profiles/dkan/themes/nuboot_radix/theme-settings.php`

By adding:

```
/**
 * Submit function for theme settings form information.
 */
function THEMENAME_site_information_theme_settings_form_submit(&$form, &$form_state) {
  variable_set('site_name', $form_state['values']['site_name']);
  variable_set('site_slogan', $form_state['values']['site_slogan']);
  variable_set('site_mail', $form_state['values']['site_mail']);
}
```

fixes it

**Comment by janette** [comment]
Yes @alexburrows the subtheme kit has not been updated for a while, thanks for the reminder.

**Comment by janette** [comment]
theme kit has been updated
