### ISSUE TITLE
Epic: Automated tests should reflect true regressions 

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2305]
_From @kimwdavidson on November 30, 2017 17:54_

Currently our automated tests show many failures that seem to be environmental and not due to real regressions in our code base. This makes it hard to know when real regressions are happening, and even harder to fix them if some tests fail in some environments and not others. 

Solving this issue will require working both on the tests themselves and on the environment the tests run on. Currently the main 2 environments are Circle CI and our local sandboxes.

# Tasks

- 

_Copied from original issue: NuCivic/dkan_management#36_

**Comment by fmizzell** [comment]
https://github.com/GetDKAN/dkan_starter/pull/502
