### ISSUE TITLE
Add 'How to add your company' to help page

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2306]
Can we add this info to the help page in docs (http://docs.getdkan.com/en/latest/community/help.html)?

--

## Add your company

If you provide DKAN development and/or support services, here's how to add your company to business directory:

* create a /dkan page on your website (ex: https://civicactions.com/dkan/)
* create a [new issue](https://github.com/GetDKAN/dkan/issues/new) and include logo, company name, link to /dkan page, brief description of services with respect to DKAN

**Comment by stefaniefgray** [comment]
See https://github.com/GetDKAN/dkan/pull/2346

**Comment by stefaniefgray** [comment]
Page where update will go: http://docs.getdkan.com/en/latest/community/help.html
