### ISSUE TITLE
Extends dataset API to support paragraphs

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2316]
In #2226, We are allowing the API to work with the basic structure of nodes as given by Drupal when a node_load is performed programatically.
In (add reference to enhanced metadata PR), the metadata for datasets can now be extended by adding bundles of metadata fields to the datasets. 

We need to make sure that we can create properly extended datasets through the API.

It is possible that given the correctly structured data, the create and update portions of the dataset API will just work, but we need to make sure.

The goals of this ticket are: 

1. Experiment with the creation and update of datasets with extended metadata bundles to see if there are any issues.
2. Fix whatever issues we might encounter
3. Document any quirks coming from the enhanced metadata when dealing with the API.

**Comment by fmizzell** [comment]
@dafeder Can you think of any other details that we should add here?

**Comment by kimwdavidson** [comment]
Security updates and bug fixes only in the D7 version of DKAN. Closing.
