### ISSUE TITLE
Update contrib modules

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2322]
- [ ] ctools (1.14)
- [ ] field_group (1.6)
- [ ] file_entity (2.21 )
- [ ] globalredirect (1.6)
- [ ] honeypot (1.24)
- [ ] imagecache_actions (1.9)
- [ ] job_scheduler (check revision) (2.0)
- [ ] link (1.5)
- [ ] manualcrop (1.7)
- [ ] media_youtube (3.7)
- [ ] migrate (2.10)
- [ ] panopoly_images (1.54)
- [ ] panopoly_widgets (1.54)
- [ ] rules (2.11)
- [ ] search_api (1.24)
- [ ] select_or_other (2.23)
- [ ] views (3.20)
- [ ] views_bulk_operations (3.5)

**Comment by kimwdavidson** [comment]
Don't think we need these updates. Closing. @janette, if you disagree, go ahead and submit a PR!
