### ISSUE TITLE
Discovery: Fix Pantheon/GUI installer

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2324]
Trying to install DKAN 1.14.1 on Pantheon fails both on the installation step and the post-install. The resulting site is missing the front page and generally unusable. 

* Figure out if the issue is with the GUI installer generally of specific to Pantheon
* Fix!

**Comment by janette** [comment]
```
An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://dev-dkan-test2.pantheonsite.io/install.php?profile=dkan&locale=en&id=1&op=do StatusText: OK ResponseText: Fatal error: Class 'SearchApiIndex' not found in /srv/bindings/e8f0c11e71444ef8b9e2b75cfc1acff5/code/profiles/dkan/modules/contrib/search_api/search_api.module on line 2682
```

**Comment by janette** [comment]
Notice: Undefined index: distribution_name in drupal_install_profile_distribution_name() (line 207 of /srv/bindings/e8f0c11e71444ef8b9e2b75cfc1acff5/code/includes/install.inc).

**Comment by dafeder** [comment]
This is on Pantheon or just running the GUI installer locally?

**Comment by janette** [comment]
@dafeder this is with the Pantheon install, if I enable the dkan modules that should be enabled by default, and create a front page, the site is usable and stops complaining... I did not know there was a local GUI installer

**Comment by janette** [comment]
@dafeder 
Looking at the last dkan drops build on jenkins I saw `ERROR: Permission to NuCivic/dkan-drops-7.git denied to nucivicmachine.` so I logged in as nucivicmachine and accepted the invitation to the repo

I built the dkan-drops repo locally with the GUI and had no errors, built as expected.
I then deleted the pantheon site I created yesterday and used the same link from the docs to try the install again, this time there was 0 errors, not sure what to make of that

**Comment by janette** [comment]
The pantheon spinup is working, Kim is creating a calendar event to periodically check the process an a regular basis
