### ISSUE TITLE
Changelog Management

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2325]
_From @fmizzell on October 18, 2017 16:9_

I am not sure what our current policies are (I have not looked either), but changelogs are a pain. They cause all sorts of conflicts in the codebase.

I would like for the changelog to be automated and standard so we can keep our messy hands out of them, or, if we can not go this far, at least create some new standards to minimize conflicts.

_Copied from original issue: NuCivic/dkan_management#18_

**Comment by erogray** [comment]
_From @fmizzell on December 27, 2017 13:43_

@kimwdavidson Can we consider moving this up in the priority list?

**Comment by kimwdavidson** [comment]
Absolutely - we talked about making this the next item after the branching strategy ticket, and this is in needs spec until that one's done, I think?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
