### ISSUE TITLE
Can't preview resource after import in the Datastore

### ISSUE THREAD

**Issue by marcomacaro** [GetDKAN/dkan#2326]
Hello,
I having problem to preview the CSVs resources after import them in the Datastore and i can't find any log error (Apache, MySQL, ..)
There is no problem to preview it before the import in the Datastore.

![capture](https://user-images.githubusercontent.com/29282337/34890203-4724a0d2-f7d1-11e7-94e3-2747b855ab53.PNG)

I never had this problem with all other installation of DKAN.

Now this is my setup:
DKAN 7.x-1.14
RedHat 7
Apache 2.4.6
MySQL 5.7
PHP 5.6.32

Thanks,
Marco

**Comment by janette** [comment]
@marcomacaro if you are using the fast import option, drop the datastore and try importing with fast import disabled

**Comment by marcomacaro** [comment]
@janette I use normal import. I tried also with fast import but I got the same result.

**Comment by marcomacaro** [comment]
I have analyzed the request and I know that the request URL is 
../api/3/action/datastore_search?=&resource_id=a9ed198e-1b81-46ef-a639-c39cb3d77e22
instead of
..?q=api/action/datastore/search.json&resource_id=a9ed198e-1b81-46ef-a639-c39cb3d77e22

![capture](https://user-images.githubusercontent.com/29282337/34957880-c4c4f536-fa2f-11e7-9d3e-dc69c562577a.PNG)


Thanks,
Marco

**Comment by marcomacaro** [comment]
Ok, i had to enable apache mod_rewrite.

Thanks
