### ISSUE TITLE
Bulk update: Change Value option breaks on validation errors

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2330]
When bulk updating content with the Change Value option the form errors on two validation functions:
 - dkan_harvest_field_attach_validate_source_uri
 - role_export_roles_form_validate

### Steps to reproduce
- Visit the `admin/content` page
- Check a box next to existing content
- Select **Change value** from the operations drop down
- Add/change a value to one of the fields and click **Execute**
- You will see the following errors
```
Machine-readable name field is required.
Source URI protocol not allowed! Allowed protocols are http://, https://, file://, public://, private://
```

### Acceptance Criteria
- User should be able to update field values from the VBO UI on `admin/content`

**Comment by frederic-balu** [comment]
Same issue on LAMP environment.

**Comment by susisiman** [comment]
Closed due to inactivity. Feel free to open!
