### ISSUE TITLE
dkan update issue 1.12.9 to 1.14

### ISSUE THREAD

**Issue by bibinax** [GetDKAN/dkan#2331]
I have updated my dkan version from 1.12.9 to 1.14 and i am getting a PDOException on Update #7018.

> Update #7018
> 
> Failed: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ddc.field_data_field_language' doesn't exist: UPDATE {field_data_field_language} SET field_language_value=replace(field_language_value, :underscore, :dash); Array ( [:underscore] => _ [:dash] => - ) in dkan_update_7018() (line 324 of /var/www/html/ddc/profiles/dkan/dkan.install)
> 

How to resolve this issue?

**Comment by janette** [comment]
You might want to upgrade in steps, 1.12.9 > 1.13.7 > 1.14.1 there were major changes from 1.12 to 1.13

Otherwise you could try adding this update to a custom module and have it run before the 7018 update.

```
/**
 * Add language field.
 */
function hook_update_N() {
  // Check that a language field does not already exist.
  if (!field_info_field('field_language')) {

    // Create the field base.
    $field = array(
      'active' => 1,
      'cardinality' => -1,
      'deleted' => 0,
      'entity_types' => array(),
      'field_name' => 'field_language',
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'locked' => 0,
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(),
        'allowed_values_function' => 'dkan_dataset_content_types_allowed_language_values',
      ),
      'translatable' => 0,
      'type' => 'list_text',
    );
    field_create_field($field);

    // Create the field instance on the bundle.
    $instance = array(
      'field_name' => 'field_language',
      'bundle' => 'dataset',
      'default_value' => NULL,
      'deleted' => 0,
      'description' => 'This should adhere to the RFC 5646 standard. This language subtag lookup provides a good tool for checking and verifying language codes. A language tag is comprised of either one or two parts, the language subtag (such as en for English, sp for Spanish, wo for Wolof) and the regional subtag (such as US for United States, GB for Great Britain, MX for Mexico), separated by a hyphen. Regional subtags should only be provided when needed to distinguish a language tag from another one (such as American vs. British English).',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 17,
        ),
        'search_result' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'label' => 'Language',
      'required' => 0,
      'settings' => array(
        'text_processing' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(
          'apply_chosen' => 1,
        ),
        'type' => 'options_select',
        'weight' => 24,
      ),
    );
    field_create_instance($instance);
  }
}
```

**Comment by bibinax** [comment]
Having same issue when trying to update 1.12.9 > 1.13.7. 

Getting same error message

**Comment by janette** [comment]
@bibinax do you get the error on every page? Can you attach a screenshot? You can try
```
drush rr
drush updb
drush fra -y
```
to make sure all of the dkan updates have been applied.

**Comment by bibinax** [comment]
i tried all these and the error still exists. Also now i am getting one another error , 

> Fatal error: Class 'HarvestMigration' not found in /var/www/html/ddh_199673/profiles/dkan/modules/dkan/dkan_harvest/modules/dkan_harvest_datajson/dkan_harvest_datajson.migrate.inc on line 11 

Checked the module directories. Files and functions are there..

**Comment by bibinax** [comment]
All the issues are occurring when i try to update from 1.12.9 to 1.13.7 or 1.14.1. Created separate instances for  both 1.13.7 and 1.14.1 those are working perfectly. But when i upgrade it, its not working

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
