### ISSUE TITLE
react-jsonschema-form for data dictionary creation

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2335]
## Background

In #2333 we are adding a JSON field and specification selector to create a data dictionary based on the tabular data spec.

## User story

As a data uploader, I want an intuitive way to create data dictionaries without having to enter raw JSON.

## Acceptance criteria

* Override the dictionary data JSON field textarea element with a react-jsonschema-form[https://github.com/mozilla-services/react-jsonschema-form] element
* Add configuration for the form to the plugin architecture for data dictionary specifications
* Form allows us to build valid tabular data specification documents
* Bonus: if the "app" for tabular data spec creation is decoupled from Drupal it would be cool to release this as a tool

**Comment by acouch** [comment]
We will be doing this in D8! Closing for D7.
