### ISSUE TITLE
Data dictionary display and validation

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2336]
## User story

As a site visitor, I want to be able to see a guide to using the data I'm downloading.

## Acceptance criteria

* If tabular JSON data dictionaries are used, we can display the schema in an easy-to-read table on the resource  page, themed similarly to the metadata as it appears elsewhere in DKAN
* If the data dictionary is a simple file, present it as a link on the resource page, themed nicely and with an appropriate icon from our font libraries

## Sample schema
```
n example schema would look like the following. Note that a minimum age of 18 is specified in the Age column and a string that looks like an email address must be present in the Email column:

{
  "fields": [
    {
      "name": "Name",
      "type": "string",
      "description": "User’s name"
    },
    {
      "name": "Email",
      "type": "string",
      "format": "email",
      "description": "User’s email"
    },
    {
      "name": "Age",
      "type": "integer",
      "description": "User’s age",
      "constraints": {
        "minimum": 18
      }
    }
  ]
}
```

**Comment by kimwdavidson** [comment]
Depends on #2333

**Comment by JayDarnell** [comment]
Frictionless table schema: https://frictionlessdata.io/specs/table-schema/
