### ISSUE TITLE
File field for optional upload/linking, allow CSV upload

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2338]
## User story

As a data creator, I want to add a remote or uploaded file to a resource as a data dictionary in the case that creating one on the website is not practical for me.

## Acceptance Criteria

* Data dictionary nodes have a file field as well.
* File field accepts both uploads and URL to remote file (using Filefield Source, already in DKAN core)
* Content types accepted: JSON, CSV, XLS, PDF, DOC, DOCX, XLSX

**Comment by dafeder** [comment]
@kimwdavidson: 

- [ ] Confirm list of file extensions
