### ISSUE TITLE
Convert correctly-formatted CSV data dictionaries to JSON-schema

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2340]
## User story

As a data depositor, I want to be able to create a data dictionary as a CSV but still have it presented as a native (JSON Schma) data dictionary on the data portal, so that I can get the full benefits of the native functionality but define my columns using my own spreadsheet workflow.

## Acceptance criteria

* Define a CSV format that maps to our JSON/frictionlessdata schema for tabular data
* If an uploaded data dictionary is a CSV and validates to our standard, automatically convert to JSON and store in the data field of the _data dictionary_ node
* If an uploaded data dictionary is not in CSV, or is CSV but doses _not_ validate, display a simple status message: "Your data dictionary is not in a format that this system recognizes. It will be presented as a simple file link. Click here to read more about creating data dictionaries that are compatible with the tabular data schema standard, which will integrate with more of the built-in functionality on this data portal." (This copy is subject to change and open to criticism!)

Depends on #2338

**Comment by JayDarnell** [comment]
Pull request 2406 tackles this issue. The one item I wasn't sure of was where the "Click here" link should point to in the event the supplied CSV file was not in a recognized format.
