### ISSUE TITLE
Get user guide content into read the docs

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2342]
https://docs.google.com/document/d/1FeNw5DGd_GUM3v2XD8NxRjfy2Vxwp5Fpu_BjJ4mIG5o/edit#heading=h.gjz9143nm8zs

https://docs.google.com/document/d/1wLx7JT8D-6k68qUis0HeDFxraAjcd_r_eVycnGN0eig/edit?usp=sharing

**Comment by janette** [comment]
Keep an eye out for duplicate content, lets merge the info from these sections and replace one of them with a link to the other:
- http://dkan.readthedocs.io/en/latest/admin/people/group_roles_and_permissions.html
- http://dkan.readthedocs.io/en/latest/components/dataset/groups.html#managing-groups-and-members

**Comment by erogray** [comment]
Closing since initial purpose of ticket has been accomplished, see also #2629
