### ISSUE TITLE
Discovery: Scientific ontology support

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2344]
Many science data platforms have a need to support complex hierarchical ontologies to classify their data. Build a widget that could be used to drill down and select a field from a large (60,000+ object) ontology and store that value in a simple way in the database. Then display it in a way that shows the context in the hierarchy.

## Acceptance criteria

* Ontologies must be converted to JSON and then exposed to the module via an API. The [obographs]
(https://github.com/geneontology/obographs) spec looks promising
* Javascript widget can show a tree built from a JSON ontology
* A single term can be selected. This term is then stored as a field value with any relevant metadata
* On node display, the selected term is displayed with its parents, for instance `Business > Store > Grocery Store` 

NOTE: This will be added to the dkan_sci_metadata module

**Comment by csparr** [comment]
@dafeder wanted an assessment of whether this is still useful.

I see we first suggested it in the context of the Fundref vocabulary. This is not particularly a scientific vocabulary content-wise, but it is one of the custom, externally created vocabs that seems necessary for most scientific datasets.

In our case, we also use the NAL thesaurus, other projects are probably using their own ontologies.

So the point here is that it is a common need to apply terms from an externally created controlled vocab. Heck, this is also the case with POD 1.1 program and bureau codes and the ISO Topic Codes, both of which are used for data.gov and therefore useful for DKAN core.

I can't remember if we have rational machine-readable output in the RDF and JSON that includes the external URIs for these terms; that's a consideration too.

If this is NOT provided in the product, then it should be clear in documentation what is the most DKAN friendly customization process we all should be following.

**Comment by dafeder** [comment]
We've done project-specific custom solutions for this in different cases, and don't have any specific plans around this for DKAN2 yet but there are some good ideas in this ticket we may return to. Closing for now.
