### ISSUE TITLE
Document available modules for DKAN

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2348]
From @nerdstein: 
It would be nice if we had a directory of community sponsored modules listed on the website. It could be a list of name, purpose, and link to the code repo.

Here are a few from Angry Cactus:

https://github.com/angrycactus/dkan-harvest-collector - Add the concept of "data.json collectors"
https://github.com/angrycactus/dkan-harvest-secop - And a plugin for the above module that crawls a government website for csv links and collects them into a data.json file for harvesting by the harvester
There will certainly be more.It would be nice if we had a directory of community sponsored modules listed on the website. It could be a list of name, purpose, and link to the code repo.

Here are a few from Angry Cactus:

https://github.com/angrycactus/dkan-harvest-collector - Add the concept of "data.json collectors"
https://github.com/angrycactus/dkan-harvest-secop - And a plugin for the above module that crawls a government website for csv links and collects them into a data.json file for harvesting by the harvester
There will certainly be more.

From @lukefretwell:
FYI I asked AC if they could add more info to the repos:

angrycactus/dkan-harvest-secop#1
angrycactus/dkan-harvest-collector#1

**Comment by kimwdavidson** [comment]
Kim to make an ask in Slack and compile

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
