### ISSUE TITLE
Error on catalog.xml generation

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2349]
```
Error: Default value for parameters with a class type hint can only be NULL in /mnt/www/html/ridata/dkan/libraries/symfonyserializer/Encoder/XmlEncoder.php, line 47
```

This should fix it https://github.com/GetDKAN/open_data_schema_map/commit/13abe7420cf63af52f8b2cd004ef8b54ce3f0410

This is merged into 1.14.1 so sites on 1.14 will not be able to view `domain.com/catalog.xml` until they are upgraded

**Comment by kimwdavidson** [comment]
@janette: Is this fixed? Do we still need this ticket?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
