### ISSUE TITLE
Is there a process for capturing relevant discussion from Slack into documentation?

### ISSUE THREAD

**Issue by lukefretwell** [GetDKAN/dkan#2350]
Reference: https://github.com/GetDKAN/ops/issues/93

via @nerdstein:

Since DKAN slack is not a paid Slack, it does not have an archive. This limits the use of things like pinned items, which can help to persistently track useful items.

One other option is to consider a process in which relevant Slack conversations are subsequently tracked within DKAN's github documentation.

Are there any thoughts on how this could be done?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
