### ISSUE TITLE
Discovery: Bulk uploader?

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2352]
As a data provider using DKAN, I would like to be able to directly add data resources in bulk, preferably while specifying metadata for each batch.

**Comment by dafeder** [comment]
Do you mean you would create a new dataset for each resource upon upload? Perhaps this could be achieved by zipping everything up together and following the [Data Package Specification](https://frictionlessdata.io/specs/data-package/). 

For now I think we'd need to write scripts to do this over the API.

**Comment by kimwdavidson** [comment]
@erogray What do you think about Dan's solution? Would that work?

**Comment by erogray** [comment]
A Zip file uploader would definitely be useful.

It seems like there's a need among users for both bulk uploads and bulk metadata changes (since some folks have tried to use Harvest for both purposes), so developing a UI for one or both of these purposes would be smart. 

Developing a reliable script to do this by API would also be of immediate use to some current users.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
