### ISSUE TITLE
Improve dataset author vs. author labeling

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2353]
Datasets have both an Author and also an Author. These do different things, and this can cause confusion and user error. Improved helptext and/or field labels might make it easier to avoid problems.

![Screen Shot 2018-02-01 at 4.15.37 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599edcd72c5115001a3d84b6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f26b7191a37cf1132e4f5c585ecc3c4a4356bcbbd671f3e57862804e0ee480695a72c33517afebd71bbe01ba248e1e8de3b8824dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ce44e55a2133565e7702431.png)

and also 

![Screen Shot 2018-02-01 at 4.15.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599edcd72c5115001a3d84b6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f26b7191a37cf1132e4f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ee480695a72c33517afebd71bbe01ba248e1e8de3b8824dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ce44e55a2103766e4762431.png)

## Acceptance criteria

* Label the dataset field as "Dataset Author"
* Modify the helptext for the node author field to say _User who owns this piece of content. This will not be part of the public metadata and is independent of the dataset's "Author" field._

**Comment by kimwdavidson** [comment]
@erogray: Could we just remove the "Authored By" field? Otherwise, we could make it say "Created by" instead?

**Comment by erogray** [comment]
The Dataset Author field serves a useful metadata purpose and is heavily used by some sites. We shouldn't remove it. The Drupal Authoring Information fields are baked into Drupal and also shouldn't be removed. 

I don't think a name change for the Author field is a good solution, on the theory that it follows metadata standards (though I don't see specific info about 'Author' on either https://www.w3.org/TR/vocab-dcat/ or https://project-open-data.cio.gov/v1.1/schema/), so perhaps I'm wrong? 

My inclination is just to improve the helptext for user-friendliness. Right now the Dataset Author says "This is the author of the dataset." But as a user adding data in a hurry, this doesn't add much value. Something more like "This information will be shared publicly to show the author of the dataset."

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by erogray** [comment]
A related question came up just this morning; I think this is a valuable ticket.

**Comment by susisiman** [comment]
Closed due to inactivity. Feel free to open!
