### ISSUE TITLE
DKAN SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2357]
In **DKAN 7.x-1.14** when i try to import a specific CSV file (attached:[test_file.zip](https://github.com/GetDKAN/dkan/files/1699659/test_file.zip)) I get the error 

> DKAN SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column "COLUMN NAME".

I checked the table created and i found an int type in the field that should actually be bigint. 

If i manually change the fields type to bigint the problem is resolved, but DKAN should automatically detect that.
This is probably related to https://github.com/GetDKAN/dkan/issues/1347
Actual error to test: 
> SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'actual_expenditure_2013' at row 1

**Comment by dafeder** [comment]
@chrodos - as designed, if you're using feeds (the default datastore importer) the parser only looks at the first 50 rows to determine the column type. It looks like from your CSV that the values that would trigger a bigint are too far down to be detected. It would be I think too expensive to parse the entire file to determine column types beyond any doubt. For now I think the option is what you've done, to change manually and re-import, but we are working on user-defined schemas for resources, and hopefully a new workflow where there is a step to confirm or modify a resource's schema before importing.

**Comment by chrodos** [comment]
@dafeder I understand that this will increase the load. I totally agree with the additionally step to verify the auto detected schema and people can change the wrongly identified fields. The workaround is valid, but unfortunately it requires direct access to the DB and this is not suggested for people that don't have the necessary experience.

Thank you.
