### ISSUE TITLE
Discovery: improve logging?

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2361]
As a DKAN administrator, I'd like to easily learn when and how large changes to my site happened so that I can better recover from one-time problems and better diagnose ongoing issues.

**Comment by kimwdavidson** [comment]
@erogray:  Can you provide some use cases?

**Comment by erogray** [comment]
Possible situations that'd benefit from better logs include
- cron problems 
- failed datastore imports
- harvest problems

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
