### ISSUE TITLE
Enable Password Policy module

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2362]
Per Acquia Insight (Security category):

---

**Details**
Requiring your site members to use passwords with some base degree of complexity can help protect their accounts and your site from intrusion. This is particularly true in the case of privileged users and administrators. The [Password Policy](https://drupal.org/project/password_policy) module can help enforce these rules.

**Actions / resolutions**
Enable the [Password Policy](https://drupal.org/project/password_policy) module. The configuration options will vary based on your site's user base and purpose, but here are some suggestions that will get you started with minimal intrusion into your members' experience.

Visit /admin/config/people/password_policy/add on your site. Name the policy something like **Strict**, and select all privileged roles on your site. Set these values: Length 10, Punctuation 1, and Username 1. This will require your administrators to have a password at least 10 characters long which includes at least 1 character that isn't whitespace or alphanumeric, and cannot contain their username. Click **Create**.
Return to /admin/config/people/password_policy/add on your site. Name the policy something like **Loose**, and select all less-privileged roles on your site. Set these values: Length 8 and Username 1. This will require your non-administrators to have a password at least 8 characters long which cannot contain their username. Click **Create**.
Adjust these to taste, but remember that excessively long or complex password requirements can be a severe impediment to use for many of your members.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
