### ISSUE TITLE
Enable Username Enumeration Prevention module

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2364]
Per Acquia Insight (Security category):

---

**Details**
There are a few channels through which attackers can discover usernames on your website, increasing those accounts' vulnerability to brute force attacks. The [Username Enumeration Prevention](https://drupal.org/project/username_enumeration_prevention) module addresses the most common methods of discovery, the password reset form and the Views module's autocomplete path.

If you have your site usernames set to email addresses it's even more important to limit their public display.

**Actions / resolutions**
Enable the [Username Enumeration Prevention](https://drupal.org/project/username_enumeration_prevention) module on your website. It has no configuration options, so its benefits will happen immediately.

**Comment by erogray** [comment]
Nice to have but low priority-- will icebox for now unless requested by a client.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
