### ISSUE TITLE
Discovery: Worth it to Enable Views Litepager module?

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2366]
Per Acquia Insight (Performance category):

---

**Details
If your site does not use views, please ignore this alert**

The Views Litepager module solves a problem of scalability for sites with large amounts of content. Drupal's core pagination system creates a pager navigation that shows exactly how many pages of content exist for the content list. This requires that a COUNT query be executed based on the query used to generate the list.

While COUNT queries are blazingly fast on tables with MySQL's MyISAM engine, they are painfully slow when using InnoDB tables (which is the recommended engine type for high traffic Drupal sites). The COUNT queries quickly degrade the more rows a table has.

The Views Litepager module solves this problem for Views pagination by providing a pager option that does not require a COUNT query to be executed. This "Lite" pager is only slightly less useful than Drupal's core pager in that it does not allow you to navigate to the "last" page and does not show how many total pages of content there are. But for large sites, this small cost in features is worth the boost in performance by ridding your pages of the painfully slow (and sometimes crippling) COUNT queries. [Learn more](https://drupal.org/project/views_litepager).

Actions / resolutions
Enable the [Views Litepager module](http://drupal.org/project/views_litepager) and use it as your paging mechanism for large views.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
