### ISSUE TITLE
Discovery: Problem adding url with greek characters

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2372]
When I try to add the URL https://www.moh.gov.cy/MOH/phs/phs.nsf/dmlovernight_gr/dmlovernight_gr?OpenDocument&highlight=διημερεύοντα to a resource I get the error messages:

> The value http://www.moh.gov.cy/MOH/phs/phs.nsf/dmlovernight_gr/dmlovernight_gr?OpenDocument&highlight=διημερεύοντα provided for Link API is not a valid URL.
    Please enter a full url (include http:// or https://)

The URL is valid.

DKAN installed: 7.x-1.14

**Comment by kimwdavidson** [comment]
Thanks for reporting - we'll try to get to this soon. Please feel free to submit a pull request if you think you see a way to fix it!

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
