### ISSUE TITLE
Discovery: Datastore import options go away when not choosing Fast Import

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2382]
When importing to datastore, selecting Fast Import feature presents options to select delimiters, read empty cells as null, etc, but those options vanish when you aren’t using Fast Import. 

As a user adding content to the datastore, I'd like to be able to choose these options when not using Fast Import.

**Comment by kimwdavidson** [comment]
This is by design - those options are only needed for Fast Import. The other option detects these options on its own.
