### ISSUE TITLE
Fix Docker to allow local use of Fast Import

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2386]
Need to fix Docker to allow local use of Fast Import

**Comment by erogray** [comment]
@fmizzell is this still required/appropriate?

**Comment by fmizzell** [comment]
@erogray Yes. It is still not working. Fast import is still a very fast useful solution for files stored in our servers so we should make our docker sandboxes work.

I did quite a bit of research and experimentation but was not able to get a working solution. I managed to get Drupal to be able to run the "LOAD DATA INFILE" query, but it had to be as the root db user, and even then there are are some problems with the configuration that will not allowing the db server to see the file. Further work and experimentation is needed.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
