### ISSUE TITLE
Datastore API using API path as "query" value for full text search

### ISSUE THREAD

**Issue by grugnog** [GetDKAN/dkan#2387]
An initial API request (e.g. from recline) comes in to:
https://data.ca.gov/dataset/data-update-automation/resource/api/3/action/datastore_search?=&resource_id=UUID&limit=0

This is then redirected (probably by hook init or boot in https://github.com/GetDKAN/dkan/blob/7.x-1.14.3/modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module#L163) to:
https://data.ca.gov/api/action/datastore/search.json?resource_id=UUID&limit=0&query=dataset/data-update-automation/resource/api/3/action/datastore_search

The "query" parameter is then (in a way that is quite nonsensical) used as a full text search value for those fields, resulting in a query like:
```
SELECT t.* FROM {feeds_datastore_dkan_file_123} t WHERE (MATCH(textfield1, textfield2, textfield3) AGAINST ('dataset/data-update-automation/resource/api/3/action/datastore_search' IN BOOLEAN MODE)) ORDER BY t.feeds_flatstore_entry_id ASC LIMIT 20000 OFFSET 0
```

**Comment by susisiman** [comment]
Closed due to inactivity. Feel free to open!
