### ISSUE TITLE
Fast import does not create FULLTEXT indexes

### ISSUE THREAD

**Issue by grugnog** [GetDKAN/dkan#2388]
Among other issues this leads it to use a fallback query structure in https://github.com/GetDKAN/dkan/blob/cf643568bd408dc6da3fc9f9488728b975e083fa/modules/dkan/dkan_datastore/modules/dkan_datastore_api/dkan_datastore_api.module#L690

**Comment by kimwdavidson** [comment]
@fmizzell: is this still needed?

**Comment by susisiman** [comment]
Fast import has been deprecated.
