### ISSUE TITLE
API requests to fast imported datastores do not return table field names/types

### ISSUE THREAD

**Issue by grugnog** [GetDKAN/dkan#2390]
You can see this during API requests to a fast imported datastore - the fields JSON object will be contain only empty/null fields.

It appears that this is caused by some metadata not being stored (or being stored incorrectly) during the import. In other words the data table itself is not the issue (tested by manually dumpling fast imported data into a table created by a non-fast run, after which the API still worked fine). I didn't identify where exactly this metadata differs between fast and non-fast imports, but my guess would be in either the feeds or the data module tables.

**Comment by kimwdavidson** [comment]
@erogray @janette : on the fast import, is the import being queued or is running in the browser?

**Comment by janette** [comment]
@kimwdavidson it is queued, but rarely finishes

**Comment by dafeder** [comment]
DKAN v1 issue, closing due to EOL.
