### ISSUE TITLE
Geocoder for existing datastore resources

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2391]
## User Story

As a data uploader, I want to geocode existing resources in the datastore, so that I can plot tables with address data on a map.

## Background

The [feeds_flatstore_processor](https://github.com/GetDKAN/feeds_flatstore_processor) module, used to load CSV resources into the datastore, provides integration with the geocoder module, but only does geocoding _during import_. This creates a number of problems for the import itself, and anyway Feeds is being phased out of the datastore in favor of faster, simpler options.

See the [`FeedsFlatstoreProcessor` class](https://github.com/GetDKAN/feeds_flatstore_processor/blob/master/FeedsFlatstoreProcessor.inc) for specifics on how datastore columns are passed to the geocoder.

A better option would be to build an integration with geocoder that can be run on an _existing_ datastore resource. Perhaps in the "manage datastore" tab on a resource, an additional section for geocoding could be added. This would iterate through an existing resource, add coordinates columns with standardized names, and geocode line-by-line.

The "manage datastore" form on resources is defined [here](https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_datastore/includes/DkanDatastore.inc#L152).

## Acceptance criteria

* Create new module: dkan_datastore_geocoder
* New module would still use the [https://www.drupal.org/project/geocoder](Geocoder) module for geocoder account management
* We will probably need to create a [Batch process](https://www.drupal.org/docs/7/api/batch-api/overview) to iterate through groups of rows (10 at a time? 50?)
* Assume that attempting the geocode an entire resource at once will probably fail (API limits, timeouts etc), so we need a way to track progress and pick up where we left off.
* While probably not necesarry for an MVP, we should have a way to configure
  1. How many addresses to geocode per hour or day
  2. A global counter that tracks progress toward that limit
  3. A [queue system](https://api.drupal.org/api/drupal/modules%21system%21system.queue.inc/group/queue/7.x) that schedules chunks of rows to be geocoded on cron runs untill all queued rows for all resources selected for geocoding have been processed.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
