### ISSUE TITLE
Discovery: Add CSV support to API

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2392]
DKAN currently offers a Datastore API to work with resources managed by the DKAN datastore (https://dkan.readthedocs.io/en/latest/apis/datastore-api.html).

The API returns the results from API query in many formats (JSON, YAML, XML, etc). While these formats are popular, the CSV format is highly supported by many Open Data platforms like DKAN and other data related applications. 

The DKAN API currently does not support returning the results from an API request in CSV format which can keep us from being able to integrate with many of these data management, visualization, and analysis  tools.

## Implementation Details

The Datastore API leverages the drupal services module (https://www.drupal.org/project/services) for most of its functionality. The custom functionality for the API is located in the module `/dkan_datastore/modules/dkan_datastore_api`.

The formats in which the API returns the request are not actually custom, they are provided by the services module. 

Sevices also offers a hook to register new formatter types, in a per server basis. Look at the function `rest_server_response_formatters()` in `/services/servers/rest_server/rest_server.module` for further details.

The following tasks should fulfill the goals of this issue:

- [ ]  Creating a services formatter that outpus CSV and works with the rest_server.
- [ ] Configure the Datastore API in DKAN to work with the new formatter.

**Comment by schnuerle** [comment]
DKAN API Docs: http://dkan.readthedocs.io/en/latest/apis/datastore-api.html#parameters

Test API endpoint with Louisville crime data: https://data.louisvilleky.gov/api/action/datastore/search.json?resource_id=f550700b-23b6-426f-b18f-7423ec290ce6&limit=5

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by schnuerle** [comment]
I think is a really important feature, and one that doesn't seem too difficult to implement, would allow wider use of the API, and it being a much simpler output that is a subset of the JSON or XML.

**Comment by acouch** [comment]
@schnuerle Thanks for re-opening. Agreed this would be a nice feature.

Looks like this module https://www.drupal.org/project/services_rest_csv_response would make that possible without additional coding.

One reason we've hesitated to implement this is that if a user uploads a csv and adds it to the datastore and then the datastore is updated the uploaded CSV would no longer reflect the updated data in the datastore. Adding the CSV endpoint wouldn't necessarily make that easier so maybe we could add this before handling "switching" the uploaded CSV file to the datastore or updating the existing file. We will discuss internally and post an update.

**Comment by kimwdavidson** [comment]
Security updates and bug fixes only in the D7 version of DKAN. Closing.
