### ISSUE TITLE
Explore and Integrate Recline preview options for grid View

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2393]
It has been a long time since we've taken a step back and looked at current features available in the [Recline.js](http://okfnlabs.org/recline/) library and how we might better leverage them in DKAN. Let's take a look at the grid view specifically.

Currently, when previewing uploaded resources as a grid, the default limit is 100 records. That makes it harder for the user to really get a sense of how very large files would appear. 

Some ideas:
- Increase the number of datapoints to ... 1000? 10,000?
- Make it very obvious on the preview that you are looking at only a portion of -
 the data set (e.g display a label that says something like: Displaying 10,000 of 50,000 records. Change dataset visualization size.)
- Make it easy to increase the number of datapoints displayed by the preview.
- Consider creating a mechanism to change the default preview record number size in configuration settings somewhere.
- Improve styling to give less of a 90's spreadsheet look

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
