### ISSUE TITLE
Discovery: Explore and integrate Recline preview options for chart view

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2394]
It has been a long time since we've taken a step back and looked at current features available in the [Recline.js](http://okfnlabs.org/recline/) library and how we might better leverage them in DKAN. Let's take a look at the chart/graph view specifically and explore how we could:

* Improve the UI and layout
* Add better help text

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
