### ISSUE TITLE
Discovery: Explore and integrate Recline preview options for map view

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2395]
It has been a long time since we've taken a step back and looked at current features available in the [Recline.js](http://okfnlabs.org/recline/) library and how we might better leverage them in DKAN. Let's take a look at the map view specifically and explore how we could

* Better show more than 100 points at a time
* Filter by columns
* Sorting by date/other fields
* Display different icons
* Auto link KML/GeoJSON over to google/other online map service - (note - in the [DKAN Recline module](https://github.com/GetDKAN/recline) there is already some functionality along these lines, outside of Recline.js)

Other possibilities:

* Add [choropleth functionality](https://github.com/GetDKAN/recline.view.choroplethmap.js)?
* ...

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
