### ISSUE TITLE
Sort search results by date added

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2396]
As a data consumer, I should be able to sort dataset search results by date added, so that I can find the most up to date information.

* Add "Date created" to the list of sort options on the search page
* When selected, sort nodes on their `created` property

The dataset search page (a page manager page + a view) is primarily defined in the dkan_sitewide_panels module.

To see current search results:
- Go to demo.getdkan.org
- Click on Datasets in the navigation to see dataset search results

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
