### ISSUE TITLE
Search results sorted and grouped by group/publisher

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2397]
As a data consumer, when I search for datasets, I should have the option to see them sorted by group, so that I can browse according to groups I'm interested in. 

*  "Group" would be an option in the sort options at the top of the page.
* If group is selected, results would be "grouped" inside a box for each group, so it would be clear where one group ends and other begins.

The dataset page is primarily defined in the dkan_sitewide_panels module.

To see current functionality:
- Go to http://demo.getdkan.com/
- Click on the Datasets link in the navigation to see the current search results

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
