### ISSUE TITLE
Document Disqus commenting functionality for datasets

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2398]
As a user, I should be able to comment on datasets, so that I can communicate with the publisher and other parties also interested in the dataset. 

## Background

While Drupal contains its own commenting system, we want to avoid the maintenance headache of giving user accounts to the many users who could be registering to comment. We have had success integrating with [Disqus](https://disqus.com/) in the past.

A module exists for DKAN/Disqus integration but it is very out of date: https://github.com/NuCivic/data_disqus

It may or may not be easier to start from scratch and build a new module based on the [Drupal Disqus](https://www.drupal.org/project/disqus) module. An integration module will still be needed to capture configuration settings for the dataset content type.

To see a dataset:
- Go to demo.getdkan.com or your local sandbox
- Click on Datasets in the navigation
- Choose a dataset from the search results

**Comment by SalahMessaoud** [comment]
I worked on something similar, probably it needs some improvements  https://github.com/NuCivic/dkan_feedback
### On dataset page
![related_feedback](https://user-images.githubusercontent.com/1775858/36642096-7df9c5fc-1a3a-11e8-9567-1f590289fcde.png)
### Full content of the comment
![comment_page](https://user-images.githubusercontent.com/1775858/36642095-7de45fdc-1a3a-11e8-9c82-9a84526a5cb9.png)

**Comment by dafeder** [comment]
Thanks @SalahMessaoud - this ticket is specifically to integrate the Disqus service

**Comment by schnuerle** [comment]
To me it seems the new Drupal Disqus module should be the way to go.  https://www.drupal.org/project/disqus  

Our site is Drupal 7 so that looks good.  There are some instructions for it.

**Comment by acouch** [comment]
Lets at least add this to the docs.

**Comment by kimwdavidson** [comment]
Security updates and bug fixes only in the D7 version of DKAN. Closing.
