### ISSUE TITLE
"Your file for this resource has been added to the datastore." seems overly sticky

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2400]
The "Your file for this resource has been added to the datastore." message seems to appear inappropriately on pages that don't necessarily call for it (for instance, it can show up on a data story!).
![Screen Shot 2018-02-20 at 1.00.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599edcd72c5115001a3d84b6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456f36b7191a379f1122b4f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ee480695a72c33517afebd71bbe01ba248e1e8de3b8824dd2f42f67b6d5db1063474f4dcbed5727a19041c95df742e04b55a1163e6ae6772431.png)

**Comment by kimwdavidson** [comment]
@erogray: is there any pattern you see to get this message? maybe running a datastore import in another window while you're in this one or something like that?

**Comment by erogray** [comment]
I'm not sure; it has definitely shown up on days where I had not personally imported anything to the datastore. But perhaps someone else had?

I was, for instance, able to visit the CDT DKAN site, login, then visit a random resource (https://data.ca.gov/dataset/caltrans-traffic-volumes/resource/90286025-4b62-427f-8282-38880e20ee7a), and see the message show up.

**Comment by dafeder** [comment]
I think the expected behavior is for this to always show up to logged-in users with permission to manage the datastore, so it's clear on the resource page if they're seeing data from the file or the API. I agree there is probably a better way to display this information that wouldn't look like some operation was just completed.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
