### ISSUE TITLE
Grid columns too narrow to read header

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2408]
We hear about this issue frequently, and we'd love for it to work better! Currently, previewing a resource in the grid format is difficult, because the narrow columns mean you often can't see longer column headers or datapoints with more text. The columns can be manually resized, but it's difficult to tell that's an option.

To replicate:
- Log in to DKAN
- Click on the content link in the navigation
- Choose a dataset like "Florida Bike Lanes"
- Note the narrow columns

Some ideas:
- Default column width to fit their headers
- Default previews to be the full width of the preview space
- Add help text to point out that columns can be manually resized

**Comment by dafeder** [comment]
The grid comes from recline.js, the data previewing library we share with CKAN.

The library is pulled in by the recline module, maintained here: https://github.com/GetDKAN/recline.js

...and that pulls in our own fork of the Recline library: https://github.com/GetDKAN/recline

**Comment by janette** [comment]
set `fitColumns: true`
https://github.com/okfn/recline/blob/master/src/view.slickgrid.js#L63

![dkan](https://user-images.githubusercontent.com/314172/36924227-7069d470-1e33-11e8-8698-18cd13e2b918.png)

**Comment by kimwdavidson** [comment]
Security updates and bug fixes only in the D7 version of DKAN. Closing.
