### ISSUE TITLE
Update the DKAN Drops 7 package

### ISSUE THREAD

**Issue by odvietnam** [GetDKAN/dkan#2413]
Hi developers,

Do you intend to keep the DKAN Drops 7 package updated with newest Drupal and modules? If not, what is the alternative option?

Thank you!

**Comment by janette** [comment]
Yes @odvietnam DKAN Drops 7 will be updated this week

**Comment by odvietnam** [comment]
Thank you! That would be very helpful.

**Comment by janette** [comment]
@odvietnam here it is https://github.com/GetDKAN/dkan-drops-7/releases/tag/7.x-1.14.4
