### ISSUE TITLE
Discovery: file storage via S3

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2414]
Some clients need to store large amounts of files, which is impractical using current storage scheme. 
https://docs.acquia.com/acquia-cloud/manage/files/about
https://docs.acquia.com/article/using-external-storage-files

We should look into decoupling files storage, such that large files can be kept on S3. 

https://www.drupal.org/project/s3fs
https://www.drupal.org/project/s3fs_cors
https://www.drupal.org/project/amazons3

**Comment by fmizzell** [comment]
@erogray Given that #2428 provides a lowly-integrated yet workable solution to use S3 as a storage mechanism to keep large files, do we still need this open?

**Comment by erogray** [comment]
Closing in favor of https://github.com/GetDKAN/dkan/issues/2179 and https://github.com/GetDKAN/dkan/pull/2428 - Discovery seems complete.
