### ISSUE TITLE
Enable multipart API uploading for large files

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2415]
API uploads of large files are problematic in a number of ways. Breaking those files into smaller files, then uploading and reassembling them, would solve most of these issues.
https://www.drupal.org/project/httprl might be one approach.

**Comment by erogray** [comment]
It might be useful to keep https://github.com/GetDKAN/dkan/issues/2414 in mind as well.

**Comment by janette** [comment]
## Option 1
S3 integration

## Option 2

- Add additional endpoint (append)
- use post_process_alter on attach_file
- (count columns to validate)
- use fwrite to append the existing file

https://www.drupal.org/project/services/issues/1484992#comment-6159510

**Comment by grugnog** [comment]
@kducharm has a bunch of S3 upload experience that might be useful here

**Comment by erogray** [comment]
@fmizzell is this ticket still our path forward?

**Comment by erogray** [comment]
@fmizzell is this still a thing, or can we close this?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
