### ISSUE TITLE
Indicate on dashboard if a harvest is in progress

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2416]
The Harvest UI has some limitations that can be confusing for users.
1. Harvests sometimes display 500 or other errors, despite still being in progress. Ideally this error would be more accurate and/or verbose, so that users would know that the Harvest was still operating.
2. The Harvest Dashboard itself (/admin/dkan/harvest/dashboard) should show in-progress harvests as in-progress.

See also https://github.com/GetDKAN/dkan/issues/2460

**Comment by erogray** [comment]
@erogray will try to replicate this.

**Comment by erogray** [comment]
To replicate: 
1. in a vanilla DKAN instance, create a new harvest from https://www.data.va.gov/data.json.
2. wait an hour or so as the harvest proceeds, until it stops proceeding.

**Comment by paul-m** [comment]
More current Harvest documentation here: https://dkan.readthedocs.io/en/latest/user-guide/guide_harvest.html

In DKAN 2.x, we currently have the various harvest-related Drush commands, and the harvest list UI available at the path `admin/dkan/harvest`. From there you can click through to the dataset import status dashboard at `admin/dkan/datastore/status`.

Please follow up with a new issue.
