### ISSUE TITLE
Datapreview errors after import into datastore

### ISSUE THREAD

**Issue by LeKono** [GetDKAN/dkan#2417]
Hey guys,

I am pretty new to DKAN and all the cool stuff it is able to do. I encountered an error that gives me headache for the past week. My installation works fine so far, I create a new dataset and upload a .csv file which previews just fine in the grid view.
DKAN announces that the data is not yet stored in the datastore and that I should do that via the Manage Datastore view. And that is where the problem starts.

I go there and hit 'import', it also imports successfully but as soon as I go back to the view it plainly shows me an 'error' with no error-code what so ever it just says 'error' where the grid preview should be.

I checked the console in the process and found that the URL that is called for the preview
`localhost/api/3/action/datastore_search?=&resource_id=736d1890-9fe8-43e3-acad-267c6407bb97&limit=0`
gives me the error. I don't know if I have done something wrong in the setup process?

I use a self build docker container located at `https://hub.docker.com/r/lekono/mykan/` so I can use a clean version for testing on different machines every time. I also used the DROPS-7 version of DKAN.

I hope someone can help me with this.

Thank you in advance :)

**Comment by LeKono** [comment]
Okay. I have enabled rewrite module for Apache2 and added

`<Directory ...>
AllowOverride All
</Directory>`

Seems like there were issues with the URL redirection, everything working fine now. :)

**Comment by manduda** [comment]
I have the same problem. After import into database, datapreview show "Error". 

> Okay. I have enabled rewrite module for Apache2 and added
> 
> `<Directory ...> AllowOverride All </Directory>`
> 
> Seems like there were issues with the URL redirection, everything working fine now. :)

This solution is not working for me. Rewrite module was already enabled.
