### ISSUE TITLE
Discovery: Bug: Unpublishing and then re-publishing Harvests from the same URI cause dataset conflicts

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2433]
As discovered in https://github.com/NuCivic/client-usva-data/issues/107, re-running a modified harvest that results in deletion or unpublishing of existing datasets seems to fail to delete/unpublish correctly, meaning that the datasets can no longer be replaced or deleted without a migrate-rollback and migrate-deregister step.

See especially https://github.com/NuCivic/client-usva-data/issues/107#issuecomment-373867892 for the fix.

**Comment by erogray** [comment]
Cases of known problems: 
1. create a harvest from a single source, and run it so that datasets are created.
2. edit the harvest to exclude some of the datasets, so that the datasets are deleted.
3. create a new harvest to filter so that it only gets the previously excluded datasets.
This will run into trouble because it's trying to re-create incompletely deleted datasets.

The other version of this problem is:
1. create a harvest, and run it so that datasets are created.
2. unpublish the harvest (and thus its datasets).
3. find the datasets in the content menu, and delete them.
This creates "zombie" datasets that cannot be completely deleted.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by erogray** [comment]
This is a significant bug. Reopening.

**Comment by erogray** [comment]
@stefaniefgray can you  try to re-create this issue on a non-client environment? test these three scenarios:
1. creating two harvests from a single json, but filtering them by different keywords 
2. create two harvests from a single json, with filters by keywords such that the results overlap
3. create a harvest, then unpublish it and its datasets from the harvest dashboard; then re-create a new copy of the same harvest

we're looking for instances in which the resulting datasets are unavailable or otherwise incorrect — keep track of errors or other symptoms

**Comment by stefaniefgray** [comment]
**The 3 Harvest scenarios listed above**

1. **Creating two harvests from a single json, but filtering them by different keywords:**
Trying using https://www.usda.gov/data.json by "Corn" and "Rural sociology."
Corn: 11 datasets
Rural Sociology: 7 datasets.

There are currently no datasets with both keywords.
Both harvests ran properly, no issues.

2. **Create two harvests from a single JSON, with filters by keywords such that the results overlap:**
Adding a new USDA Harvest where it definitely overlaps - there are 7+ datasets with both "corn" and "soybeans" as keywords. (There should be 23 datasets.)

Both harvests ran properly; I can see datasets from all of the above harvests, even with the overlap.

3. **Create a harvest, then unpublish it and its datasets from the harvest dashboard; then re-create a new copy of the same harvest**

Let's remove the "rural sociology" Harvest source by unpublishing it and its datasets.
First, I unpublished the rural sociology Harvest source.

This is what happens after clicking unpublish:

![screenshot 2018-08-02 00 24 49](https://user-images.githubusercontent.com/9059428/43549859-84560bdc-95ea-11e8-8443-1850111dcabb.png)

The items from the original "rural sociology" Harvest are all still published on the Datasets page, even after the error page and after going back and making sure "unpublished" was checked.

If I click on a Dataset that was originally from this Harvest, I get the same error page as shown above.

Now, let's try creating a new copy of the same Harvest.

After creating and running a new "rural sociology" Harvest, I can check my work by looking for the dataset "Rural-Urban Commuting Area Codes."

The original datasets from the previous and unpublished "rural sociology" Harvest are now showing errors and are inaccessible.

http://stefanie.dkandemo.nuamsdev.com/dataset/rural-urban-commuting-area-codes is completely broken, and can only be accessed through its new link from the latest Harvest - http://stefanie.dkandemo.nuamsdev.com/dataset/rural-urban-commuting-area-codes-0. 

DKAN should recognize that those datasets are one and the same.

**Comment by erogray** [comment]
So it looks like the only problematic part here is if you unpublish a harvest (or otherwise change a harvest in such a way that unpublishes its content, e.g. adding filters to restrict a harvest); because the harvested datasets are not completely unpublished. If the datasets are then harvested again, zombies occur. This is a much narrower set of circumstances than I'd previously thought, and is good news.

**Comment by erogray** [comment]
Seems to have been more or less fixed; or at least, has become very difficult to replicate.
