### ISSUE TITLE
Improve data-cleaning and/or validation on import

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2439]
As a DKAN data publisher, I'd like to be notified if my CSV (or TSV? Excel? possibly other types?) resource has trailing spaces, incorrect data types, or other common issues at the time that my data is added so that I don't accidentally wreck visualizations or provide invalid results to data consumers.

Integration with http://goodtables.okfnlabs.org/ or other tools might be a good approach.

**Comment by dafeder** [comment]
This is what's being addressed with the work related to #2608.
