### ISSUE TITLE
Bug: intermittent page visibility problems

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2443]
Occasionally and for unknown reasons, one or more pages on a DKAN site can become invisible and appear empty to unauthenticated users. Clearing varnish seems to fix this. Let's find out why this happens and, if possible, how to fix it.

**Comment by erogray** [comment]
May be connected to Acquia Purge?

**Comment by erogray** [comment]
iceboxing until we have a way of finding out circumstances that might cause this; can't replicate otherwise.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
