### ISSUE TITLE
Add correct version numbers for DKAN-DROPS-7 tags

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2444]
When I updated DKAN using drops-7 (DKAN 7.x-1.14.4 release) there is an issue with the version display. The admin/reports/status does not provide the version, and in the updates it shows that version 7.x-1.13.7 is installed.

Screenshots:
![dkan version](https://user-images.githubusercontent.com/5204324/38324342-b6951714-3848-11e8-9b96-adb264dce93a.png)

**Comment by chrodos** [comment]
Found the problem in profiles/dkan/dkan.info . The line 

> version = 7.x-1.14.4

 is missing at the end of that file.

**Comment by chrodos** [comment]
I tested it and it works on admin/reports/status

But on admin/modules/update?
It shows DKAN version 1.13.7 and shows an update to 1.14.5 that is already completed.

![dkan_update](https://user-images.githubusercontent.com/5204324/38371365-ebc9e692-38f4-11e8-90bc-57e6fdad64c1.png)

**Comment by dafeder** [comment]
We need to start using the tarball from DKAN releases, since we do longer add the version to the tag.

**Comment by fmizzell** [comment]
The release of dkan-drops for 7.x-1.15.5 contains the correct release information. Once that gets merged I believe we can close this ticket. https://github.com/GetDKAN/dkan-drops-7/pull/74
