### ISSUE TITLE
Pantheon build is broken

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2445]
Problems with Pantheon build — seems like theme is partially missing or something?

<img width="578" alt="screen shot 2018-04-03 at 12 56 59 pm" src="https://user-images.githubusercontent.com/21176376/38380515-d66d9fd2-38b8-11e8-9ed4-06293d809230.png">
<img width="594" alt="screen shot 2018-04-03 at 1 11 09 pm" src="https://user-images.githubusercontent.com/21176376/38380593-04562a04-38b9-11e8-8304-bb2986a23169.png">

**Comment by janette** [comment]
An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://dev-drop-test-1145.pantheonsite.io/install.php?profile=dkan&locale=en&id=2&op=do StatusText: OK ResponseText: Fatal error: Call to a member function processImport() on null in /srv/bindings/8e475ab51300484f93f85934f93f9001/code/profiles/dkan/modules/dkan/dkan_fixtures/modules/dkan_default_content/dkan_default_content.install on line 19

No migration found with machine name dkan_default_content_groups

**Comment by janette** [comment]
Building the site locally worked perfectly, no errors.

**Comment by janette** [comment]
- When installing on Pantheon the installation is not enabling all of the features needed.
- Instructions on the README file for **How to update dkan profile** are old.

user is instructed to run 
```
# Make a branch so we can test the travis build sep
git checkout -b rebuilding_dkan_profile
# Run dkan update script
cd scripts
./rebuild-dkan.sh
# Add, Commit, Push and check the travis build for the 'rebuilding_dkan_profile' branch
git add ../profiles/dkan -A
git commit -m "Rebuilding dkan"
git push origin rebuilding_dkan_profile
```

**./rebuild-dkan.sh**
```
#!/bin/bash

cd ../profiles
rm -rf dkan
git clone --branch 7.x-1.x http://git.drupal.org/project/dkan.git
git checkout 7.x-1.3
cd dkan
rm -rf .git
rm .gitignore
sh dkan.rebuild.sh
```

and dkan.rebuild.sh does not exist

**Comment by erogray** [comment]
Closing in favor of https://github.com/GetDKAN/dkan/issues/2537
