### ISSUE TITLE
Group page not visible when click view button

### ISSUE THREAD

**Issue by ghost** [GetDKAN/dkan#2446]
Thank you for this great open source software, i started using it in my project, but can you help me ? 

I've installed fresh dkan-drops-7 on MAMP server, everything seems to work but when i click on group name or group view button, no visible view.

this is my current view
![kosong](https://user-images.githubusercontent.com/11894892/38397409-140425f2-3970-11e8-86f1-90188fce18a5.png)

when i compare to the demo website, the group view like this
![isi](https://user-images.githubusercontent.com/11894892/38397242-44a4f818-396f-11e8-89df-ae9147e77ed4.png)

what is the problem ?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
