### ISSUE TITLE
Home link path doubled when site installed in directory

### ISSUE THREAD

**Issue by leeomara** [GetDKAN/dkan#2451]
## Description

When DKAN is installed in a sub directory of a webroot (e.g. `example.com/data`), the home link in the header has the path doubled (e.g. `/data/data`)

I am using DKAN 7.x-1.14.5.

## Steps to Reproduce

- Place DKAN in webroot subdirectory (mine is in `data`)
- Update `$base_url` in `settings.php` to match (e.g. `http://127.0.0:8888/data`)
- Visit the home page (or any other page)
- Notice the URL of the home link has the path doubled (e.g. `/data/data`)

## Acceptance Criteria

The home link should be the site root.

## Test Updates

None.

## Documenation Updates

None.

**Comment by kimwdavidson** [comment]
@leeomara Would you mind rebasing your branch against the 7.x-1.x branch? The tests were broken you first pushed this. Thanks!

**Comment by erogray** [comment]
Thanks @leeomara !
