### ISSUE TITLE
Resources' iframe preview can be larger

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2457]
iframe previews on non-tabular resources are set to smaller than necessary; can they be set to 100% width?

See for instance https://data.ca.gov/dataset/drinking-water-%E2%80%93-urban-water-supplier-monitoring-%E2%80%93-drinc/resource/657f1147-b280-4e13-be14 or https://www.data.va.gov/dataset/mental-health-statistics-explorer/resource/010b003a-ccac-4e64-8af3-c33ca45392f7

<img width="1210" alt="screen shot 2018-04-13 at 4 33 04 pm" src="https://user-images.githubusercontent.com/21176376/38761530-882962da-3f38-11e8-9db7-27279f1758ca.png">

**Comment by janette** [comment]
iframe previews are being removed https://github.com/GetDKAN/recline/pull/98
