### ISSUE TITLE
Bug: Admin Toolbar sometimes disappears in IE

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2459]
Several users have reported that after initial login, the Admin Toolbar vanishes (though they can still get to domainname/admin/ ). This appears to only happen in Internet Explorer.

**Comment by janette** [comment]
### Short term fix
https://www.drupal.org/node/457384#comment-9262471
Uncheck **Cache menu in client-side browser** at `admin/config/administration/admin_menu` performance tab

### Patch to fix client side caching
https://www.drupal.org/project/admin_menu/issues/2219467

**Comment by erogray** [comment]
If it helps, VA now reports that this also sometimes happens in Win/Chrome.

**Comment by janette** [comment]
@erogray we can disable the search form in the admin menu on the settings page as well under 'plugins'. I will disable both the **cache menu in client side browser** and the **search** on VA. If other clients have issues you can update their settings as well.

**Comment by erogray** [comment]
Thanks @janette ! I've let VA know. I've also adjusted those settings on data.ri.gov and let them know as well.
