### ISSUE TITLE
Discovery: Harvest UI improvement: Errors

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2460]
Errors that appear in message at the time of harvest can be confusing and aren't always stored on error page. Can we suppress these and populate the errors page instead?

As a DKAN administrator, I'd like for Harvests that encounter errors to suppress them until harvest completion, and then display them in a human-readable fashion (either at the time of harvest completion, or on the errors page (/node/x/harvest-errors), so that I can find the source of problems.

See also https://github.com/GetDKAN/dkan/issues/2416

To replicate: 
1. Create a new harvest for https://open.fda.gov/data.json. Click through to "Harvest Now". 
3. Once the harvest has completed, note that there are a large number of errors showing on the page: things like "Resource remote url (http://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfRES/res.cfm) extension (cfm) not allowed" and "Resource remote url (http://) not valid!" in pink. There are also a large number of messages in green, but many of them seem to qualify as errors of some sort: "Node 43 doesn't have a proper file path." or "This filemime type (application/zip) can be added as a resource, but cannot be imported to our datastore."
4. Visit the harvest's Errors page (example: http://demo.getdkan.com/node/41/harvest-errors). There will be no errors listed.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by erogray** [comment]
I'd advocate for improving Harvest errors; I spend a significant amount of time and energy diagnosing harvest issues and improved errors would help.

**Comment by erogray** [comment]
Some examples:
<img width="1163" alt="screen shot 2018-12-19 at 3 36 01 pm" src="https://user-images.githubusercontent.com/21176376/50254678-dcc59680-03a3-11e9-9e6f-b99712cffb23.png">
( ^ from http://demo.getdkan.com/harvest_source/harvest-hyphens )

<img width="1046" alt="screen shot 2018-12-19 at 3 39 06 pm" src="https://user-images.githubusercontent.com/21176376/50254783-4a71c280-03a4-11e9-9281-3d1b29c02d6f.png">
<img width="1420" alt="screen shot 2018-12-19 at 3 39 16 pm" src="https://user-images.githubusercontent.com/21176376/50254784-4a71c280-03a4-11e9-95a9-d2dc2f821688.png">
( ^ from http://demo.getdkan.com/harvest_source/openfdatest — in this case http://demo.getdkan.com/node/191/harvest-errors seems pretty useful, though the messages are different )

**Comment by erogray** [comment]
@dafeder at your request, I've added specific steps-to-reproduce using the FDA json source.

**Comment by kimwdavidson** [comment]
Closing in favor of #2819
