### ISSUE TITLE
Password change updates user permissions

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2465]
In latest DKAN 1.14.5 (drops-7 package) I perform the following steps:
1) Assign a user the workflow contributor role
2) Add the user as an administrator to a group
3) User changes the password from the profile form
4) User permissions are automatically updated and the group administrator role is lost. When the password updates a message appears that the administrator role is removed

I am not sure that this is a normal procedure. Anyone else having this issue?

**Comment by erogray** [comment]
@stefaniefgray can you replicate this?

**Comment by janette** [comment]
@chrodos to be a group admin the user needs the editor or site manager role https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.module#L367

**Comment by chrodos** [comment]
@janette OK, I undesrtand that, but if this is not allowed, then the group admin option should not be available for other roles other than the editor or the site manager. Otherwise, the system allows an admin to give any user the group admin role and it revokes it when the password changes.

**Comment by stefaniefgray** [comment]
QAing once more - installed Workflow on Jenkins site

1. Assign a user the workflow contributor role - Done with example account
2. Add the user as an administrator to a group - Done
3. User changes the password from the profile form - Done
_4. User permissions are automatically updated and the group administrator role is lost. When the password updates a message appears that the administrator role is removed._

This is correct, and is still an issue:

![screenshot 2018-06-19 14 53 32](https://user-images.githubusercontent.com/9059428/41618250-9a9da0e4-73d0-11e8-894d-dc2a4f4f3fd4.png)

**Comment by erogray** [comment]
Per our conversation earlier today: 
1. workflow contributors cannot be group administrators, because group administrators can edit others' content.
2. DKAN checks this role at the time of password reset, and at that time enforces the above relationship.

Probably the best solution to this is to do the role check _at the time of role assignment/change_, so that permissions are properly enforced at the time one would expect, and this doesn't happen unexpectedly at the time of password change.

**Comment by erogray** [comment]
I've added https://github.com/GetDKAN/dkan/issues/2574 which should address this issue. I'm closing here to prevent duplication. Thanks for bringing this to our attention @chrodos!
