### ISSUE TITLE
Discovery: Can harvested resources be queued for datastore import?

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2471]
Harvested data is not automatically added to the datastore, but perhaps it could/should be? 

(Perhaps this would be set at the time a harvest is created or edited)?

**Comment by dafeder** [comment]
@erogray this feels like a potentially dangerous option to offer. Can we discuss more about the specific issue this is addressing and other potential solutions? Also to note: we would probably need to address this beyond just the harvest context, and allow automated datastore import for new resources created through any mechanism (node form, API etc)

**Comment by erogray** [comment]
This is dangerous because we'd need to load the entire files in many cases in order to know how big the file is, which would almost certainly cause trouble for harvests trying to access large files; there's also no clear way to check file size beforehand. We could add a "use at your own risk" option.

One option: if a resource is _already_ in datastore, the harvest could trigger a re-import. This would be a much safer practice. This could happen at the end of the harvest process as a check: does this datastore have a datastore imported status? If so, re-import on next cron.

**Comment by kimwdavidson** [comment]
@erogray needed for this discussion and to spec

**Comment by erogray** [comment]
Potential approach:
- checkbox on harvest source to automatically re-import datastores after harvest
- if table exists, re-import (we have working api import script to draw on)
- if table does not exist, provide message that a new resource needs to be added manually
- would need to decide acceptable size limit for import

**Comment by kimwdavidson** [comment]
Ero to close and create updated ticket.
