### ISSUE TITLE
Move Memcache Module to DKAN from DKAN Starter

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2477]
Recommended by Acquia Insight (Performance category):

---

**Details**
Memcache is a key/value storage daemon that allows you to lighten the load on your MySQL server by putting the contents of all the cache tables into an in-memory storage engine. Using memcache will make your site perform better under load and reduce instances where table locking can occur.

**Actions / resolutions**
[Download](http://drupal.org/project/memcache) the Memcache module for your website.

This module requires additonal steps to enable, so read its readme or the [online documentation](http://drupal.org/node/1131458).

**NOTE:** If you are an Acquia Cloud customer, the memcache daemon is already installed on your server. [Learn more about how to enable memcache for your site](https://docs.acquia.com/cloud/performance/memcached). 

Using memcache in Drupal does not require the module, but it is wise to periodically check the memcache report pages (provided by the memcache admin submodule) to ensure you have sized memcache correctly.

For more information about installing modules, see [Installing contributed modules (Drupal 7)](https://drupal.org/documentation/install/modules-themes/modules-7) or Installing contributed modules (Drupal 5 and 6) at drupal.org.

[Learn more](https://docs.acquia.com/cloud/performance/memcached)

**Comment by acouch** [comment]
Memcache is currently used with most DKAN projects [through DKAN Starter](https://github.com/GetDKAN/dkan_starter/blob/master/build.make#L40). We have discussed just moving it directly to DKAN since almost everyone uses it.

**Comment by dafeder** [comment]
We're leaning against including this in DKAN core. We are looking at creating an example custom makefile for [dkan-tools](https://github.com/GetDKAN/dkan-tools), and could include this there.
