### ISSUE TITLE
Search all content when using the search block

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2484]
- When you hit a 404, the search block in the header doesn't function correctly. It isn't returning any results.
- Searching via the search block filters content by type = dataset, let's let the user decide which filters to use

https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc#L489

change 'dataset' to 'search'

**Comment by erogray** [comment]
@kimwdavidson of interest

**Comment by erogray** [comment]
See also https://github.com/NuCivic/healthdata/issues/1050
