### ISSUE TITLE
Make all the maps the same

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#2490]
Follow up to https://github.com/GetDKAN/dkan/pull/2489

Different maps in different places look different. For example, the map use for the "Data Extent" Block in a dataset  looks different than the Recline map used to visualize a resource.  It would be great to make all of the maps consistent.

### Acceptance Criteria
- User can set the `dkan_map_tile_url` variable via the UI
- The variable informs both the data extent block and the recline map which tiles to use
https://github.com/GetDKAN/recline/blob/7.x-2.x/recline.js#L96
https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_sitewide/dkan_sitewide.blocks.inc#L171

**Comment by dafeder** [comment]
Update recline to use the new variable for map tiles.
