### ISSUE TITLE
Add the Republic of Cyprus Open Data Portal to DKAN sites list

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2493]
Hello,

The Republic of Cyprus has just launched its new data portal(http://www.data.gov.cy/) based on DKAN, so please add it to the DKAN sites list.

**Comment by acouch** [comment]
Congrats! Looks amazing. We will add it to the sites list.

**Comment by chrodos** [comment]
@acouch Thank you.

**Comment by janette** [comment]
Also add https://dados.educacao.sp.gov.br/
