### ISSUE TITLE
Improve Test Speed

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2494]
Current tests using docker compose and our local development containers take about 25 mins. The breakdown is:

| Task | Time |
| ---| --- |
| Install Docker and Dependencies | 01:36 |
| Download and start containers | 04:31 |
| Make DKAN | 02:16 |
| Install DKAN | 05:09 |
| Run Behat Tests | 10:21 |
| Run PHP Unit Tests | 01:21 |

### Docker containers in our own base image

I was hoping I could reduce **Download and start containers ** by using our down base container instead of ``ubuntu:1604``. I started that work here: https://github.com/GetDKAN/dkan-docker/blob/master/.docker/circle-base/Dockerfile

However I was unable to get **docker-compose** to run in the docker container locally, though there are [some recipes](https://gist.github.com/danielcosta/8e4529b491c43f0e2322e4ce243a6cee) out there and [Docker in Docker](https://github.com/jpetazzo/dind) which suggest it can be done.

That would shave off about **4 minutes**.

### Adding `dist/` folder to DKAN so we don't have to 'Make DKAN` in the tests

If we created a `dist/` folder for DKAN that would help in some of our other pipelines and save **2 minutes**.

### Using Database from latest point release

If we used a pre-built database from our last point release instead of installing from scratch every time we would save an additional **4 minutes**.

### Culling Some of the Behat UI Tests

The Behat tests running selenium are really slow and some of them are not well written. We could review and remove some.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by dafeder** [comment]
We're particularly interested in doing #s 1 and 3 here. Moving to needs spec
