### ISSUE TITLE
Dataset Modified Date not changing on edit dataset

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2495]
When a dataset is edited the Modified Date  does not change. I tried changing various fields values in the dataset form and adding new resources. The modified date remains the same.

**Comment by janette** [comment]
@chrodos what version of dkan are you using? this is the only thing I can find in recent issues https://github.com/GetDKAN/dkan/issues/1905

**Comment by chrodos** [comment]
@janette Its DKAN (dkan-7.x-1.14.5) from the drops-7 package.

**Comment by janette** [comment]
I have the 7.x-1.14.7 drops-7 locally, (only minor changes from 1.14.5), dkan_workflow enabled, and I'm getting the expected updated modified date when editing datasets...
Try adding some debug code here https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_dataset/dkan_dataset.module#L1301 to see if you can find out what the hang up is

**Comment by chrodos** [comment]
@janette I have started getting somewhere. This is the part of the code that gets activated:
``if (isset($node->field_harvest_source_modified) &&
    !empty($node->field_harvest_source_modified->value())) {
    $date = format_date($node->field_harvest_source_modified->value(), 'iso_8601_date');``

For some reason it detects all datasets as a harvested datasets. None of the datasets though are harvested.

**Comment by chrodos** [comment]
@janette I checked the 2 tables **field_data_field_harvest_source_modified** and **field_data_field_harvest_source_issued** and they are populated. These are the values of the $node->field_harvest_source_modified and $node->field_harvest_source_modified->value() for a specific dataset.

```
field_harvest_source_modified=Property field_harvest_source_modified
field_harvest_source_modified_value=1519208082
```

**Comment by janette** [comment]
@chrodos thank you for taking the time to  investigate that, the PR above should fix the issue.
