### ISSUE TITLE
Incomplete or No Cache-control and Pragma HTTP Header Set

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2502]
Risk identified by Zap scan (see  https://github.com/NuCivic/healthdata/issues/1010 ):

The cache-control and pragma HTTP header have not been set properly or are missing allowing the browser and proxies to cache content.

**Comment by grugnog** [comment]
I think we discussed this in Slack recently - this is expected (and I think OK) when scanning Drupal as anonymous. When logging in or submitting forms you will get no cache headers.

**Comment by erogray** [comment]
Submitted as false positive; closing.
