### ISSUE TITLE
Web Browser XSS Protection Not Enabled

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2503]
Risk identified by Zap scan (see  https://github.com/NuCivic/healthdata/issues/1010 ):

Web Browser XSS Protection is not enabled, or is disabled by the configuration of the 'X-XSS-Protection' HTTP response header on the web server

**Comment by erogray** [comment]
False positive; not an actual problem.

**Comment by janette** [comment]
@erogray actually we fixed this one with `$conf['seckit_xss']['x_xss']['select']=2; ` in the settings.php file
