### ISSUE TITLE
Add Row Level Transformations for New Datastore and Add Geocoding Example

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2515]
The new datastore does not yet have an API for row level transformations. This would slow operations but allow for transforming the data as it is loaded or updated. This would be useful to correct issues with the data as part of an ETL pipeline. An example would be geocoding address information.

## Geocoding Example

The current datastore uses the Geocoder Drupal 7 module to get Geocoding service provider keys. I would recommend using the PHP Geocoder library instead.

It would also be good to have a way of telling the datastore which resources should be geocoded and what fields to geocode. This is available in the UI of the current implementation:

![image](https://user-images.githubusercontent.com/512243/40023339-bf6d4680-5798-11e8-960d-8c0e66846594.png)

**Comment by erogray** [comment]
@acouch can you estimate the effort for this?

**Comment by dafeder** [comment]
Closing this for now - re-open if needed. For geocoding specifically, it seems like it would make much more sense to de-couple that from the import process and geocode a separate process once import is complete.
