### ISSUE TITLE
How-to Documentation for Editors

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2522]
As a new Editor and/or Workflow Approver, I'd like to know how to get started using DKAN so that I can confidently and correctly add datasets and other content.

**Comment by stefaniefgray** [comment]
https://github.com/GetDKAN/dkan/blob/stefaniefgray-docs3/docs/components/workflow.rst

^ Can push to live

**Comment by erogray** [comment]
Appears to have been completed.
