### ISSUE TITLE
Permissions for Datastore

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2523]
We should refactor the permissions for the Datastore and use them in the new API. 

## Acceptance Criteria

* Access callback should not make reference to feeds
* dkan_datastore_download_access should no longer be needed
* Generally clean up the page and permissions hooks in dkan_datastore.module to fit new paradigm as much as possible
* API resources should use same permissions logic as UI equivilants

**Comment by kimwdavidson** [comment]
Needs rebasing against #2481 and #2482
