### ISSUE TITLE
Discovery: audit tests

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2524]
We know that many DKAN tests aren't performant and may need replacing. But how many of them? Once we know, we can better estimate the scope of work required to have the tests suite we want.

This should be timeboxed: to a half day.

**Comment by erogray** [comment]
Might be do-able simply by reviewing skipped tests?

**Comment by erogray** [comment]
See also https://github.com/GetDKAN/dkan/issues/2525

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
