### ISSUE TITLE
Discovery: improve one or two sample tests, measure performance improvements

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2525]
In order to better establish the potential improvements that a general tests refactor would represent, it'd be useful to pick one or more representative tests (probably Selenium?) and replace them with new ones, and measure the improvements that result. We can then extrapolate to estimate the potential gains from larger refactoring efforts.

**Comment by kimwdavidson** [comment]
Closing in favor of incremental test improvement
