### ISSUE TITLE
Import all content from source XLS file error.

### ISSUE THREAD

**Issue by vietlv** [GetDKAN/dkan#2530]
- I have a file XLS. After add dataset and preview success
![image](https://user-images.githubusercontent.com/6602895/40341032-ea254ae8-5dac-11e8-854c-c3c9de8a8e13.png)
- Now I import content of data but error SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name
![image](https://user-images.githubusercontent.com/6602895/40340913-0b97fc26-5dac-11e8-9270-0ed5fbf49699.png)
-  This is my file.
[danhsach.zip](https://github.com/GetDKAN/dkan/files/2024878/danhsach.zip)
- I hope everyone help me.
- Thanks !

**Comment by stefaniefgray** [comment]
Trying the following on my Jenkins site:
- Original file as XLS
- Original file as CSV
- Clean new XLS
- Original file with blank field fixed (in both formats or just whichever one worked)

**Comment by stefaniefgray** [comment]
Results from http://stefanie.dkandemo.nuamsdev.com/ (7.x-1.14.5):

- XLS files can't be imported to the Datastore; only CSV files.
- The file works perfectly fine when saved and exported as a CSV.
- Vietnamese language support does not break anything within DKAN when it comes to the Datastore and Data Previews, and neither does having a blank cell.

Recommendation: Try saving and reuploading the file as a CSV.

**Comment by vietlv** [comment]
I know when import to the Datastore CSV file successed. But If the XLS file is not supported, why is the Import button still present?
Thanks supported !

**Comment by erogray** [comment]
Thanks for pointing this out @vietlv -- that's definitely a good improvement to make. I've filed https://github.com/GetDKAN/dkan/issues/2540 so that we can work on making this clearer in the future.
