### ISSUE TITLE
Harvest datasets page should show Topic and Publisher facets, not Author

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2535]
As a site manager, I'd like to be able to easily filter down to specifics of what's included in a given harvest's datasets using Topic and/or other facets so that I can assess the nature of the data being added by that harvest source.

<img width="308" alt="screen shot 2018-05-24 at 12 02 30 pm" src="https://user-images.githubusercontent.com/21176376/40505938-b1c087c2-5f4a-11e8-9ea7-10fcd777b96b.png">

Right now only Author and Tags are available as facets on the domainname/harvest_source/harvestname page. The Author is either the Drupal Author, in which case for harvests it'll pretty much always be Admin, or the metadata Author, which may or may not be set to something useful. Either way, Publisher and Topic are more important facets.

**Comment by erogray** [comment]
Possibly features revert?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.

**Comment by dafeder** [comment]
DKAN v1 issue, no longer relevant.
