### ISSUE TITLE
Can't add new content home page

### ISSUE THREAD

**Issue by vietlv** [GetDKAN/dkan#2536]
- I try add new content at home page but can't.
- I have done the following steps.
  Step 1: After login with role admin, I click button plus as image

![image](https://user-images.githubusercontent.com/6602895/40525365-da5f2d36-6009-11e8-89e5-f16c6defc2bf.png)

 Step 2: A popup show with content as image

![image](https://user-images.githubusercontent.com/6602895/40525502-8aa2402a-600a-11e8-841a-590972f223e6.png)

I hope evereyone help me.

**Comment by janette** [comment]
@vietlv can you check to make sure dkan_ipe is enabled

**Comment by vietlv** [comment]
A few day ago I was busy. Now I see your support. I make dkan_ipe is enabled and success.
Thanks @janette  so much !
