### ISSUE TITLE
Update module produces errors when checking for new versions of DKAN modules

### ISSUE THREAD

**Issue by boabjohn** [GetDKAN/dkan#2537]
Howdy all, similar to other reports, but just adding the most recent.
Pantheon provides a list of custom upstream builds here:
https://pantheon.io/docs/start-state/

That link fires off a new DKAN build, which (after a lot of building) gives this for a homepage:
`Error message
Warning: in_array() expects parameter 2 to be array, null given in DBObject->__set() (line 63 of /srv/bindings/c7c353dff2244e6fa56e9b21a8501b54/code/profiles/dkan/modules/contrib/eck/eck.classes.inc).
Warning: in_array() expects parameter 2 to be array, null given in DBObject->__set() (line 63 of /srv/bindings/c7c353dff2244e6fa56e9b21a8501b54/code/profiles/dkan/modules/contrib/eck/eck.classes.inc).
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pantheon.t' doesn't exist: SELECT t.* FROM {} t WHERE (name = :db_condition_placeholder_0) ; Array ( [:db_condition_placeholder_0] => visualization ) in DBObject->load() (line 133 of /srv/bindings/c7c353dff2244e6fa56e9b21a8501b54/code/profiles/dkan/modules/contrib/eck/eck.classes.inc).`

I am not gear-headed enough to know what to do next...hoping that there may be a reasonable solution recipe I can follow along?
Thanks!

Connects https://github.com/GetDKAN/dkan/issues/2445

**Comment by janette** [comment]
### 1.15.2 tag

![dkan-drop-1-15-2___pantheon_dashboard](https://user-images.githubusercontent.com/314172/41933408-65325598-7949-11e8-9b90-a5e376ad48da.png)

**Comment by acouch** [comment]
@boabjohn Can you try the following steps? https://acouch.github.io/dkan-site/pantheon/ Maybe we should add this to the docs.

**Comment by boabjohn** [comment]
G'Day @acouch ,
Thanks for the encouragement to have another go. I am quite keen to get a DKAN instance up and rolling because we've just been contacted by one of the NCRIS networks asking if we can expose a CKAN/DKAN endpoint to their researchers.
Exciting times for our little project!

And the DKAN delpoy on Pantheon seems to go smoother. However, I'm still hitting hitches.
1: I'm running the Ubuntu bash on Win10 Pro which is pretty good, but some configs are a bit tricky. Eg, I have drush running fine and a git repo for all my other Pantheon sites. But Terminus refused to install properly (could not create a cache directory)
2: I tried running the drush si method from my home directory, but got a "drush needs a more functional environment to run" message
3. So I finished the profile install via Pantheon, by directly loading the site and allowing the Drupal UI to run through the installation. All seemed to go smoothly enough. HOwever, going straight to Reports>Available updates, I get:
-----
Notice: Undefined index: dkan in dkan_sitewide_update_status_alter() (line 209 of /srv/bindings/b3c6909aa9a64e6a89aed177bb07e40b/code/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 224 of /srv/bindings/b3c6909aa9a64e6a89aed177bb07e40b/code/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 224 of /srv/bindings/b3c6909aa9a64e6a89aed177bb07e40b/code/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_version in dkan_sitewide_update_status_alter() (line 249 of /srv/bindings/b3c6909aa9a64e6a89aed177bb07e40b/code/profiles/dkan/modules/dkan/dkan_sitewide/dkan_sitewide.module)

-----
4. I turned off "All notices" and just focused on Warnings and Errors and got this:
-----
Warning: Invalid argument supplied for foreach() in theme_update_report() (line 53 of /srv/bindings/b3c6909aa9a64e6a89aed177bb07e40b/code/modules/update/update.report.inc).
Warning: sort() expects parameter 1 to be array, null given in theme_update_report() (line 182 of /srv/bindings/b3c6909aa9a64e6a89aed177bb07e40b/code/modules/update/update.report.inc).
Warning: implode(): Invalid arguments passed in theme_update_report() (line 193 of /srv/bindings/b3c6909aa9a64e6a89aed177bb07e40b/code/modules/update/update.report.inc).
----

There are no actual errors yet...but I'd just like a bit of reassurance that this level of noise is expected and manageable?

There is one module with a security update pending and several with pending updates. Not sure if I should first try to update all modules before getting stuck into configurations.

Your advice or guidance much appreciated!

Kind regards....

**Comment by janette** [comment]
@jjalcolea that is a faulty check for version info, so yes you can ignore those warnings, or apply #2637 as a patch until the next release.

**Comment by jjalcolea** [comment]
Thanks @janette. Please note that the link provided in the documentation to launch a DKAN site in Pantheon doesn't seem to work either (https://dashboard.getpantheon.com/products/dkan/spinup)

Best,

Juanje.

**Comment by dafeder** [comment]
@jjalcolea just tested the link and it worked for me. What are you seeing?

**Comment by dafeder** [comment]
I'm going to rename this issue as its focus has narrowed quite a bit. There are clearly issues with pantheon installs beyond the version check but those will be addressed in other tickets.
