### ISSUE TITLE
Datastore import needs helptext and/or logic so that users know only CSVs and TSVs can be imported

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2540]
As a DKAN user, I want to see appropriate information/options for import about which filetypes can be imported, so that I can import files to the datastore without being confused when some of them don't work. 

The datastore can only import CSVs and TSVs, but users currently have no clear way of knowing this. 

See also https://github.com/GetDKAN/dkan/issues/2530

**Comment by dafeder** [comment]
DKAN v1 issue, closing due to EOL.
