### ISSUE TITLE
Remove Number of Members from Groups Page

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2558]
The member numbers is not something that needs to be public:

![image](https://user-images.githubusercontent.com/512243/41256039-6ee685b4-6d96-11e8-8f49-f67293254c64.png)

We could either remove that or make it optional and include a check box in the admin to turn it on or off.

## User Story

As an anonymous user
I should not see the number of members in a group

## Notes

We should decide if we just remove this or add a user story to make it optional.

**Comment by erogray** [comment]
1 hr if removing; if configurable, half-day or more?
probably removing is the better option? hard to imagine anyone being bothered.
