### ISSUE TITLE
Make Links to Resources Optional

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2559]
While DKAN does provide a number of useful [preview types](https://docs.getdkan.com/en/latest/components/visualizations/datapreviews.html#additional-preview-types) it is also common for data to have no preview. This may be because we don't have a preview for that data type or data has CORS enabled or is not directly available.

DKAN already provides "open with" and and "go to resource" links which makes the direct link redundant. Some internal catalogs or catalogs with certain types of data have a majority of their resources which are not previewable. We should give admins the option removing the link to the resource for anonymous users. In the screenshot below the yellow would not be a link for anon users:

![image](https://user-images.githubusercontent.com/512243/41295894-a156f59a-6e29-11e8-97b2-904e99803bf6.png)
  
Some alternatives to this are: 

* always remove the link for anon users
* make the preview optional on the resource itself
* improve the user experience for resources with no preview

## User Stories

As a site manager
When I visit the DKAN settings
Then I should be able to toggle resource links globally

As an anonymous user
When I visit a dataset
And the Site Manager has turned off resource links
Then I should not be able to click on the resource title
When I click "Go to Resource"
Then I should go directly to the linked or uploaded resource
When I click "Open with" then I should go to a preview of the resource
Or to a tool that can consume the resource

**Comment by dharizza** [comment]
Security updates and bug fixes only in the D7 version of DKAN. Closing.
