### ISSUE TITLE
Improve datastore API documentation

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2564]
<img width="471" alt="slack" src="https://user-images.githubusercontent.com/314172/41428022-69196dec-6fce-11e8-912e-03d81c4d33b0.png">

**Comment by janette** [comment]
Related: https://github.com/GetDKAN/dkan/issues/2488

**Comment by willieseabrook** [comment]
This has been noted by our customer. See my more detailed comment in #2488

**Comment by kimwdavidson** [comment]
Duplicate of #2488. Closing
