### ISSUE TITLE
Discovery: UX improvements to non-feeds datastore

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2568]
Acceptance criteria: 
End-to-end test new datastore
Note areas for UX improvement
Create tickets for bugs and UX improvements

**Comment by dafeder** [comment]
## Notes

## Initial "manage datastore screen"

![image](https://user-images.githubusercontent.com/309671/43738681-6df3c6ac-9993-11e8-913a-1b416ea29d3b.png)

1. "Import" and "Drop datastore" appear on this screen but do nothing.
2. In most cases I can imagine, a site would only provide one "manager" to people. In that case it does not really make sense to provide a selection every time, with a single choice. 

## Import screen

![image](https://user-images.githubusercontent.com/309671/43739539-7270630e-9996-11e8-912f-8db1b5bf5350.png)

1. "Drop datastore" tab still not doing anything at this point
2. "Status" not differentiated from the status text below it
3. Importer should have human-readable name or at least just display the class w/o namespace
4. What does storage status mean?
5. What does "data importing" mean?

**Comment by dafeder** [comment]
## Import/status screen post-import

![image](https://user-images.githubusercontent.com/309671/43777055-b243c046-9a1f-11e8-959a-4de5a2b65f03.png)

1. Is this really the "import" screen at this point?
2. Storage status still not providing useful information
3. Could be confusing that "import" button still appears as it did before, even though we've completed the import.

**Comment by dafeder** [comment]
## Suggestions

1. Find way to remove first step when redundant. When there is only one importer available, "manage datastore" should take us right to the import form, even if nothing is initialized. The status area should be replaced by something like "No datastore table exists for this resource. Use the import form below to create one." (In future, maybe the manager selection could be a field on the importer form that reloads the form via ajax if changed.)
2. Remove tabbed interface. "Drop" becomes a button next to "import" once it's actually an option. The screen we currently see when viewing the "drop" screen becomes simply the confirmation form for the "Drop" button. "Import" is grayed out once data importing is complete.
3. When only one manager is available, hide the "importer" status line.
4. Hide the "storage" status line. This is never useful information to the user.
5. Capitalize import options ("delimeter" etc)
6. Add help text to top of page.
7. I imagine there are some UX improvements to be made on the experience of having an import interrupted part way and then coming back to the datastore screen, but not sure how to test that.

**Comment by kimwdavidson** [comment]
8. Need mechanism to change importer once configured (Gerardo)
