### ISSUE TITLE
Move View/Revision Tab to Bottom of Node View

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2570]
We've received feedback that the View / Revision tab is not a great UX for anon users. It doesn't have much sense to see the (View) button at the top of the screen as you are already viewing the dataset. This comes from Drupal's default View/Edit tab and has never been addressed. If we were just to remove the (View) button the (Revisions) button would seem more out of place.

We should move it to the node view:

![image](https://user-images.githubusercontent.com/512243/41551777-e81e3d8c-72fa-11e8-985f-f72105479ccc.png)

We should also think about remove the (View) tab from resources as well.

## User Stories
As an anonymous user on a dataset page
I should not see the View tab at the top of the page
I should not see the Revision tab at the top of the page
I should see "Revision History" at the bottom of the page
I should see the total number of revisions
I should see the most recent 4 revisions
I should see a link to the full revision history

As a content creator on a dataset page
I should see the (View) (Edit) tab at the top of the page

**Comment by dharizza** [comment]
Security updates and bug fixes only in the D7 version of DKAN. Closing.
