### ISSUE TITLE
Enforce workflow roles vs group roles at the time of role change

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2574]
Per https://github.com/GetDKAN/dkan/issues/2465, it can be confusing for users if a role change doesn't behave as expected, which can happen when workflow roles and group administrator roles are changed independently.

As a site manager, I'd like to be prevented from assigning a content creator/workflow contributor to a group administrator role without changing their workflow role also, so that I'm not confronted with unexpected status changes later.

**Comment by dafeder** [comment]
This was fixed in #2644
