### ISSUE TITLE
Allow KML files

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2575]
As discovered in https://github.com/NuCivic/cadepttech/issues/60 and https://github.com/NuCivic/cadepttech/issues/111, resources with KML extensions can be blocked and result in errors in harvests. 

Most likely these filetypes should be allowed by default.

**Comment by janette** [comment]
kmz, bin, json too?

**Comment by kimwdavidson** [comment]
allow kml, kmz, json, shp
