### ISSUE TITLE
Resource not updated when workflow state is "needs review" or "draft"

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2578]
When a user (contributor) updates a resource when the workflow state is "needs review" or "draft" the resource is not updated and the other users (moderator,admin) does not see the updated version.

DKAN version dkan-7.x-1.14.5
Workflow module ON

Steps to reproduce:
1. Choose an existing dataset with a resource and click update the resource
2. Remove the existing csv file and add a new one
3. Set the status of the resource to need review
4. Check the resource from the workbench

The file is still the old one. When you try to publish it you will see that only the old resource is available.

**Comment by janette** [comment]
https://www.drupal.org/project/workbench_moderation/issues/2447659
https://www.drupal.org/node/2021903#comment-11401095
https://www.drupal.org/node/1838640

**Comment by janette** [comment]
@erogray do you want to rank this for the to do column

**Comment by janette** [comment]
Testing with 
- workbench_moderation 7.x-3.x-dev 
- drafty 7.x-1.0-rc1
- patch: https://www.drupal.org/files/issues/workbench_moderation-preserve-history-2824798-14.patch

Results
- Creating a draft on a dataset and clicking 'view draft' does display edited title but none of the edits on other fields
- Creating a draft on a resource and clicking 'view draft' the published version is displayed
