### ISSUE TITLE
Issue displaying in table view url with spaces

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2579]
When a CSV file contains URLs with spaces the table visualization is not displaying the url correctly. See for example [this link](https://www.data.gov.cy/dataset/%CE%AC%CF%81%CE%B8%CF%81%CE%B1-%CE%B9%CE%BD%CF%83%CF%84%CE%B9%CF%84%CE%BF%CF%8D%CF%84%CE%BF%CF%85-%CE%B3%CE%B5%CF%89%CF%81%CE%B3%CE%B9%CE%BA%CF%8E%CE%BD-%CE%B5%CF%81%CE%B5%CF%85%CE%BD%CF%8E%CE%BD-%CF%83%CF%84%CE%BF-%CF%80%CE%B5%CF%81%CE%B9%CE%BF%CE%B4%CE%B9%CE%BA%CF%8C-%C2%AB%CE%B1%CE%B3%CF%81%CF%8C%CF%84%CE%B7%CF%82%C2%BB/resource/bd4bd11a-5075-476d-af09#{view-grid:{columnsWidth:[{column:!AA,width:82},{column:!Year,width:84},{column:!Issue,width:196},{column:!URL,width:683}],fitColumns:true}})
![screenshot](https://user-images.githubusercontent.com/5204324/41763790-d483dd80-7607-11e8-8237-4120db20749f.png)

**Comment by janette** [comment]
@chrodos you would need to replace the spaces with `%20` in the file to get the urls to work.

**Comment by dafeder** [comment]
@chrodos closing this - I don't think there's a way we could anticipate URLs with spaces in them, which are not technically valid. Please feel free to re-open if you'd like to discuss further.
