### ISSUE TITLE
Source field don't let me upload a file in create a chart visualization

### ISSUE THREAD

**Issue by luisoidor** [GetDKAN/dkan#2583]
When I create a chart visualization, the Source field don't let me upload a file. So, only I can see the field Source, but I can't upload a file or select a dataset. Any idea?
![captura](https://user-images.githubusercontent.com/40614899/41944348-03112636-796d-11e8-8bb2-f9737309bb06.PNG)

**Comment by janette** [comment]
@luisoidor what version of DKAN are you using? The latest version will give you two options, using an existing resource from the site or uploading a new file. 

![comparison_tool](https://user-images.githubusercontent.com/314172/42698408-6c0efc1c-8683-11e8-89ac-0906be673977.png)

Your form is missing the options, could you try reverting the following features: visualization_entity, visualization_entity_charts, and visualization_entity_charts_dkan. Then clear cache.

**Comment by luisoidor** [comment]
I don't know that happend, but chart's fields are missing. I created the fields and it works!
