### ISSUE TITLE
Add Lock bot and set time period for open tickets

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2584]
A lot of projects have started using the lock bot (https://github.com/apps/lock) for closing tickets after a certain time period. Some active projects and the default is 30 days: https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/lock.yml#L4

I think something closer to 4 months would be better for our release period.

**Comment by dafeder** [comment]
Closing for now, may re-assess at a later time. We're doing more active grooming at the moment so seems less important.
