### ISSUE TITLE
Improve remote file redirect handling in harvest

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2591]
When harvests encounter a URL in JSON that redirects somewhere, we're using effectiveURL — but some of these have queries that expire, meaning that the resulting resource has a broken link. We're currently dealing with this (in https://github.com/NuCivic/cadepttech/issues/123 and https://github.com/GetDKAN/dkan/pull/2586) by removing the query portion of the link, but there may be a better approach (such as using the URL listed in the original JSON).

**Comment by erogray** [comment]
Plan of action:
Find and run 4 different types of redirects in harvests, and try running with JSON version rather than effectiveURL; if this causes issues, use the lopping-off-the-query approach (in #2586 ) and see if that works. If that causes issues, panic.

**Comment by dafeder** [comment]
#2586 will fix this but we need a documentation update before this issue can be closed.

**Comment by janette** [comment]
@erogray documentation was added to the PR and merged https://github.com/GetDKAN/dkan/pull/2586/files#diff-9185437597aefb2b6289c4253a53fdc9R74
