### ISSUE TITLE
Undefined Index errors

### ISSUE THREAD

**Issue by KOTAGIRI-SAIRAJ** [GetDKAN/dkan#2593]
Notice: Undefined index: dkan in dkan_sitewide_update_status_alter() (line 209 of /modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 224 of /modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_major in dkan_sitewide_update_status_alter() (line 224 of /modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: existing_version in dkan_sitewide_update_status_alter() (line 249 of /modules/dkan/dkan_sitewide/dkan_sitewide.module).
Notice: Undefined index: project_type in update_manager_update_form() (line 113 of /modules/update/update.manager.inc).
Notice: Undefined index: project_type in update_manager_update_form() (line 113 of /modules/update/update.manager.inc).

CSS ERRORS as well in this format
@import url("webroot/modules/system/system.base.css?pbt20d");

can anyone help me out in resolving these errors

**Comment by janette** [comment]
@KOTAGIRI-SAIRAJ 
This means your build of DKAN does not have a version number declared in the .info file, can you view the CHANGELOG.txt file to see which version you have? If you add a line to the dkan_sitewide.info file like this: `version = 7.x-1.15.2` that should clear the errors.

**Comment by KOTAGIRI-SAIRAJ** [comment]
Thanks for the fast response..@janette
I have updated dkan_sitewide.info file as suggested but still the same error..
Any more changes needed.. ??
Thanks in advance

**Comment by Farnoosh63** [comment]
I have the same errors. 
dkan_sitewide.info file version: 7.x-1.15.2
Any updates on this issue?
Thanks

**Comment by KOTAGIRI-SAIRAJ** [comment]
Hi @Farnoosh63 
I didn't find any solution..
but we can still work on the application by skipping the errors..
I was doing the same..

**Comment by janette** [comment]
@KOTAGIRI-SAIRAJ @Farnoosh63
Here is a patch you could try https://patch-diff.githubusercontent.com/raw/GetDKAN/dkan/pull/2637.patch

This will be in the [7.x-1.15.4](https://github.com/GetDKAN/dkan/releases) release

**Comment by dafeder** [comment]
Closing this - feel free to reopen if you need further assistance.
