### ISSUE TITLE
Fulltext Search within attachments with TIKA/Solr

### ISSUE THREAD

**Issue by ipaulet** [GetDKAN/dkan#2596]
I tried to configure DKAN in order to be able to search inside attachments, PDF's and Word Documents at least. I tried many configurations (with search_api_solr, Apache Solr Search and Apache Solr Attachments, Search API Attachments and TIKA) and I didn't succeed, 
I red the documentation and I also integrated TIKA as local app with Search API Attachments but I didn't have a succesful result. I am still not able to search inside the attachments.
I think the settings should be easy but somehow I make something wrong.

Could you please help me with a proper documentation to be able to configure dkan and search inside resources/attachments? The tutorials and the documentation we can found searching the web didn't help.

I'm using the following setup for our platform:

Ubuntu 16.04 VM
DKAN 1.15.2 with drupal 7.59 Core
Solr 6 Server
PHP 7.2.7

**Comment by janette** [comment]
This would be a great feature but is not currently scheduled in the roadmap. Community contributions are welcome.
