### ISSUE TITLE
Make sure that automatic datastore importing will work according to documentation

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2598]
http://dkan.readthedocs.io/en/stable/components/datastore.html appears to describe automatic importing options, which use Fast Import. Once Fast Import is deprecated by 1.16, will this still work? 
[ ] Is this documentation currently accurate?
[ ] Will it continue to be correct after pending datastore importing updates?

Per the documentation linked above:

> Processing Options
> By default Resource files are added to the DKAN Datastore manually. This can be changed to:
> 
> - Import upon form submission
> - Import in the background
> - Import periodically

> Changing Default Datastore Import Behavior
> Default behavior for linked and uploaded files is controlled through the Feeds module. To access the Feeds administrative interface, enable the Feeds Admin UI module (which is included but not enabled by default in DKAN). Once turned on you can access the Feeds UI at /admin/structure/feeds. You should see two Feeds Importers by default:
> 
> 

> Import on submission
> To import a Resource file upon saving the resource, click Import on submission in the settings section for each importer:

![datastore-import-submission](https://user-images.githubusercontent.com/21176376/43411815-296cc4f6-93e0-11e8-98e4-ae7f86a4d075.png)

> This is not recommended for large imports as a batch screen will be triggered that will not stop until the entire file is imported.
> 
> Process in background
> This setting means that once an import has started, it will be processed in 50 row increments in the background. Processing will occur during cron. The queue of imports is managed by the Job Schedule module. Each cron run will process a maximum of 200 jobs in a maximum of 30 seconds. Note that an import won’t be started by saving the Resource form. This will only be triggered by clicking “Import” on the “Manage Datastore” page or if triggered programatically. This setting can be used in addition to “Import on submission” option to start imports that will be imported in the background.
> 
> Periodic import
> Importing items on a periodic basis makes the most sense if you have a file you are linking to that you want to periodically re-import. This setting requires that cron is running on a regular schedule.
> 
>

**Comment by janette** [comment]
## Current functionality
1. Jenkins datastore run, triggered every 10 min., runs `dkan_datastore_fast_import_queue` This is only processing files that have manually been added to the datastore with the fast import box ticked. If the file is large, it may take a few cron runs to complete.

2. Periodic datastore importing requires the **Feeds Admin UI** be enabled and configured. We have not enabled this for any clients as of yet. Once enabled and configured, files **will** be automatically added to the datastore on cron runs but **will not** be imported on node creation as stated by the docs.

An error does display after cron run: 
```
Notice: Trying to get property of non-object in dkan_dataset_dataset_changelog_run() (line 861 of /var/www/dkan/modules/dkan/dkan_dataset/dkan_dataset.module).
``` 

3. Changes in remote files are reflected once the datastore refreshes on cron runs.

## Future functionality
With the elimination of the **feeds** module, I am not sure. Passing to @fmizzell as he will be writing up the documentation on the NEW datastore.

**Comment by fmizzell** [comment]
@erogray Given that the new datastore paradigm does not utilize feeds, we will be losing some of the functionality that Feeds used to provide. Those changes will be reflected in the new documentation.

@dafeder @acouch @janette What are your thoughts on how we communicate "loss of functionality". This functionality was never DKAN's as it is Feeds who is providing the extra functionality, but given that it is mentioned in the documentation, should it be addressed?

**Comment by kimwdavidson** [comment]
Let's add notes about the loss of functionality to the release notes.
