### ISSUE TITLE
Error while adding a Resource to a Dataset

### ISSUE THREAD

**Issue by LeKono** [GetDKAN/dkan#2602]
Hey guys,

I have an annoying problem while adding a Resource to my DKAN server. More specific linking that Resource to a Dataset. While it gets uploaded and linked properly (which I checked on the Content page). I get to see an Error-Page that just states:

"Error - The website encountered an unexpected error. Please try again later."

I can not find any helpful logging or error information to tackle that myself. The weird thing is, like I stated above: The Resource gets uploaded and linked properly to its corresponding Dataset.

edit:
Oh, I should add that uploading the Resource without any linked Dataset works totally fine.

I hope someone could guide me to the right direction :)

Thank you very much.

**Comment by janette** [comment]
@LeKono I am having trouble trying to reproduce this, can you be specific on the exact steps, what version of DKAN, etc.

**Comment by janette** [comment]
@LeKono ah yes, upgrading Feeds breaks several things, so if you can revert that change you should have better results. See #2251

If you still have the issue after fixing your Feeds version let me know.

**Comment by LeKono** [comment]
@janette unfortunately my feeds is updated at `profiles/dkan/modules/contrib`.
Is there a 'gold standard' on how to downgrade a module propperly?

**Comment by janette** [comment]
@LeKono you can use git https://www.drupal.org/project/feeds/git-instructions, checkout the revision listed in the dkan-org.make file then apply the patch listed or pull the module from the dkan-drops-7 repo https://github.com/GetDKAN/dkan-drops-7
