### ISSUE TITLE
Openess Score For Resource Files

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2609]
[Five-Star Open Data](https://5stardata.info/en/) is an institution in Open Data. There have been requests to expose the openess score of resources similar to:

![image](https://user-images.githubusercontent.com/512243/43333722-30476162-9199-11e8-9ba2-c963b7559038.png)

It seems like this could be accomplished with these steps:

### Add Openness Score Field to Resource

Add a field to resources to allow users to enter a score.

### Automate Openness Score

The score could be automated by checking the media type.

**Comment by acouch** [comment]
Here is how CKAN does the openess score calculation: https://github.com/ckan/ckan/wiki/Data-quality

**Comment by dafeder** [comment]
Want to get a sense of how much demand there would actually be for this...
