### ISSUE TITLE
Problem linking resources with dataset using apis

### ISSUE THREAD

**Issue by yjorozco** [GetDKAN/dkan#2611]
Good Evening. I need some help. I am trying to upload files using the apis. I am using the pydkan proyect and full_crud.py to comunicate with dkan. When it creates the resource and links it with the dataset, this error comes up :  INSERT INTO field_data_field_dataset_ref (entity_type, entity_id, revision_id, bundle, delta, language, field_dataset_ref_target_id) VALUES ('node', '142', '189', 'resource', 'target_id', 'und', NULL) .  Dkan puts the target_id in the delta field. This is the configuration in  full_crud.py: data = {
       'title': 'Test Resource',
       'type': 'resource',
       'field_dataset_ref': {
           'und': {
               'target_id': dataset_nid,
           },
           
       },
   } (editado)

**Comment by fmizzell** [comment]
The API has changed, and it now expects field structures exactly like what you would get from node_load() or what you would give to node_save(). A commit just got merged in pydkan to get the full_crud example working again.
