### ISSUE TITLE
Bug: Harvests should be able to accept periodicity info in Modified field

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2612]
Per https://project-open-data.cio.gov/v1.1/schema/#modified Harvests ought to be able to accept values like "R/P1D", "R/P2W", etc. in addition to dates. Currently this appears to not be the case. This may have implications for architecture: where should non-date/periodicity values be stored?

Could be added to Frequency (i.e. accrualPeriodicity), but we'd need to decide how to handle JSON that includes both values.

**Comment by dafeder** [comment]
I propose that we change the source_updated field to be a plain text field and use PHP to validate for all the permutations of ISO 8601 that the Project Open Data spec allows.
