### ISSUE TITLE
Discovery: how can user roles/permissions be less confusing?

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2623]
As a site manager, I'd like site permissions (who can do what) to be clearer and less complex, so that I can be confident I know which permissions are granted to which user.

The combination of DKAN core roles (administrator,site manager,editor,content creator) and Group roles (pending group member, active group member, administrator group member) and Workflow roles (contributor,moderator,supervisor) can be a real vortex of confusion, even though/because they seem similar and in use may often overlap.

Are there ways to simplify the UI around these roles, or even combine them so that site managers can have less moving parts to take into account?

**Comment by erogray** [comment]
re: https://civicactions.atlassian.net/browse/OPENDATA-189

**Comment by janette** [comment]
Ideally only CA users would have the administrator role.

Can you specify what is confusing: https://dkan.readthedocs.io/en/latest/components/permissions.html

Summary
content creators:
- create resources and datasets
- edit own stuff

editors:
- create resources, datasets, data stories, data dashboard, visualizations
- can edit own stuff and any resource/datasaet/story/dashboard in their group created by others

site manager
- create/edit/delete ANY content in ANY group
- add/remove users
- create/edit groups
- create/edit harvest source

**Comment by erogray** [comment]
The DKAN core roles are clear enough, I think; the problem is how they combine with group roles and workbench roles.

I've had multiple inquiries from users who could not find a role combination in which a user could edit datasets that they did not create. This was due to editors being assigned to groups, but only as Pending group members (it's unclear that group members need to be activated after being assigned to a group); and/or assigned to groups, but not as group administrators. 

In addition, lower-level roles sometimes seem to subtract permissions from higher-level roles, such that someone assigned to more than one role may not have the permissions available to the higher-level one. I've also seen instances in which site managers attempted to make someone both a Content Creator and also an Editor.

**Comment by erogray** [comment]
If we could skip the group-member-activation step, that'd make things easier. Right now, if you as a site manager add a user to a group, you still need to go to the group's page to activate them, but there's no indication anywhere that this is so unless you already know to do it. If we could allow group members to be assigned without that pending_member stage, it'd be a significant improvement. I don't see a lot of use cases so far for group membership to be that carefully guarded.

**Comment by erogray** [comment]
Proposed resolution: skip Pending group activation, so that group roles are unnecessary for users to consider: at that point Editors in a group will always automatically be group administrators without having to manually change group role.

**Comment by erogray** [comment]
Closing in favor of #2630
