### ISSUE TITLE
Data.json contact info incorrectly formed

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2625]
“@type”: “vcard:Contact” is excluded from data.json, such that it shows as:

```json

"contactPoint": {
  "fn": "firstname lastname",
  "hasEmail": "mailto:email@address.com"
}

```

instead of following the proper ProjectOpenData 1.1 schema:

```json

"contactPoint": {
  "@type": "vcard:Contact",
  "fn": "Jane Doe",
  "hasEmail": "mailto:jane.doe@agency.gov"
 }
```

**Comment by acouch** [comment]
Looks like it is not required https://project-open-data.cio.gov/v1.1/schema/#contactPoint-type so maybe not an issue? Where is this getting reported?

**Comment by kimwdavidson** [comment]
this looks like a pretty old issue and not necessarily a bug, though this request does make sense. possible professional services option.
