### ISSUE TITLE
Group membership should skip Pending

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2630]
When DKAN site users are added to Groups, they should become active members of the Group immediately and not need a separate activation. If Editors, they should also immediately become Group admins.

This ought to dramatically reduce user role confusion and make the site easier to use.

See also #2623 and #2624

**Comment by janette** [comment]
Just need to fix the pending membership state: https://www.drupal.org/project/og/issues/2744405

The group role is already automated https://github.com/GetDKAN/dkan/pull/1786
