### ISSUE TITLE
Add search sort by created date

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2631]
Currently, out-of-the-box DKAN allows sorting of search results by "Date changed" and "Title". As a data consumer, I'd like to also be able to sort by created date so that I can view search results in the order that they were generated.

See for example https://data.city.kyoto.lg.jp/search?query=&sort_by=created&sort_order=DESC&f%5B0%5D=type%3Adataset&f%5B1%5D=type%3Aresource&op=%E6%A4%9C%E7%B4%A2

<img width="461" alt="screen shot 2018-08-17 at 3 49 04 pm" src="https://user-images.githubusercontent.com/21176376/44291724-2acf5f80-a235-11e8-9351-79883df59832.png">

**Comment by janette** [comment]
@erogray I can have a PR for this by EOD

**Comment by erogray** [comment]
See also https://github.com/GetDKAN/dkan/issues/2396
