### ISSUE TITLE
Create smoke tests

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2646]
It's not practical to run the full suite of DKAN tests on sites that have been configured, customized, etc. We should have a core group of "smoke tests" that make sure nothing has broken after an upgrade, but don't try to run every core DKAN test because there are too many differences.

## Acceptance Criteria

- Look at Javascript tests and choose a small set that is representative of the major components of DKAN
- Tag added to smoke tests
- Resolve workflow issue
- A minimum number of tests are now used for project sites for testing releases (modify site repos' circleci  config to run only smoke tests)
- Document config changes for sites

**Comment by kimwdavidson** [comment]
Janette to look at Javascript tests and choose a small set that is representative of the major components of DKAN

**Comment by janette** [comment]
Unable to reproduce the errors on circleci in local sandbox, everything passes locally

**Comment by kimwdavidson** [comment]
Blocked by GetDKAN/dkan-tools#20

**Comment by fmizzell** [comment]
@janette I rebased the PR. Now the tests are running but we are getting some failures.
