### ISSUE TITLE
Resource preview error (database prefix) after datastore import

### ISSUE THREAD

**Issue by vfonsecaz** [GetDKAN/dkan#2648]
Hi,

After importing a resource to a datastore a new db table is created, in my case, _dk7feeds_datastore_dkan_file_3_

When previewing the resource the db table queried **doesn't add the db prefix** (dk7)

![dkan](https://user-images.githubusercontent.com/9846715/44908391-2ca82100-ad13-11e8-93a4-ddb2e2398fd7.jpg)

**Comment by dafeder** [comment]
@vfonsecaz thanks for reporting this bug. We are in the middle of a major datastore refactor and would be focusing on making sure this works correctly there and that there is a good upgrade path. The new version of the datastore will be released very soon. If you would like to submit a PR to fix this for the version you're currently using we'd be happy to review it.

Please feel free to re-open this issue if needed.
