### ISSUE TITLE
Dataset URL aliases don't respect input form

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2651]
As a user, I'd like to be able to specify the URL alias for my dataset so that I can ensure memorable and typable web addresses. 

Currently the URL appears to depend only on the dataset Title and not the specified URL.

For instance, http://andrew.dkandemo.nuamsdev.com/dataset/title-sure-long:
<img width="341" alt="screen shot 2018-09-04 at 3 23 13 pm" src="https://user-images.githubusercontent.com/21176376/45062253-f3e2b180-b05c-11e8-8cfe-1ac73f1869f4.png">
Or http://andrew.dkandemo.nuamsdev.com/dataset/descriptive-title:
<img width="384" alt="screen shot 2018-09-04 at 3 29 36 pm" src="https://user-images.githubusercontent.com/21176376/45062353-5f2c8380-b05d-11e8-94fe-a099d0bd46f0.png">

/admin/config/search/path/list allows manual editing of aliases, but that's not particularly useful for most content creators.

**Comment by erogray** [comment]
See https://civicactions.atlassian.net/browse/OPENDATA-329 for user-submitted example

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended
