### ISSUE TITLE
Multilingual recipe

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2655]
While DKAN has been successfully launched in languages other than English dozens of times, the process for getting started and maintaining is not well-documented. In addition, DKAN provides no support out-of-the-box for true multilingual implementations. A future point release of DKAN will provide an easy path to enabling multilingual content, site manager access to the translation interface, a themed language switcher, and other improvements to make multilingual interfaces as seamless as possible.

**Comment by jjalcolea** [comment]
This would be a great addition.

Best,

Juanje.

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended. Open separate issues for multilingual support in DKAN 2.x+
