### ISSUE TITLE
Custom view for checking metadata and dataset quality

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2657]
As a site manager, I'd like a built-in custom report to allow me to find and unpublish datasets with metadata quality issues, so that I can ensure that my data quality is high.

Out-of-the-box DKAN sites should include a custom report that includes a status change option by checkbox (for publishing/unpublishing many datasets at once), and filters to select and find datasets that may need improvement or removal.

Suggested filters to enable finding datasets with the following characteristics include:
- with no resource
- by published status
- by Publisher
- by Harvest source 
- by Updated date 
- by Author
- (Federal clients only) by bureauCode 
- (Federal clients only) by programCode.

Examples: 
https://healthdata.gov/admin/reports/datasets_metadata_checker
https://healthdatagovdev.prod.acquia-sites.com/admin/reports/datasets_with_no_resource

**Comment by erogray** [comment]
bureauCode and programCode can be based on federal extras toggle?

**Comment by acouch** [comment]
Does ``/admin/config/services/odsm/validate/pod`` provide some of that functionality? Maybe each dataset needs a validation flag?

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended
