### ISSUE TITLE
Harvest error-proofing

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2659]
As a site manager, I need a harvest that encounters errors to fail elegantly, log the problem somewhere useful, and then continue with the next available dataset, so that problems like incomplete metadata don't cause larger failures to complete updates to harvested datasets.

For an example, try harvesting 

https://s3.amazonaws.com/dkan-default-content-files/ca-dkan-demo-data.json

The harvest will fail due to some broken links, but won't log the errors, just print them to the screen. 

It's possible that most of these probems are happening in resources, and just wrapping certain steps in try/catch would prevent fatal errors.

**Comment by erogray** [comment]
Needs specific examples to test

**Comment by kimwdavidson** [comment]
Closing in favor of #2819
