### ISSUE TITLE
Doubled-up header rows in grid above a certain number of rows

### ISSUE THREAD

**Issue by nditechteam** [GetDKAN/dkan#266]
With a large enough number of columns in an imported resource, you get a bizarre second header row in the Grid view

**Comment by kimwdavidson** [comment]
Need to find out if this is still an issue.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
