### ISSUE TITLE
When a resource is changed, re-save dataset

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2663]
As a site manager, I want to be sure that the modified date for a dataset updates automatically when a resource in the dataset is modified, so that my metadata does not become incorrect. 

When a resource's modified date is updated, can we trigger a re-save on the dataset?

**Comment by dafeder** [comment]
Would have to think through workflow implications; a new draft of a resource should not change the published modified date until it's been published.

**Comment by erogray** [comment]
This seems like an important feature to keep on our to-do list. Site managers should be able to feel confident that modified dates are accurate.

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended
