### ISSUE TITLE
Can't preview resources with  'X-Frame-Options' set to 'sameorigin'

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2669]
Previews on resources linking to websites appear to fail if the domain name includes a country code TLD like .lc or .scot. 
Will updating Recline help?

Some potential URLs to test with:
https://www.gov.scot/
http://data.govt.lc/
https://cira.ca/
http://registre.quebec/
http://www.gov.na/about-namibia
http://www.data.go.jp/
https://data.gov.il/
https://data.gov.in/catalog/union-budget-2018-19

**Comment by janette** [comment]
this might be the prob  'X-Frame-Options' set to 'sameorigin'.

**Comment by erogray** [comment]
x-frame-options means that previewing URLs might be unreliable no matter what. Is it better to just remove previews for external webpages? Or to show them only if x-frame-options are not set?

Potential course of action:
1. look at google analytics to see if resource previews are commonly used
2. assess popularity of previews for site managers

if we determine that these previews are not important, perhaps we should remove them entirely.
if we think they are important:
we could modify preview pages to check for x-frame-options set to sameorigin, and if so instead of showing iframe show a message that says something like "This webpage has disabled external previewing, but you can visit the page at _link_".

**Comment by erogray** [comment]
Let's call this a research ticket for now and do some research.

**Comment by erogray** [comment]
https://github.com/GetDKAN/recline/pull/98 indicates that previews were intentionally removed in 1.15 branch of recline but dkan isn't using that branch yet.

**Comment by acouch** [comment]
Looks like we are using ``7.x-2.x`` in DKAN https://github.com/GetDKAN/dkan/blob/7.x-1.15.3/drupal-org.make#L8 but the ``1.15`` branch of Recline has not been pulled into ``7.x-2.x``.
