### ISSUE TITLE
Feature request: Ability to flag/unpublish Project Open Data non-compliant datasets added via Harvester

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2672]
As a Site Manager, I would like to be able to customize Harvests so that Project Open Data (and other metadata schema) non-compliant datasets are not displayed on the live site. This would also apply to existing Harvests.

We need an improvement that would flag non-schema compliant datasets and automatically unpublish them (rather than delete, so that they could be reviewed first.). Ideally, they'd be listed on a separate error page of their own.

**Comment by dafeder** [comment]
I think @erogray's suggestion -- validating the incoming data.json and skipping any records that produce errors -- is the way to go. But we still need to figure out how to communicate that clearly to people after it happens. This requires further speccing.

**Comment by dafeder** [comment]
Note: we need to be able to control for federal vs non-federal requirements

**Comment by erogray** [comment]
See also https://github.com/NuCivic/healthdata/issues/1115
