### ISSUE TITLE
Document data dictionaries and validation

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2680]
Write a new page in DKAN docs describing both data dictionaries and validation process.

**Comment by csparr** [comment]
Would love to see some documentation on this. Will be asking some questions in the DKAN slack channel in case @rhabbachi can answer.

**Comment by rhabbachi** [comment]
Link to the Slack thread: https://dkan.slack.com/archives/CCT1QV2J0/p1565375658001700

**Comment by kimwdavidson** [comment]
Planning this work on the Drupal 8 version in #3169. Closing.
