### ISSUE TITLE
More information on datastore import progress

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#2682]
In the new datastore in branch ```datastore-improvements``` we use a hybrid approach in which we attempt to import a file with a batch process, but if the file is too large, we interrupt the batch process and transition to continue the import process in a cron job.

When the cron job is running we do not get much information about the progress. Also while visiting the datastore page for the resource in progress, it is difficult to know how far things have gone and how much longer it should take.

## Acceptance criteria
- If a local file, get the total filesize, so that we can get a percentage based on number of chunks processed
- If a remote file, _attempt_ to get the filesize through a HEAD request, and do the same
- Progress % should be visible on datastore page if in progress
- If no filesize available, provide "Unknown" on datastore page
- Bonus: if possible, provide output to terminal when running the cron command (# of records and progress if available)

**Comment by erogray** [comment]
@fmizzell should this be a dkan2 ticket?

**Comment by erogray** [comment]
@fmizzell is this ticket still relevant?

**Comment by fmizzell** [comment]
We have a nice report accessible through drush in 2.x.
