### ISSUE TITLE
Discovery: improve "temporarily unavailable" error page

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2686]
The "Temporarily Unavailable" error page can be more confusing and/or uninformative than necessary; can it be improved?

![hdg error](https://user-images.githubusercontent.com/21176376/46506994-97a5b580-c7f3-11e8-88f8-61ec5c4038c1.jpg)

**Comment by dafeder** [comment]
This comes from the host (Acquia in this case) and we don't really have control over it.
