### ISSUE TITLE
Harvests populating Post Date with modified date?

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2687]
Possible bug: when harvesting from a source data.json that includes issued date and also modified date values, it seems that the modified dates are winding up in the Post Date field instead of using the issued date. (Needs more investigation)

**Comment by stefaniefgray** [comment]
Issue is in the front page block which orders datasets by date created

**Comment by erogray** [comment]
Suggested solution: 
1. when a dataset is not harvested, mirror Created Date into Harvest Source Issued field when a dataset is not harvested; and also mirror Modified Date into Harvest Source Modified field when a dataset is not harvested; 
2. create a View for Latest Datasets that uses Harvest Source Issued field (for recently created); and/or a View for Recently Updated Datasets that uses Harvest Source Modified.
3. consider having those fieldnames not named "Harvest Source" since they're now universal (not just for harvested values)

**Comment by erogray** [comment]
Fix on product should be a minor task but update path for existing data will require a hook; will also need to double-check to see if other code depends on these fields

**Comment by dafeder** [comment]
After some discussion we're not convinced this should go into DKAN core. Solution would be a small custom node update hook on the project site that populates the `created` property into the `field_harvest_source_issued` in any instance where that field does not get a value from a harvest. The view would then be sorted on the `field_harvest_source_issued` field. Let's also publish this as a "recipe."
