### ISSUE TITLE
Harvest "The modified value is not a valid ISO 8601 Date" errors

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2688]
When a modified date does not include a day (example: in yyyy/mm format, like "modified": "2018-05"), the resulting dataset may pick up another date value instead.

**Comment by janette** [comment]
Let's remove the date formatter and display the value as is rather than forcing a specific date format.

**Comment by janette** [comment]
@erogray do we have an example we can use for QA purposes

**Comment by erogray** [comment]
Some examples (drawn from https://healthdata.gov/node/2648186/harvest-errors, all harvesting from https://dashboard.healthit.gov/data.json):
- https://healthdata.gov/dataset/2015-edition-market-readiness-hospitals-and-clinicians-data renders the date as "2018-09-19".  The source json however has this as "modified": "2018-05".
- https://healthdata.gov/dataset/state-health-it-policy-points-contact uses "modified": "2017-07"
- https://healthdata.gov/dataset/ehr-products-used-meaningful-use-attestation uses "modified": "2017-08"

**Comment by acouch** [comment]
@janette Is the "modified date" the node update date? Is it possible to fix this without moving "modified" to its own field?

**Comment by janette** [comment]
@acouch the value is stored in an existing hidden field called `field_harvest_source_modified`, the fix for this is a better date validator that can handle partial dates like '2017-08'

**Comment by dafeder** [comment]
We're going to pause on this and take another look at possible solutions...
