### ISSUE TITLE
Datastore tables should be generated as innodb tables

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2698]
The new datastore is missing a step to add full-text to strings. The new datastore does not add types for columns so we would want to full-text all of the columns or do some discovery for strings. The old code is https://github.com/GetDKAN/feeds_flatstore_processor/blob/master/feeds_flatstore_processor.module#L168

Additionally the API docs include ``q (string) – fulltext search`` when it should be "query", not "q".

After addressing this we could also close https://github.com/GetDKAN/dkan/issues/2042

**Comment by erogray** [comment]
@janette to bring up with PQDC team

**Comment by janette** [comment]
search across all columns

**Comment by erogray** [comment]
@acouch is this a documentation need? Or a shortcoming of Recline? Or both?
Or is this not relevant for D7?

**Comment by erogray** [comment]
@acouch is this a documentation need? Or a shortcoming of Recline? Or both?
Or is this not relevant for D7?

**Comment by erogray** [comment]
@acouch ^

**Comment by erogray** [comment]
@janette to bring up with PQDC team

**Comment by janette** [comment]
To do: switch the datastore tables to innodb

**Comment by erogray** [comment]
New datastore tables are being generated as InnoDB, this can be considered done
