### ISSUE TITLE
Fix harvest process for importing license values

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2715]
Currently the license data is entered into a select field. When harvesting the license values are urls and end up in the search facet as unclickable links

## Acceptance Criteria
- License values are 'converted' to the select field key values when they match an option that exists.
Existing options: https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_dataset/modules/dkan_dataset_content_types/dkan_dataset_content_types.license_field.inc#L64
- Values that do not match an option the 'Other' key is selected and the value saved to 'field_license[und][other]' 

![license_field](https://user-images.githubusercontent.com/314172/47507565-03e66880-d838-11e8-91b8-ca0c311a0de7.png)

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended
