### ISSUE TITLE
data.json has html in downloadURL and accessURL values

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2716]
Invalid data.json files when remote files are used. Need to update the ODSM token
`[node:field-resources:Nth:field_link_remote_file] || [node:field-resources:Nth:field-upload:url]`
to 
`[node:field-resources:Nth:field_link_remote_file:url] || [node:field-resources:Nth:field-upload:url]`

## Steps to reproduce
1. Add a resource to a dataset, use the remote file field and enter 'https://www.va.gov/QUALITYOFCARE/SAIL_FY18_Q2/SAIL-23_stcloud_fy18q2.xlsx'
2. Save and rebuild the data.json file `drush odsm-filecache data_json_1_1`
3. Confirm the file is now invalid due to html tags in the downloadURL value
![html_in_downloadurl](https://user-images.githubusercontent.com/314172/47662244-918fc400-db68-11e8-9c13-26abc0ddafe8.png)

## QA Steps
1. Add a resource to a dataset using the remote file field
2. rebuild the data.json file
3. confirm the downloadURL is valid (url only, no html)

**Comment by dafeder** [comment]
Can't reproduce, and needs more detail.

**Comment by janette** [comment]
@dafeder updated the info
