### ISSUE TITLE
Error while enabling dkan link checker

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2727]
When I tried to enable the DKAN link checker, I received an unexpected error message. I checked in the logs and this is the actual php message I received:

Location: http://<URL>/admin/modules/list/confirm
Message: DatabaseSchemaObjectExistsException: Table linkchecker_block_custom already exists. in DatabaseSchema->createTable() (line 663 of /var/dkan_test/includes/database/schema.inc).

When you repeat this process (modules->enable module dkan link checker) it works.

**Comment by dafeder** [comment]
Thanks for reporting @chrodos - we can't reproduce. It sounds like in your case you have a one-time workaround and we haven't heard this from anyone else so I'm going to close. Please feel free to re-open and/or submit a fix.
