### ISSUE TITLE
Bug: Anonymous Users Can View Unpublished Nodes authored by Anonymous

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2728]
When DKAN_workflow is enabled: Anonymous users are able to view unpublished content if the content is authored by 'anonymous'.
This happens when content is created and the author field is left blank

## Steps to reproduce
- Enable dkan_workflow
- Create content that is unpublished and authored by 'anonymous'
- view the content as an anonymous user

## Acceptance Criteria
- Anonymous users should NOT be able to view unpublished content.
- Content creators should be able to view their own unpublished content.
- Site managers and editors can view any unpublished content

Related: https://github.com/GetDKAN/dkan/issues/2311

**Comment by erogray** [comment]
Seems likely to be a Drupal issue, not just a DKAN issue?
