### ISSUE TITLE
Pull in/document region selects for leaflet draw widget

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#2731]
@jacintocapote did some work several years ago to provide a select list of geographic regions for the data extent field, to avoid having to draw oneself. This is very useful functionality but needs to be pulled in correctly to DKAN and documented. See work in:

https://github.com/GetDKAN/leaflet_draw_widget/commit/cb310060aabe44673fd71e35208759bc1340c56f#diff-5d160af1bba2304bba7b198f97d98ad9
https://github.com/GetDKAN/leaflet_draw_widget/pull/11
https://github.com/GetDKAN/leaflet_draw_widget/pull/9

**Comment by kimwdavidson** [comment]
This isn't currently on our roadmap, but we do think it's a great idea. We're closing for now, but please reopen (or even better, submit a PR) if this is of interest to you.
