### ISSUE TITLE
QA New Datastore

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2735]
- [ ] large file
- [ ] historically difficult file
- [ ] recline previews work
- [ ] embeded preview works

**Comment by janette** [comment]
![datastore](https://user-images.githubusercontent.com/314172/48181460-2d4dcc80-e2ed-11e8-92e4-69258f0804a5.png)

**Comment by janette** [comment]
VA resource test
http://janette.dkandemo.nuamsdev.com/node/4/datastore

```
Invalid line 1 in https://www.va.gov/DIGITALSTRATEGY/cemdata/states/ngl_alabama.csv; header: ["d_first_name","d_mid_name","d_last_name","d_suffix","d_birth_date","d_death_date","section_id","row_num","site_num","cem_name","cem_addr_one","cem_addr_two","city","state","zip","cem_url","cem_phone","relationship","v_first_name","v_mid_name","v_last_name","v_suffix","branch","rank","war"] values: ["Winston","Russell","Langley",null,"08\/24\/1950","03\/09\/2018","2",null,"1341","ALABAMA NATIONAL CEMETERY","3133 HIGHWAY 119",null,"MONTEVALLO","AL","35115","http:\/\/www.cem.va.gov\/CEM\/cems\/nchp\/alabama.asp","205-665-9039","Veteran (Self)","Winston","Russell","Langley",null,"US MARINE CORPS","LCPL","VIETNAM",""]
```

**Comment by erogray** [comment]
When importing the CSV at http://janette.dkandemo.nuamsdev.com/dataset/ero-test-data/resource/3282ee42-50e6-4e5c-8bce-1df00566aa27#{} I got a "SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs" error.

<img width="1164" alt="screen shot 2018-11-09 at 12 18 37 pm" src="https://user-images.githubusercontent.com/21176376/48286233-deea1c00-e419-11e8-9b2b-9d71e96db7ca.png">

**Comment by erogray** [comment]
Trying to import the gravesite data (from a VA resource) for http://janette.dkandemo.nuamsdev.com/dataset/ero-test-data/resource/78694916-ffb0-4b6f-8656-a536e5fe8832#{} yielded a generic Error:

<img width="451" alt="screen shot 2018-11-09 at 12 32 49 pm" src="https://user-images.githubusercontent.com/21176376/48286822-b531f480-e41b-11e8-8591-c661bbda1774.png">

**Comment by erogray** [comment]
After importing http://janette.dkandemo.nuamsdev.com/dataset/ero-test-data/resource/7549be3e-179b-4db3-8cdb-008475bbf5a1 (which seemed successful) I viewed the API (seems to look good), but then when I hit the Back button to get back to the Resource, I got a formidable block of pink.

<img width="1136" alt="screen shot 2018-11-09 at 12 48 41 pm" src="https://user-images.githubusercontent.com/21176376/48287492-ef9c9100-e41d-11e8-9ec7-349b553ffc4e.png">

**Comment by erogray** [comment]
If I attempt to import a PDF file, the importer shows some mixed messages.

<img width="314" alt="screen shot 2018-11-09 at 12 53 26 pm" src="https://user-images.githubusercontent.com/21176376/48287687-8f5a1f00-e41e-11e8-8e13-140174da48ee.png">

**Comment by erogray** [comment]
After importing the standard test fixture http://janette.dkandemo.nuamsdev.com/dataset/ero-test-data/resource/bd2b8c33-4def-4a58-9a7e-f1e8075ed338 and clicking the Download button (which, as previously noted, doesn't work) I get an interesting combination of error messages, depending on which page I look at:
<img width="1174" alt="screen shot 2018-11-09 at 1 09 04 pm" src="https://user-images.githubusercontent.com/21176376/48288396-d2b58d00-e420-11e8-8031-cbd4de79d22e.png">
<img width="1419" alt="screen shot 2018-11-09 at 1 09 13 pm" src="https://user-images.githubusercontent.com/21176376/48288397-d2b58d00-e420-11e8-8c06-e4ae75eac647.png">
<img width="1164" alt="screen shot 2018-11-09 at 1 09 28 pm" src="https://user-images.githubusercontent.com/21176376/48288399-d34e2380-e420-11e8-9b96-1f0b1390e196.png">

**Comment by erogray** [comment]
Download button seems to work correctly now!

On https://ba15eb9d-e36c-48e4-821f-df693ed795d7--pr-2734.probo.build/node/45/datastore I got some gnarly import errors on what seems like a pretty normal CSV (https://ba15eb9d-e36c-48e4-821f-df693ed795d7--pr-2734.probo.build/dataset/ero-test-data/resource/22c408a4-7b64-448a-b1dd-c10021cb7f22): 
<img width="1303" alt="screen shot 2018-11-12 at 1 04 37 pm" src="https://user-images.githubusercontent.com/21176376/48375090-ad708b00-e67b-11e8-9361-725ada9ffc4c.png">

**Comment by janette** [comment]
@erogray even with the built-in disclaimer at the top? 
![info](https://user-images.githubusercontent.com/314172/48376212-d8fd7080-e68f-11e8-9f5f-d70f84ab1830.png)

**Comment by erogray** [comment]
When adding a remote CSV, https://ba15eb9d-e36c-48e4-821f-df693ed795d7--pr-2734.probo.build/dataset/test-dataset/resource/978c60a5-12f5-4252-a03c-9782e522b3ce , I got a "Node 44 doesn't have a proper file path." error:

<img width="439" alt="screen shot 2018-11-12 at 2 31 56 pm" src="https://user-images.githubusercontent.com/21176376/48379109-d72faf00-e687-11e8-90cc-29c309a8b735.png">

**Comment by janette** [comment]
@erogray @stefaniefgray The above example resource was added to the **API or Website URL** field, so would not be expected to be added to the datastore. The user would either need to use the **upload** field or **remote file field**

**Comment by erogray** [comment]
When adding a remote file that's an XLS, http://www.energy.ca.gov/almanac/electricity_data/vintage/Vintage_Annual_Power_Plant_capacity.xls to https://ba15eb9d-e36c-48e4-821f-df693ed795d7--pr-2734.probo.build/dataset/us-tobacco-usage-statistics/resource/311727ad-a0b8-49c3-bbc8-0e20d0d91682 I got "Notice: Undefined offset: 1 in DrupalRemoteStreamWrapper::getHeaders() (line 96 of /src/dkan/modules/contrib/remote_stream_wrapper/remote_stream_wrapper.inc)."

<img width="735" alt="screen shot 2018-11-12 at 3 27 20 pm" src="https://user-images.githubusercontent.com/21176376/48381177-abb0c280-e68f-11e8-8cea-e9d449f28719.png">

**Comment by erogray** [comment]
As with the XLS file linked to above, it seems like in general some filetypes are not correctly icon-identified when a resource is created. A Zip file also shows a "data" icon in https://ba15eb9d-e36c-48e4-821f-df693ed795d7--pr-2734.probo.build/dataset/us-tobacco-usage-statistics/resource/ba83ef35-f0d2-422d-9977-49f13d58291c

**Comment by erogray** [comment]
I've added a TSV file: https://ba15eb9d-e36c-48e4-821f-df693ed795d7--pr-2734.probo.build/dataset/florida-bike-lanes/resource/8599ca38-8fd1-4590-a2ba-0babd693569f#{} but I get a "cannot be imported to our datastore." message, which seems incorrect for this filetype.

<img width="956" alt="screen shot 2018-11-12 at 3 56 36 pm" src="https://user-images.githubusercontent.com/21176376/48381991-ba00dd80-e693-11e8-99aa-22dff60ab8df.png">

**Comment by erogray** [comment]
QA is complete, moving to test on actual sites
