### ISSUE TITLE
Can't import non-English characters into Datastore

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2742]
As a DKAN user who speaks a language other than English, I would like to be able to upload data resources to my site and import them to the Datastore.

I have created a CSV in Greek called "Fruit Quantities," and it shows the total of apples, oranges and bananas.

The file displays perfectly within DKAN - however, it cannot be imported to the Datastore without throwing an error.

"SQLSTATE[42000]: Syntax error or access violation: 1166 Incorrect column name ‘’

I do not think this is a true SQL error; I believe this is an issue with support for non-English characters.

*Acceptance criteria:* I can import my Greek data resource into the DKAN Datastore.

See original ticket filed by Chrodos -- 2741

**Comment by janette** [comment]
@stefaniefgray can you supply the file

**Comment by stefaniefgray** [comment]
File from Chrodos: http://opendata-sandbox.ouc.ac.cy/dataset/%CE%BC%CE%AD%CF%83%CE%B5%CF%82-%CE%B4%CE%B1%CF%80%CE%AC%CE%BD%CE%B5%CF%82-%CF%84%CE%BF%CF%85%CF%81%CE%B9%CF%83%CF%84%CF%8E%CE%BD-%CE%BA%CE%B1%CF%84%CE%AC-%CE%BC%CE%AE%CE%BD%CE%B1/resource/c81bed08-2cbe-445c-97b8-8da428884359#{view-graph:{graphOptions:{hooks:{processOffset:{},bindEvents:{}}}},graphOptions:{hooks:{processOffset:{},bindEvents:{}}}}

Appears to be working now; asked him in #2741, am waiting for a response

**Comment by kimwdavidson** [comment]
Looks like this is good to go. Closing.
