### ISSUE TITLE
Harvest filters are case-sensitive - help-text or modification needed

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2746]
As a user attempting to harvest datasets to my DKAN site from https://gishubdata.nd.gov/data.json, I specifically want to filter for datasets with the Topic "Geoscientific."

There are 18 datasets with this theme on the NDGIS portal.

However, if I put a filter for theme = "geoscientific," Harvest reports that there are zero datasets available.

By changing it to "Geoscientific," I was able to access the 18 datasets.

*Acceptance criteria:*

Either:
The Add/Edit Harvest Source page needs help text above the filter fields explaining that filters are case-sensitive.

OR:
Harvest filter fields should no longer be case-sensitive.

**Comment by dafeder** [comment]
I think these _should_ be case-sensitive, so let's add some help text to what's already there and link to docs for more. We should perhaps revamp the docs a bit as well, but under another issue.

**Comment by dafeder** [comment]
We'll make a new ticket to group all help text issues on the harvest form. Closing this one.
