### ISSUE TITLE
CartoDB previews are broken, not available for any file type

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2749]
As a user who wants to share geospatial data on my DKAN portal, I would like to be able to preview common GIS file types such as KML and GeoJSON using Carto (formerly known as CartoDB.)

As an admin, I've enabled Carto for the aforementioned file types on the DKAN dataset previews page, located at admin/dkan/dataset_preview

I have also cleared the cache, and double-checked all relevant settings.

As shown in the image below, ArcGIS previews are possible within DKAN, and a button is available next to an ESRI REST file.

![screenshot 2018-11-15 14 08 42](https://user-images.githubusercontent.com/9059428/48581968-81097880-e8e0-11e8-9661-44b270d87297.png)

However, there should also be a "CartoDB Preview" button available next to the GeoJSON and KML files. There is not.

Carto is proprietary software -- and because I'm not quite sure if this feature has ever worked, I don't know if it's worth salvaging. 

It may be more trouble than its worth to preview items stored on DKAN within Carto, and may be better to use an open-source previewing tool such as Leaflet.js or Mapbox/OpenStreetMap.

**Comment by dafeder** [comment]
@stefaniefgray can you please enter some specific steps to reproduce, including links to files to use, so that we can check this without too much flailing around?

**Comment by erogray** [comment]
Test shown above can be viewed at http://andrew.dkandemo.nuamsdev.com/dataset/114thcd-2ndsession

**Comment by stefaniefgray** [comment]
Steps to reproduce:
1. Go to admin/dkan/dataset_preview and enable all possible CartoDB previews, then save configuration:

![screenshot 2018-11-27 12 02 26](https://user-images.githubusercontent.com/9059428/49104864-59010a00-f23c-11e8-8967-e400486b191a.png)

2. Clear the cache, to be safe.

3. Create a new Harvest Source from https://data-va-oei-ncvas.opendata.arcgis.com/data.json (a USVA GIS resource).

4. Check out the dataset that was harvested - it contains a CSV and a KML file. Both of these formats had CartoDB previews enabled. However, the "CartoDB Preview" button fails to appear.

**Comment by janette** [comment]
@stefaniefgray this may be fixed by https://github.com/GetDKAN/dkan/pull/2772

**Comment by erogray** [comment]
Appears to have been fixed by https://github.com/GetDKAN/dkan/pull/2772
