### ISSUE TITLE
Documentation License & Translation

### ISSUE THREAD

**Issue by kominoshja** [GetDKAN/dkan#2753]
Hi all!
 I wanted to translate the documentation here: https://docs.getdkan.com/en/latest/admin/index.html
I'm unsure about the license it's in, and therefore, if it can be translated into another license. 
Can you please help me out?

**Comment by erogray** [comment]
Hi @kominoshja, thanks for asking about this! The documentation (and the application) is open source. Please feel free to translate. You can see license terms at https://docs.getdkan.com/en/latest/license.html

**Comment by kominoshja** [comment]
Thank you @erogray! I'm closing this issue!
