### ISSUE TITLE
can't add group

### ISSUE THREAD

**Issue by sediqamousavi** [GetDKAN/dkan#2757]
As a site manager, after deleting group content type and then again add group content type, I can't add a group  

## Steps to Reproduce
1.delete group content type
2.again add group content type
3.add group from add content menu
![s](https://user-images.githubusercontent.com/43989585/49063452-0c660080-f235-11e8-95c4-f08f4ff6f72f.PNG)

**Comment by erogray** [comment]
@sediqamousavi deleting a content type isn't really reversible; you can try reverting dkan features: `drush fra -y`but if that doesn't work you might need to reinstall dkan from scratch.

**Comment by sediqamousavi** [comment]
My problem has been resolved.@erogray thank you for your help
