### ISSUE TITLE
Recipe or Setting to Enable CORS for the Datastore API

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2764]
We would like to be able to [enable CORS](https://enable-cors.org/) for the datastore API so users can request data more easily from applications.

This would likely either be done in:

* .htaccess
or
* services module

If the solution is in services module would be optimal if this setting is configurable and off by default.

## Acceptance Criteria
Add the goals and desired results that this issue should accomplish when complete.

- [ ] CORS headers present on datastore API
- [ ] CORS not enabled on other routes
- [ ] Security review
- [ ] Documentation

**Comment by erogray** [comment]
@acouch should this be a roadmap candidates card?

**Comment by erogray** [comment]
moving to unprioritized backlog since not currently a known user priority

**Comment by dharizza** [comment]
Security updates and bug fixes only in the D7 version of DKAN. Closing.

**Comment by hoogw** [comment]
Why the dkan demo site NOT enable CORS ??????

I get this error


Access to XMLHttpRequest at 'http://demo.getdkan.org/data.json' from origin 'http://localhost:10' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by hoogw** [comment]
Please enable cors for medicare


Access to XMLHttpRequest at 'https://data.cms.gov/provider-data/data.json' from origin 'http://localhost:10' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
domain.js:773
