### ISSUE TITLE
Recline preview produces unecessary query

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#2765]
Visiting a resource with the datastore enabled and a recline preview enabled produces a query that includes the full path of the resource. For example visiting:

``/dataset/gold-prices-london-1950-2008-monthly/resource/api/3/action/datastore_search``
produces:
``/api/action/datastore/search.json?resource_id=4d6d64b8-5c1d-49b6-a222-652fd4a7cb35&limit=0&query=dataset/gold-prices-london-1950-2008-monthly/resource/api/3/action/datastore_search``

## Steps to Reproduce

1. Import resource to datastore 
2. Visit resource
3. See similar query as above in the network tab of yr favorite open source browser

## Acceptance Criteria

- [ ] visiting recline does not produce query in the datastore
- [ ] querying in recline still works (enter word in search and press "go")

**Comment by dharizza** [comment]
Fixed in https://github.com/GetDKAN/recline/pull/103
