### ISSUE TITLE
DKAN installation breaks after update of Administration menu

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#2768]
Add a brief description about the purpose of the issue.

## Steps to Reproduce
Add steps for reproducing the issue including any file(s) needed to reproduce.

1. Go to modules->update
2. Update Aministration menu plugin from 7.x-3.0-rc5 to 7.x-3.0-rc6
3. The site enters in an infity redirect loop and the browser shows an error

**Comment by dafeder** [comment]
@chrodos we don't really support updating individual modules like this - the DKAN build is managed through make files and updating modules through the interface is untested. We recommend waiting for a future DKAN release that contains the correct version.

If you _must_ update one of DKAN's core dependencies, there are a few ways this could be accomplished -- downloading the module manually and placing it in either profiles/dkan/modules/contrib or sites/all/modules; or modifying drupal-org.make. The strategy will depend on how you are maintaining your codebase. Let's try to find some time to talk on DKAN slack about your particular issue?
