### ISSUE TITLE
Write a test for custom extensions

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2783]
DKAN allows modification to the allowed file extensions for resources via `dkan_allowed_extensions()`
The UI is here: `/admin/dkan/dataset_forms` 

## Acceptance Criteria
1. There is a test for creating a resource with a custom file type and it passes.
2. There is a test for harvesting a resource with a custom file type and it passes.

**Comment by erogray** [comment]
Won't be addressed in DKAN 1; DKAN 2 will need other methods.
