### ISSUE TITLE
Help text for add/edit harvest page

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2786]
As a site manager or administrator, I'd like for the "Add Harvest" page (or edit page), /node/add/harvest-source, to contain useful help text so that I can confidently create harvests without multiple trial and error attempts.

See also https://github.com/GetDKAN/dkan/issues/2746

Some suggestions:
- *Title* should note any restrictions or specifications, and also include help text that says something like "This text will be visible from the Harvest Dashboard, and will also show up as the source for all datasets created by this harvest".
- *Description* could say something like "This text should help any other authenticated users understand the purpose of the harvest, including any filters, exclusions, defaults, and overrides used".
- *Source URI* could say something like "This should be a valid, publicly available URI that specifies a valid JSON file."
- *Type* currently says "Type of source we are harvesting.", which is nice, but perhaps a link to https://project-open-data.cio.gov/v1.1/schema/ would also be helpful.
- *Filters* should say what it does. Currently this text is "Add one or more filters to narrow a harvest to a specific subset of fields and values." A more clear version might be "Add one or more filters to narrow this harvest to _include only datasets_ with a specific subset of fields and values." 
- *Filters* (and excludes, defaults, overrides) should also include some way for the user to know what fieldnames are possible, or at least link to the used schema so that folks can look it up. If there's a way to make this a drop-down, that'd be ideal. https://docs.getdkan.com/en/latest/components/harvest.html has some good information here, but some sort of indicator on-page would be sensible.
- *Filters* (and excludes, defaults, overrides) should also include an indication of why there are two empty fields. The first is for fieldnames, and the second for values, but there's no indication of this on the page. Perhaps a bit of text that says "The field on the left is the type of value (e.g. keyword, publisher.name or theme) that you would like to exclude/override/whatever. The field on the right is the value which you wish to filter for/exclude/provide a default for/replace".
- *Topics* has this text: "Chose topics to be associated with this harvest source. Topics chosen here will be applied to all datasets harvested from this source." This is good, but the first word should have another o in it.

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended
