### ISSUE TITLE
Harvest and DKAN Workflow : Overriding moderation state of a harvested node

### ISSUE THREAD

**Issue by OmarBochkati** [GetDKAN/dkan#2791]
Hi,

I am trying to override the moderation state of harvested nodes and set it by default to "needs_review".
I attempted to achieve this by overriding the "workbench_moderation_state_new" at field mapping level in both "dkan_harvest.migrate.inc" and "dkan_harvest_datajson.migrate.inc" but whenever I harvest as Workflow Contributor and content creator, the harvested nodes go straight to published.

I currently have DKAN 7.x-1.15.5, can you please point me to what I'm doing wrong here

Thank you for your consideration
Kind regards

**Comment by OmarBochkati** [comment]
@janette Thank you for your time and consideration.
Thanks to you I was able to override the states of the harvested nodes. I will see if I can add an option in the harvest source form for this.

**Comment by janette** [comment]
Excellent! looking forward to the PR @OmarBochkati 😉 also be sure to keep your changes in a patch file so you can keep up to date with the latest DKAN release

```
projects:
  dkan_harvest:
    patch:
       1: '../patches/dkan-harvest-status-override.patch'
```
