### ISSUE TITLE
Finish Button dont save the Chart (edit)

### ISSUE THREAD

**Issue by arturoigb** [GetDKAN/dkan#2796]
## Steps to Reproduce

1.Create a Charts
2.Edit the Charts, Press the Finish button
3.View if the changes are there. No changes are made in the chart.

![2019-01-12 1](https://user-images.githubusercontent.com/31836207/51076377-c2f73680-1665-11e9-8493-cbbdc9327d5e.png)
![2019-01-12 2](https://user-images.githubusercontent.com/31836207/51076378-c2f73680-1665-11e9-8395-12d675bfd2fc.png)
![2019-01-12 3](https://user-images.githubusercontent.com/31836207/51076379-c2f73680-1665-11e9-9c38-61875be20f19.png)
![2019-01-12 4](https://user-images.githubusercontent.com/31836207/51076390-e621e600-1665-11e9-8f72-5cad8bd1d393.png)

**Comment by arturoigb** [comment]
I reinstall and make the test with a clean Dkan.. And continue the problem
![2019-01-14](https://user-images.githubusercontent.com/31836207/51139957-46a25600-1813-11e9-8e09-69840818d726.png)
![2019-01-14 1](https://user-images.githubusercontent.com/31836207/51139959-4904b000-1813-11e9-830d-e41a253072d2.png)
![2019-01-14 2](https://user-images.githubusercontent.com/31836207/51139962-4a35dd00-1813-11e9-8aaa-47e033d384d0.png)
![2019-01-14 3](https://user-images.githubusercontent.com/31836207/51139965-4b670a00-1813-11e9-8063-656897604e06.png)

**Comment by arturoigb** [comment]
what kind of spec you need?¿

**Comment by stefaniefgray** [comment]
Hi Arturo,

I am currently unable to replicate this issue while using a basic sample file. Here is the file I am using to create my chart: http://stefanie.dkandemo.nuamsdev.com/sites/default/files/africa-data_0.csv

It seems there may be an issue with your data, or how it is loaded into the chart. Can you please send me a link to the file you're trying to use so that I can see if the problem is with the file or the site itself? Thank you!

Stefanie Gray
CivicActions Support

**Comment by arturoigb** [comment]
http://www.numerosdepanama.com/visualization/ve_chart/19
[expo banano resumen anual.zip](https://github.com/GetDKAN/dkan/files/2766025/expo.banano.resumen.anual.zip)



First i do any graphic with the csv that you send.
then i try to change colors, like example, press the finish button and no change are saved..



![2019-01-16](https://user-images.githubusercontent.com/31836207/51278178-e85aac00-19a7-11e9-8c13-408d7243a9b0.png)
![2019-01-16 1](https://user-images.githubusercontent.com/31836207/51278183-ea246f80-19a7-11e9-9515-350730da3bb9.png)
![2019-01-16 2](https://user-images.githubusercontent.com/31836207/51278189-ec86c980-19a7-11e9-8e07-0c0676a7360d.png)


sorry about my english

**Comment by arturoigb** [comment]
http://www.numerosdepanama.com/visualization/ve_chart/29

**Comment by arturoigb** [comment]
Hi... Sorry about these...
The waf is the problem... sorry to not check that. im not the server admin...
i will close the issue, and sorry to tak your time and for my english =)
