### ISSUE TITLE
Remove vocabulary machine name patch

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#28]
> posted by gaele on January 27, 2014 at 8:17am
> Currently DKAN distro uses a core patch #995156: Use vocabulary machine name for permissions. The issue is set at "Won't fix". The suggested alternative is to use Taxonomy access fix.

---

> Posted by acouch on January 27, 2014 at 5:28pm
> I don't want to add another module to the code base at this point to cover this use case.
> 
> I would consider removing this patch since I don't think we are using it. I would want to make sure we aren't breaking existing installations. I don't think that is the case unless someone is exporting taxonomy permissions which we wouldn't know about.

**Comment by dafeder** [comment]
Let's do some quick research to see if this is still needed. Low priority but would be nice to solve.
