### ISSUE TITLE
Discovery: Harvest revision consolidation

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2814]
Harvested datasets accumulate large numbers of revisions. 
Harvest revisions are authored by anonymous, they share the same timestamp. 
A new revision is created for every resource and every tag on on the dataset.

![revisions](https://user-images.githubusercontent.com/314172/53039409-c8098b80-3444-11e9-99b3-797767a0786a.png)

Let's do a controlled test to see if this happens whenever we update a dataset or resource.

Run a controlled test: Create a dataset with several resources; make a change to a single resource and check the revision log (and the queue table). Do the same for modifications to a dataset node.

## Acceptance Criteria
- A single revision is added to the dataset if a resource is changed.
- NO extra revisions added to datasets if a dataset is changed (but not a resource)

**Comment by dharizza** [comment]
I created a dataset with 5 resources; once I changed either the dataset or any resource, no extra revisions were created. Also tested on a harvested dataset and when we do manual changes, they don't trigger the extra revisions.

I noticed that if dkan_workflow is not enabled, the messages are different even when they are logged in the same timestamp, for example:

![image](https://user-images.githubusercontent.com/2200763/53600820-22ef6100-3b70-11e9-9646-b381df83a66c.png)

If dkan_workflow is enabled, we get the same message for every revision and then it looks like the revisions are duplicated, but I'd say a revision is created every time we add a new resource to the dataset during the harvest process.

**Comment by dharizza** [comment]
New revisions are added to a dataset every time we update any of it resources, sometimes it is not reflected immediately because it gets added to the queue. This is not an issue in the usual workflow but we want to change it during harvest, so this work is being done in https://github.com/GetDKAN/dkan/issues/2826, closing this ticket in favour of that one.
