### ISSUE TITLE
Previews for some harvested resources show up as 503s

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2818]
Some resources (large CSVs, harvested as Remote Files) are showing up in Recline with a "Failed to load file. Service Temporarily Unavailable. Code: 503" error, which seems inappropriate since the files exist. I think it'd be preferable to show users something like "Unable to preview from remote website" instead.

An example: https://data.ca.gov/dataset/periodic-groundwater-level-measurements/resource/b3674f01-c483-430a-9cc2-916296ea18f2

**Comment by acouch** [comment]
Looks like this is coming from the CSV.js library https://github.com/GetDKAN/dkan_starter/blob/master/dkan/libraries/csv/csv.js#L24

Maybe we need to check before sending it to Recline.

**Comment by kimwdavidson** [comment]
@janette to spec

**Comment by erogray** [comment]
@erogray will try to re-create a resource to see if this is a harvest issue, a remote-file issue, or neither

**Comment by erogray** [comment]
When added to a new dataset as a remote-file, a 500 ISE error results: http://andrew.dkandemo.nuamsdev.com/dataset/test-dataset/resource/6cd3bdf5-dc24-4d38-96d5-32e020f9ef91
When added as a local file, a "too large or unavailable" results.
This seems like a problem with remote files.

**Comment by erogray** [comment]
Moving to unprioritized backlog since there isn't an immediate demand for fixing large remote file previews.

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended
