### ISSUE TITLE
Harvest revision clean up

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2825]
Create a script to purge duplicate revisions from existing datasets.

For datasets with multiple revisions with the same timestamp, keep a single revision and delete the rest.

**Comment by dharizza** [comment]
The command created for this is `drush ddpr` which is alias for `drush dkan-dataset-prune-revisions`. 
Note: When both options `--node-max` and `--revision-max` are present, the `--revision-max` is the one which limits the amount of revisions being deleted.
