### ISSUE TITLE
Add DKAN site in Bolivia

### ISSUE THREAD

**Issue by calemanmacias** [GetDKAN/dkan#2831]
Please add this site to your list (https://docs.getdkan.com/en/latest/introduction/dkan-sites.html and https://getdkan.github.io/dkan-sites/):

Location: La Paz-Bolivia
Address: https://datosabiertos.cedla.org

Thank you,
Carlos Aleman

**Comment by dharizza** [comment]
Work done in https://github.com/GetDKAN/dkan/pull/2851 and https://github.com/NuCivic/dkan-sites/pull/16
