### ISSUE TITLE
dkan_datastore_lock set to 1 results in infinite loop / WSOD in Dkan\Datastore\LockableDrupalVariables->getLock()

### ISSUE THREAD

**Issue by neuronick** [GetDKAN/dkan#2836]
If variable **dkan_datastore_lock** is set to 1 (probably as a result of failed update), this results in infinite loop / WSOD which is extremely difficult to debug, as it doesn't produce any error in logs.

## Steps to Reproduce
1. Run variable_set('dkan_datastore_lock', 1); via Devel PHP
2. Go to a resource, containing CSV file (local or remote)
3. There will be infinite loop and a WSOD as a result

**Comment by kimwdavidson** [comment]
@neuronick Thanks for reporting! We'll take a look at this. In the meantime, if you'd like to submit a pull request, we'll be happy to review it.

**Comment by grugnog** [comment]
We are working on this in https://github.com/GetDKAN/dkan/pull/2876
