### ISSUE TITLE
DKAN will not immediately import this file to the Datastore if it is a valid CSV

### ISSUE THREAD

**Issue by datphamict** [GetDKAN/dkan#2843]
Add a brief description about the purpose of the issue.
Dear ALL,

I have already import csv via Dkan Rest API follow the document DKAN will immediately import this file to the Datastore if it is a valid CSV. But it is not as document,

Error:"There is nothing to manage! You need to upload or link to a file in order to use the datastore."

![nh](https://user-images.githubusercontent.com/38518509/53940410-378ba600-40e8-11e9-9b32-ff10320b7a5b.png)

## Steps to Reproduce
Add steps for reproducing the issue including any file(s) needed to reproduce.

1.
2.
3.

## Acceptance Criteria
Add the goals and desired results that this issue should accomplish when complete.

- [ ]
- [ ]
- [ ]

## Subtasks
Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [ ] Is there a test for the issue
- [ ] Is there documentation for the issue
- [ ] Are follow up tickets needed

**Comment by janette** [comment]
@datphamict it sounds like you may have added the file to the `link_api` field, make sure use the `link_file` or `upload` field for files

**Comment by datphamict** [comment]
Dear  janette ,

I use DKAN Dataset Rest API to attach file to resource.

API is request finish and attach file succeess, but csv file is not import to datastore??
(follow the document DKAN will immediately import this file to the Datastore if it is a valid CSV)

Example API request, PHP code:

$request_url = 'http://exam/api/dataset/node/76/attach_file';

$file ="./SampleCSVFile_2kb.csv";

// Setup file data.
$file_data = array(
    'files[1]' => curl_file_create($file),
    'field_name' => 'field_upload',
    'field_format' => 'csv',
    'attach' => 0
);

// Setup request.
$curl = curl_init($request_url);
curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: multipart/form-data','Accept: application/json', 'X-CSRF-Token: ' . $csrf_token));
curl_setopt($curl, CURLOPT_POST, 1); // Do a regular HTTP POST.
curl_setopt($curl, CURLOPT_POSTFIELDS, $file_data); // Set POST data.
curl_setopt($curl, CURLOPT_COOKIE, "$cookie_session");
curl_setopt($curl, CURLOPT_HEADER, TRUE);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($curl, CURLOPT_FAILONERROR, TRUE);

// Execute request and get response.
$response = curl_exec($curl);

echo $response;

**Comment by janette** [comment]
@datphamict you will need to use the UI to add the file to the datastore, it is not automatic.

**Comment by erogray** [comment]
Closing since the workaround is to use the UI to import; feel free to reopen or create another ticket if you have other questions or suggestions
