### ISSUE TITLE
Add support for ReCAPTCHA

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2849]
Some sites are experiencing spam problems (e.g. with feedback module), and ReCAPTCHA might help with this. Currently only standard arithmetic and image CAPTCHAs are available.

**Comment by kimwdavidson** [comment]
Adding this is uncomplicated, but we should discuss the management of non-core contrib modules.

**Comment by erogray** [comment]
Planned approach:
- add ReCAPTCHA to client sites currently using CAPTCHA (GOSA and HHS)
- document in client Nuclino pages
- add a template for contrib modules used on client sites outside core for reference.

**Comment by kimwdavidson** [comment]
Closing in favor of feedback#115
