### ISSUE TITLE
Add National Data Portals for Pacific Island Countries to DKAN Sites List

### ISSUE THREAD

**Issue by tavitas** [GetDKAN/dkan#2861]
Hello,

The Secretariat of the Pacific Regional Environment Programme (SPREP) project Inform has launched national data portals for Pacific Islands countries below based on dkan, please add to the dkan sites list. 

American Samoa: [https://americansamoa-data.sprep.org](url)
Cook Islands: [https://cookislands-data.sprep.org](url)
Federated States of Micronesia: [https://fsm-data.sprep.org](url)
Fiji: [https://fiji-data.sprep.org](url)
Kiribati: [https://kiribati-data.sprep.org](url)
Republic of the Marshall Islands: [https://rmi-data.sprep.org](url)
Nauru: [https://nauru-data.sprep.org](url)
New Caledonia: [https://newcaledonia-data.sprep.org](url)
Niue: [https://niue-data.sprep.org](url)
Palau: [https://palau-data.sprep.org](url)
Papua New Guinea: [https://png-data.sprep.org](url)
Samoa: [https://samoa-data.sprep.org](url)
Solomon Islands: [https://solomonislands-data.sprep.org](url)
Tonga: [https://tonga-data.sprep.org](url)
Tuvalu: [https://tuvalu-data.sprep.org](url)
Vanuatu: [https://vanuatu-data.sprep.org](url)

Pacific Environment Data Portal: [https://pacific-data.sprep.org](url)

**Comment by stefaniefgray** [comment]
See https://github.com/GetDKAN/dkan/pull/2869

**Comment by tavitas** [comment]
Thanks guys! Really happy to see them listed

**Comment by stefaniefgray** [comment]
Page just needs a final review of my edits and then it's good to go
