### ISSUE TITLE
Problem with the editor in place

### ISSUE THREAD

**Issue by JuanAlejo32** [GetDKAN/dkan#2866]
Greetings, first of all first I apologize for my bad English.
Now I have a problem with the section "the editor in place", which only allows me to add this content, but I saw that in the documentation of the page, it allows more options, how can I solve this ?.

I wait for a quick response and thank you for your attention.

![image](https://user-images.githubusercontent.com/22005128/56750206-ddeb4380-6748-11e9-8bbf-355414e3c078.png)

**Comment by janette** [comment]
@JuanAlejo32 you will need the 'administrator' role, then instead of using the IPE 'customize this page' link at the bottom of the node, you will instead click the 'Customize Display' link next to the 'Edit' tab on top. Then click the 'content' link.

**Comment by JuanAlejo32** [comment]
thanks for answering me!, now first verify that I am an administrator user.
![image](https://user-images.githubusercontent.com/22005128/56812842-531a4f80-6801-11e9-8717-883d68a8ee85.png)

Then I tried to search "" customize Display ", but unfortunately I did not find it.
![image](https://user-images.githubusercontent.com/22005128/56813803-61696b00-6803-11e9-95af-472a886c32ac.png)

**Comment by janette** [comment]
@JuanAlejo32 sorry if you are talking about the front page you are right the local tasks are not displayed, you will need to:
1. go to `admin/content`
2. find your front page from the list and click `edit`
3. Click the 'Customize display' button
4. Click 'content' under Operations
5. Click the _gear_ at the top left of a defined region
6. Click 'add content'

![customize_front](https://user-images.githubusercontent.com/314172/56814286-77c3f680-6804-11e9-8e17-86a4a76cdef3.png)

**Comment by JuanAlejo32** [comment]
thanks for the help, it worked!
