### ISSUE TITLE
drush command to delete orphaned nodes

### ISSUE THREAD

**Issue by erogray** [GetDKAN/dkan#2882]
As a DKAN developer, I'd like a drush command to delete orphaned nodes, so that in the event of an unexpected harvest event I can more easily do cleanup activities.

**Comment by erogray** [comment]
@dharizza is this done already, or is there work pending?

**Comment by janette** [comment]
@beeyayjay hold on this one, we are removing workbench from HHS which would make this no longer needed.

**Comment by erogray** [comment]
No longer necessary since this is an uncommon issue with a Views workaround
