### ISSUE TITLE
New DKAN Install - Front Page Blank and No In-Place-Editor

### ISSUE THREAD

**Issue by dyaw-Drexel** [GetDKAN/dkan#2883]
Hi,

I am working with a new install of DKAN. I am running this on Ubuntu 18.04 as a VM using VirtualBox. 

I am running into an issue here where the front page is blank and I don't see the in-place-editor. Was there supposed to be a default front page? And can anyone help me with this? Thanks! 

![image](https://user-images.githubusercontent.com/50875663/58101397-87d5b880-7bad-11e9-8687-aa594549f87f.png)

Thanks,

Dan Yaw

**Comment by dyaw-Drexel** [comment]
Also if I try to manually make a page, I get these errors on the top:


    Notice: Undefined variable: path in include() (line 14 of /home/uhc-server-test/dkan/webroot/profiles/dkan/themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php).
    Notice: Undefined variable: bg_color in include() (line 14 of /home/uhc-server-test/dkan/webroot/profiles/dkan/themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php).
    Notice: Undefined variable: tint in include() (line 15 of /home/uhc-server-test/dkan/webroot/profiles/dkan/themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php).
    Notice: Undefined variable: padding in include() (line 17 of /home/uhc-server-test/dkan/webroot/profiles/dkan/themes/nuboot_radix/panels/layouts/dkan_front/panels-dkan-front.tpl.php).

**Comment by janette** [comment]
@dyaw-Drexel did you create a custom theme? Those variables are set up in Nuboot Radix for the DKAN_front panel layout option.

If you have not enabled the default content feature you could create a page and assign it in the settings `admin/config/system/site-information`

![front-page](https://user-images.githubusercontent.com/314172/58134528-bfb02080-7bec-11e9-9fa5-6a25c366379e.png)

**Comment by dyaw-Drexel** [comment]
That works! Thanks!
