### ISSUE TITLE
Add test for datastore lock changes

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2884]
see #2876

lock is stored in a global lock variable, requesting a new lock will extend the expiration of the lock and return true. So to test a failed lock we need it to be called from a separate process.

to test we need a server to request a url
https://api.drupal.org/api/drupal/modules%21simpletest%21tests%21lock.test/function/LockFunctionalTest%3A%3AtestLockAcquire/7.x

hypothesis: use a drush command to acquire a lock, run a second drush command to also acquire the lock

**Comment by erogray** [comment]
@janette and @fmizzell to cowork
