### ISSUE TITLE
If Harvest source is invalid, Harvest should warn with error message instead of getting stuck in loop.

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2886]
As a user creating a Harvest Source in DKAN, I have accidentally pasted a regular URL, and not a harvest source URI, into the 'Source URI' box.

![Screenshot 2019-05-29 16 32 51](https://user-images.githubusercontent.com/9059428/58595910-6f117680-822f-11e9-9a7d-d45ae0cbd806.png)

In turn, Harvest gets stuck in an infinite loop, as displayed in the video below. An error message guiding the user back to the original Create Harvest Source page would be more helpful.

https://slack-files.com/T0297RSQF-FJS9C8C1Z-8062517bca

**To replicate:**
- Create a new DKAN Harvest source
- Use http://www.google.com/notarealurl as the Source URI
- Click "Save"

**Acceptance criteria:** After inputting an invalid Harvest Source URI, the user should encounter an error message page with a back button.

Error message should say something along the lines of “This isn’t a valid Harvest source link; please try again with a source URI in data.JSON, XML or RDF format.” (Or whichever formats are valid.)

**Comment by erogray** [comment]
It'd be ideal to catch the error; but since we're moving toward DKAN2 harvest instead, we should focus on it instead.
