### ISSUE TITLE
Implement Elysia cron

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2896]
https://www.drupal.org/project/elysia_cron

Should Elysia cron replace Jenkins? Would add site-specific settings, which could make updating more complex; but does make the site itself more portable.

Could also add but disable by default so that it could be enabled on a per-site basis.

**Comment by erogray** [comment]
No D8 version yet, https://www.drupal.org/project/contrib_tracker/issues/2615318
