### ISSUE TITLE
Problems to migrate the dataset from CKAN to DKAN 

### ISSUE THREAD

**Issue by vmendieta** [GetDKAN/dkan#2902]
Is there an extra module that allows me to migrate all the dataset I have in a CKAN to my new DKAN portal? what format should data.json have?
Try using the DKAN Harvest by passing the data.json from my ckan but it does not bring anything.
It will be a format problem? The ckan is 2.2 and the URL to the data.json is https://www.datos.gov.py/data.json

**Comment by rhabbachi** [comment]
Comparing the output of data.json from http://demo.getdkan.com/data.json to the one from https://www.datos.gov.py/data.json, seems like you have the `dataset` array but missing the metadata for the json itself.

Try to change from 
```
[
...(datasets)...
]
```
to
```
{
"@context": "https://project-open-dat….1/schema/catalog.jsonld"
"@id": "http://demo.getdkan.com/data.json"
"@type": "dcat:Catalog"
"conformsTo": "https://project-open-data.cio.gov/v1.1/schema"
"describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json"
"datasets":
[
...(datasets)...
]
}
```
And see if it works.

![image](https://user-images.githubusercontent.com/1914306/59499921-52607a00-8e90-11e9-929a-0069c7f7ba17.png)

**Comment by erogray** [comment]
Hi @vmendieta, we're closing this since it seems answered. Please re-open the issue if you're still having trouble.
