### ISSUE TITLE
Create documentation on Feedback

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#2904]
The Feedback module is now included within out of the box DKAN, but there is nothing about it mentioned on https://dkan.readthedocs.io/.

### Acceptance criteria:
"Feedback" gets a page of its own under Components (https://dkan.readthedocs.io/en/latest/components/)

**Comment by erogray** [comment]
Timeboxing to two hours

**Comment by stefaniefgray** [comment]
Created https://github.com/GetDKAN/dkan/pull/2943/ - need developer to review and push to live on Read the Docs

May have formatting issues in code block portion since Github doesn't provide accurate previews of RST formatting

**Comment by stefaniefgray** [comment]
Also, as per the 2019 DKAN Docs audit showing how our ReadTheDocs directory is organized: https://docs.google.com/spreadsheets/d/1tc7mMYhIqMvkHUPmV7XzEFBndu4dsHZmkwC8-guPfiE/edit#gid=1541715932 --

DKAN Feedback is _not_ an out-of-the-box component of DKAN, and isn't an option on the 7.x.1.x modules page. Therefore, it belongs under Development instead of Components.
