### ISSUE TITLE
Data preview is not showing on page

### ISSUE THREAD

**Issue by Kerberos7** [GetDKAN/dkan#2910]
![image](https://user-images.githubusercontent.com/9345896/60188564-dcd2b180-9872-11e9-9545-1dfd658f6148.png)

For some reason, the data preview panel is not showing on page since last week. Before it worked OK for csv and xls.

**Comment by janette** [comment]
@Kerberos7 are there any errors in the console or logs that contain clues? was the file updated? was it added to the datastore? code changes?

**Comment by erogray** [comment]
@kerberos7 feel free to reopen this ticket and let us know if you have additional questions or clues.
