### ISSUE TITLE
Add Tirana Open Data portal to DKAN sites list

### ISSUE THREAD

**Issue by lorelajano** [GetDKAN/dkan#2916]
Hello, I am the person responsible for developing and managing the official Open Data portal for the city of Tirana. Now it is public over the internet in the url : https://opendata.tirana.al/
This portal is built with DKAN platform. We would like to add it in the list of DKAN sites published in the official website of DKAN  https://docs.getdkan.com/en/latest/introduction/dkan-sites.html
If there is any criteria for this process we would like to be informed about it.
Thank you!

**Comment by lorelajano** [comment]
Please can I have an answer?

**Comment by dharizza** [comment]
Hello,

Sorry for the late answer, we added the site to the list but the doc wasn't published. We just published it and now you can see the site here https://docs.getdkan.com/en/latest/introduction/dkan-sites.html

Thank you!

**Comment by lorelajano** [comment]
Thank you very much !
 I appreciate your help.
