### ISSUE TITLE
Migrating from MySQL to Postgres on DKAN?

### ISSUE THREAD

**Issue by dyaw-Drexel** [GetDKAN/dkan#2917]
I have been able to move the database successfully, but after updating settings.php, I run into various issues, including breaking admin sections. Other then moving the database and updating settings.php, is there anything else I should be doing?

**Comment by erogray** [comment]
Hi @dyaw-Drexel, we don't currently recommend using Postgres with DKAN, but there may be good information about how to best do this sort of migration within the larger Drupal community.

**Comment by dyaw-Drexel** [comment]
Well since the site is still in development, I went ahead and started fresh using Postgres from the start. Only issue I encountered was it breaks the Panelizer, but I fixed it by patching with this https://www.drupal.org/project/panelizer/issues/2774909 and flushing all caches

**Comment by janette** [comment]
Nice! thanks for sharing @dyaw-Drexel
