### ISSUE TITLE
Set up CI/CD pipeline for DKAN2 on Google Cloud

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2926]
Should be a template that will work for future client sites

**Comment by erogray** [comment]
@kimwdavidson does this ticket need additional notes?

**Comment by kimwdavidson** [comment]
@aabond: what do you think we should do with this ticket?

**Comment by aabond** [comment]
Hello @kimwdavidson,

I spoke with Karen yesterday about this.  She mentioned she would chat with you and Tejas to see if I could have some more time to finish this before getting back on Globalnet.  Not sure if a consensuses has been reached.  Perhaps @janette , @dafeder , and @fmizzell could continue fleshing out the jenkins-x pipeline (i.e. add the integration tests, enable the db restores, etc).  That would at least get us to the point where we have preview environments and perhaps the staging environment in place to enable further DKAN2 development.  This might buy us some time where I can come back at later juncture and continue work on the production environment and all that's involved with that.

**Comment by erogray** [comment]
Closing in favor of https://github.com/NuCivic/dkan_management/issues/303
