### ISSUE TITLE
Functionality to display on the main page which is the most consulted dataset

### ISSUE THREAD

**Issue by vmendieta** [GetDKAN/dkan#2932]
There is a functionality to display on the main page, which is the most consulted dataset? like a dataset ranking?
I would like to ask a question, if it is not the right place for her, could you tell me where? Thank you

**Comment by managume** [comment]
First of all you need to activate Statistics module. Then you can create a view block using:

### Fields (i.e)
Content: Title
Content: statistics: Total views.
### Filter Criteria
Content: Published (Yes)
Content: Type (=Dataset)
### Sort Criteria
Content statistics: Total views (desc).

To finish go to **Pager** section and in _User pager_ choose how many Datasets you want to show and if you want a _more link_.

Once created go to edit the Welcome page in Content. Click in Customize display, select the content operation and add the view block in any region you want.

I hope that helps you :)

**Comment by vmendieta** [comment]
Thank you very much for your help!!
I will test and comment on the results XD

**Comment by vmendieta** [comment]
I could generate a block with a table, but would it be feasible to generate some graph instead of a table?
![bloque](https://user-images.githubusercontent.com/8810083/62323905-57947b00-b476-11e9-857c-7995409cb841.jpg)

**Comment by managume** [comment]
I've never used chart format in a view display but it can be interesting. Check this out. https://www.drupal.org/docs/8/modules/charts/create-charts-using-views-0/steps-to-create-charts-using-the-views-ui

**Comment by vmendieta** [comment]
it not worked for me .. someone who can help me please :(

**Comment by erogray** [comment]
Thanks @managume! That's a neat trick. We'll take a look and see if we have any other ideas.

**Comment by stefaniefgray** [comment]
@managume Thank you so much for your contributions to this thread!

@vmendieta Your idea for creating a chart from a View is fascinating! Although I haven't been able to figure out how to get it to work, I'm going to pass this on to one of my DKAN colleagues and see if they can think of a solution. Will keep you posted if I hear anything!

**Comment by vmendieta** [comment]
Thank you very much, I will be attentive to any feddback

**Comment by stefaniefgray** [comment]
Hi @vmendieta 

Sincere apologies for such a late response! We've looked into this issue, and unfortunately, haven't been able to find a way to make charts from a View.

Wishing you the best of luck in researching a solution - and if you find one, please share it with us. :)

**Comment by erogray** [comment]
Closing since we don't have a current solution; please feel free to reopen if progress is made
