### ISSUE TITLE
Internal data  tab  not does not appear

### ISSUE THREAD

**Issue by vmendieta** [GetDKAN/dkan#2939]
Internal data  tab  not does not appear, the internal data tab is no longer
![imagen](https://user-images.githubusercontent.com/8810083/62866628-4271e480-bcdf-11e9-8de7-5d5864cc04cb.png)

Steps to Reproduce
1.Go to Administration->Structure->Entity type->Vizualitation->Chart-> Add Chart
## Acceptance Criteria
The internal data tab should be in the form like the image:
![imagen](https://user-images.githubusercontent.com/8810083/62866916-0c813000-bce0-11e9-97b7-24bce03b925e.png)

**Comment by janette** [comment]
@vmendieta we can not reproduce this on a standard DKAN installation, are there customizations to your site we should be aware of?

**Comment by vmendieta** [comment]
It is a standard insatalcion and I have translated into Spanish, maybe the translation has generated a problem.

**Comment by vmendieta** [comment]
I have solved it.
Within **Manage fields** I have added one more field as in the figure
1
![imagen](https://user-images.githubusercontent.com/8810083/62873381-4c9adf80-bced-11e9-9057-04bdd5bd3792.png)
2
![imagen](https://user-images.githubusercontent.com/8810083/62873264-15c4c980-bced-11e9-869b-d390de8367e6.png)
