### ISSUE TITLE
Is there a related content panel?

### ISSUE THREAD

**Issue by vmendieta** [GetDKAN/dkan#2941]
Same as in CKAN, where the content related of one dataset i can see whit the other 
Below is an example of what would be in CKAN
![imagen](https://user-images.githubusercontent.com/8810083/62896264-ab2c8180-bd1e-11e9-9123-7c4593a33104.png)

**Comment by kimwdavidson** [comment]
There isn't at the moment, but it's a great suggestion! If you submit a pull request, we'd be happy to review it, and in the meantime, we'll add it to our feature request list.

**Comment by managume** [comment]
@vmendieta maybe solves your need by creating a new content type (e.g. Application) with an _UUID Reference_ field with _Node_ as **Target type** and _Dataset_ checked as **Target bundle**. Now you can create an Application related to a Dataset. 

Additionally you can create a page view to show all related Application of a specific Dataset using Filter criteria fields.

**Comment by vmendieta** [comment]
thank you so much for help me

**Comment by vmendieta** [comment]
The solution that I have found is simple, I have generated a view that collects a type of "Applications" content that I have created more or less as I mentioned it @managume , although it could in the future have by default this content in DKAN, which is generated in a  automatic way when putting the dataset an information of related applications.
My solution: 
![imagen](https://user-images.githubusercontent.com/8810083/63945091-c5659f80-ca40-11e9-92a7-ff07bf9652ba.png)

**Comment by erogray** [comment]
Closing since this hasn't been active lately, but please feel free to submit pull requests; this could also be a good feature to add to DKAN 2 in the future.
