### ISSUE TITLE
Google Analytics problem

### ISSUE THREAD

**Issue by vmendieta** [GetDKAN/dkan#2942]
I have followed the steps to install the Google Analytics module and it does not appear.
Step :
1- download the compressed file from the module from https://www.drupal.org/project/google_analytics
2- I unzipped it
3- I copied it to sites / all / modules /
4- I went to the DKAN administrator but it's not there

Acceptance Criteria:
Expected result-> see the Google Analytics module in the list of new modules  and enable it

**Comment by managume** [comment]
https://ftp.drupal.org/files/projects/google_analytics-7.x-2.6.tar.gz

I have tried it with a 7.x.1.16.14 instance and it appears in modules list after installation. Please, try this:

1. Go to https://www.drupal.org/project/google_analytics

1. a

**Comment by vmendieta** [comment]
My main problem is that there is no url field, or option to install
![imagen](https://user-images.githubusercontent.com/8810083/63029020-d24d9500-be7d-11e9-9e7a-c04d1c934b55.png)

**Comment by vmendieta** [comment]
you see online this opcion in Module
![imagen](https://user-images.githubusercontent.com/8810083/63029387-7afbf480-be7e-11e9-860d-893e367912b8.png)

but the previous version of Dkan in another local instalation i see more opcions, and the option Install

**Comment by janette** [comment]
@vmendieta you need to enable the update module to get the "install" UI functionality

**Comment by vmendieta** [comment]
@janette I'm new to this, how should I do it please

**Comment by managume** [comment]
@vmendieta search in modules list 'Update manager' and enable it

**Comment by vmendieta** [comment]
thank you so much for help me

**Comment by vmendieta** [comment]
I have already been able to see the installation button but I cannot use FTP, I have tried as I mentioned above and without being able to see Googe Analytics, however I have been able to install, for example, the TagClouds module, simply by copying the folder and then going to Modules and to me the module appeared

**Comment by vmendieta** [comment]
I solved it, the user who had permission on the folder had been changed

**Comment by vmendieta** [comment]
I solved it, the user who had permission on the folder had been changed
