### ISSUE TITLE
Create a rough plan for DKAN/CKAN interoperability

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#2946]
- [ ] Where are potential points for sharing tools between the CKAN and DKAN ecosystems
- [ ] How much can we avoid duplicating efforts?
- [ ] List of what needs to be built for DKAN2 and whether or not it can be shared
- [ ] What is the interoperability strategy? Data packages? Something else?
- [ ] What processes do we need to get the two systems working together

Notes
- DMS roadmap: https://docs.google.com/spreadsheets/d/1KZxdDC5nlifrgzMwD-b1pRZXvYJXLwl7_QVDx570xxk/edit#gid=0

**Comment by erogray** [comment]
@kimwdavidson  is this still in our roadmap?

**Comment by erogray** [comment]
Currently no rough plan is planned, but upcoming work will be likely to bring CKAN and DKAN closer together -- closing this ticket in the meantime
