### ISSUE TITLE
Add Solucionex to business directory

### ISSUE THREAD

**Issue by managume** [GetDKAN/dkan#2950]
Hello! In our company we are interesed in appearing in the [DKAN business directory](https://docs.getdkan.com/en/latest/community/help.html#add-your-company) to offer professional and collaborative services.

**Company:** Solucionex
**Logo:** https://www.solucionex.com/themes/custom/solucionex/img/logos/logo_solucionex.png
**Link:** https://www.solucionex.com/dkan
**Description:**
Solucionex is a Spanish company specialized in the development of advanced open source solutions with Drupal. We use technologies as CKAN and DKAN to create robust user friendly open data portals focused on corporations and public administrations.

**Comment by dharizza** [comment]
Hello,

Your company appears now in our directory here https://docs.getdkan.com/en/latest/community/help.html#add-your-company

Thank you.
