### ISSUE TITLE
HarvestSource machine_name not found  DKAN ERROR

### ISSUE THREAD

**Issue by rajatmtr30** [GetDKAN/dkan#2966]
Add a brief description about the purpose of the issue.

## Steps to Reproduce
Add steps for reproducing the issue including any file(s) needed to reproduce.

1. when i add a source in harvest source 404 not found popup comes.
2. In logs" HarvestSource machine_name not found." messgae comes and i unable to add harvest source ibn dkan locally
![Screenshot from 2019-09-24 15-08-02](https://user-images.githubusercontent.com/52307959/65500603-27e57a80-dedd-11e9-8f68-6978f2d1c17d.png)

3.

## Acceptance Criteria
Add the goals and desired results that this issue should accomplish when complete.

- [ ]
- [ ]
- [ ]

## Subtasks
Add a list of things that need to be done to accomplish the Acceptance Criteria.

- [ ] Is there a test for the issue
- [ ] Is there documentation for the issue
- [ ] Are follow up tickets needed
![Screenshot from 2019-09-24 15-10-28](https://user-images.githubusercontent.com/52307959/65500788-7561e780-dedd-11e9-82e2-6beff5c01489.png)

**Comment by erogray** [comment]
Hi @rajatmtr30 — can you tell us a bit more about this? What source are you trying to harvest from, and what's the machine_name that is showing up in the harvest? (Also, what version of DKAN is this?)

**Comment by rajatmtr30** [comment]
Hi @erogray   --- i m using drupal version : 7.67 and for dkan by this url i clone $ git clone --branch 7.x-1.x https://github.com/GetDKAN/dkan.git .
I m trying to add the url in harvest source:
http://data-atgis.opendata.arcgis.com/data.json

**Comment by erogray** [comment]
Hi @rajatmtr30 — I suspect that this is an issue with the machine_name for the harvest. I've been able to harvest from http://data-atgis.opendata.arcgis.com/data.json without any trouble, but we've seen some issues with harvests in the past if the harvest name itself is extra long or has unusual characters. The machine_name gets created from the title that you give a harvest. 

<img width="348" alt="Screen Shot 2019-09-26 at 10 58 25 AM" src="https://user-images.githubusercontent.com/21176376/65713011-13c08b00-e04d-11e9-9ef0-a0c95b649010.png">

I'm seeing for instance, that if I title a new harvest "test harvest" and then give it the source `http://data-atgis.opendata.arcgis.com/data.json` it works fine. But if I give it the title "http://data-atgis.opendata.arcgis.com/data.json" it will fail to cache no matter what the source is. You might try creating a new harvest with a short, simple title and see if that fixes the issue.

**Comment by janette** [comment]
FYI when creating a harvest you are able to edit the machine name, it just defaults to use the first 31 characters of the title otherwise

![edit_harvest_machine_name](https://user-images.githubusercontent.com/314172/65721061-ed134c00-e06e-11e9-85b4-5433dad837aa.png)

**Comment by rajatmtr30** [comment]
I m getting too confused in creating harvest source . machine name is not coming in below title. And after creating harvest source this page is coming and after go back i got the name in list harvest
![Screenshot from 2019-09-27 09-58-32]

(https://user-images.githubusercontent.com/52307959/65742404-9c9efb80-e10d-11e9-8e93-d3d5899fd3db.png)
![Screenshot from 2019-09-27 09-57-29](https://user-images.githubusercontent.com/52307959/65742405-9c9efb80-e10d-11e9-9178-08615360f1cd.png)

**Comment by rajatmtr30** [comment]
Hi @erogray @janette  can you please share the steps to install locally dkan with all functionalities in fresh ubuntu 18.04.

**Comment by janette** [comment]
@rajatmtr30 you won't see the machine name below the title until you start typing.

Here are installation instructions: https://dkan.readthedocs.io/en/latest/installation/basic.html

**Comment by rajatmtr30** [comment]
thank you it resolved now
