### ISSUE TITLE
the group no longer appears

### ISSUE THREAD

**Issue by vmendieta** [GetDKAN/dkan#2970]
Some dataset show the group and others do not, I am using a Spanish translation (both belong to the same group but only in one sample)
![imagen](https://user-images.githubusercontent.com/8810083/66655218-122cc080-ec12-11e9-9731-d63a743fb1f9.png)
![imagen](https://user-images.githubusercontent.com/8810083/66655251-1e188280-ec12-11e9-8efc-d9f845c6af94.png)
![imagen](https://user-images.githubusercontent.com/8810083/66655267-2375cd00-ec12-11e9-9d2e-c05112c3ae9f.png)

**Comment by stefaniefgray** [comment]
Closing in favor of https://github.com/GetDKAN/dkan/issues/2948
