### ISSUE TITLE
Get a list of topics through the rest api

### ISSUE THREAD

**Issue by sediqamousavi** [GetDKAN/dkan#2974]
I want to get a list of topics through the rest API. By what URL can I get this listing?

**Comment by janette** [comment]
Not finding a way to do this on dkan for drupal 7, these are what I've tried:
```
/api/dataset/taxonomy_term.json?parameters[vid]=2
/api/dataset/node.json?fields=field_topic
/api/dataset/node.json?fields=field_pod_theme
```

on dkan for drupal 8 it is
`/api/v1/theme`
