### ISSUE TITLE
Upload errors

### ISSUE THREAD

**Issue by smielza** [GetDKAN/dkan#2979]
Looks like we are receiving two separate upload errors. The first was one of our users attempting to upload an .xlsx file, and the second screenshot is myself trying to upload a .png and then a .doc. I inherited this site, did not set it up myself.

![image](https://user-images.githubusercontent.com/57536238/68677094-6e447680-0529-11ea-8b34-3cb8cf69498d.png)

![image](https://user-images.githubusercontent.com/57536238/68677107-769cb180-0529-11ea-9933-bdf8004c8baf.png)

## Steps to Reproduce
Add steps for reproducing the issue including any file(s) needed to reproduce.

1. Simply try uploading any file, any format.

## Subtasks
Add a list of things that need to be done to accomplish the Acceptance Criteria.

- File system settings should all be correct under site config
- Might be AFS permissions fighting Unix permissions?
- Is this because of outdated patching/updates?

![image](https://user-images.githubusercontent.com/57536238/68677358-fb87cb00-0529-11ea-9bdc-ce4b15e5adce.png)

**Comment by erogray** [comment]
Hi @smielza - what version of DKAN are you using? if older than 7x.1.17 then you might want to update it to take advantage of more current patches.

**Comment by smielza** [comment]
Thanks @erogray I think you're right - I know it was set up in March 2019 - what's the best way to check my version?

**Comment by janette** [comment]
@smielza you can check the changelog file or view the install profile on `admin/reports/status` to see what version of dkan you are running. The /sites/default/files directory should be 775.

**Comment by smielza** [comment]
@janette & @erogray  Got it. Can you point me toward the files I need? I'll need to manually update in my test site and the patching steps don't seem to be working. Still getting errors on the file.module

**Comment by smielza** [comment]
Writing back to close the issue: discovered it's unrelated to patching. We have a bug where we must let Drupal create the folder(s) in which the uploads are stored.  Went in to each content type individually and managed the field to assign a non-existant subfolder beneath /files. Seeing it missing, Drupal created the subfolder, and uploads now work.
This is in conjunction with AFS and unix permissions being correct.  Not sure why this is a thing, but all is working now! Thanks for the earlier advice @janette & @erogray
