### ISSUE TITLE
Remove Administration Views module

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#2981]
https://www.drupal.org/sa-contrib-2019-076

The module is no longer supported. Remove it from the code base.

## Acceptance Criteria
- [ ] admin/content = dkan_administration_nodes
- [ ] admin/files = dkan_administration_files
- [ ] remove dependencies[] = admin_views
- [ ] dkan_feedback and dkan_workflow work as expected

**Comment by nandt** [comment]
hello Janet ! Do you have any plan for the module?

**Comment by janette** [comment]
Hi @nandt,
the plan is to remove admin_views from the code base.
