### ISSUE TITLE
Column ordering triggers fatal error if data imported to DataStore

### ISSUE THREAD

**Issue by jjalcolea** [GetDKAN/dkan#2994]
If you try to order a datastore-imported CSV resource by any colum in the preview page, it fails and renders Recline unusable.  
Please note that this error doesn't happen if the data is not imported to the DataStore.

## Steps to Reproduce
1. Upload a CSV file
2. Import to DataStore
3. Preview in table mode
4. Click on any column title to order by that column

Additionally, we've found cases of this problem "in the wild", for example check [this resource](https://data.nal.usda.gov/dataset/data-eleven-years-mountain-weather-snow-soil-moisture-and-stream-flow-data-rain-snow-transition-zone-johnston-draw-catchment-reynolds-creek-experimental-watershed-and-critical-zone-observatory-usa-v11/resource/62881af6-3023-4146-8bbb-c8d22de11f9f) in the USDA open data portal.

## Acceptance Criteria
- Data should be ordered by the clicked column

**Comment by jjalcolea** [comment]
Additional information: all our CSV files are UTF-8 and all column names are a mix of lower case letters and occasionally the "_" character in between.

**Comment by janette** [comment]
thanks @jjalcolea for reporting this

`Uncaught TypeError: Cannot read property 'total' of undefined`
 
https://github.com/GetDKAN/recline/blob/6db1ab729d14f40150f6571457331ff3bde8752d/backend.ckan_get.js#L115
```
my.query = function(queryObj, dataset) {
    var wrapper;
    if (dataset.endpoint) {
      wrapper = my.DataStore(dataset.endpoint);
    } else {
      var out = my._parseCkanResourceUrl(dataset.url);
      dataset.id = out.resource_id;
      wrapper = my.DataStore(out.endpoint);
    }
    var actualQuery = my._normalizeQuery(queryObj, dataset);
    var dfd = new Deferred();
    var jqxhr = wrapper.search(actualQuery);
    jqxhr.done(function(results) {
      var out = {
        total: results.result.total,
        hits: results.result.records
      };
      dfd.resolve(out);
    });
    return dfd.promise();
  };
```

**Comment by jjalcolea** [comment]
Hi @janette , just curious if you plan to address this bug anytime soon; it's quite visible and really detracts from the DKAN user experience...

Thanks in advance,

Juanje.

**Comment by erogray** [comment]
@jjalcolea the CivicActions team has been putting most of our efforts toward building out DKAN2, which doesn't use Recline (and thus doesn't have this particular problem). We'd be happy to look at a pull request though!

**Comment by managume** [comment]
Bug is in the **objToQuery** function that builds and returns the query string. Currently it is building the **sort** parameter like this:

`&sort=cod_universidad asc`

And the right way should be:

`&sort[cod_universidad]=asc`

So a possible solution is to add the following condition in [line 136](https://github.com/GetDKAN/recline/blob/6db1ab729d14f40150f6571457331ff3bde8752d/backend.ckan_get.js#L136)

```javascript
if(p == 'sort'){
    str += '&' + p + '[' + obj[p].split(' ')[0] + ']' + '=' + obj[p].split(' ')[1] ;
}else{
    str += '&' + p + '=' + obj[p] ;
 }
```

**Comment by janette** [comment]
Thank you @managume your fix is in the [latest release](https://github.com/GetDKAN/dkan/releases/tag/7.x-1.18.1)
