### ISSUE TITLE
Gold price demo dataset should use full range in the temporal_coverage field

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#30]
> Posted by marians on October 1, 2013 at 4:15am
> In order to illustrate how the API returns values for the temporal_coverage field, the Gold Price sample dataset (http://demo.getdkan.com/node/7/json) should make use of that field.

From https://drupal.org/node/2074381

**Comment by dafeder** [comment]
Revisiting - we sort of do this now but we don't have an end time. We should put "2008" as the end time.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it. If we get feedback about this feature we may decide to make it a higher priority.
