### ISSUE TITLE
File encoding UTF-8 Issue after Importing to Data API

### ISSUE THREAD

**Issue by AhmadMiladKakar** [GetDKAN/dkan#3000]
When I am going to upload a resource that has CSV-UTF-8 format to Dataset,
it is previewing and downloading correctly but when I am going to manage datastore and importing to generate Data API, my resource file Local language changes to symbols during downloading the file from Resouces.

## Steps to Reproduce

1. Upload Resource
2. Preview Resource
3. Download Resource (Work properly)
3. Manage Datastore
4. Import 
5. Download Resource (Not Work properly changing to symbols local languages)

## Acceptance Criteria
Add the goals and desired results that this issue should accomplish when complete.

- [ After upload resource and manage datastore Data should remain same format ]
- [ Data should preview, Download in UTF-8 format ]
- [ Data API should generate in UTF-8 format in JSON]

**Comment by janette** [comment]
@AhmadMiladKakar can you try this revision https://github.com/GetDKAN/dkan/pull/3025, or wait for fix, it will be in the 1.18.3 release
