### ISSUE TITLE
DCAT Version 2 

### ISSUE THREAD

**Issue by jensr** [GetDKAN/dkan#3014]
Hi 
With the recent announcement that DCAT version 2 is now published (https://www.w3.org/blog/2020/02/data-catalog-vocabulary-dcat-version-2-published-today/ ) I was just wondering if there is a roadmap for DCAT 2 implementation for DKAN? 

From my (limited) understanding, the new version relaxes certain constraints, while adding new classes and properties.

**Comment by erogray** [comment]
Hi @jensr -- we're looking into this for the Drupal 8 version of DKAN, DKAN2 will eventually be adjustable/customizable for different schemas. No current plans to do this for DKAN 1 though.

**Comment by jensr** [comment]
Thanks Ero - that makes sense - given the developments towards Drupal 8, i completely understand this.
