### ISSUE TITLE
Pagination (Data Lost and Repeat)

### ISSUE THREAD

**Issue by sediqamousavi** [GetDKAN/dkan#3020]
When there are more datasets in the topic, data needs to paginate in several pages, after clicking on the next page, some data of the first page are repeating on the next page and some of them become lost.
I think this problem is related to adding the query string parameter to URL
 
![Capture](https://user-images.githubusercontent.com/43989585/74309810-46afb500-4d89-11ea-8153-dec561bcb4b0.PNG)

**Comment by janette** [comment]
@sediqamousavi I am unable to reproduce the issue, do you have custom code that might be altering the results? Otherwise try re-indexing your datasets here `admin/config/search/search_api/index/datasets`

**Comment by sediqamousavi** [comment]
@janette I don't have custom code and I also re-indexed the datasets but it didn't solve the problem
![Capture](https://user-images.githubusercontent.com/43989585/74368020-7514ab00-4df0-11ea-849a-52e51f0920da.JPG)
## Steps to Reproduce:
1- please go to this link [http://data.gov.af:8090/search/field_topic/health-4/type/dataset?sort_by=changed&q=search/field_topic/health-4/type/dataset&page=0%2C1](url)
2- click on the first and second page
3- then back to the first page
some data on the first page are repeating on the next page and some of them become lost.

**Comment by erogray** [comment]
Hi @sediqamousavi this looks like it must be a search indexing issue; we see that the "Users of Family Planning" shows up twice in search _only_ if the dataset filter is off (this should normally mean that you'd see datasets and also resources). Can you retry reindexing?

Are you seeing it happen with any other specific datasets?

**Comment by sediqamousavi** [comment]
@erogray Hi ero, 
I have tried reindexing and I saw this problem with other datasets

**Comment by erogray** [comment]
Hi @sediqamousavi, we can't see the site and haven't been able to replicate the problem; please feel free to reopen this issue if you'd like to discuss further.

**Comment by sediqamousavi** [comment]
Hi @erogray our sort criteria (sort by changed) can't give our entries a unique position and then bug occurs
In our view interface, under "Sort Criteria" I added a filter called : "Indexed Node: Entity ID" and placed it third under the "Indexed Node: Date created (Exposed)" filter.
