### ISSUE TITLE
datastore import: csv-file with numeric column name

### ISSUE THREAD

**Issue by eGovCologne** [GetDKAN/dkan#3026]
Importing a csv-file with numeric column name in the datastore without changing the entire column name does not work.
According to the mysql indentifier specification the import should work, if the column name is quoted with backticks `.

## Steps to Reproduce
Upload a csv-file with a numeric column name in the datastore.
If the column is called 4, the column looks like __num_4 after datastore import. I tried to quote the numeric column name with ", ' and ` but nothing seems to work.

**Comment by erogray** [comment]
Thanks eGovCologne! This seems like an interesting puzzle; our folks are currently focused on DKAN 2, but if you'd like to submit a pull request for this issue we'll be happy to review it.
