### ISSUE TITLE
DKAN Harvest Failures

### ISSUE THREAD

**Issue by seshelby** [GetDKAN/dkan#3028]
First, I apologize if this is not the place to post this. I have been unable to find a general forum to request help regarding DKAN. We have been unable to get harvest to work as expected. During the harvest new datasets are always created but generally only one or two resources are added. The failure is always with the following error: filesize(): stat failed for http://datahub-gocolumbiamo.opendata.arcgis.com/datasets/c201e52524094d9d939db0ed78ac1803_0.kml?outSR={"latestWkid":102697,"wkid":102697} File /var/www/dkan/includes/file.inc, line 617

To reproduce this:
1. Go to Dkan Harvest Dashboard
2. Click add source 
3. Enter a title and source url (https://datahub-gocolumbiamo.opendata.arcgis.com/data.json)
4. Click "Save"
5. Click "Harvest Now"
6. Click on the datastore name and verify that no resources were imported.

Thank you for any help that you can provide.

**Comment by janette** [comment]
@seshelby when I harvested your source, it indicated that several resources did not have a proper file path. The downloadURL and accessURL urls must actually point to a file.

```
Node 94 doesn't have a proper file path.
Node 95 doesn't have a proper file path.
Node 102 doesn't have a proper file path.
Node 103 doesn't have a proper file path.
Node 110 doesn't have a proper file path.
Node 111 doesn't have a proper file path.
Node 118 doesn't have a proper file path.
Node 119 doesn't have a proper file path.
Node 126 doesn't have a proper file path.
Node 127 doesn't have a proper file path.
```

**Comment by seshelby** [comment]
Thanks for the reply. It turns out that it was a Drupal bug.  I am really surprised that someone else has not reported this before. It appears to have been around for a very long time. I will include a link that eludes to it. The fix, while not ideal was to modify Drupal core to suppress the warning. 

https://www.drupal.org/project/drupal/issues/1335032
