### ISSUE TITLE
DKAN site backup fails because of dead behat link

### ISSUE THREAD

**Issue by markus-m-becker** [GetDKAN/dkan#3036]
Site backup using Backup/Migrate module of a fresh installation of the most recent DKAN drop from https://github.com/GetDKAN/dkan-drops-7/tree/7.x-1.18.1 (and older versions) fails with the log message:

> The backup could not be completed because The following files: 
> /XXX/profiles/dkan/test/bin/behat
> could not be read.

Actually, ./profiles/dkan/test/bin/behat is a dead link pointing to ../vendor/behat/behat/bin/behat

## Steps to Reproduce
1. Install DKAN drop from https://github.com/GetDKAN/dkan-drops-7/tree/7.x-1.18.1
2. Start entire site backup at admin/config/system/backup_migrate

## Acceptance Criteria
- Backup of a fresh DKAN installation runs smoothly without error message

## Subtasks
- Remove dead link or provide link target

**Comment by erogray** [comment]
Hi @marcus-m-becker, 
You only need to back up the /src directory to preserve custom build; you might also want the newer release, https://github.com/GetDKAN/dkan-drops-7/tree/7.x-1.18.3

**Comment by janette** [comment]
@markus-m-becker are you using [DKAN Tools]() to manage your site? If so, you can create a patch that will remove the file every time you update DKAN. Here is the history of that file https://github.com/GetDKAN/dkan/commit/dfd8b4b1e1cea43b8b199fa5d7e98a39c8121888

1. create a patch file and add it to `src/patches/dkan/`
2. create a file called `CustomCommands.php` and put it in `src/command`

```
<?php
namespace DkanTools\Custom;

use DkanTools\Util\Util;
/**
 * This is project's console commands configuration for Robo task runner.
 *
 * @see http://robo.li/
 */
class CustomCommands extends \Robo\Tasks
{
    /**
     * Sample.
     */
    public function customPatch()
    {
        $patchDir = Util::getProjectDirectory() . '/src/patches/dkan';
        $patchFiles = [];

        if (is_dir($patchDir)) {
            $patchFiles += scandir($patchDir);
        }
        foreach($patchFiles as $fileName) {
          $info = pathinfo($fileName);
          if (in_array($info['extension'], ['patch', 'diff'])) {
              $fileRelPath = '../src/patches/dkan/' . $fileName;
              $this->say($fileRelPath);
              $result = $this->taskExec('patch -p1 --no-backup-if-mismatch -r - <')
                ->arg($fileRelPath)
                ->dir('dkan')
                ->run();
              $this->say($result->getMessage());
          }
        }

    }

}
```

**Comment by markus-m-becker** [comment]
Thanks @janette for your support with the patch. I'm not using DKAN Tools (yet). By now, I delete the file manually every time I update DKAN.

**Comment by janette** [comment]
You're welcome @markus-m-becker I'm going to close this then to tidy up our board 😄
