### ISSUE TITLE
No count returned when using datastore sql endpoint

### ISSUE THREAD

**Issue by dgading** [GetDKAN/dkan#3058]
When making a request using the sql endpoint total count for a rows found is not returned with the query.

This issue appeared when working with the datastore and data-preview tables. An example query made looks like `https://dkan2.ci.civicactions.net/api/1/datastore/sql/?query=[SELECT * FROM 7f498ba2-2c03-539d-bdc3-127350a9f99c][WHERE date = "%25195%25"][LIMIT 20 OFFSET 0]` which will always return a length of 20 or below which is expected because of the LIMIT set. But the table needs to let users know that this is only 1-20 of say 120 actual results which is used in the pagination of the table and messaging. To get this a second call can be made using `https://dkan2.ci.civicactions.net/api/1/datastore/sql/?query=[SELECT%20COUNT(*)%20FROM%207f498ba2-2c03-539d-bdc3-127350a9f99c][WHERE%20date%20=%20%22%25195%25%22]` but that means every time a table filter is made, 2 api calls need to be made.

The datastore endpoint does give the initial amount which is useful for non-dynamic tables and sections.

**Comment by kimwdavidson** [comment]
Using different approach. Closing.
