### ISSUE TITLE
Simplify docker compose setup

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3069]
- Cleanup un-used container (memcached, browser, solr).
- Stop keeping cli container always up, use `run` instead of `exec` to run when needed.

**Comment by edmargomes** [comment]
@dafeder how do you think about this?

I create this structure to PECE project: https://github.com/PECE-project/drupal-pece/tree/pece2.0

I used docker4drupal project and drupal-project

**Comment by rhabbachi** [comment]
Latest work on this https://github.com/GetDKAN/dkan-tools/pull/226

**Comment by dafeder** [comment]
@edmargomes cool - will take a look!

**Comment by janette** [comment]
@rhabbachi can this be closed or is there further work to be done?

**Comment by rhabbachi** [comment]
Can close, work either merged or direction changed.
