### ISSUE TITLE
Bug: Publisher API generates a new entry when adding values with json form

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3070]
`api/1/metastore/schemas/publisher/items`

When adding values to publisher description, or publisher image with the metadata json form, new entries are added to the publisher api rather than appending the existing publisher.

![publisher_api](https://user-images.githubusercontent.com/314172/79135010-4f663c80-7d74-11ea-82ea-cf2578569377.png)

**Comment by janette** [comment]
This was fixed by https://github.com/GetDKAN/dkan2/pull/333
