### ISSUE TITLE
Document best practices for Internationalization

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#31]
Internationalization has been tested and a public example will be available soon. Make this part of the distro. Allow enabling in installation.

**Comment by ziodave** [comment]
+1

**Comment by acouch** [comment]
> make sure there aren't any things we are doing in the distro to inhibit multi-lingual (we've actually done a lot of work on this)

We've done this successfully with a couple of projects so if there are blockers they shouldn't be too large

We have not made progress on the latter two points but will try and get it in our queue.

**Comment by oriole9g** [comment]
Is there any documentation about DKan Internationalization? maybe we could do a short list of steps.

**Comment by dafeder** [comment]
@oriole9g that's a great point. I think we need to package up some configurations that will create a standardized way of doing this in DKAN (as well as some out-of-box translations in common languages) but also documentation will be a big component. As you may have seen we have a #multilingual channel in the DKAN community Slack now. Hope to be able to make progress on this soon, I know a lot of people have been working on this on their own.

**Comment by acouch** [comment]
This is not on our near term roadmap. There are a lot of DKAN sites that use internationalization and the recipe isn't super difficult. I'm renaming the issue to at least document best practices for teams who want to implement.
