### ISSUE TITLE
Create new date/time widget

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3105]
## Description
The built in date-time widget forces the user to submit a full date-time value, we need a widget that will make it easy to add dates to the "Issued" field but also allow for simple dates such as `2019` or `2015-03`

https://github.com/rjsf-team/react-jsonschema-form
https://react-jsonschema-form.readthedocs.io/en/latest/advanced-customization/#custom-widget-components

The rjsf library date widget requires a full datetime value to be collected. The POD requirements are: 
> Dates should be ISO 8601 of least resolution. In other words, as much of YYYY-MM-DDThh:mm:ss.sTZD as is relevant to this dataset.

## Acceptance Criteria
The date widget  that allows minimum data entries
1. **Issued**:  should allow dates such as `2017` or `2000-03-15`
2. **temporal coverage**: should be two text inputs (or more) and we assemble them to match the format required _2000-01-15T00:45:00Z/2010-01-15T00:06:00Z_
3. **modified**: should also be able to collect repeating interval codes rather than a date.

## Details Tasks
- [ ] Find an existing component or javascript library that will handle a non-date input

**Comment by janette** [comment]
- [ ] https://github.com/smackjax/ez-react-date-input
- [x] https://github.com/netojose/react-select-datepicker
- [ ] https://github.com/JMcAmmond/react-select-datepicker
