### ISSUE TITLE
ResourceMapper

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#3108]
One of the most useful features of DKAN is its capability to allow users to explore the data to some degree to help them figure out whether it is the right data for them before downloading it. To allow this data previewing we get a copy of a remote file, parse it, and store it in a database table.

In other scenarios, we might be consuming data from "private" sources and we might need to get a local copy of the files not only for previewing but to simply make the available. In this instances we might also need to know what the local url for public access to the file is. 

The point is that a file can be seen from many perspectives withing DKAN:
1. A remote file
1. A local copy
1. A datastore table
1. A local URL

The FileMapper is an attempt at unifying the management of these different perspectives.

**Comment by drasgardian** [comment]
Sometimes it isn't a file at all, but is a URL reference to a remote API - see the 3 tab options when adding a resource in dkan 1.

**Comment by janette** [comment]
@drasgardian if it is a reference to a remote API that should be stored as an `accessUrl` not as a `downloadUrl`
