### ISSUE TITLE
D9 compatibility

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3109]
## Subtasks

- [ ] run operate status module
- [ ] run rector
- [ ] add to documentation re: D9 compatibility

**Comment by tgurr** [comment]
Recently https://github.com/GetDKAN/dkan/pull/3121 has been merged, but not referenced here and this issue hasn't been updated accordingly. What is the actual status of D9 compatibility and DKAN 2.x, is it already expected to work with the latest released DKAN version 2.2.0?

**Comment by kimwdavidson** [comment]
DKAN is working with the latest D9. Closing.
