### ISSUE TITLE
Problem in ajax with chrome 83

### ISSUE THREAD

**Issue by chrodos** [GetDKAN/dkan#3113]
When chrome was updated to version 83 the add and remove resource stopped working. I am working on a dkan-7.x. I did some googling and I found this that is probably relevant: https://www.drupal.org/project/drupal/issues/3138421

<img width="427" alt="2020-05-28_22-10-03" src="https://user-images.githubusercontent.com/5204324/83183856-3b627880-a131-11ea-965c-d48cb0b5e391.png">

**Comment by dharizza** [comment]
A working patch has already been committed to D7 and as per https://www.drupal.org/project/drupal/issues/3143016 a new release will come in a couple of days, so we're going to wait until that release to include this in 1.18.6.

It looks like this is not an issue for D8.

**Comment by dharizza** [comment]
Hello!

This issue has been fixed in latest release https://github.com/GetDKAN/dkan/releases/tag/7.x-1.18.6.
