### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by pnpierce713** [GetDKAN/dkan#3117]
We have installed drupal and now trying to install dkan-tools. When following the steps to start the nginx proxy in docker we are getting 503 Service Temporarily Unavailable when going to http://dkan

What items are we missing and should look for? This is running on RHEL 7.8, and has php 7.4.6, mysql 5.7.30, Apache/2.4.6, and Drush Commandline Tool 10.2.2 which should be the latest versions available at this time.

**Comment by janette** [comment]
@pnpierce713 it sounds like you are not using the docker containers provided by dkan-tools. Do you have an existing Drupal site already running on your environment? If you have a working URL then edit _src/frontend/.env.production_ to use that url and run `npm run build` in _src/frontend_

**Comment by pnpierce713** [comment]
We have a working Drupal site running and are able to access it from a browser. Where we are confused is where we should be trying to access dkan? We run the docker container but have to either move the apache server off port 80 or run the docker container on a different port. Should be be overwriting the drupal site with dkan? the dkan-tools are currently installed at /var/www/html/drupal/dkan-tools. We have not installed dkan yet as the instructions said to get dkan-tools installed first.

We are unable to find a src/frontend in the dkan-tools directory. This is the listing under the src directory:
ll -a
total 8
drwxr-xr-x 4 root root   83 Jun  3 14:55 .
drwxr-xr-x 8 root root  225 Jun  4 10:13 ..
-rw-r--r-- 1 root root 4056 Jun  3 14:55 BasicCommands.php
drwxr-xr-x 2 root root  262 Jun  3 14:55 Command
-rw-r--r-- 1 root root 1810 Jun  3 14:55 SymlinksTrait.php
drwxr-xr-x 2 root root   46 Jun  3 14:55 Util

**Comment by janette** [comment]
@pnpierce713 if you have a Drupal site that was not created with dkan-tools, then you would need to run `export DKTL_MODE="HOST"` we do not support this method but it is there if you want to use it.

Try these steps:

```
composer require 'getdkan/dkan:2.1.0'
dktl drush en dkan frontend sample_content
dktl drush dkan:sample-content:create
dktl drush sapi-i
dktl frontend:install
```
This last command is what downloads the frontend application to _src/frontend_ and will symlink it to _docroot/data-catalog-frontend_

Edit the `/src/frontend/.env.production` file to change the GATSBY_API_URL to reflect your site url. (`dktl url`)

To check if it is working go to [your-site-url]/api/1/search, if you see json output, it is working and you can proceed to build the frontend pages.

```
dktl frontend:build
```

**Comment by pnpierce713** [comment]
Thank you for the help, this is the first experience we have had with drupal but we have been linux admins for many years. We went ahead and started over and now we are not using our own drupal install and using docker. We found that RHEL 7 comes with docker 1.13 so we first updated our docker repo and now have docker 19.03.11 installed. We also found that versions of docker above 18 renamed  docker-runc to just runc and had to create a symbolic link in order to get dkan tools to initialize a new project. Everything was running smooth this time up until we ran 'dktl install' and it's throwing this error:

`[root@SERVER www]# docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
e2c2da6feee6a51e2dab01bc0242149bfe2efa70b198f176af75b08f58a42267
[root@SERVER www]# docker container ls
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                NAMES
e2c2da6feee6        jwilder/nginx-proxy   "/app/docker-entrypo…"   15 seconds ago      Up 12 seconds       0.0.0.0:80->80/tcp   clever_northcutt
[root@SERVER www]# dktl install
Starting docker containers.
Starting www_solr_1 ...
Starting www_memcached_1 ...
Starting www_memcached_1 ... done
Starting www_web_1 ... done
Starting www_browser_1 ... done
Starting www_cli_1 ... done
 [Exec] Running drush si standard -y in /var/www/docroot
 [Exec]  Exit code 1  Time 9.952s
 [Exec] Running drush en dkan dblog config_update_ui -y in /var/www/docroot
 [Exec]  Exit code 1  Time 0.383s
 [Exec] Running drush config-set system.performance css.preprocess 0 -y in /var/www/docroot
 [Exec]  Exit code 1  Time 0.346s
 [Exec] Running drush config-set system.performance js.preprocess 0 -y in /var/www/docroot
 [Exec]  Exit code 1  Time 0.342s
 [Exec] Running drush config-set system.site page.front "/home" -y in /var/www/docroot


  Command config-set was not found. Drush was unable to query the database. As a result, many commands are unavailable. Re-run your command with --debug to see relevant log messages.


 [Exec]  Exit code 1  Time 0.349s
 [Exec] Running chmod u+w sites/default in /var/www/docroot
 [Exec] Done in 0.018s

[root@SERVER www]# docker container ls
CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
e2c2da6feee6        jwilder/nginx-proxy                       "/app/docker-entrypo…"   About an hour ago   Up About an hour    0.0.0.0:80->80/tcp                                                       clever_northcutt
efe4daaac36b        getdkan/dkan-cli:latest                   "/opt/startup.sh /bi…"   2 hours ago         Up About an hour    0.0.0.0:32774->8888/tcp                                                  www_cli_1
f47b8585514a        selenium/standalone-chrome-debug:2.53.1   "/opt/bin/entry_poin…"   2 hours ago         Up About an hour    4444/tcp, 0.0.0.0:32773->5900/tcp                                        www_browser_1
8cf99dc6e4b5        getdkan/dkan-docker:php72-web             "/usr/sbin/apache2ct…"   2 hours ago         Up About an hour    0.0.0.0:32772->80/tcp, 0.0.0.0:32771->443/tcp, 0.0.0.0:32770->8888/tcp   www_web_1
dbb55b44b263        wodby/mariadb:latest                      "/docker-entrypoint.…"   2 hours ago         Up About an hour    0.0.0.0:32769->3306/tcp                                                  www_db_1
618661a85156        memcached                                 "docker-entrypoint.s…"   2 hours ago         Up About an hour    11211/tcp                                                                www_memcached_1
f69e8097b012        devinci/drupal-solr:3.x                   "/bin/sh -c /opt/sta…"   2 hours ago         Up About an hour    0.0.0.0:32768->8983/tcp                                                  www_solr_1`

I also included what docker images are running. When I try to go to http://dkan after this error all we get is: 'The website has encountered an unexpected error. Please try again later.' I have shut down apache and mysql on our server as the docker containers are running those services. Can you please let us know where we should look next?

**Comment by janette** [comment]
@pnpierce713 I'm still confused if you are using the dkan-docker images or your own. Based on the output it looks like you've skipped some steps.

```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```
this is a good start, this will allow you to see the front end. Continue with the following commands to get a working demo site inside your project directory:

```
dktl init
dktl get 8.8.6
dktl make
dktl install --demo
```
These steps will build a new Drupal site, with the dkan module enabled, the frontend code downloaded to the right spot, sample content created and indexed, and the frontend dataset pages built.

Also we have made some updates to the [DKAN Tools readme](https://github.com/GetDKAN/dkan-tools) to hopefully be more clear.

**Comment by pnpierce713** [comment]
Thank you. We were using the dkan-docker images. We went ahead and removed everything and started over and followed your instructions and were able to get the demo running after that. I'm not sure what we missed but thank you for your help in getting this resolved.
