### ISSUE TITLE
Problem with install and activate dkan in drupal 8.9.0

### ISSUE THREAD

**Issue by ixtogt** [GetDKAN/dkan#3118]
When i try to activate dkan in drupal modules, i have this error 

PHP Fatal error:  Interface 'Contracts\RetrieverInterface' not found in ...modules/dkan-2.1.0/modules/metastore/src/SchemaRetriever.php on line 11

what could be going on?

**Comment by janette** [comment]
@ixtogt did you install dkan with `composer require 'getdkan/dkan:2.1.0'`? this will download the required dependencies

**Comment by ixtogt** [comment]
Hi janette, 

i retry my drupal installation (drupal 8.9.0) with composer and now i have other problem, 
whe i run `composer require 'getdkan/dkan:2.1.0'` give this error: 

`Loading composer repositories with package information
Updating dependencies (including require-dev)`

`mmap() failed: [12] Cannot allocate memory`

`mmap() failed: [12] Cannot allocate memory`

`mmap() failed: [12] Cannot allocate memory`

`Fatal error: Out of memory (allocated 780148736) (tried to allocate 67108872 bytes) in phar:///.../composer/composer.phar/src/Composer/DependencyResolver/RuleSet.php on line 84`

**Comment by janette** [comment]
@ixtogt I would suggest try using the Docker/Docker Compose method outlined in [DKAN Tools](https://github.com/GetDKAN/dkan-tools) that is a controlled and tested environment. You could try increasing memory_limit but If you want to use your own set up you will have to debug those memory issues on your own.

**Comment by thierrydallacroce** [comment]
@ixtogt `composer` is known to run out of the default amount of memory it is provided with, even though it allocates itself 1.5 GB. There are ways to increase this limit, either via aliasing it or preceding it with an environment variable. More info can be found [here](https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors).

That said, @janette is correct, if you can stick with the recommended approach of using `dktl` and Docker, it shouldn't be an issue. Internally, `dktl` sets an environment variable early in its process in its [bin/app.php](https://github.com/GetDKAN/dkan-tools/blob/master/bin/app.php).

**Comment by kimwdavidson** [comment]
Closing. Feel free to reopen if you have additional questions

**Comment by Rkedemi** [comment]
I am running my website on a Windows machine under WAMP. I have being trying to install and activate DKAN2 on Drupal 8 and I am always getting the error below.

( ! ) Fatal error: Interface 'Contracts\RetrieverInterface' not found in D:\wamp\www\drupal8\modules\dkan-2.3.0\modules\metastore\src\SchemaRetriever.php on line 11

**Comment by gurvinder-singh** [comment]
I get below when i try **composer require 'getdkan/dkan:2.1.0'**

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for getdkan/dkan 2.1.0 -> satisfiable by getdkan/dkan[2.1.0].
    - getdkan/dkan 2.1.0 requires getdkan/datastore dev-original-column-names -> no matching package found.

**Comment by dafeder** [comment]
@gurvinder-singh was probably a mistake to have pointed to a dev branch in a release, we could potentially go back and fix. But, any reason you're specifying the exact version number in your composer file like that? Why not just `composer require getdkan/dkan`?

**Comment by risesnow** [comment]
> @gurvinder-singh was probably a mistake to have pointed to a dev branch in a release, we could potentially go back and fix. But, any reason you're specifying the exact version number in your composer file like that? Why not just `composer require getdkan/dkan`?

Hi, I also get error

Problem 1
    - Root composer.json requires getdkan/dkan 2.12.1 -> satisfiable by getdkan/dkan[2.12.1].
    - getdkan/dkan 2.12.1 requires drupal/indexer 1.0.x-dev -> found drupal/indexer[dev-1.0.x, 1.0.x-dev (alias of dev-1.0.x)] but it does not match your minimum-stability.

All command I try

> composer require getdkan/dkan 
> composer require getdkan/dkan:* 
> composer require getdkan/dkan:2.12.1

 it still getting the same problem (composer.json requires getdkan/dkan and requires drupal/indexer not match minimum-stability)
