### ISSUE TITLE
File Upload Widget

### ISSUE THREAD

**Issue by dharizza** [GetDKAN/dkan#3126]
## User Story

As a data publisher, I want to be able to upload files through a user interface, so that I can share my data without having to use a remote file.

## Acceptance Criteria
(add once we decide if we're using data.gov's UI)

## Implementation details:

Create custom widget that allows users to choose what they want to add (either a URL or file).

- widget should be a field chooser with two tabs: 
  - [ ] one for URL 
  - [ ] one for file upload
- add validations:
  - [ ] If user chooses url —> we should validate if it is a valid url.
  - [ ] If user chooses a file upload —> we should validate if the resulting URI corresponds to an existing file.
- both fields will return an URI, which is what will be saved in the JSON Metadata field

Relates to https://github.com/GetDKAN/dkan2/issues/409

**Comment by dafeder** [comment]
Putting aside as we expirement with a form-api solution. See #3166

**Comment by janette** [comment]
blocked by #3166

**Comment by susisiman** [comment]
Still blocked, form api is in progress, en route to be closed soon.
