### ISSUE TITLE
How do you get the full site for dkan running?

### ISSUE THREAD

**Issue by pnpierce713** [GetDKAN/dkan#3132]
I've been working with another admin for the past 2.5 weeks trying to get a working version of dkan going for a demo in our environment. So far we have gotten DKAN 1.17 working but it throws ajax errors when trying to add sources inside of harvest, and we haven't gotten to the next step of getting solr connecting to our Cloudera cluster. We have also tried DKAN 2.1(with docker images with dkan-tools) but we have only gotten the demo site to run which doesn't have anywhere to login where we can add harvest sources and a solr connection. When we try to install dkan with an existing Drupal 8.8.8 install via the install instructions, it gives a dktl error saying to run dktl init first when running 'dktl drush en dkan frontend sample_content'.

We are running RHEL 7.8 and php 7.3(with drupal 7) or 7.4(with drupal 8), mysql 5.7.30, and apache 2.4.6(the latest from red hat repo). What would be our best bet to get a working site that we can modify, DKAN 1.17 or go with 2.1? We are both experienced Linux admins but this is our first time using drupal and dkan. Are we missing something simple? We are fine with running in docker as well but don't know how to set it up and be able to login to DKAN to edit the site.

Here is a sample of what we did to try out dkan 2.1 with a new local drupal 8 install:
yum install composer(Composer version 1.10.7 2020-06-03 10:03:56)
mkdir /myworkspace
cd /myworkspace
git clone https://github.com/GetDKAN/dkan-tools.git
linked dktl to /usr/local/sbin/dktl
install drupal-8.8.8 in /var/www/html/
create drupal database in mysql
login to http://localhost/drupal-8.8.8 and install drupal(no issues here)
composer require 'getdkan/dkan:2.1.0'
dktl drush en dkan frontend sample_content(at this point it says it run dktl init first, I run that and it fails to start the cli docker container)

**Comment by janette** [comment]
@pnpierce713 

DKAN 1.17: What are the errors you are getting, can you post them?
DKAN 2.1: There is no UI for adding harvests yet, for now you register a source with a drush command:
```
drush dkan-harvest:register '{"identifier":"example","extract":{"type":"\\Harvest\\ETL\\Extract\\DataJson","uri":"https://source/data.json"},"transforms":[],"load":{"type":"\\Drupal\\harvest\\Load\\Dataset"}}'
```
Read more about that here https://demo.getdkan.com/modules/contrib/dkan/docs/harvest.html

DKAN Tools: These commands are designed to stand up a site starting at the docker containers. If you want to use the commands without using the managed containers then you would need to run `export DKTL_MODE="HOST"` more on that here: https://github.com/GetDKAN/dkan-tools/blob/master/README.md

Your example steps are fine, you don't have to use dkan-tools, but then on the last step just run `drush en dkan frontend sample_content`
You can log in at http://localhost/user
and you will need to manually build the REACT frontend: the steps are here: https://github.com/GetDKAN/data-catalog-frontend/blob/master/README.md

**Comment by pnpierce713** [comment]
Thank you for your assistance. Here is an update on what we are seeing:

DKAN 1.17:
Here is the error we receive when we try to add a json data source(https://data.cdc.gov/api/views/qwpv-wpc8/columns.json): 

Error

The website encountered an unexpected error. Please try again later.

This is what our Harvest dashboard looks like:
![image](https://user-images.githubusercontent.com/66386437/85042460-db1f8f00-b150-11ea-8b9f-051ecdef1abb.png)

This is the error we receive when we try to delete a data source:
Error message
An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: /drupal-7.72/dkan/webroot/?q=batch&id=20&op=do StatusText: Service unavailable (with message) ResponseText: EntityMetadataWrapperException: Unable to get the data property machine as the parent data structure is not set. in EntityStructureWrapper->getPropertyValue() (line 457 of /var/www/html/drupal-7.72/dkan/webroot/profiles/dkan/modules/contrib/entity/includes/entity.wrapper.inc).

![image](https://user-images.githubusercontent.com/66386437/85042729-2afe5600-b151-11ea-8cec-4cc153879d56.png)

DKAN 2.1:
The biggest issue we are having here is there is no where to login and get to the admin interface when building the docker containers. Thank you for the links on harvest it DKAN 2.1. We will be working on getting it setup today and I'll update on our progress later today.

**Comment by janette** [comment]
DKAN 1.7: 
That json file you posted (https://data.cdc.gov/api/views/qwpv-wpc8/columns.json) is not publicly available and looks like a data dictionary endpoint...? For harvesting use https://data.cdc.gov/data.json

DKAN 2.1:
Running `dktl init` sets up the containers and the project file structure, there is no need for a login. 
To harvest from the source you mention, it would be 
```
drush dkan-harvest:register '{"identifier":"cdc","extract":{"type":"\\Harvest\\ETL\\Extract\\DataJson","uri":"https://data.cdc.gov/data.json"},"transforms":[],"load":{"type":"\\Drupal\\harvest\\Load\\Dataset"}}'
```
to register it, then run with
```
drush dkan-harvest:run cdc
```

**Comment by pnpierce713** [comment]
DKAN 1.7:

Here is what happens when I try the json file you linked:
![image](https://user-images.githubusercontent.com/66386437/85061977-55f6a300-b16d-11ea-8d09-5433d356fa2e.png)

Then I hit save and this comes up:
![image](https://user-images.githubusercontent.com/66386437/85062097-82122400-b16d-11ea-8464-b2e6046a1566.png)

Then when I go back it's created this again:
![image](https://user-images.githubusercontent.com/66386437/85062336-f220aa00-b16d-11ea-8f6b-7afb062ce849.png)

**Comment by pnpierce713** [comment]
DKAN 2.1:
Thank you that makes more sense on how to add harvest sources. Is there a way we can get the admin toolbar in dkan 2.1? This is what it looks like in DKAN 1.17 and thought there would be something similiar in 2.1:

![image](https://user-images.githubusercontent.com/66386437/85062605-60656c80-b16e-11ea-9327-2b3e3bcc47bf.png)

Without that I don't see how we can add users with various roles like there is in the older version.

Thank you

**Comment by janette** [comment]
DKAN 1.7: looks like there is something wrong with the build, check the output on `/admin/reports/dblog` (enable database logging if not enabled) or check the php error.log

DKAN 2.1: Click on 'People' to add users, set up roles, and add permissions

![people](https://user-images.githubusercontent.com/314172/85063977-8986fc80-b170-11ea-96a3-0859f9113f33.png)

**Comment by pnpierce713** [comment]
DKAN 2.1:
Here is what we are getting when running the manual data-catalog-frontend install after npm start. I'm guessing it's due to createpages failing is why we get nothing on our site. Some of the other tabs work though, such as 404, publishers, and about:

`> data-catalog-frontend@1.0.0 start /var/www/html/drupal-8.8.8/data-catalog-frontend
> npm run develop


> data-catalog-frontend@1.0.0 develop /var/www/html/drupal-8.8.8/data-catalog-frontend
> gatsby develop

success open and validate gatsby-configs - 0.050s
success load plugins - 0.919s
success onPreInit - 0.017s
success initialize cache - 0.009s
success copy gatsby files - 0.030s
success onPreBootstrap - 0.013s
success createSchemaCustomization - 0.008s
success source and transform nodes - 0.061s
success building schema - 0.353s

 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the createPages lifecycle:

Request failed with status code 404



  Error: Request failed with status code 404

  - createError.js:16 createError
    [data-catalog-frontend]/[axios]/lib/core/createError.js:16:15

  - settle.js:17 settle
    [data-catalog-frontend]/[axios]/lib/core/settle.js:17:12

  - http.js:236 IncomingMessage.handleStreamEnd
    [data-catalog-frontend]/[axios]/lib/adapters/http.js:236:11

  - task_queues.js:84 processTicksAndRejections
    internal/process/task_queues.js:84:21

  - From previous event:

  - api-runner-node.js:258 runAPI
    [data-catalog-frontend]/[gatsby]/dist/utils/api-runner-node.js:258:22

  - api-runner-node.js:375 Promise.catch.decorateEvent.pluginName
    [data-catalog-frontend]/[gatsby]/dist/utils/api-runner-node.js:375:15

  - From previous event:

  - api-runner-node.js:374
    [data-catalog-frontend]/[gatsby]/dist/utils/api-runner-node.js:374:12

  - timers.js:456 processImmediate
    internal/timers.js:456:21

  - From previous event:

  - api-runner-node.js:368
    [data-catalog-frontend]/[gatsby]/dist/utils/api-runner-node.js:368:11

  - From previous event:

  - api-runner-node.js:275 module.exports
    [data-catalog-frontend]/[gatsby]/dist/utils/api-runner-node.js:275:12

  - index.js:421 module.exports
    [data-catalog-frontend]/[gatsby]/dist/bootstrap/index.js:421:9

  - develop-process.js:433 async module.exports
    [data-catalog-frontend]/[gatsby]/dist/commands/develop-process.js:433:7


failed createPages - 0.081s
success createPagesStatefully - 0.095s
success onPreExtractQueries - 0.003s
success update schema - 0.037s
success extract queries from components - 0.837s
success write out requires - 0.037s
success write out redirect data - 0.010s
success Build manifest and related icons - 0.121s
success onPostBootstrap - 0.137s
⠀
info bootstrap finished - 5.444s
⠀
success run page queries - 0.058s - 6/6 103.91/s
⠀
You can now view data-catalog-frontend in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
warn ESLintError:
/var/www/html/drupal-8.8.8/data-catalog-frontend/src/pages/publishers.js
  1:17  warning  'useState' is defined but never used   no-unused-vars
  1:27  warning  'useEffect' is defined but never used  no-unused-vars
  2:8   warning  'axios' is defined but never used      no-unused-vars

✖ 3 problems (0 errors, 3 warnings)

success Building development bundle - 12.183s
netst`

![image](https://user-images.githubusercontent.com/66386437/85063607-01085c00-b170-11ea-8c25-f892a7c23d62.png)

![image](https://user-images.githubusercontent.com/66386437/85064414-26e23080-b171-11ea-8373-1012644c2252.png)

**Comment by janette** [comment]
@pnpierce713 Perfect, this is actually working as expected since you do not have dataset content. If you run the harvest drush commands above or enable the 'sample_content' module, then in `src/frontend` run `npm run build` you should see the search page working and dataset pages as well.

**Comment by janette** [comment]
Testing with the CDC endpoint, looks like it is a Socrata site so you would need to add some ETL to make the values validate against the POD schema. This is done through the Transform class.

![harverst](https://user-images.githubusercontent.com/314172/85067195-e802a980-b175-11ea-8632-90808566c0d8.png)

**Comment by pnpierce713** [comment]
Here is our error results from 'npm run build'

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'build' ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle data-catalog-frontend@1.0.0~prebuild: data-catalog-frontend@1.0.0
6 info lifecycle data-catalog-frontend@1.0.0~build: data-catalog-frontend@1.0.0
7 verbose lifecycle data-catalog-frontend@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle data-catalog-frontend@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/html/drupal-8.8.8/data-catalog-frontend/node_modules/.bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle data-catalog-frontend@1.0.0~build: CWD: /var/www/html/drupal-8.8.8/data-catalog-frontend
10 silly lifecycle data-catalog-frontend@1.0.0~build: Args: [ '-c', 'gatsby build --prefix-paths' ]
11 silly lifecycle data-catalog-frontend@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle data-catalog-frontend@1.0.0~build: Failed to exec build script
13 verbose stack Error: data-catalog-frontend@1.0.0 build: `gatsby build --prefix-paths`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid data-catalog-frontend@1.0.0
15 verbose cwd /var/www/html/drupal-8.8.8/data-catalog-frontend
16 verbose Linux 3.10.0-1127.10.1.el7.x86_64
17 verbose argv "/usr/bin/node" "/bin/npm" "run" "build"
18 verbose node v12.18.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error data-catalog-frontend@1.0.0 build: `gatsby build --prefix-paths`
22 error Exit status 1
23 error Failed at the data-catalog-frontend@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by janette** [comment]
@pnpierce713 what are the datasets on your site? the sample content? or the CDC harvest?

**Comment by pnpierce713** [comment]
The CDC harvest

**Comment by janette** [comment]
1. `dktl drush dkan:harvest:revert cdc`
2. `dktl drush dkan:harvest:deregister cdc`
3. Go to `/admin/dkan/dataset` and add a dataset manually. 
2. `dktl drush sapi-i`
3. `dktl frontend:build`

If that gets you a working dataset page, then the frontend code is working as expected. 

If you get more errors, then try removing `src/frontend/node_modules` and run npm install, npm run build again. Or `gatsby develop` might give you more information...

If you don't get errors:
You can then add the CDC harvest but this time create a custom module to fix the missing values on that source.

1. Copy the socrata_harvest module from here https://github.com/GetDKAN/dkan/pull/3137/files to your site.
2. Enable the module
3. Add the transform to your harvest plan:
```
drush dkan-harvest:register '{"identifier":"cdc","extract":{"type":"\\Harvest\\ETL\\Extract\\DataJson","uri":"https://data.cdc.gov/data.json"},"transforms":["\\Drupal\\socrata_harvest\\Transform\\Socrata"],"load":{"type":"\\Drupal\\harvest\\Load\\Dataset"}}'
```
4. `dktl drush dkan:harvest:run cdc`
5. `dktl drush sapi-i`
6. `dktl frontend:build`

**Comment by kimwdavidson** [comment]
We'll close this ticket up. Feel free to reopen if you have more questions.
