### ISSUE TITLE
Unexpected error when trying to access datasets within Drupal

### ISSUE THREAD

**Issue by tgurr** [GetDKAN/dkan#3142]
I've just installed Drupal 8.9.1 and DKAN 2.2.0 and added the sample-content as well as created a new test dataset, when trying to display them from `https://opendata.domain.local/admin/content/datasets`, e.g. `https://opendata.domain.local/dataset/bc9af3ec-5eb5-4291-a3cf-81daa73f5e66` I get an error from Drupal: `The website encountered an unexpected error. Please try again later.`

In the PHP log I get: `[26-Jun-2020 11:47:16 Europe/Berlin] Uncaught PHP Exception UnexpectedValueException: "The Response content must be a string or object implementing __toString(), "boolean" given." at /var/www/opendata.domain.local/drupal8/vendor/symfony/http-foundation/Response.php line 399`

Software versions in use:
apache-2.4.43
php-fpm-7.4.7
mariadb-10.4.13

**Comment by tgurr** [comment]
Small update on this one:

![Screenshot_20200629_121058](https://user-images.githubusercontent.com/414984/85996486-9de8b600-ba08-11ea-8ffe-bcef3e279c13.png)

When clicking on Title to access a dataset the `/admin/dkan` in the URL is omitted resulting in the error, while clicking on edit allows me to browse/edit the dataset.

**Comment by janette** [comment]
@tgurr 
are you using dkan-tools?

if yes:

Is the proxy running?
```
docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
```

Did you index?
```
dktl drush dkan:metastore-search:rebuild-tracker
dktl drush search-api:index
```

Did you build the frontend files?
```
dktl frontend:install
dktl frontend:build
```

**Comment by tgurr** [comment]
@janette I'm not using dkan-tools and also no docker. I've installed Drupal, Drush and DKAN with composer, followed by 

```
drush en dkan frontend sample_content
drush dkan:sample-content:create
drush search-api:rebuild-tracker
drush sapi-i
```

During testing I've installed everything multiple times and the issue seems to be reproducible to me, no matter if installing DKAN into Drupal 8.9.1 or 9.0.1.

As this is in the Drupal backend the frontend is not involved, but I also did (re-)build the frontend, which is working for me.

**Comment by janette** [comment]
@tgurr the links you have circled in red will take you to the React dataset display page, the error indicates that the frontend is not built or the proxy is not working. Can you pull the latest dkan-tools updates and run

```
dktl frontend:install
dktl frontend:build
dktl proxy:connect
```

**Comment by tgurr** [comment]
@janette thanks for the explanation. I don't use dkan-tools. Looking at the dkan-tools source it seems to introduce traefik as additional proxy component. I wonder why this can't be just simple links to the React frontend, without introducing yet even more complexity. But it looks like I've to live with having the broken links in the backend.

**Comment by ghost** [comment]
Closing this ticket due to inactivity.

**Comment by janette** [comment]
@tgurr if you pull the latest release you can test the updates made to the admin view of datasets and links. The dataset form iteself is now a Drupal form.

**Comment by tridoxx** [comment]
i have the same error you fix it ? @tgurr

**Comment by dafeder** [comment]
@tridoxx what versions of DkAN and Drupal? Can you post a stack trace or at least the class/method/line that is throwing it?

**Comment by tgurr** [comment]
> i have the same error you fix it ? @tgurr

I've switched to CKAN now that it supports Python3, when evaluating an opendata platform it was still on Python2 which was already end of life so no viable solution back then.
