### ISSUE TITLE
Clean up dataset json schema file

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3143]
## User story
When I manually add a dataset, I should not see any fields that don't require human data entry, so that I'm not confused

## Acceptance criteria
When I manually add a dataset
I should not see a distribution identifier field 
I should not see a media type field

## Details/Tasks
- remove distribution identifier
- remove file size
- add suggested list for format and media type
- hide media type

**Comment by susisiman** [comment]
@fmizzell Are you code reviewing this?
