### ISSUE TITLE
Update  getCatalog() function to use base_url

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#3165]
`metasatore/src/Service.php` is currently using a hard coded http://dkan from `schema/collections/catalog`, we want it to use the $base_url value instead

**Comment by kimwdavidson** [comment]
Use base URL scheme

**Comment by dafeder** [comment]
@janette I actualy don't see where this is happening? No hard-coded http://dkan I can find outside the tests, where we should probably change but they don't seem to be breaking atm. Can you confirm and either add back to the appropriate column of the Triage project or close? Thanks
