### ISSUE TITLE
Move from rjsf to Drupal Form API

### ISSUE THREAD

**Issue by dharizza** [GetDKAN/dkan#3166]
## Description
The idea is to move away from react-jsonschema-form and create the dataset form based on a JSON schema using the Drupal Form API so we can have full control over the form and still have all the drupal capabilities available.

## Requirements
- Map basic fields from the JSON schema to form API widgets (this should include validators for the fields)
- Build the metadata based on submitted values and create the dataset (and references).
- Get as many fields working as possible and create extra tickets for the ones that does not.
- Support UI schema based on rjsf UI schema.
- Support adding objects like distributions as needed.

## Acceptance Criteria
- A form is created based on the current DKAN JSON Schema and a schema-ui.
- The form is available in a demo page.

**Comment by janette** [comment]
plugin in metastore
somewhere in the form life cycle, turn info into json and place into the json field
node form vs. new form to decouple from regular node
make it a field widget thing
how to target specific field within field widget for error reporting to user (phase 2)

**Comment by janette** [comment]
will need extra work if sticking with node rather than entity

**Comment by dharizza** [comment]
Ready for review in https://github.com/GetDKAN/dkan/pull/3195
