### ISSUE TITLE
Harvest drush commands to show run details

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#3170]
## User story
As a data publisher, when I am running a harvest via drush, I want to see if the harvest was successful or what went wrong with the harvest after it completes, so that I know the status and how I might fix it if necessary. 

## Notes
It's hard to find information about what went wrong (or right!) on a harvest run after it's complete; the `drush dkan:harvest:run` command provides only very basic output. 

Initial proposal for commands:

[coming soon]

**Comment by rhabbachi** [comment]
Proposed command `dkan:harvest:status`

Shows a table with list of processed items and status of various stages of the harvest run process.

**Comment by rhabbachi** [comment]
Assigning to @dafeder  for review.
