### ISSUE TITLE
Reduce Composer's memory use with `zaporylie/composer-drupal-optimizations`

### ISSUE THREAD

**Issue by colans** [GetDKAN/dkan#3183]
Please require [zaporylie/composer-drupal-optimizations](https://packagist.org/packages/zaporylie/composer-drupal-optimizations) in `composer.json`.

Otherwise, Composer can run out of RAM when calculating dependencies on small VMs.  See https://www.jeffgeerling.com/blog/2018/make-composer-operations-drupal-way-faster-and-easier-on-ram for details.  Thanks!

**Comment by janette** [comment]
@colans the PR for this breaks our automated builds and I don't have bandwidth to troubleshoot at the moment so closing the issue for now.

**Comment by colans** [comment]
Why not keep it open until someone can resolve?  Closing it means that it's not a problem, which is incorrect.  Thanks.

**Comment by colans** [comment]
This is definitely *not* done.

**Comment by dafeder** [comment]
@colans is there a reason you want this added to DKAN itself? DKAN for D8 is just a module, we want to keep its dependency footprint as small as possible. Your site/project composer.json seems to be the correct place to add a dependency to this kind of composer utility.

**Comment by colans** [comment]
I suppose that's fair.  I'm used to thinking of DKAN as an installation profile.
