### ISSUE TITLE
Cannot add sample content without Drush

### ISSUE THREAD

**Issue by colans** [GetDKAN/dkan#3184]
How can one install the sample content without Drush?  I couldn't find a Configure link on the Extend/modules page, and nothing else in the menus.  Also, there doesn't appear to be a `.routing.yml` file so there doesn't appear to be a way to do this from the Web UI, but maybe I'm missing something.

I'm trying to run DKAN on Aegir, but Drush cannot be used because it appears to be too old for this (due to [Aegir 3 is incompatible with Drush 9+](https://www.drupal.org/project/provision/issues/2953349)).

Running it via `dktl` doesn't work either because it requires Docker, which I'm not installing on a client VM.  (Docker is great for local development, but I don't recommend running it anywhere else.)

```sh
aegir@aegir-dev2 ~/platforms/dkan_2020-08-13-02/docroot/sites/dkan.aegir-dev2.hres.ca
 % dktl drush @dkan.aegir-dev2.hres.ca dkan:sample-content:create
docker and docker-compose are required. Exiting.
aegir@aegir-dev2 ~/platforms/dkan_2020-08-13-02/docroot/sites/dkan.aegir-dev2.hres.ca
 % drush cc drush                                                    
'drush' cache was cleared.                                                                                                      [success]
aegir@aegir-dev2 ~/platforms/dkan_2020-08-13-02/docroot/sites/dkan.aegir-dev2.hres.ca
 % drush @dkan.aegir-dev2.hres.ca dkan:sample-content:create 
The drush command 'dkan:sample-content:create' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache[error]
if you have installed new extensions.
aegir@aegir-dev2 ~/platforms/dkan_2020-08-13-02/docroot/sites/dkan.aegir-dev2.hres.ca
 % drush --version                                          
 Drush Version   :  8.1.16 
```

### Workaround

I'm tried temporarily requiring `drush/drush`, but I get:

```sh
 % drush dkan:sample-content:create
PHP Warning:  pcntl_exec(): Error has occurred: (errno 13) Permission denied in phar:///usr/local/bin/drush/includes/startup.inc on line 419
Error has occurred executing the Drush script found at /var/aegir/platforms/dkan_2020-08-13-02/vendor/drush/drush/drush
(errno 13) Permission denied
```

...which I'm still trying to track down.

**Comment by janette** [comment]
@colans what version of dkan are you running? For a 7.x-1.x site you can just enable the _dkan_default_content_ module. For a Drupal 8/DKAN 2.x site, drush 9.x is the minimum requirement, and to get the sample content you would need to run `drush dkan:sample-content:create`, otherwise you can go to `admin/dkan/dataset` and add your own datasaet content manually.

**Comment by colans** [comment]
This is for Drupal 8.  It would be nice to get a demo site up without Drush, is all, as Aegir 3 doesn't support Drush 9+ .  If there were a button to click on the Drupal site to do this, it would be great.

Thanks for the response!

**Comment by susisiman** [comment]
We are closing this ticket due to lack of bandwidth. Please feel free to submit a pull request!
