### ISSUE TITLE
Simplifying the communication of referenced information in metadata.

### ISSUE THREAD

**Issue by fmizzell** [GetDKAN/dkan#3186]
### Problem
Currently, we have 3ish ways to see our metadata:
1. Original
```
{
    "title": "Hello",
    "distribution": {
        "title": "Title",
        "url": "http://site.com/file.csv
    }
}
```
2. DKAN's internal storage 
```
{
    "title": "Hello",
    "distribution": unique-identifier
}
```
3. Original with information about DKAN's internal references to other objects
```
{
    "title": "Hello",
    "distribution": {
        "identifier": unique-identifier,
        "data": {
            "title": "Title",
            "url": "http://site.com/file.csv
        }
    }
}
```

2 is an internal representation and is not really accessible to the users, or even programmatically through the API, but 1 and 3 are accessible.

The current mechanism to choose which version you see/get is a global static variable. This solution has served us well so far, but from the initial implementation, we wanted to do something different. Global flags bring uncertainty and it makes code harder to reason about given its side-effects. Here is some pseudo-code of how this global flag can land us in trouble:

```
set_show_references_global_flag(TRUE);
$distribution = getDataset('123')->getDistribution();
saveDistribution($distribution);
```
Any code that retrieves that dataset after our manipulation of the distribution will most likely fail. The problem here is that we are retrieving data in a format that looks like 3, and saving/storing it. DKAN expects the data that it processes to always look like 1, but we do not have, yet, the mechanism to guarantee that for internal references, like distributions, our data respects the schema (If our pseudo-code tried to save the full dataset, DKAN would have told us that the data did not comply with our schema).

### Solution
The solution we want to implement, eventually, is to validate these pieces of JSON data that are being saved individually against their respective schema. This will protect our data, but the global flag is still a bad way to ask for what one needs. So we are going to solve that first since it is an easier problem to address.

The proposed solution here is to have a single internal representation of our data. Here is what it will look like:
```
{
    "title": "Hello",
    "distribution": {
        "title": "Title",
        "url": "http://site.com/file.csv
    }
    "%Refdistribution": {
        "identifier": unique-identifier,
        "data": {
            "title": "Title",
            "url": "http://site.com/file.csv
        }
    }
}
```
This new format gives everyone that needs information about the internal references in DKAN what they need, while still keeping the original metadata in a state that should not put the system in a bad state even if we accidentally tried to store it.

**Comment by dafeder** [comment]
@fmizzell this is makes a ton more sense than the current storage/transformation system. One thought -- there's something about the `%Ref` prefix having no separtation from the property name that doesn't sit right with me. Is that based on a convention you've seen elsewhere? My instinct would be to separate the prefix from the property name with something - a dot, a pipe, a colon, whatever.
