### ISSUE TITLE
Content type misssing !

### ISSUE THREAD

**Issue by mrdoruya** [GetDKAN/dkan#3190]
![Annotation 2020-08-26 154723](https://user-images.githubusercontent.com/50456616/91319097-e4ae1e80-e7b3-11ea-9e85-64b534302296.png)
Hi,
I am trying to add new content to my front page with the customize this page button but i am missing several content types. How can i get all the other content type like : Existing content, Table, or New custom content for example.
 I'm using dkan on drupal 7.72
Thank you for your help.

**Comment by janette** [comment]
@mrdoruya can you try reverting features and clear cache
```
drush fra -y
drush cc all
```

**Comment by mrdoruya** [comment]
@janette Thank you for your reply.
Unfortunatly I do not have drush. I am on Windows.
Is there a way to do this without drush ?

**Comment by janette** [comment]
@mrdoruya you will need to go through the overridden features at `admin/structure/features` and manually click through the overridden ones to revert them. Then at `admin/config/development/performance` you can click the button to clear all caches.

**Comment by susisiman** [comment]
Closing for now but please reopen if you continue having issues.
