### ISSUE TITLE
Update local copies along with changes to remote files

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3206]
## User Story
As a data publisher, when there is a change to a remote file, I want local copies to refresh, so that I can download the most up to date version of the data and so the database will also be refreshed for API calls. 

As a data publisher, I want to make sure that file names remain the same even when files are updates, so that I can be sure that it is the same file and all bookmarks are the same URL. 

## Implementation notes:
- Ideally, local copies would refresh whenever it's different from the remote file, but specifying a frequency might be a way to get around that if we're unable to detect when a remote file has changed.
- Historical periodic updates notes: https://github.com/GetDKAN/dkan/issues/3192
- File names have no changes even with updates 

Estimate:

**Comment by susisiman** [comment]
Gerardo and Dharizza will meet to discuss this further

**Comment by susisiman** [comment]
Mostly addressed in #3552  and will create new ticket if we want a different kind of trigger
