### ISSUE TITLE
Wrong ampersand masking in API

### ISSUE THREAD

**Issue by eGovCologne** [GetDKAN/dkan#3210]
I tested this behavior with the latest release 1.18.10.

I try to link the following resource within a dataset:
https://www.stadt-muenster.de/ows/mapserv706/odalkisserv?REQUEST=GetFeature&SERVICE=WFS&VERSION=1.0.0&TYPENAME=ms:stadtgebiet&OUTPUTFORMAT=CSV&EXCEPTIONS=XML&MAXFEATURES=1001

When I use the method "API or Website URL" the json output of the API api/3/action/package_show looks like this:
![image](https://user-images.githubusercontent.com/4679393/93219707-edb75d80-f76b-11ea-8bb6-f53805a93004.png)

The blue marked url is wrong, because the ampersand sign gets masked two times:
- \u0026
- amp;

In result the url is broken.

**Comment by eGovCologne** [comment]
After some testing I figured out that the bug gets shipped with the release 1.15.2.
In release 1.15.1 the above url is fine.
With the release 1.15.2 the url is broken, because the ampersand sign gets masked two times.

**Comment by kimwdavidson** [comment]
We're in pretty minimal maintenance mode on DKAN1 while we work on rolling out DKAN v2 in D8. We likely won't be able to prioritize addressing this, but we would welcome any pull requests you'd like to make.

**Comment by susisiman** [comment]
Closing due to lack of bandwidth. Feel free to submit a pull request!
