### ISSUE TITLE
Clipping icons in Feature Topics

### ISSUE THREAD

**Issue by Joebjammin** [GetDKAN/dkan#3226]
Any help solving this one would be appreciated.

<img width="1440" alt="2020-09-30_17-13-48" src="https://user-images.githubusercontent.com/42526991/94745191-3e23e300-0348-11eb-913f-a18a6cf1d620.png">

**Comment by janette** [comment]
Hi @Joebjammin there is history on this issue: https://github.com/GetDKAN/dkan/issues/2820 

We've also tried to re-generate the font with a larger view box boundary but the clipping still occurs at certain sizes. You could try experimenting with the font size to see if you find one that is acceptable, or avoid the icons where clipping occurs. We've exhausted the time allotted to fixing this bug as the focus is now on the 2.x branch, but if you come up with a solution please submit a pull request.

**Comment by Joebjammin** [comment]
OK thanks Janette.
