### ISSUE TITLE
DKAN 2 on Windows Server

### ISSUE THREAD

**Issue by papachc** [GetDKAN/dkan#3230]
Hi guys,
Is DKAN 2 supported on Windows server? 
Can DKAN 2 run on Windows server? 
If yes, can you direct us to the relevant installation notes?

Thanks,

Bambos

**Comment by janette** [comment]
@papachc you can try this https://www.drupal.org/documentation/install/windows
or https://www.drupal.org/docs/develop/local-server-setup/windows-development-environment

If you have specific issues related to the DKAN module let us know.

**Comment by papachc** [comment]
Thanks Janette. Will have a look and revert if needed.
