### ISSUE TITLE
Fix handling of orphaned content

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#3234]
## Describe the bug
Running `dkan:sample-data:remove` does not remove the example content.

## Steps To Reproduce
1. Stand up a demo site
```
dktl init
dktl demo
```
2. Try to remove the content.
```
dktl drush dkan:sample-content:remove
dktl drush queue:run orphan_reference_processor
dktl drush dkan:metastore-search:rebuild-tracker
dktl drush sapi-i
dktl drush cr
```
3. Go the content admin screen
  - The sample content will be published
  - The moderated content tab will be empty
4. Go to the search screen
  - Results will show there are 0 datasets
  - All facets will still be visible with (0) counts
5. Go to the home screen
  - the topic cards will still display

## Expected behavior
orphan_reference_processor should delete companion property nodes that are not used in other datasets.
Blocker: Deleting distributions needs to be handled carefully, see: #3343

**Comment by dafeder** [comment]
@janette picked this back up and tried to reproduce... behavior now seems to be that all cleanup happens correctly, but unneeded reference entities are now unpublished but still present, which I believe is the desired current behavior as per #3409. Let me know if this should be reopened.
