### ISSUE TITLE
Documentation: Add how-to for user stories

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3242]
User stories here: y from https://app.mural.co/t/civicactions3117/m/civicactions3117/1597344460919/736d05bbb8c2826bf5549cbbbea447d8eaa78e80 

- [ ] Create a dataset
- [ ] Add metadata
- [ ] Add data resource
- [ ] Submit dataset

**Comment by janette** [comment]
Sidebar
- Installation
- Components (DKAN modules)
  -- Metastore
           * landing page with general about info, link to service class
  -- Datastore
           * landing page with general about info, link to service class
  -- Harvest
           * landing page with general about info, link to service class
- Drush commands
- REST API Docs (links to the swagger page)
- React Frontend
- Tutorials
- FAQ
- Glossary
- Contributing: https://docs.chirripo.dev/contributing/

Remove community section
