### ISSUE TITLE
DKAN APIs Help

### ISSUE THREAD

**Issue by AhmedKhater** [GetDKAN/dkan#3247]
HI, I'm working with DKAN Rest APIs for a workflow integrations using the python library pydkan and it's working very well for most of the required functions but there is a function that i don't know how to implement and i hope if you can help me.
I want to attache a remote file to a resource of the dataset, not uploading the file just reference the remote file.
I know how to do this through the admin portal UI but i want to do this by code.​

**Comment by janette** [comment]
@AhmedKhater instead of using 'field_upload' as in [this example](https://github.com/GetDKAN/pydkan/blob/master/examples/attach_file_to_node.py#L18), use 'field_link_remote_file'

**Comment by janette** [comment]
Sorry @AhmedKhater I misspoke, the [pydkan](https://github.com/GetDKAN/pydkan) code does not support remote files

**Comment by rhabbachi** [comment]
@AhmedKhater Unfortunately attaching remote files entry is apparently not supported by the DKAN REST API. The [attache_file](https://dkan.readthedocs.io/en/latest/apis/rest-api.html#add-a-file-to-a-resource) endpoint is using the [`attach_file` feature from the service module](https://github.com/GetDKAN/dkan/blob/7.x-1.x/modules/dkan/dkan_dataset/modules/dkan_dataset_rest_api/dkan_dataset_rest_api.services.inc#L92) which expect a file upload to work. If you manage to work on an improvement you contribution is very welcome!

DKAN 1.x is currently only minimally supported with security patches and critical bug fixes as we are currently shifting our focus to the [next iteration of DKAN based on Drupal 8/9](https://github.com/GetDKAN/dkan/releases). If you are able to use/work with it, you are welcome to give it a whirl and we would be happy to hear about it!

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended
