### ISSUE TITLE
Consider using a bolder font to make it easier to read

### ISSUE THREAD

**Issue by mgifford** [GetDKAN/dkan#3265]
## Describe the bug
There are legibility issues with some of the fonts used in the demo.

![Screen capture of page with National Health Council & Health Care in blue](https://user-images.githubusercontent.com/116832/99097110-283f4a00-25a5-11eb-891f-8cfa2c1e9996.png)

## Steps To Reproduce

Screenshot is from http://demo.getdkan.org/search/

## Expected behavior

Improve the readability by making the font bold.

References:
https://webaim.org/techniques/fonts/
https://webdesign.tutsplus.com/articles/designing-accessible-content-typography-font-styling-and-structure--cms-31934
https://accessibility.psu.edu/legibility/fontface/

## PR
https://github.com/GetDKAN/data-catalog-app/pull/67

**Comment by alexiscott** [comment]
Setting the font weight to "normal" will make a big difference, it's currently set to "300".

It would also make the body font in other places look more readable, in my opinion.

![image](https://user-images.githubusercontent.com/5583342/110141119-21974580-7dd5-11eb-9a77-3b1cca2b64c7.png)

You can see the difference here:
font-weight: normal
![image](https://user-images.githubusercontent.com/5583342/110141826-d29de000-7dd5-11eb-88cc-a8ff389eec6d.png)


Where it was:
![image](https://user-images.githubusercontent.com/5583342/110141390-63c08700-7dd5-11eb-9244-92e3c55ad7bd.png)

**Comment by alexiscott** [comment]
@mgifford Hi!
I see this ticket has been closed, but I don't believe the fix has been made. Just wanted to check in with you as to what should be the status?
Thanks!

**Comment by mgifford** [comment]
It should be re-opened.  This hasn't been fixed yet.

**Comment by alexiscott** [comment]
Add PR: https://github.com/GetDKAN/data-catalog-app/pull/67

@mgifford  This would result in something like this. Let me know if this these Firefox screenshots are acceptable for QA or if you need a review site (currently we only see things on http://demo.getdkan.org/ once QA approved and merged).

![image](https://user-images.githubusercontent.com/5583342/111490142-0f08fe80-873b-11eb-84b4-87059a43896c.png)

**Comment by alexiscott** [comment]
![image](https://user-images.githubusercontent.com/5583342/111490346-3cee4300-873b-11eb-9243-45aef99c9850.png)

**Comment by alexiscott** [comment]
Hi @mgifford 
Given that we do not have a review site process at present, I wonder if it could be a QA option for you editing the CSS in Firefox or Chrome dev tools on http://demo.getdkan.org/ ?
The proposed fix is very basic and would require changing just the weight of the body font from _300_ to _normal_.

```
body {
    background-color: #f9fafb;
    color: #3b3b3b;
    font-weight: 300;
    font-size: 1.6rem;
    font-style: normal;
    font-family: "Rubik","Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
}
```

to 

```
body {
    background-color: #f9fafb;
    color: #3b3b3b;
    font-weight: normal;
    font-size: 1.6rem;
    font-style: normal;
    font-family: "Rubik","Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
}
```

**Comment by mgifford** [comment]
I find this much easier to read.

Before 330 weight:
![DKAN-Demo-Before-300-weight](https://user-images.githubusercontent.com/116832/112007311-f150e600-8afa-11eb-9be7-c10f2d3e7479.png)

Afterwards regular weight:
![DKAN-Demo-After-regular-weight](https://user-images.githubusercontent.com/116832/112007310-f0b84f80-8afa-11eb-8984-4bb9eb5d2377.png)

**Comment by alexiscott** [comment]
Thanks @mgifford !

**Comment by alexiscott** [comment]
@dgading 
I think that we are good to merge https://github.com/GetDKAN/data-catalog-app/pull/67, unless you see any issues with the SCSS code changes?

**Comment by ghost** [comment]
Hi @dgading Could you please review this ticket or let me know when you're planning on reviewing it? Thanks!

**Comment by dgading** [comment]
I think this was updated and can be closed. I merged this here: https://github.com/GetDKAN/data-catalog-app/pull/67

Any other discussion should probably be in the app repo as I don't check this one as much.
