### ISSUE TITLE
Fatal error: Interface 'Contracts\RetrieverInterface'

### ISSUE THREAD

**Issue by Rkedemi** [GetDKAN/dkan#3275]
Every time I install the DKAN2 I get the error below:- 

Fatal error: Interface 'Contracts\RetrieverInterface' not found in D:\wamp\www\drupal88\sites\all\modules\dkan\modules\dkan_schema\src\SchemaRetriever.php on line 11

**Comment by janette** [comment]
@Rkedemi are you using [dkan-tools](https://github.com/getdkan/dkan-tools)? and the latest version of DKAN?
Can you list the steps you are doing. For example:

```
composer install
drush en dkan frontend -y
...
```

**Comment by Rkedemi** [comment]
I have have drupal running on wamp on a widows machine. I have downloaded DKAN and un-packaged it under modules. I have then logged in and tried to enable the dkan modules. It then gives that massage. Please advise

**Comment by janette** [comment]
@Rkedemi there are dependencies that need to be installed so you will need to run `composer update` to get the necessary libraries.
