### ISSUE TITLE
Referenced entities should not generate new entity when modified

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#3282]
This feels like unexpected behavior, and negates usefulness of separating things like resources/distributions into separate nodes.

**Comment by kimwdavidson** [comment]
@dafeder to split into two tickets, assign tickets to @fmizzell and move to To Do.

**Comment by susisiman** [comment]
This may be best to leave as is with node storage and address in entity storage when there is time.

**Comment by dafeder** [comment]
Only practical solution we have for this is #3386. Closing this in favor of that. There may be other ways to handle this and we can make other tickets for them as they come up.
