### ISSUE TITLE
PHP Notice with taxonomy term reference in open_data_schema_map

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#3293]
## Describe the bug
I am experiencing a PHP notice while using a taxonomy term reference field in a multi value field schema mapping - 
`Notice: Undefined index: target_type in open_data_schema_map_endpoint_process_map_recursion() (line 1070 of /var/www/koeln-dkan/profiles/dkan/modules/contrib/open_data_schema_map/open_data_schema_map.module).
`

As far as I can see there is a check for unpublished nodes related to that part of the code. This is not applicable for taxonomy terms.

This is about the [open_data_schema_map module](https://www.drupal.org/project/open_data_schema_map)

## Steps To Reproduce

- Add a multivalue taxonomy term reference field to a dataset
- Use this field in schema mapping (tokens)
- Fill in values for the field in a dataset
- Open the XML/RDF representation of the dataset
- look in drupal watchdog for the notice

## Expected behavior
No notice should be given for taxonomy term reference fields

##Fix
Checkout this merge request for a possible fix: https://github.com/GetDKAN/open_data_schema_map/pull/122

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended
