### ISSUE TITLE
Add support for Twitter Cards and Facebook OpenGraph tags for better social previews

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#33]
Add twitter cards (https://dev.twitter.com/docs/cards) and facebook opengraph tags for better social previews (e.g.: https://twitter.com/chucker42/status/349643948555378688). See implementation example walkthrough here: http://webwash.net/tutorials/display-twitter-cards-drupal-using-meta-tag.... Would involve programming in some good defaults for data pages, so when people share a data page, it looks good.

Connects #1850

**Comment by dafeder** [comment]
Still would be good to do this.

**Comment by dangur** [comment]
May want to use [MetaTag Drupal module](https://www.drupal.org/project/metatag) for Facebook OpenGraph tags.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
