### ISSUE TITLE
DKAN site for Urban Institute: https://datacatalog.urban.org

### ISSUE THREAD

**Issue by DouglasMurray** [GetDKAN/dkan#3317]
Hello
The Urban Institute has launched a DKAN site for our public datasets, 47 at last count are available on https://datacatalog.urban.org .  The site was launched publicly in September 2019; details are available in this Medium post: https://urban-institute.medium.com/announcing-the-urban-institute-data-catalog-ce2c787e38e9 

It would be great if you could include us on your list of DKAN instances. For any further information you might need, please contact me: Douglas Murray (dmurray@urban.org) or Graham MacDonald (GMacDonald@urban.org)

Thanks!
Doug Murray

**Comment by janette** [comment]
Congrats @DouglasMurray the site looks great! I've added you to the list of DKAN instances https://getdkan.org/community/

**Comment by DouglasMurray** [comment]
thanks! much appreciated!
