### ISSUE TITLE
Add facet API for resources 

### ISSUE THREAD

**Issue by sediqamousavi** [GetDKAN/dkan#3324]
We need to filter resources of a dataset based on year as we filter Datasets based on tags, topics...
Is it possible with search API?
We need to add a Facet API: Search service: resource: year block to view
this filter is possible for datasets:
![Screenshot (77)](https://user-images.githubusercontent.com/43989585/105629206-4952cf80-5e5f-11eb-9b56-938f1c07e45a.png)

**Comment by dafeder** [comment]
Closing as support for DKAN 1.x has ended
