### ISSUE TITLE
Warning on dataset creation:  in_array() expects parameter 2 to be array, null given in dkan_dataset_groups_og_role_grant()

### ISSUE THREAD

**Issue by Julian-Held** [GetDKAN/dkan#3334]
Whenever we create a dataset or add a resource, after pressing the save button dkan shows the following warning:
`Warning: in_array() expects parameter 2 to be array, null given in dkan_dataset_groups_og_role_grant() (line 471 of /var/www/dkan/profiles/dkan/modules/dkan/dkan_dataset/modules/dkan_dataset_groups/dkan_dataset_groups.module).`

The new dataset or resource is still created successfully.

I already searched around in the code. I'm not very familiar with PHP but from what I can tell, the warning is caused by
`if (in_array('content creator', $user->roles)`
in which `$user->roles` does indeed seem to be null, because $user seems to be empty. The variable is created as:
`$user = user_load($uid);` I checked `$uid`, which contains a number (which I assume is correct), so it seems `user_load()` is broken for me. That's surprising to me, because I would guess that if `user_load() ` was always broken, then large parts of the dkan instance shouldn't work, which is not the case.

The only other thing that gets logged is a notice for my user:
`Notice: Trying to get property 'uid' of non-object in user_access() (line 818 of /var/www/dkan/modules/user/user.module).`
No idea if that is connected at all.

Any hints on how I can try to track down the issue?

- Drupal 7.78
- dkan-7.x-1.18.15 (via dkan-drops-7)
- mysql 8.0.22
- PHP 7.3.26
- ubuntu 20.04
- apache 2.4.41

**Comment by kimwdavidson** [comment]
possible duplicate of #3355, will investigate

**Comment by jtallantumich** [comment]
@mimurrayy Have you made any headway with issue? We're experiencing a very similar issue.

**Comment by Julian-Held** [comment]
We just updated to 7.x-1.18.16 (dkan-drops-7) and that fixed the problem for us.
