### ISSUE TITLE
Generalize data storage for metastore to not be node-specific

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#3339]
A whole bunch of the magic exists in this class, problem is that class is not connected to Drupal, it's triggered by our API directly. Any code that exists in that class will have to be replicated or we need to figure out if there is a way we can move it into the Drupal realm. or maybe separate buisiness logic from storage logic.

In the Data class, a lot of node logic lives in "store" method. Create a new storage interface that's injectable/swappable, to replace Data class and SAE. 

We also want to make sure that there is no business logic that should live in the hooks so that is trapped in the storage class.

## Task
- [x] Abstract data storage and related classes and create interfaces so we can swap node and custom entity

**Comment by ghost** [comment]
Hi @dafeder  Could you please review this ticket or let me know when you're planning on reviewing it? Thanks!

**Comment by ghost** [comment]
@sussimsua Should we continue tracking this ticket in the Support board? It's been in Code Review for a month.

**Comment by ghost** [comment]
From Susana in Slack: We can drop it from the support board.

**Comment by dafeder** [comment]
Being done as part of #3321, closing this ticket for now.
