### ISSUE TITLE
Spike: API calls to public endpoints fails with Authorization header

### ISSUE THREAD

**Issue by rhabbachi** [GetDKAN/dkan#3348]
## Describe the bug
Calling a public DKAN endpoint with the Authorization header returns 403 Forbidden. It does not matter if the Authorization is correct or not.

## Steps To Reproduce
1. Have a target site with DKAN installed.
2. Call a public endpoint (for example /api/1/metastore/schemas/dataset)
```sh
$ curl --location --request GET "$(dktl url)/api/1/metastore/schemas/dataset" \
--header 'Accept: application/json' \
--header 'Authorization: Basic c3VzYW5hLnNpbWFuOnN1c2FuYS5zaW1hbg=='
```
## Expected behavior
Calling public APIs should not fail when any form of authorization is used.

**Comment by dafeder** [comment]
No longer an issue
