### ISSUE TITLE
Spike: /api/1/search API bug when publisher have comma in the name

### ISSUE THREAD

**Issue by rhabbachi** [GetDKAN/dkan#3364]
# Description
/api/1/search returns publisher facets with the correct number of datasets associated but fails to returns those datasets when the publisher name contain a comma.

When a publisher name contain commas, the APIs should return the correct 

# Acceptance Criteria
- Document approach

# Estimate: 5

**Comment by ghost** [comment]
Nikolay is blocked because he needs help with tests from Gerardo.
