### ISSUE TITLE
Local file trasher option

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan#3365]
## User Story: 
Data files live on a storage system, and data managers don't need them both in DKAN and in that system, so once the data is in the datastore, DKAN no longer needs to store the file as well. Not storing the file reduces space issues and strain on the system. 

When an import has been completed, delete the file from the local resources folder, and remove the localized "perspective" of the resource for the database.

This should be an optional behavior that is off by default, and can be enabled through an admin form.

## Acceptance Criteria:
If the behavior is enabled,
- If I create a dataset with a remote file there is no local copy of the file after the datastore is complete. The download link continues to point to the remote file.
  - In above scenario, the filefetcher job record is also deleted
  - local_file and local_url records are also deleted from the resource mapper table
- If I create a dataset with an uploaded file there is no duplicate file of the dataset after a datastore is complete

If the behavior is not enabled,
- Files remain in the file system as they do now. 
- Download links point to the localized file URL.

## Estimate: 
5 days

**Comment by janette** [comment]
suggested AC modifications


## Acceptance Criteria
If the option is enabled:
- If I create a dataset with a **remote** file:
    * The local copy of the file from sites/default/files/resources/... is removed after the datastore is complete. 
    * The download link continues to point to the remote file.
    * The jobstore_filefetcher_filefetcher record is deleted
    * local_file and local_url records are deleted from the resource mapper table
- If I create a dataset with an **uploaded** file:
    * The local copy of the file from sites/default/files/resources/... is removed after the datastore is complete. 
    * The file located at sites/default/files/uploaded_resources/ remains and is the source of the download link

If the option is not enabled (i.e. current behavior):
- If I create a dataset with a **remote** file:
    * Files remain in the file system as they do now. 
    * The download link continues to point to the remote file.
- If I create a dataset with an **uploaded** file:
    * The file located at sites/default/files/uploaded_resources/ is the source of the download link
