### ISSUE TITLE
Use RootedJsonData for validation in metastore service

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#3372]
Code to be adjusted:
- [x] metastore_search. Facets adjusted to RootedJsonData
- [x] Drupal\Tests\metastore_search\Unit\SearchTest
- [x] Drupal\Tests\metastore_search\Unit\Plugin\search_api\datasource\DkanDatasetTest::test
- [x] Drupal\Tests\datastore\Service\ResourcePurgerTest
- [x] Drupal\Tests\harvest\Load\DatasetTest
- [x] Drupal\Tests\json_form_widget\Unit\SchemaUiHandlerTest
- [ ] Consider using RootedJsonData in Storage 'retrieve'-like methods

Estimate: 1 day

**Comment by ghost** [comment]
Nikolay expects this to be done in 2 days.

**Comment by ghost** [comment]
Nikolay should put this ticket aside and help Riadh with metastore work (Chadia and Susana will assign him the tickets), then review testing on #3372 with Dan after he comes back from vacation.

**Comment by ghost** [comment]
@sussimsua Removing this from our Support board as well.
