### ISSUE TITLE
Improve Helptext on Metadata Form

### ISSUE THREAD

**Issue by ghost** [GetDKAN/dkan#3374]
As a data publisher, I want to have better descriptions on what the fields are so that I can better fill them out when adding datasets.

Note: Helptext will be based off research from UX work on the data.gov metadata form and Stefanie's research for St Lucia

Acceptance criteria:
- Description matched information in the Figma spreadsheet below.
https://www.figma.com/proto/klRVVF5U6fFmDbiu3s6L3g/Metadata-Form?node-id=730%3A0&scaling=min-zoom

https://docs.google.com/spreadsheets/d/1ejsxggxtdph_MqSiImzY95g8RmbB3fTjATQ08fK19Bo/edit?usp=sharing

**Comment by dharizza** [comment]
@cmugisha not sure what to do about this ticket, I think a lot of other tickets were created to cover this one up. Not sure if we should close this one and just add links to the other tickets here.

**Comment by ghost** [comment]
@dharizza You're right. I'm seeing some of the form tickets we documented have a helptext aspect to them, so I will close this one. Cc: @sussimsua
