### ISSUE TITLE
How to install dkan

### ISSUE THREAD

**Issue by ugintl** [GetDKAN/dkan#3402]
I want to install dkan for D8 or 9, but I did not find anything about how to do it. I do not want to install it on an existing site.

**Comment by fmizzell** [comment]
@ugintl https://demo.getdkan.org/modules/contrib/dkan/docs/start.html

**Comment by ugintl** [comment]
I have already visited this link. From this link "**Starting a new project**

Follow the instructions on the DKAN Tools README to generate new Drupal site with DKAN installed on your system." I also followed **DKAN tools readme** link, but no guidance there as well. I am missing something?

**Comment by janette** [comment]
@ugintl add DKAN to your site with 

```
composer require 'getdkan/dkan'
composer update
```

This will add DKAN to your project and install all dependencies.

**Comment by nmichalakis** [comment]
Hi, i cant install dkan 2 in a new drupal 8.9.14 website.
composer require 'getdkan/dkan' or composer require 'getdkan/dkan:2.10.1' fails.
Please advice. 
Thank you.
![Screenshot 2021-04-27 at 17 06 41](https://user-images.githubusercontent.com/25632631/116255635-1b8d6780-a77b-11eb-88cd-56779d391365.jpg)

**Comment by janette** [comment]
@nmichalakis did you make the changes to your composer.json file listed in the [release notes](https://github.com/GetDKAN/dkan/releases/tag/2.10.0)?

**Comment by nmichalakis** [comment]
@janette thank you! that was it. I updated the composer.json as described  in the release notes (https://github.com/GetDKAN/dkan/releases/tag/2.10.0) and then composer require 'getdkan/dkan'.

**Comment by luisgil06** [comment]
How can I install Dkan 2.13.10 ?

Thanks in advance.

**Comment by tridoxx** [comment]
@nmichalakis  hi you did it work?

**Comment by nmichalakis** [comment]
@tridoxx sorry no.

**Comment by paul-m** [comment]
The real solution, for a new DKAN site, is to use the `getdkan/recommended-project` metapackage which you can read about here: https://dkan.readthedocs.io/en/latest/installation/index.html#starting-a-new-dkan-project

To add DKAN do your existing site, you'll need to modify your composer.json to include asset-packagist, as outlined here: https://github.com/GetDKAN/dkan/releases/tag/2.10.0

Then you should be able to say `composer require getdkan/dkan -W`.
