### ISSUE TITLE
Referencer changes

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#3429]
## User story

Distributions, or any other referenced metastore item, should be independently editable. This should work both through the drupal edit form and the API (updating a distribution object directly).

## Implementation

1. Store any referenced item similarly to datasets -- don't wrap the metadata in a {"identifier", "data"} object but use standard DCAT-US or equivalent schemas at the root level. This happens in the `Referencer::createPropertyReference()` method. (#3450)
2. We should not be using Drupal node or entity storage in the Referencer, we should use DKAN storage directly. (#3454)
3. We should create explicit hash storage and retrieval methods in the storage clases. Nodes are storing hashes in the title, Metastore Entity will store hashes in a separate field (this field needs to be implemented but that's outside scope of this ticket). (#3465)
4. Update sub-schema files to lost the "data" wrappers (#3450)

Estimate: 5 days

**Comment by ghost** [comment]
We will break down this ticket into 3:
#3450 
#3454 
#3465

**Comment by dafeder** [comment]
No longer needed, everything except #3450 is complete.
