### ISSUE TITLE
Start implementing "behaviors" to trigger ResourceMapper

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#3430]
User Story:

Acceptance criteria: 

Estimate: 2 days

**Comment by ghost** [comment]
Dan to add a description to this ticket.

**Comment by ghost** [comment]
@dafeder and @dharizza to meet today to refine this ticket so that Dharizza can pick it up tomorrow.

**Comment by dafeder** [comment]
We never implemented this - was essentially #3552. Unclear if there would still be value in more abstracted "behaviors" assigned to schemas or schema properties but closing this issue as it never picked up steam.
