### ISSUE TITLE
Bug: Datastore import fails when manually creating datasets

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#3443]
## Steps to reproduce
- Create a dataset at `node/add/data`
- Run `drush queue:run datastore_import`
- Confirm output is `Processed 0 items from the datastore_import queue in 0.01 sec.`
- Seems to be a missing step on node creation, only the source perspective is present in the dkan_metastore_resource_mapper table

![issues](https://user-images.githubusercontent.com/314172/116310448-a4060b00-a76f-11eb-950a-a37e18b269f9.png)

User Story:

Acceptance criteria: 

Estimate: 2 days

**Comment by ghost** [comment]
Janette and Gerardo to try and find this issue and they will document their findings in this ticket.
