### ISSUE TITLE
Update Swagger Document API

### ISSUE THREAD

**Issue by ghost** [GetDKAN/dkan#3471]
## Due date:
June 2nd

## Description: 
The purpose of this ticket is to document the API changes, all of which we will use for the user training, as well as help desk support.

## Acceptance Criteria: 
All API changes will be well documented. The documentation will be linked within this ticket and also on Confluence. It will be peer-reviewed. And it will also be reviewed by a non-technical person like Heidi

## Estimate: 
5

**Comment by cmugisha** [comment]
Nikolay and Dan will pair on this.
