### ISSUE TITLE
Hide record number from DKAN

### ISSUE THREAD

**Issue by ghost** [GetDKAN/dkan#3474]
## Due date:
June 2nd

## Acceptance Criteria: 
Upon completion of this work, the Agent/Broker Tracker data will hide the record number from DKAN

## Description: 
The work involved in this ticket is as follows:
A/ front end: hiding the record number in the preview (i.e., dropping column)
(not required with DKAN 3441)
B/ back end: CSV download would need to
This ticket coincides with DKAN 3441 (back end fix)

## Estimate: 
1

**Comment by klimp-drupal** [comment]
Closing the issue. The PR https://github.com/GetDKAN/dkan/pull/3505 is merged
