### ISSUE TITLE
Empty distribution node creation when nothing is submitted for distribution

### ISSUE THREAD

**Issue by akaroleff** [GetDKAN/dkan#3501]
## User Story
As an authenticated user, I should not see ghost distributions in my content list.

## Acceptance Criteria
1. log in as an authenticated user
2. create a dataset without a distribution and save
3. visit admin/content
4. confirm that you do not see an empty distribution node

## Estimate
1 day 

## Due
Not a priority, it does not block other work, it is unlikely someone would create a dataset without a distribution but it would be bad practice to not address this possibility.

**Comment by akaroleff** [comment]
Needs the following @janette.day
Repo location review & edit
User story fleshed out
A/C fleshed out
Story points
Due date & what it blocks

**Comment by dafeder** [comment]
Might be a referencer bug but more likely something to do with the form logic. Will investigate.
