### ISSUE TITLE
Dataset with & in title displays as &amp;

### ISSUE THREAD

**Issue by akaroleff** [GetDKAN/dkan#3525]
## User Story
As an anonymous user, I should see an "&" on a dataset page title when it is used instead of "&amp"

## Acceptance Criteria
1. visit a dataset page that uses "&" in the title as an anonymous user 
2. the title on the dataset page uses "&" properly and not "&amp;"

## Estimate
1 day 

## Due
TBD

**Comment by dafeder** [comment]
Need to do a bit of debugging to figure out every place where a string might be getting sanitized like this and see if it's feasible to at least remove HTML entities on the way out. In the meantime, recommend title-specific fix on the front end.
