### ISSUE TITLE
Confirm timestamps match between post request data and update date

### ISSUE THREAD

**Issue by akaroleff** [GetDKAN/dkan#3532]
### User Story
Timestamps should match between post request data and update date.

Timestamps were not matching during, i.e., the update date does not match the post request date. May 31 and June 1 were the two stamps show. The work in this ticket is to confirm if it was an actual bug or else an anomaly due to proximity to midnight. 

### Story Points
1

**Comment by dafeder** [comment]
This is primarily an upstream issue and should also be helped by #3545
