### ISSUE TITLE
Tech Spike: Ability to append or edit a dataset and instead of file overwrite to update data

### ISSUE THREAD

**Issue by akaroleff** [GetDKAN/dkan#3535]
### User Story
As an API user, I want to be able to append or edit a dataset instead of only overwriting the data when I want to update the data. 

Currently: DKAN Core cannot append or edit a dataset and instead relies on a file overwrite to update data. 

The work involved in this ticket (requiring refinement) is to outline the technical details to be able to 
* edit existing datasets
* append existing datasets

### Story Points
2

### Due
TBD

**Comment by dafeder** [comment]
Iceboxing for now. The mysql import is so fast that this seems less urgent now, and have some new doubts about the overall desirability of this.
