### ISSUE TITLE
Dataset dasboard separate from harvest dashboard

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#3538]
We have some very useful interfaces in the harvest_dashboard module, but the importer status stuff is not available for datasets outside of harvests.

To improve visibility of import status let's:

1. Separate the Harvest Dashboard main page and the Harvest-specific page into two sepratate menu items. We will have a new page called "Datastore Import Status", with filters including "harvest." Move the Code for this page into the datastore module.
2. Fix the links in the harvest dashboard and make sure they go to the right place. Move the harvest dashboard code into the main harvest module and start phasing out the harvest_dashboard module.
3. We should make this information easier to find via the API, in a way that more closely resembles the dashboard. Propose and addition to or modification of the datastore API in another ticket.

**Comment by susisiman** [comment]
On @klimp-drupal queue. Low priority.

**Comment by dafeder** [comment]
Known issue: needs helptext on the pages and content in the central documentation. Creating new ticket stub for that.
