### ISSUE TITLE
SQL query execution returns an error instead of a payload

### ISSUE THREAD

**Issue by akaroleff** [GetDKAN/dkan#3542]
### User Story
...SQL query execution returns an error instead of a payload

### Story Points 
2

### Due
7/2/2021

**Comment by dafeder** [comment]
This was due to working with a dataset that had one column with an uncommon amount of data in it -- trying to do a SELECT without a limit exhausted PHP memory. Not clear how we might make this fail more gracefully in the future but as an edge case, closing for now.
