### ISSUE TITLE
Handle long column names in MySql importer

### ISSUE THREAD

**Issue by susisiman** [GetDKAN/dkan#3544]
## User Story: 
Tables with column names larger than 64 characters will not import.  We need to look into how the default importer handles long column names and replicate that for MySql. The MySql importer should mimic what the default importer does when creating column names. 
 
## Acceptance Criteria: 
I can add a table with a column name of 70 characters long and it will work the same whether I use default or MySql importer. 

## Estimate: 
1/2 day for investigation

**Comment by dharizza** [comment]
This work is done in #3515, fixed with [this](https://github.com/GetDKAN/dkan/pull/3515/commits/493fbcead55f26162cf6db14af564a63c70ea52d) commit.
