### ISSUE TITLE
Prevent bad downloadURL from breaking site

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#3550]
## Describe the bug
There is no protection against a dataset having an unusable remote file.

## Steps To Reproduce
Create a dataset with a bad remote file url.
Run the datastore_import queue
Run cron

```
[error]  TypeError: Argument 1 passed to Drupal\datastore\Service\ResourceLocalizer::getFileFetcher() must be an instance of Drupal\common\Resource, null given, called in /mnt/www/html/openpayments/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourceLocalizer.php on line 51 in Drupal\datastore\Service\ResourceLocalizer->getFileFetcher() (line 159 of /mnt/www/html/openpayments/docroot/modules/contrib/dkan/modules/datastore/src/Service/ResourceLocalizer.php)
```
if you adjust the ResourceLocalizer.php to

![resourcelocalizer](https://user-images.githubusercontent.com/314172/124970578-b4e3c000-dfed-11eb-96ed-038f2cc8b1ab.png)

you then get an error further up the stack
```
Error: Call to a member function getStatus() on null in Drupal\datastore\Service->getResource() (line 150 of /mnt/www/html/openpayments/docroot/modules/contrib/dkan/modules/datastore/src/Service.php) 
```
## Expected behavior

If a dataset is created with a remote file that does not return an actual file, handle it gracefully. Running cron should not cause the site to go down.

**Comment by dafeder** [comment]
Recent merges to 2.x may have remediated this issue. @janette to test the site where this was observed against a new 2.x build.
