### ISSUE TITLE
DKAN delivers appropriate HTTP cache headers

### ISSUE THREAD

**Issue by akaroleff** [GetDKAN/dkan#3558]
### User Story
DKAN is [returning the page directly via a Symfony response](https://github.com/GetDKAN/dkan/blob/2.x/modules/frontend/src/Controller/Page.php) rather than a page array (which is the part that contains cache tags/contexts and makes it cachable by Drupal core) or other higher level API that would enable Drupal to set appropriate HTTP headers.

This is occurring on frontend pages as well as /api responses, and perhaps other endpoints also - we should validate that all DKAN pages can be cachable.

### Notes

DKAN will need to switch the implementation to use either:

1. [Drupal's CacheableResponse](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Cache%21CacheableResponse.php/class/CacheableResponse/8.2.x) instead of a vanilla Symfony response - this is the ideal method (especially for the API routes) as it would allow longer cache expiration times since cache tags can be used to enable efficient invalidation (including of the Akamai cache, which supports cache tags) when datasets are updated.

2. [Implement it's own cache headers using](https://symfony.com/doc/current/components/http_foundation.html#managing-the-http-cache|https://symfony.com/doc/current/components/http_foundation.html#managing-the-http-cache) - this is simpler to implement, but doesn't offer easy options for cache invalidation, so would likely necessitate shorter cache expiration times for resources that change frequently.

I did a quick test by adding this to the DKAN frontend [Controller/Page.php](https://github.com/GetDKAN/dkan/blob/2.x/modules/frontend/src/Controller/Page.php) linked above and confirmed that this does add cache headers: 

```
 $response = Response::create($pageContent);
 $response->setCache([ 
 'public' => true, 
 'private' => false, 
 'max_age' => 600, 
 'last_modified' => new \DateTime(), 
 ]);
  $response->setVary('Cookie');
 return $response;
```

This isn't an ideal fix on it's own however, it doesn't include an etag or useful last_modified date - nor deal with cache invalidation using the Acquia/Akamai modules (hence the short max_age) - it also doesn't fix other routes like /api that have the same issue.

We should include Drupal config to enable/disable caches (disabled by default in DKAN core) and set expiry

### Story Points 
1

### Due 
07/14/21

**Comment by grugnog** [comment]
@klimp-drupal been working on debugging this a bit and happy to talk you through the problem and review PRs etc. The plan is to go with approach 2 (just adding direct headers) for now, and reevaluate using approach 1 (or something like it) later on, especially for the API where cache invalidation is more important.
