### ISSUE TITLE
PHP 7.4 compatibility testing

### ISSUE THREAD

**Issue by susisiman** [GetDKAN/dkan#3560]
User Story: 

- Acquia is mandating an update in october, and general people are using PHP 7.4, I don't want to site to go down  and want to support PHP 7.4 

Note: 

- Research best practices on CI and testing PHP upgrades 

Acceptance Criteria: 

- DKAN throws no error on PHP 7.4 or 7.3  
- Is backwards compatible to whatever the minimum drupal php requirement is

**Comment by grugnog** [comment]
I think this is probably resolved by #3446
