### ISSUE TITLE
Helptext improvement for Download URL field 

### ISSUE THREAD

**Issue by susisiman** [GetDKAN/dkan#3561]
## User Story 

The current helptext for Download URL field is confusing users as it's based on a metadata definition.  The field UI and phrasing should following UX best practices. 

## Acceptance Criteria 
- Change  the label of the distribution fieldset from "Project Open Data Distribution" to "Data File"
- Change the **distribution** description to: "A distribution is a container for the data object. Each distribution should contain one accessURL or downloadURL. When providing a downloadURL, also include the format of the file."
- If possible move the distribution description to the top of the fieldset.
- Change the data file **title** description from "Human-readable name of the distribution" to "Human-readable name of the file"
- Change the data file **description** description from "Human-readable description of the distribution" to "Human-readable description of the file"
- On the downloadURL field, change "Upload File" to "Upload Data File", and change "Remote File URL" to "Link To Data File"
- On the upload option can we display the max upload size?

**Comment by dharizza** [comment]
Work done in https://github.com/GetDKAN/dkan/pull/3642
Some notes:
- About `If possible move the distribution description to the top of the fieldset.` there is a bug in Drupal related to this, I tried putting all the description at the top but for the fieldsets and date fields it doesn't work, in theory we can do it by setting up  the description_display to before, like `$element['#description_display'] = 'before';` but it is being ignored, according to https://www.drupal.org/node/3143489 it is fixed on Drupal 9.3.x but we're still locked in 9.1 so can't fix it yet (we could create our templates to avoid having it fixed at the bottom but that would need to be a case by case fix).
- About `On the upload option can we display the max upload size?` it is possible, we would only need to define the upload validator similar to this: `$element['#upload_validators']['file_validate_size'][] = 25600000;`, we can do it in the WidgetRouter class in the handleUploadOrLinkElement function, I don't know what is the right size, also believe we could make this configurable but we would need to validate against the general max size allowed and I was having issues with that part locally. Decided not to do it yet to discuss with team.
