### ISSUE TITLE
Bug: metadata form breaks when javascript aggregation is enabled

### ISSUE THREAD

**Issue by susisiman** [GetDKAN/dkan#3562]
Check libraries to see if jquery or some other dependency need to be added 
https://github.com/GetDKAN/dkan/blob/2.x/modules/json_form_widget/json_form_widget.info.yml 

## Steps to Reproduce 
- Turn on javascript aggregation 
- Confirm multi-select fields are breaking (theme, tags, publisher) 
- Examine consule and ensure that no other fatal errors are happening 
- Bonus: enable Claro and repeat

**Comment by dharizza** [comment]
Tested this with latest DKAN 2.x in Drupal 9.0.14 and 9.2.1, with CSS and JS aggregated (separated and then both aggregated at the same time), old local installation and fresh installation, using Bartik as admin theme and also using Claro but every time the console is clean, the form is submitted correctly, and fields are working properly (can create new items, select existing ones, remove selected options).

I also tested in the demo site and things look okay (though the demo site has a lot of issues if CSS is aggregated not sure why, but with just JS aggregated it works okay).

Only thing I noticed is when Claro is enabled the upload_or_link "widget" doesn't load properly, the upload element appears before the checkboxes (this happens even without aggregation, only when using Claro, haven't been able to fix yet). 

Apart from that I couldn't replicate the issue reported here. Please provide more test steps and info about the version where this error is occurring.

**Comment by janette** [comment]
Thank you for checking Dharizza, turns out this is a downstream issue due to the use of 'edit' domains that are different than the public domain and we have a CORs strict-origin-when-cross-origin issue.
