### ISSUE TITLE
Drupal 9.2 support

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan#3615]
Get tests passing on Drupal 9.2.x.

**Comment by thierrydallacroce** [comment]
First, I created a branch/draft PR here: https://github.com/GetDKAN/recommended-project/pull/4

Then I modified my local DKTL to make use of the above branch, like so:
``` 
     private function drupalProjectCreate()
     {
-        $projectSource = "getdkan/recommended-project:9.x-dev";
+        $projectSource = "getdkan/recommended-project:dev-drupal-9.2";
         $createFiles = $this->taskComposerCreateProject()
```

**Comment by thierrydallacroce** [comment]
Then I started on DKAN branch https://github.com/GetDKAN/dkan/pull/3604.

Worked though fixing a few things and unit tests. Apparently, having depreciation notices fails the overall unit tests, even if each unit test passes. At first there were 497, I got it down to 90.

Currently, I'm a bit unsure how to progress if we're keeping 8.9 compatibility until November 2021.
