### ISSUE TITLE
Fix `NULL` being used by default instead of "none" option in `triggering_properties`

### ISSUE THREAD

**Issue by clayliddell** [GetDKAN/dkan#3622]
## Describe the bug
Encountered this error when creating a dataset without "Dataset properties" set under **DKAN** > **Metastore referencer**:
```
Warning: array_filter() expects parameter 1 to be array, null given in Drupal\datastore\EventSubscriber\DatastoreSubscriber->onPreReference() (line 179 of modules/contrib/dkan/modules/datastore/src/EventSubscriber/DatastoreSubscriber.php). 
```

## Steps To Reproduce
Create a dataset without "Dataset properties" set under **DKAN** > **Metastore referencer**.

## Expected behavior
This warning should not occur.

**Comment by dafeder** [comment]
Could not reproduce; appears to no longer be an issue
