### ISSUE TITLE
Enhance realated documents field to allow link text

### ISSUE THREAD

**Issue by janette** [GetDKAN/dkan#3633]
## User Story
When I add related document links to my dataset I would like to provide nice human readable text to inform the user what they are clicking on rather than just displaying the URL which may not be clear at all what it leads to.

## Acceptance Criteria
As a data publisher I can add related document links and provide custom text as the link text.

**Comment by dafeder** [comment]
I think the way to address this is just in the schemas for individual sites. If we want we can create a sort of enhanced DCAT-US module once we ship #3761 that includes a field for this, but that it not overlap with any existing properties in DCAT-US 1.1. 

According to the [DCAT-US 3.0 documentation](https://doi-do.github.io/dcat-us/#properties-for-dataset), `page` or `documentation` might be appropriate properties, and they do provide a vocabulary for a "document" object. As is often the case for RDF classes the docs are a little difficult to translate into a schema, but I think it would look something like this:

```json
{
  "documentation": [
    {
      "@type": "foaf:Document",
      "homepage": "http://example.org/docs/mydoc",
      "title": "My document title"
    }
  ]
}
```

The [DCAT-US 1.1 context](https://resources.data.gov/schemas/dcat-us/v1.1/schema/catalog.jsonld) already includes the `foaf` vocabulary and the properties for `foaf:homepage` and `dc:title`.

**Comment by dafeder** [comment]
@janette can you close this if this seems to satisfy the use-case/user story?

**Comment by TheETupper** [comment]
@janette create a JIRA ticket for CMS site component

**Comment by janette** [comment]
Done.
