### ISSUE TITLE
Lexical error 

### ISSUE THREAD

**Issue by walinchus** [GetDKAN/dkan#3638]
Trying to get data from here: https://data.cms.gov/data-api/v1/dataset/9840e2af-7398-43f7-9693-2f8b6ba27be1/data?limit=996113

This works fine:

```
>library(dkanr)
> dkanr_setup(url = 'https://data.cms.gov')
> dkanr_settings()
<dkanr settings>
  Base URL:  https://data.cms.gov 
  Cookie:  
  Token:  
```

## But then I get an error
`resp <- list_nodes_all(filters = c(type = 'dataset'), as = 'df')`
**Error: lexical error: invalid char in json text.
                                       <!doctype html><html lang="en">
                     (right here) ------^**

**Comment by janette** [comment]
@walinchus try asking here: OEDAUserResearch@cms.hhs.gov
