### ISSUE TITLE
A single dataset can be imported multiple times by the same queue job

### ISSUE THREAD

**Issue by clayliddell** [GetDKAN/dkan#3639]
## Describe the bug
Due to a bug in the implementation of the `\Drupal\Core\Cron` service, a queue item is only ever leased for 1 second (there's a Drupal Core issue to resolve this [here](https://www.drupal.org/project/drupal/issues/2893933)).
This can be a problem if a single dataset takes too long to import and a second instance of the `\Drupal\Core\Cron` service is run on another thread, since it could result in an attempt being made to import the same dataset twice. In such a case, a datastore could be polluted with duplicate data from the dataset file.  

## Steps To Reproduce
1. Create a new dataset with a large resource file (>= 100 MB).
2. Run cron using Drush (`drush cron`).
3. Run another instance of cron using Drush (`drush cron`).
4. Wait until both cron jobs have completed.
5. Observe duplicate rows in the imported dataset.

## Expected behavior
A single `datastore_import` queue job should only ever be run once.

**Comment by clayliddell** [comment]
It seems the best way of handling this may be to just prevent the `datastore_import` job from being run by cron, and instead setup a separate system cron job to run the `datastore_import` queue using Drush.

The `drush queue:run` command has better facilities for preventing multiple concurrent cron instances from attempting to process the same jobs.

We will need to add drush as a dependency to DKAN if we take this approach. We will also need to add a "Setup" section to the DKAN documentation for setting up a cron job for processing the `datastore_import` queue.

**Comment by dafeder** [comment]
Holding off till tested on Acquia

**Comment by clayliddell** [comment]
Successfully tested on Acquia. Passing back to review.

**Comment by dafeder** [comment]
I am reopening this because I believe this needs to be noted in DKAN documentation.

**Comment by dafeder** [comment]
Added docs PR. @clayliddell please review and merge/close if that makes sense.

**Comment by clayliddell** [comment]
It seems I made a mistake, closing this ticket prematurely. A lease time still needs to be added to the `datastore_import` queue (hence the above PR).
