### ISSUE TITLE
Creating 2 datasets where the distribution has identical JSON causes them to share the same distribution

### ISSUE THREAD

**Issue by grugnog** [GetDKAN/dkan#3648]
## Describe the bug

Having this happen is confusing to end users as if they later directly edit the shared distribution it will affect both datasets.
This is also a rich source of potential edge cases and other bugs.

## Steps To Reproduce

- Create dataset A
- Create dataset B with a distribution title/format/URL that is identical to dataset A
- Observe that only 1 distribution is created and that this distribution is referenced by both dataset A and B

## Expected behavior

Each dataset should have distinct distributions.

## Notes

This may be caused by the distribution JSON being used as a seed for the distribution UUID generation, in which case this could be resolved simply by switching to regular time based UUIDs.

**Comment by dafeder** [comment]
This seems to not be a problem since #3662. Closing.
