### ISSUE TITLE
Drush dkan-datastore:import Waiting

### ISSUE THREAD

**Issue by mahmudinashar** [GetDKAN/dkan#3652]
Hi all, im new in dkan (and drupal). I just use dkan for a goverment to provide some open data and information to public.

I face some difficulties to check the progress of dkan import datastore.

What i do is :
1. **drush dkan-datastore:list**, it say "waiting". But it's to long.
2. I check through database, it say : status : error
3. 1 check in **drush queue:list** , there is no queue in list.

```
`The same file tested in my local, running well and csv success parse to the database, but why not in prod`.
```

4. I compare through **drush core:status**, both production and local is same (use same php 7.4, drupal 9.1.1 and same drush 10.5).

5. I do **drush dkan-datastore:import**, no output/no error, but the status l of importing is still waiting.

this is the file [https://filebin.net/5yh0ezwvaicf6dk5](url)
this is the json that send to insert dataset via API :
`{
  "@type": "dcat:Dataset",
  "identifier": "3f64265aa-31b47f27e-82db489ec-144d5",
  "title": "Lorem Ipsum",
  "description": "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit",
  "keyword": [
    "PDPB",
    "TPS"
  ],
  "theme": [
    "Adhoc"
  ],
  "accessLevel": "public",
  "issued": "2021-09-02",
  "modified": "2021-09-02",
  "publisher": {
    "@type": "org:Organization",
    "name": "Tekmas"
  },
  "distribution": [
    {
      "@type": "dcat:Distribution",
      "name": "test_csv",
      "status": "done",
      "downloadURL": "https://opendatadev.kpu.go.id/sites/default/files/files/1077dac30d8ba676b8960c6a62aea742.csv",
      "mediaType": "text/csv",
      "format": "csv",
      "title": "test_csv",
      "url": "https://opendatadev.kpu.go.id/sites/default/files/files/1077dac30d8ba676b8960c6a62aea742.csv"
    }
  ]
}`

Ask,
1. What's the problem ?
2. Correct way to check or step to trace the process of import data(csv).
3. For example datastore name is **datastore_6862ggsjHgj72837383**, where does the name come from, and where (table) that show connection between dataset - query - datastore 

Thanks for all your help!
@fmizzell @dharizza

**Comment by dafeder** [comment]
Sorry @mahmudinashar I must have missed this. Is this still an issue?

**Comment by t2wang** [comment]
I'm facing the same problem. I know this is an old issue. Any possible updates on this?

**Comment by WaudoDavid** [comment]
Hello @t2wang, am curious to understand where you able to deploy dkan without ddev? If so I'd be happy if you let me know how. Am just learning on how to use it.

**Comment by t2wang** [comment]
Hi @WaudoDavid, I don't think I've ever deployed DKAN without ddev. I'm only following instructions listed out by the DKAN installation page.

**Comment by WaudoDavid** [comment]
@t2wang what about customization is it running as local. Also is your db the default one it comes with?

**Comment by WaudoDavid** [comment]
Am trying to use it in production and I understand ddev is for local deployments only @t2wang  @mahmudinashar @dafeder ?

**Comment by dmundra** [comment]
@WaudoDavid not sure if this thread is appropriate. Maybe review this discussion https://github.com/GetDKAN/dkan/discussions/4089. To use DKAN on a site, you want to use composer to install like other packages see this https://dkan.readthedocs.io/en/latest/installation/index.html#adding-dkan-into-an-existing-project. You would use ddev if you want to work on making commits/changes to dkan itself.

@t2wang could you describe which versions you are using and the steps and errors to recreate what you are seeing?

**Comment by t2wang** [comment]
@dmundra I have resolved the issue by manually clearing the Drupal queue.

**Comment by dmundra** [comment]
Thanks @t2wang. I am going to close this.
