### ISSUE TITLE
sample content no carga contenido muestra

### ISSUE THREAD

**Issue by Roiergarcia** [GetDKAN/dkan#3658]
Hola,

Antes que nada gracias por la aportación a la comunidad.

Actualmente quiero agregar el contenido muestra proporcionado por el módulo sample_content pero al ejecutarlo con DRUSH, no me carga nada de contenido:

drush  dkan:sample-content:create

PS C:\xampp\htdocs\dkan22\web> drush  dkan:sample-content:create                                                       
 +----------------+-----------+---------+---------+--------+
| run_id               | processed | created | updated | errors |
+----------------+-----------+---------+---------+--------+
| sample_content | 0             | 0            | 0           | 0      |
+----------------+-----------+---------+---------+--------+

me podrian orientar en la solución, gracias

**Comment by janette** [comment]
@Roiergarcia  ¿Ya existen los conjuntos de datos de muestra? ¿Qué pasa si ejecutas:
```
drush dkan:sample-content:remove
```

**Comment by dafeder** [comment]
@Roiergarcia voy a cerrar esto, favor de usar el [nuevo foro](https://github.com/GetDKAN/dkan/discussions) de Github para este proyecto si necesitas mas ayuda, gracias!
