### ISSUE TITLE
Enable CORS for medicare medicaid and cmv Please !

### ISSUE THREAD

**Issue by hoogw** [GetDKAN/dkan#3660]
I get following error: 

Please enable cors for medicare

Access to XMLHttpRequest at 'https://data.cms.gov/provider-data/data.json' from origin 'http://localhost:10' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

dkan demo is NOT working with CORS

Access to XMLHttpRequest at 'http://demo.getdkan.org/data.json' from origin 'http://localhost:10' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

same CORS error for 

https://data.cms.gov/data.json

https://data.medicaid.gov/data.json

**Comment by alex-ahumada** [comment]
You can change your CORS allowed origins, methods and headers in the cors.config section of services.yml.

**Comment by dafeder** [comment]
We may want to change some of this behavior in core. See #3537. Closing this, if you have additional thoughts please add tot he comments on that issue. Thanks.
