### ISSUE TITLE
Select Distinct not working 

### ISSUE THREAD

**Issue by hoogw** [GetDKAN/dkan#3673]
Hi, everyone, 

         I want to use 

                SELECT DISTINCT column_name FROM my_table

         But the DISTINCT keyword cause invalid error.    response are  "message": "Invalid query string."

         For example: 

                https://data.cms.gov/provider-data/api/1/datastore/sql?query=%5BSELECT%20DISTINCT%20state%20FROM%205c9494ce-f9ba-5a5f-aa6f-f85b9a237b52%5D%5BWHERE%20state%20%3D%20%22AK%22%5D%3B&show_db_columns=false

         the test page; 

                     https://data.cms.gov/provider-data/dataset/2fpu-cgbb

Does dkan support DISTINCT keywords?

**Comment by dafeder** [comment]
Hi hoogw - not at this time. We did recently ship a new GROUP BY like feature but for now it is only available on the newer JSON-based datastore API endpoint. See #3731
