### ISSUE TITLE
command 'drush' not found

### ISSUE THREAD

**Issue by hwangkyh** [GetDKAN/dkan#3676]
Hello! I've been working on trying to install DKAN on to a digital ocean droplet running Ubuntu 18.04 by using https://dkan.readthedocs.io/en/latest/installation/basic.html however at the step "drush make --prepare-install drupal-org-core.make webroot --yes" the terminal returns with "Command 'drush' not found, did you mean:" etc. I have installed php, checked git installation, installed composer to download drush, installed apache server, mysql server, created one mysql database and associated user so am confused as to where it is going wrong. I do have the entirety of the steps I have taken on terminal that I am attaching here. Thank you so much!

[dkan 24 sep.pdf](https://github.com/GetDKAN/dkan/files/7228116/dkan.24.sep.pdf)

**Comment by thierrydallacroce** [comment]
@hwangkyh , it's possible the instructions assume that Drush Launcher was installed globally using https://github.com/drush-ops/drush-launcher, but before you proceed you could try replacing `drush` with `./vendor/bin/drush`.
