### ISSUE TITLE
Demo site: unable to download dataset on Chrome

### ISSUE THREAD

**Issue by thierrydallacroce** [GetDKAN/dkan#3683]
Chrome blocks `http://` downloads on `https://` pages.

### Steps to reproduce

1. Use Chrome or a chromium-based browser
2. Visit https://demo.getdkan.org/dataset/1f2042ad-c513-4fcf-a933-cae6c6fd35e6 (Lock can be visible next to url on screenshot below)
3. Click on "U.S. Adult Smoking Rate" link to download the dataset
4. Download does not occur. The console reveals the reason:
    > Mixed Content: The site at 'https://demo.getdkan.org/' was loaded over a secure connection, but the file at 'http://demo.getdkan.org/sites/default/files/distribution/1f2042ad-c513-4fcf-a933-cae6c6fd35e6/CDCSmokingRates.csv' was loaded over an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

<img width="1696" alt="Screen Shot 2021-09-29 at 1 33 40 PM" src="https://user-images.githubusercontent.com/729791/135345179-2d633724-1cf1-4a28-8088-343e9984066b.png">

**Comment by thierrydallacroce** [comment]
Browsers consider both the getdkan.org and demo.getdkan.org certificates valid, though they differ. If I inspect and change the link in Chrome to `https://`, it allows downloading the CSV. Though I'm no SSL expert, this tells me it's not a certificate problem (for Chrome at least), but an http vs https issue.

**Comment by dafeder** [comment]
Created PR for this in demo site build script GetDKAN/jenkins_release_n_update_builds#3

**Comment by dafeder** [comment]
@thierrydallacroce can you confirm this works now?

**Comment by thierrydallacroce** [comment]
@dafeder, verified it works now.
