### ISSUE TITLE
Mastodon account for this project

### ISSUE THREAD

**Issue by linux-lukas** [GetDKAN/dkan#3685]
Would a Mastodon account for this project be possible?

Why? 
For project information and announcements, for example, and interaction with the DKAN community in Fediverse.

**Comment by dafeder** [comment]
@Lukas2112 we will consider it, thanks. Right now our social media presence in general is pretty tiny, hope to improve that soon!

**Comment by linux-lukas** [comment]
With an account in the Fediverse, you would attract new people to your project and existing "clientele" to the Fediverse - many city councils are now also piling up in the Fediverse, thanks to data protection commissioners from German federal states.
