### ISSUE TITLE
https://fair.healthdata.be/ using DKAN2

### ISSUE THREAD

**Issue by JohanvanBussel** [GetDKAN/dkan#3716]
Hello, the healthdata.be department of Sciensano, the Belgian federal scientific institute on public health, launched an open data portal https://fair.healthdata.be/ using DKAN2. This FAIR portal provides an overview of existing databases with health and health care related data and aims to steadily make this data discoverable and available to the public to increase public health knowledge. It is in early stage, but we wanted you to be informed.

Question: are you aware of organisations with an DKAN open data platform that have an Service Level Agreement for that portal? Could you provide us contact references of these parties?

most kind regards,
Johan van Bussel
johan.vanbussel@sciensano.be

**Comment by dafeder** [comment]
Hi Johan - excited to see this site in the world! I believe someone has reached out over email, feel free to re-open if needed.

**Comment by JohanvanBussel** [comment]
hello Dan,
My team tries to contact you about your meeting proposal on our (Belgian) DKAN project https://fair.healthdata.be/. We probably also would negotiate some technical consultancy and development for our portal. Could you respond on mails of [Asha.Nartus@sciensano.be](mailto:Asha.Nartus@sciensano.be) (she's my PA).

Many thnx,
Johan van Bussel
