### ISSUE TITLE
Dataset REST Api leads to No page found

### ISSUE THREAD

**Issue by simonovskifilip** [GetDKAN/dkan#3725]
Hello everyone, 

I have installed completely new DKAN project using `dkan-tools`. I have followed the following pattern to install the project:  
```
mkdir ${HOME}/dkan && cd ${HOME}/dkan
dktl init
dktl make
dktl install
dktl frontend:install
```
Once finished I can access DKAN by going to ` 0.0.0.0/49157 `. I want to use the REST API to create datasets and to do that I first need to go through the authentication step. According to the [documentation](https://dkan.readthedocs.io/en/latest/apis/rest-api.html)  this terminal command should return the session token:  
`curl -X POST -i -H "Content-type: application/json" -H "Accpet: application/json" -c cookies.txt -X POST 0.0.0.0:49157/api/dataset/user/login -d '{"username":"admin","password":"admin"}'`

But it returns `PAGE NOT FOUND`. Is this some bug? Or am I doing something wrong?

**Comment by dafeder** [comment]
Hi @simonovskifilip sorrry, that documentation only covers DKAN 1 on Drupal 7, we should probably make it clearer that it is deprecated.

See https://demo.getdkan.org/api or the /api page on your own site if you have a working frontend.
