### ISSUE TITLE
composer reference to  "npm-asset/select2": "^4.0" returns an error that the package cannot be found.

### ISSUE THREAD

**Issue by JeffersonWood** [GetDKAN/dkan#3740]
It looks as though this should be revised to  "select2/select2": "^4.0"

I would really like to deploy dkam, but the this along with other bugs in the composer.json file are making it difficult

**Comment by dafeder** [comment]
Hi @JeffersonWood - we've had trouble getting the main select2 composer package to install to the correct place in docroot (as a library). Happy to look at a PR if you're able to make it work, but my guess is you need to add asset-packagist as a repository to your project's composer.json. The DKAN composer.json has this but composer projects don't inheret repositories from dependencies.

May I suggest using [dkan-tools](https://github.com/GetDKAN/dkan-tools) for your build, or, alternatively, basing your project off of our [example project](https://github.com/GetDKAN/recommended-project/blob/9.x/composer.json)?

**Comment by JeffersonWood** [comment]
Thank @dafeder !. Adding the additional repository (and downgrading the admin-toolbar) solved things. Now on to setting up some sample datasets with various levels of restriction, and testing the data visualization api. Hope the combination can do a nice job of meeting our research orgs data presentation needs.
