### ISSUE TITLE
RDF - license field

### ISSUE THREAD

**Issue by kkounouni** [GetDKAN/dkan#3773]
Hello, 

We are using DKAN 1 latest version. The RDF file in the dataset and catalog returns the license field in the following format 

<dct:license>cc-by</dct:license>

the European Open Data Portal harvest our dataset and ask to change the format of the field to the following

<dct:license rdf:resource=”http://publications.europa.eu/resource/authority/licence/CC_BY”/> 

accordingly.

Is it possible to have an update on the above issue?

**Comment by janette** [comment]
@kkounouni here is some info on customizing the license options https://dkan.readthedocs.io/en/latest/development/license.html
