### ISSUE TITLE
dktl composer recline "getdkan/recline" error

### ISSUE THREAD

**Issue by VitorFCM** [GetDKAN/dkan#3778]
Hi there, I followed the DKAN installation and configuration from the tutorial described by the DKAN tools documentation here https://getdkan.github.io/dkan-tools/#newproject.html. Everything went fine until I tried to install the getdkan/recline module via the command `dktl composer require "getdkan/recline"` and got this error:
```
Info from https://repo.packagist.org: #StandWithUkraine
./composer.json has been updated
Running composer update getdkan/recline
Gathering patches for root package.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - getdkan/recline[dev-dkan-composer-dan, dev-7.x-2.x] require library/recline 1.0 -> could not be found in any version, there may be a typo in the package name.
    - Root composer.json requires getdkan/recline * -> satisfiable by getdkan/recline[dev-dkan-composer-dan, dev-7.x-2.x].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
 [Exec]  Exit code 2  Time 31.874s
``` 
I downloaded the Recline.js library from https://github.com/okfn/recline and installed it under 'sites/all/libraries/' but nothing happened.

I'm new to DKAN and it's quite possible that I'm forgetting to do something... 

Thanks!

**Comment by muhammadmohsinali** [comment]
You can try without the dktl prefix:
composer require "getdkan/recline"

**Comment by janette** [comment]
@VitorFCM are you trying to build a Drupal 7 site or Drupal 8/9 site?

DKAN for Drupal 8+ does not use the recline library, the data preview is now a React component.
