### ISSUE TITLE
Dkan chart issue 

### ISSUE THREAD

**Issue by Simha18** [GetDKAN/dkan#3786]
![3](https://user-images.githubusercontent.com/31563924/169553195-2664f5b4-b757-4e85-9825-8f2098c5f1a2.png)

While adding the chart getting error like :  Failed to fetch the resource

i am following this url : https://dkan.readthedocs.io/en/latest/components/visualizations/visualization_entity/chart.html

**Comment by janette** [comment]
@Simha18  have you tried creating a resource on a dataset to try the Internal Data option? Is the file a utf-8 encoded CSV file?
