### ISSUE TITLE
The demo website for DKAN is down

### ISSUE THREAD

**Issue by bwail** [GetDKAN/dkan#3805]
## Description
The demo website [https://demo.getdkan.org](https://demo.getdkan.org) is down for more than a week now (and maybe more), an error message shows `The website encountered an unexpected error. Please try again later.` when you try to access it directly via URL.

Browser used: Chrome

## Steps To Reproduce
Access the website via URL [https://demo.getdkan.org](https://demo.getdkan.org) from a browser

## Expected behavior
The demo website should be up and running.

**Comment by dasumner** [comment]
Confirmed that the site is down, but the nightly rebuild process is not returning any errors.

**Comment by bwail** [comment]
Checked today, the error disappeared , but the page appears totally blank now.

**Comment by janette** [comment]
@bwail the issues blocking the demo site rebuild have been resolved, thank you.
