### ISSUE TITLE
Unable to remove a harvest without deleting its datasets

### ISSUE THREAD

**Issue by thierrydallacroce** [GetDKAN/dkan#3839]
With the goal of cleaning up an old harvest from an environment where it was mistakenly added and ran, I tested both of the following approaches in a local environment:
```
drush dkan:harvest:deregister harvest_id 
```
and
```
drush dkan:harvest:revert harvest_id
```
But, both deleted the datasets.

**Comment by stefan-korn** [comment]
@dafeder : Provided a merge request for this as discussed in #3840.

One could probably add some check if there are entities related to the harvest at all and only in that case show the warning and ask for confirmation. But maybe the warning is okay in any case?

There are also some issues with the messages from the deregister comment, which are unrelated to this. See issue #3956. #3840 and #3956 will not apply together. If either of the PRs is accepted, the other will need to be updated.

**Comment by dafeder** [comment]
@stefan-korn I think we consider this resolved, feel free to re-open if you think it needs more work.
