### ISSUE TITLE
Wrong data set identifier / distributionID listed on website

### ISSUE THREAD

**Issue by tedmoorman** [GetDKAN/dkan#3854]
I'm looking at CMS OpenPayments data and trying to create a query using their API.

You can select from multiple datasets here: https://openpaymentsdata.cms.gov/datasets . For example, here is a specific dataset:
https://openpaymentsdata.cms.gov/dataset/0380bbeb-aea1-58b6-b708-829f92a48202 .

The last part of the URL is listed as the data set identifier: 0380bbeb-aea1-58b6-b708-829f92a48202
![Identifier](https://user-images.githubusercontent.com/63677618/195879272-b785f0bf-acee-43e3-8fb5-b95651a059a7.PNG)
A distributionID that is different from the last part of the URL is used in the "Datastore: query" for querying a single datastore resource: 7dfb0fb2-e573-5448-a968-67899434ce8b
![Datastore-query-distributionID](https://user-images.githubusercontent.com/63677618/195880208-d4c2244a-e965-4fd9-ada4-d87a099eb148.PNG)
If the identifier in the URL is used in the "Datastore: query" a 404 error is received.

At first, I thought one identifier might be for some sample of the data and the other identifier might reflect the entirety of the data.

I'm not sure whether this issue is on your end or from the data provider.

**Comment by janette** [comment]
@tedmoorman if you want to use the dataset ID rather than the distribution ID, (recommended when data files are updated frequently), use one of the first two endpoints in your screen shot above, the index is 0 for the first distribution, 1, if there is a second, etc.

**Comment by tedmoorman** [comment]
@janette thank you for the clarification. I'll close this
