### ISSUE TITLE
File upload extension limit

### ISSUE THREAD

**Issue by muhammadmohsinali** [GetDKAN/dkan#3856]
https://github.com/GetDKAN/dkan/blob/2.x/modules/json_form_widget/src/Element/UploadOrLink.php/

Hi, I have attached the php snippet from the dkan 2 github repository. Query is that it doesn't contain the code to limit the file upload extensions. ManagedFile::getInfo() is  implemented with the following code snippet:

 '#upload_validators' => [],

I have tried many code snippets but still it didn't work. Can someone suggest how to restrict file type extensions while uploading resources on dataset.

**Comment by janette** [comment]
@muhammadmohsinali you will need to copy the files from the dkan/schema/collections/ directory to your site {docroot}/schema/collections/.
Then modify this line https://github.com/GetDKAN/dkan/blob/2.x/schema/collections/dataset.ui.json#L170
Also update the _enum_ values for the **format** field to match your custom extensions list.
