### ISSUE TITLE
Error While Adding Dataset in DKAN

### ISSUE THREAD

**Issue by huyquoc2311** [GetDKAN/dkan#3860]
Hi, 

Im using DKAN with Drupal 7. After install DKAN, every function works smoothly except Add Dataset. When I do the first step and move to the second step (Next: Add Data). The system always return Error "The website encountered an unexpected error. Please try again later." Im checking the Recent Logs and see the error, however, Im not sure that the reason of error is from Leaflet Library or not. 

Please help me to fix this issues. I attached the error figures in this content. 

![Error While Adding Dataset](https://user-images.githubusercontent.com/104246280/197321745-51f0d5fa-422a-42aa-a336-a598b3f0fa12.png)
![Error While Adding Dataset (1)](https://user-images.githubusercontent.com/104246280/197321740-1692aa2a-a3c3-467a-9676-a9583a963925.png)
![Error While Adding Dataset (2)](https://user-images.githubusercontent.com/104246280/197321742-4d1d2849-791f-4959-91db-17030ee4f50e.png)

Thank you,
Regards./

**Comment by dafeder** [comment]
Closing, no longer supporting DKAN on Drupal 7. Please try DKAN 2 or for a more DKAN 1-like experience try [EKAN](https://www.drupal.org/project/ekan)
