### ISSUE TITLE
About display of file character code is not in UTF8

### ISSUE THREAD

**Issue by takuya310** [GetDKAN/dkan#393]
When a character code is uploaded files that are not UTF8, garbled occurs when displaying in Recline.js. 
In this regard, what has been considered?

**Comment by acouch** [comment]
Thanks for noting this. Can you provide an example file or character?

**Comment by takuya310** [comment]
Thanks.
I uploades this file. Encoding of this file is 'Shift-jis', Japanese code.
Please download csv from here.
https://www.sugarsync.com/pf/D0185285_61242988_7302946

I have tried to make new module(annai_utility) and hook node_preserve method, like this.
function annai_utility_node_presave($node) {
   $file = file_load($node->field_upload['und'][0]['fid']);
   $data = file_get_contents($file->uri);
   $data = mb_convert_encoding($data,'UTF-8','SJIS, sjis-win');
   $fp = fopen($file->uri,'wb');
   fwrite($fp, $data);
   fclose($fp);
}

I think way of fix is two patterns.
1. Change character code when user upload files.
2. Convert character code by recline.js when user view datas using grid or map.
I've tried to case1.
What do you think about this? Thank you.

**Comment by takuya310** [comment]
I understood that I can select character code of files when I import csv files to Datastore.
So, to fix above problem, I think that It is good to use case 2.  

Could you tell me the place to be changed in the recline module?
I'll try it. Thank you.

**Comment by dangur** [comment]
Need to create a file with different encoding. The file above no longer exists.

**Comment by dangur** [comment]
CIVIC-504

**Comment by dafeder** [comment]
We're going to see if we can still reproduce this. If we can, I agree we should do some sort of modification that selects character encoding both for preview and for datastore import. (It would be good to unify other options like delimeter character, header information etc between previews and datastore importer)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
