### ISSUE TITLE
Docs not working

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#3945]
## Describe the bug
The docs at https://docs.getdkan.com/ are not working at the moment (for the last few days)

## Steps To Reproduce
Visit https://docs.getdkan.com/

## Expected behavior
see the docs

**Comment by janette** [comment]
Can't find any information on this error 

```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/dkan/envs/remove-pygments/lib/python3.9/site-packages/myst_parser/parsers/sphinx_.py", line 58, in parse
    config: MdParserConfig = document.settings.env.myst_config
AttributeError: 'BuildEnvironment' object has no attribute 'myst_config'
```

**Comment by fishfree** [comment]
+1 404 Page not found now.

**Comment by fishfree** [comment]
I found we can just read the docs in the [repo](https://github.com/GetDKAN/dkan/tree/2.x/docs).

**Comment by stefan-korn** [comment]
I suppose the URL has changed to https://dkan.readthedocs.io/en/latest/index.html - So with this url this seems to be fixed.
