### ISSUE TITLE
All /dataset/dataset-uuid 404 page not found

### ISSUE THREAD

**Issue by fishfree** [GetDKAN/dkan#3952]
After adding a new dataset, on the page /admin/dkan/datasets, I clicked a dataset title, the page /dataset/33dfff9b-28a0-41c5-9651-fc261e968810 not found.
DKAN 2.x-dev, Drupal 10.0

A related question: does the recline.js module still work in DKAN 2? That's the real reason I want to use DKAN for Drupal 10.

**Comment by janette** [comment]
DKAN 2.x does not use recline.js, it is using react to build the data preview table.

**Comment by fishfree** [comment]
@janette Thank you for your tip, Janette! I did these as below:

1. Enable the module DKAN JS Frontend,
2. Build the [React frontend](https://github.com/GetDKAN/data-catalog-app) and move the whole git-cloned repo folder to my Drupal 10 production site web root folder /var/www/mysite/docroot/ 
3. Open https://mysite.com/frontend/build/index.html, it shows page not found. 
![image](https://user-images.githubusercontent.com/1741341/236587297-b4f3713e-894a-41d5-911d-15aa8bbe4001.png)

I'm not familiar with Node.js. What's the reason? How can I make it as the [official demo](https://demo.getdkan.org/dataset/d460252e-d42c-474a-9ea9-5287b1d595f6) does?

**Comment by fishfree** [comment]
After a while, the problem disappeared itself. I don't know. Now it works as designed.
