### ISSUE TITLE
Basic harvest error - one DKAN2 instance harvesting from another

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#3953]
## Describe the bug
Running a harvest, there is error message:
No items found to extract, review your harvest plan.

## Steps To Reproduce
To get going with harvesting I am trying to setup a basic harvest like it is described in the docs: https://dkan.readthedocs.io/en/latest/user-guide/guide_harvest.html
Taking this guide it seems it is only necessary to register the harvest and then run it.
Obviously it depends on the extract-uri parameter and probably this extract-uri have to deliver some kind of format for this harvest to work. This is not detailed in documentation (though there is a part about "Transforms" which indicates it is possible or maybe necessary to transform the input from extract-uri to match the local dataset configuration).
But it seems a basic harvest should be possible without transforming.
So I thought about setting up an empty dkan instance and a dkan instance with demo content.
Then I would like to harvest from the instance with demo content into the empty instance.
I thought about using the API call for a dataset: api/1/metastore/schemas/dataset/items/{identifier} as extract-uri

## Expected behavior
working harvest

**Comment by janette** [comment]
@stefan-korn the **extract-uri** should be a URL to a list of datasets in json format, for example if you were to harvest the datasets from the demo site, you would use: https://demo.getdkan.org/data.json

Transforms are for making changes to the datasets during the harvest to change or add metadata that does not exist on the source.

**Comment by stefan-korn** [comment]
@janette : Ah, thanks for the explanation. Now I understand and it's working as expected.

I missed out that data.json does provide the catalog itself.
