### ISSUE TITLE
Harvest deregister missing message

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#3956]
## Describe the bug
drush dkan:harvest:deregister does not provide a message, but instead there is:
` [warning] Undefined variable $message HarvestCommands.php:138`

## Steps To Reproduce
Register harvest with drush dkan:harvest:register
Verify that the harvest plan is registered by drush dkan:harvest:list
Deregister the harvest with drush dkan:harvest:deregister
See warning instead of success message
Verify that the harvest plan is deregistered succesfully by drush dkan:harvest:list

## Expected behavior
get the message "Succesfully deregistered the ... harvest" that is intended for this case.
Additionally a message indicating that there is no harvest plan deregistered should be output in case

**Comment by jastraat** [comment]
Merged; closing
