### ISSUE TITLE
Minor UI issue when selecting choropleth colors

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#398]
![screen shot 2015-03-09 at 5 25 44 pm](https://cloud.githubusercontent.com/assets/9059428/6564745/78e9063c-c681-11e4-94a4-e4825fe2ebd7.png)

Bubbles don't line up with buttons

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
