### ISSUE TITLE
Could not build the front-end.

### ISSUE THREAD

**Issue by ghost** [GetDKAN/dkan#3985]
Hello, 

For some reasons im unable to build latest data-catalog-app (aka the react frontend app) inside my dkan docroot (drupal 9)

**Server config ** 

smart@open-neurosecurity:/home/DKAN$ sh ./status.sh
 [Exec] Running /home/DKAN/vendor/bin/drush 'core:status' --uri in /home/DKAN
Drupal version   : 9.5.9                                      
Site URI         : https://open-neurosecurity.org/collections 
DB driver        : mysql                                      
DB hostname      : localhost                                  
DB port          : 3306                                       
DB username      : dkan                                       
DB name          : test_dkan_prod                             
Database         : Connected                                  
Drupal bootstrap : Successful                                 
Default theme    : dkan_js_frontend_bartik                    
Admin theme      : claro                                      
PHP binary       : /usr/bin/php8.0                            
PHP config       : /etc/php/8.0/cli/php.ini                   
PHP OS           : Linux                                      
Drush script     : /home/DKAN/vendor/bin/drush                
Drush version    : 10.6.2                                     
Drush temp       : /tmp                                       
Drush configs    : /home/DKAN/vendor/drush/drush/drush.yml    
Install profile  : standard                                   
Drupal root      : /home/DKAN/docroot                         
Site path        : sites/default                              
Files, Public    : sites/default/files                        
Files, Temp      : /tmp                                       
 [Exec] Done in 0.469s

**Error message ** 

$ dktl frontend:build 
 [Exec] Running CI=false npm run build in src/frontend

> @civicactions/data-catalog-app@1.3.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

./node_modules/swagger-client/es/resolver/apidom/reference/resolve/resolvers/http-swagger-client/index.js
Cannot find module: '@swagger-api/apidom-reference/configuration/empty'. Make sure this package is installed.

You can install this package by running: yarn add @swagger-api/apidom-reference/configuration/empty.

 [Exec]  Exit code 1  Time 25.103s

                                                                                
 [ERROR] Could not build the front-end.                                         
                                        
Your input on this issue is appreciated. 

smart

**Comment by janette** [comment]
@9967819 DKAN Tools is no longer supported, can you try installing [DDEV](https://ddev.readthedocs.io/en/stable/users/usage/) and follow [these instructions ](https://getdkan.github.io/dkan-ddev-addon/getting-started.html)

**Comment by ghost** [comment]
Hi Janette! 

Thank you for your reply and im sorry for this late response. Some notes about this issue: 1. I've deinstalled DDEV specifically because i dont need any Docker integration. (currently using host mode with php-fpm/nginx in production..) 2. It seem that DKAN decided to use the React app as the default frontend (aka the data-catalog-app) instead of using a standard drupal theme. However this particular feature is not a huge priority for me. In addition i'm looking to develop a free php or python based data research platform to allow authors to import/create and edit simple datasets, preferably with DCAT metadata:  https://resources.data.gov/resources/dcat-us/. Note finally that React is a node.js app that may requires third-party javascripts not fully compatible with GPLv3 license. Have a great weekend.
