### ISSUE TITLE
UX: ArcGIS and ESRI Rest file previews not available in DKAN 2.

### ISSUE THREAD

**Issue by DaniyalRaza786** [GetDKAN/dkan#4009]
Hi,
I am using DKAN 2. I want to display previews for resource files within datasets on the dataset detail page. Currently, previews are only available for CSV files. How can I enable previews for other file formats?

**Comment by dafeder** [comment]
Hi @DaniyalRaza786 that's not currently a feature of DKAN 2. If you're using a decoupled react frontend, I think it would be a question of finding an existing react component and using that in the app in place of the grid preview when the resource is an ESRI endpoint. It looks like [this repo](https://github.com/odoe/jsapi-react) may have a place to start.

This is obviously a fairly large level of effort to accomplish, but we will be very happy to share your efforts if you do find a solution, or consider merging it into one of our repos if appropriate. I think we are looking at some day having out of the box options for this but I can't speak to the timeline for that at the moment.

**Comment by dafeder** [comment]
No current plans to implement this, open to contributions
