### ISSUE TITLE
Pull request of translation function

### ISSUE THREAD

**Issue by takuya310** [GetDKAN/dkan#403]
I've translation in order to use the DKAN in Japan.
At that time, there was a part of the translation function is not written.
I fixed the following source.

> dkan_sitewide_menu/dkan_sitewide_menu.features.menu_links.inc
> dkan_dataset_content_types/dkan_dataset_content_types.field_group.inc
> dkan_dataset_content_types/dkan_dataset_content_types.features.field_instance.inc
> dkan_dataset_content_types/dkan_dataset_content_types.features.field_base.inc
> dkan_dataset/dkan_dataset.module
> dkan_dataset/dkan_dataset.forms.inc
> contrib/recline/recline.app.js
> contrib/recline/recline.field.inc
> libraries/recline/dist/recline.js
> contrib/leaflet_draw_widget/js/draw.js

These modules are also original ones, but how should I request?
Is it okay to pull request directly DKAN repository?
Thanks.

**Comment by acouch** [comment]
Great!

The items within DKAN Sitewide https://github.com/NuCivic/dkan/tree/7.x-1.x/modules/dkan/dkan_sitewide should have a Pull Request to this project.

```
dkan_dataset/dkan_dataset.module
dkan_dataset/dkan_dataset.forms.inc
```
needs to be updated here: https://github.com/NuCivic/dkan_dataset

```
contrib/recline/recline.app.js
contrib/recline/recline.field.inc
```
needs to be updated here: https://github.com/NuCivic/recline

Please let me know if you have any questions.

**Comment by takuya310** [comment]
Thanks.
I've Pull Request to dkan_sitewide, dkan_dataset, recline.

Two questions.
I've installed according to the installation instructions, differences were I have occurred.
Is that okey? Please tell me if you know about this difference.

For the following source, is it okey that I create a patch and upload to issue of Drupal?
`libraries/recline/dist/recline.js
contrib/leaflet_draw_widget/js/draw.js`

**Comment by acouch** [comment]
Thanks. We'll try and get to these as soon as we can. 

>I've installed according to the installation instructions, differences were I have occurred.
>Is that okey? Please tell me if you know about this difference.

I'm not sure what you mean. Can you try to rephrase?

**Comment by takuya310** [comment]
Thanks.
I'm sorry, I will paraphrase.
About these source, I need to send a pull request or patch below?

libraries / recline / dist / recline.js
https://github.com/NuCivic/recline

contrib / leaflet_draw_widget / js / draw.js
https://www.drupal.org/project/issues/leaflet?categories=All

**Comment by takuya310** [comment]
I add translation function, again. And pull request.
Thank you.

But I didn't know how to translate "%node:type".
In menu, "%node:type" appear as "dataset" or "resource".

/var/www/dkan-nagoya/dkan/profiles/dkan/modules/dkan/dkan_sitewide/modules/dkan_sitewide_panels/dkan_sitewide_panels.path_breadcrumbs.inc

And, I couldn't translate "Home" in breadcrumbs.
"Home" is used to condition determination. Like this.
> if ($item == '<a href="/">Home</a>')
at /dkan/themes/dkan/template.php

How should I fix this?

**Comment by takuya310** [comment]
I made patch for "https://github.com/NuCivic/recline.js".
Because this project didn't have issues, I attach a patch here.
Thank you.

https://drive.google.com/file/d/0BwC-EVUsICJXaWhJSjVwSHd5akk/view?usp=sharing

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
