### ISSUE TITLE
Allow for an empty option in select fields via schema property

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#4036]
## User Story
Currently you can not make use of the #empty_value property of the Drupal [Select](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21Element%21Select.php/class/Select) form element if using the basic select widget with the json_form_widget for a schema field.

You can use the select_other type for the list widget, but then you get the empty option and the other option.

There maybe cases where you only want the empty option but not allow the other option, i. e. an optional list field.

I propose to use a schema property on the dataset field to indicate this. Why not just name this "empty_value" and if this is set to true the #empty_value property will be used on the select form element.

One could maybe just inject an empty value in the "enum" property of the schema field, but this seems kind of "dirty".

**Comment by dafeder** [comment]
So, in this scenario, what do you want the submitted JSON to look like? An empty array, or the property should not exist at all?

**Comment by stefan-korn** [comment]
The property should not exist at all.
An optional value, you can select one from the list or select "None" and then it is empty.

**Comment by dafeder** [comment]
We are trying to reproduce the behavior of [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form) as much as possible, and it looks like there an enum field that is optional should always have an empty element in the select, which translates to no property in the JSON. We should make json_form_widget work the same way.

**Comment by stefan-korn** [comment]
Okay, then we could just use
`if (!$this->checkIfRequired($field_name, $element_schema)) {`
instead of
`if ($property->empty_value) {`
?
(see PR #4037)

**Comment by dafeder** [comment]
I think so! Does it produce the expected result?

**Comment by stefan-korn** [comment]
Yes, no value is saved in the JSON if the empty option is chosen. Updated the PR.
