### ISSUE TITLE
DKAN DDev Addon documentation link broken/missing

### ISSUE THREAD

**Issue by davilla41** [GetDKAN/dkan#4057]
Hi fellas, I'm having an issue with DDEV Addon documentation.

If you go to DKAN installation documentation on:
https://dkan.readthedocs.io/en/latest/installation/index.html

Then you can see a link to DKAN DDev Addon documentation to start a new project:
![Screen Shot 2023-11-13 at 10 43 35](https://github.com/GetDKAN/dkan/assets/149850423/0ce2e36f-3a2e-4154-84cf-4df136d9eef2)

But if you click on it you're redirected to a broken/missing page:
![image](https://github.com/GetDKAN/dkan/assets/149850423/1eb21796-b24f-44a7-8652-6330399b104f)

I appreciated any help

**Comment by janette** [comment]
Hi @davilla41, sorry about that, will get those links corrected. Until then you can find the DDEV getting started information here https://getdkan.github.io/ddev-dkan/getting-started.html
