### ISSUE TITLE
DKAN on headless VM

### ISSUE THREAD

**Issue by davilla41** [GetDKAN/dkan#4061]
Hi guys, I have DKAN installed on a headless Ubuntu 20.04 virtual machine.
My firewall allows the port needed:
![image](https://github.com/GetDKAN/dkan/assets/149850423/c4f4758f-f927-45eb-8d46-10627ca9f6bb)

This is the list of containers after installation:

```
CONTAINER ID	IMAGE							COMMAND			CREATED		STATUS			PORTS															NAMES
b8cd6f5c05c5	drud/ddev-router:v1.21.5-built				"/app/docker-entrypo…"	37 hours ago	Up 37 hours (healthy)	127.0.0.1:80->80/tcp, 127.0.0.1:443->443/tcp, 127.0.0.1:8025-8026->8025-8026/tcp, 127.0.0.1:8036-8037->8036-8037/tcp	ddev-router
ad80e87fa8be	drud/ddev-dbserver-mysql-5.7:v1.21.5-undms-built	"/docker-entrypoint.…"	37 hours ago	Up 37 hours (healthy)	127.0.0.1:33417->3306/tcp												ddev-undms-db
4a36ef3df664	phpmyadmin:5						"/docker-entrypoint.…"	37 hours ago	Up 37 hours		80/tcp															ddev-undms-dba
37f24fcd1476	drud/ddev-webserver:v1.21.5-undms-built			"/start.sh"		37 hours ago	Up 37 hours (healthy)	8025/tcp, 127.0.0.1:33421->80/tcp, 127.0.0.1:33420->443/tcp								ddev-undms-web
3d4e0d0cad84	ddev-undms-doxygen					"/bin/bash"		37 hours ago	Up 37 hours																	ddev-undms-doxygen
e9cd5d0dd1de	drud/ddev-ssh-agent:v1.21.5-built			"/entry.sh ssh-agent"	37 hours ago	Up 37 hours (healthy)																ddev-ssh-agent
```
I also modified the setting.php inside the ddev-undms-web container like this:
![image](https://github.com/GetDKAN/dkan/assets/149850423/5bced6c3-6f2e-4c82-8d95-f8c40656f17d)

And also this
![image](https://github.com/GetDKAN/dkan/assets/149850423/f1892415-3cf9-484c-8293-ce1e3a855ac1)

So my problem is that if I hit the IP address from my VM I'm getting this:
![image](https://github.com/GetDKAN/dkan/assets/149850423/cf8d407c-e1fb-465e-9d7e-7ba4fd72b380)

This is also a diagram that show the way I need to use DKAN on dev right now:
![image](https://github.com/GetDKAN/dkan/assets/149850423/607a2bd7-b522-478c-90b5-409c8b6538de)

**Comment by dafeder** [comment]
@davilla41 I think this is beyond what we can help you with here; you are really having an issue with a fairly complex and unique docker/ddev setup not with DKAN itself. Can you make this work with just a standard Drupal installation and the default ddev Drupal config? If so, and this seems to be something specific to DKAN we can try to take a closer look but otherwise I think this is more of a ddev support question.

**Comment by dafeder** [comment]
Closing, but you can re-open or create a new issue if you believe there is a DKAN-specific problem here.
