### ISSUE TITLE
WidgetRouter accepts only PHP UUID

### ISSUE THREAD

**Issue by larjohn** [GetDKAN/dkan#4064]
I installed Drupal on a Windows machine and tried to add DKAN as a module manually. Other than the composer.json stuff that I had to add from the Docker template I found out that the metadata field is disabled by default. I tried enabling it, but it thew an exception:

`Uncaught PHP Exception TypeError: "Drupal\json_form_widget\WidgetRouter::__construct(): Argument #1 ($uuid) must be of type Drupal\Component\Uuid\Php, Drupal\Component\Uuid\Com given"`

It seems that the Com class is used in Windows installations of Drupal. Why not use the broader UuidInterface instead of Php in the WidgetRouter's constructor?

**Comment by dafeder** [comment]
Sounds reasonable! Are you able to submit a PR?

**Comment by larjohn** [comment]
> Sounds reasonable! Are you able to submit a PR?

@janette was faster!

**Comment by janette** [comment]
@larjohn can you test that branch and let us know if that fixes the error.

**Comment by dafeder** [comment]
@larjohn @janette this just seems like it is more correct on its face and has no downsides so merging, but would still be interested in hearing that it did indeed fix the issue on Windows!

**Comment by larjohn** [comment]
Sorry for the delay, it did on my case

Στάλθηκε από Outlook για Android<https://aka.ms/AAb9ysg>
________________________________
