### ISSUE TITLE
Catch Guzzle Exception to avoid breaking harvest

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#4075]
## Describe the bug
During harvesting the method getRemoteMimeType is called to determine the mime type of distribution resource by calling the downloadURL. If for some reason the downloadURL is not available or broken, the harvesting will fail alltogether with a Guzzle Exception logged.

## Steps To Reproduce
Do a harvest with one resource download url not being available.

## Expected behavior
The method getRemoteMimeType should retun NULL on failure to call the downloadURL (as it is already said in the methods declaration) instead of quitting with an Exception.

**Comment by stefan-korn** [comment]
Beside this problem, there is another possible issue with that method. If the download url does timeout this might take forever or very long if the harvest is started via drush and the default timeout of 0 = forever of Guzzle client is used.

Maybe one should use Drupal's [http_client](https://api.drupal.org/api/drupal/core%21core.services.yml/service/http_client/9) service instead to get Drupal's default settings and be able to override via settings?

**Comment by dafeder** [comment]
Switching to http_client service seems like a good move. As @janette mentions in the PR we are still thinking through the right way to deal with bad URLs.

**Comment by paul-m** [comment]
We found that this issue also affects the use-case of trying to create a dataset in the Drupal UI, using a bad URL for the source URL. This led to a WSOD with the error message that guzzle had gotten a 404.

**Comment by paul-m** [comment]
Fixed. Special thanks to @stefan-korn
