### ISSUE TITLE
Metastore service needs to call logger.factory

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#4100]
## Describe the bug
The metastore service does not output correctly to the log because the logger service is not present.

## Steps To Reproduce
for example if [this exception](https://github.com/GetDKAN/dkan/blob/4f0b99310cf784445863297cd006d4d3a8a14654/modules/metastore/src/MetastoreService.php#L206) is raised, there will be no entry in the log. If you cannot reproduce an exception here, you could just add a log call in the try-part and see that the message is not logged.

## Expected behavior
message should be logged.

**Comment by paul-m** [comment]
Thanks!

In this PR we deprecated LoggerTrait and made sure it was replaced with a more direct service injection: https://github.com/GetDKAN/dkan/pull/4140

I'll close this issue and the associated PR. Feel free to open a new one if you find something else.
