### ISSUE TITLE
Provide text_format render element for string schema properties

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#4132]
## User Story
Editors want to use [text_format](https://api.drupal.org/api/drupal/core%21modules%21filter%21src%21Element%21TextFormat.php/class/TextFormat/10) render elements for long text fields (currently designated via textarea widget in schema.ui.json), for example to edit long text in CKEditor.

## Acceptance Criteria
- provide option "text_format" in schema.ui.json to indicate the text_format which should be used for the long text property.
- show "text_format" editing in JSON form widget with the indicated format.

## Caveats
It is not (easily) possible to store the format together with the string in json. Therefore I would propose to not store the format in the JSON and keep this fixed in the schema.ui.json. So it will be allowed only one format (via allowed_formats) in the text format widget and no changing is possible via UI.
The output of the string needs to be taken care independently. For example currently the [node--data template](https://github.com/GetDKAN/dkan/blob/6850890d43aec65117b5e56335254bb4073b0910/modules/metastore/templates/node--data.html.twig#L109) escapes any HTML in the string (though I suppose it is not even necessary here, because Twig does escaping itself).
If you want to output HTML in the description you need to change this and take care yourself. You also need to ensure that only the HTML you want is output, so maybe custom processing is needed (but this is done anyway via metastore_preprocess_node__data), so you can do it like there for yourself.

**Comment by dafeder** [comment]
Hi Stefan - I like this concept. Flagging @dgading.

**Comment by dafeder** [comment]
Updated this with test coverage, docs and codeclimate fixes @stefan-korn. Hoping to merge soon. Hope it is still useful to you after all this time!
