### ISSUE TITLE
Error : Call to a member function out() on boolean in leaflet_widget_widget_validate() (line 230

### ISSUE THREAD

**Issue by mrdoruya** [GetDKAN/dkan#4155]
Hi, i get this error : Error : Call to a member function out() on boolean in leaflet_widget_widget_validate() (line 230) when trying to create a dataset or when trying to edit a dataset .
How can i fix this issue. 
Drupal 7.100

**Comment by dafeder** [comment]
Hello, we don't support the Drupal 7 version of DKAN anymore. Please try DKAN 2 on Drupal 9/10.
