### ISSUE TITLE
Notice : Undefined index: label_visibility in field_group_table_field_group_pre_render() (line 181)

### ISSUE THREAD

**Issue by mrdoruya** [GetDKAN/dkan#4156]
Hi i get this notice : Notice : Undefined index: label_visibility in field_group_table_field_group_pre_render() (line 181) whenever i naviguate to a dataset. 
How can i fix this issue ?
Drupal 7.100

Thanks

**Comment by dafeder** [comment]
Hello, we don't support the Drupal 7 version of DKAN anymore. Please try DKAN 2 on Drupal 9/10.

**Comment by dafeder** [comment]
Hello, we don't support the Drupal 7 version of DKAN anymore. Please try DKAN 2 on Drupal 9/10.
