### ISSUE TITLE
Dataset ComplexDataFacade returning wrong empty value

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#4179]
The ComplexDataFacade for the Dataset is returning wrong empty values in the [getArrayValues](https://github.com/GetDKAN/dkan/blob/2.x/modules/metastore/modules/metastore_search/src/ComplexData/Dataset.php#L168) method I suppose.

If there is no value for the given property the values array is added by an empty array. This is not correct, the value should be skipped in that case.
In case there is a value (from preg_match) this is added to the values array and this is a string value (preg_match). So an empty array does not match a string value, an empty string would maybe be okay. But I think, the value should just be skipped in that case.

## Describe the bug
I cannot give an indication whether this is somewhere making problems currently in DKAN. I came across this in #4115, where it poses an issue in some circumstances. Nonetheless I think the logic is generally not correct (string vs array) and it is not caused specifically by #4115.

## Steps To Reproduce
no way (that I know of) to reproduce this in plain DKANv2

**Comment by dafeder** [comment]
Closing, see discussion in #4180. Re-open if we see an actual reproducible bug related to this.
