### ISSUE TITLE
Search API integration - Property label and description

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#4190]
## Describe the bug
The metastore_search module provides Search API integration. This means you can use every schema property as a Search API field in an index of Datasource DKAN Dataset.

But the Search API fields are only described by the property key and do not have a label nor a description.

Screenshot adding a field (see for example that 'accessLevel" is only described by property key, while normally there would also be a label for a field like with "Rendered HTML output" above.)
![grafik](https://github.com/GetDKAN/dkan/assets/3440033/719fd4c0-dc2f-448f-8629-b471bf59e49f)
A place where this is more of an issue is if you add an aggregated field and want to choose the "contained fields". Any field from the DKAN Dataset Datasource is just shown as "DKAN Dataset >>" with no additional information. This is also because of missing label and property for the Search API field.
Screenshot:
![grafik](https://github.com/GetDKAN/dkan/assets/3440033/472d6c96-3ac0-4d0a-a605-c102d68d88e4)

## Steps To Reproduce
Add a field to the DKAN search API index

## Expected behavior
Label (and description) for Search API fields of DKAN Dataset Datasource should show up. Take the title property from schema for the label and the description property from schema for the description.

**Comment by stefan-korn** [comment]
Screenshots with #4191 
![grafik](https://github.com/GetDKAN/dkan/assets/3440033/53d9b4bf-4c07-444c-b634-27cf00438c83)
![grafik](https://github.com/GetDKAN/dkan/assets/3440033/97ed49f8-ebbd-4989-be3b-a48762b7527d)

**Comment by dafeder** [comment]
Wow amazing timing @stefan-korn I am just working on a custom index and need an aggregated field, I think. Taking a look at this.
