### ISSUE TITLE
Display message when redirecting from bad dataset URL

### ISSUE THREAD

**Issue by drkloc** [GetDKAN/dkan#425]
currently, is returning the dataset search page at **dataset/**

**Comment by janette** [comment]
This seems like preferred behavior, perhaps we could add a message for the user "Sorry the dataset you are looking for does not exist" or something

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
