### ISSUE TITLE
Recline flips the order of rows in a file when switching between the grid and graph views

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#427]
States listed in A->Z order in the grid are listed in Z->A order in the graph, and vice-versa. 

Here are four comparison images of how the states are listed in the grid, and then in the accompanying chart -- [Source](http://core-7.35-update.dkan.qa.nuamsdev.com/dataset/another-dataset/resource/c8789bb1-9e6c-4446-a69c-43aea08d1a56) :

![screen shot 2015-03-26 at 1 16 38 pm](https://cloud.githubusercontent.com/assets/9059428/6922016/574bc0b6-d796-11e4-8095-507841535db6.png)
![screen shot 2015-03-26 at 1 16 46 pm](https://cloud.githubusercontent.com/assets/9059428/6922018/5b8872e6-d796-11e4-8d38-fc67bfb78fe2.png)

![screen shot 2015-03-26 at 1 16 56 pm](https://cloud.githubusercontent.com/assets/9059428/6922023/60c51bba-d796-11e4-89cd-5208cd91e33b.png)
![screen shot 2015-03-26 at 1 17 05 pm](https://cloud.githubusercontent.com/assets/9059428/6922028/680c8962-d796-11e4-844f-7b6e406abb46.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
