### ISSUE TITLE
Create a Code of Conduct

### ISSUE THREAD

**Issue by mgifford** [GetDKAN/dkan#4281]
### Feature Description

We should have a community code of conduct like https://github.com/ckan/ckan/blob/master/CODE_OF_CONDUCT.md

The TODO group is no longer maintaining theirs https://github.com/todogroup/opencodeofconduct?tab=readme-ov-file

Maybe we use one like https://geekfeminismdotorg.wordpress.com/about/code-of-conduct/

### Detailed Feature Description

We should have a code of conduct for our community.

### Problem and Motivation

They can be useful to guide community engagement.

### Potential Benefits

Users have confidence about the expectations of the community. 

### Target Audience

- [ ] End Users
- [X] Developers
- [ ] Administrators
- [ ] Other

### Possible Implementation

From: https://geekfeminism.fandom.com/wiki/Community_anti-harassment/Policy

Community anti-harassment/Policy
< [Community anti-harassment](https://geekfeminism.fandom.com/wiki/Community_anti-harassment)
[Sign in to edit](https://auth.fandom.com/signin?redirect=https%3A%2F%2Fgeekfeminism.fandom.com%2Fwiki%2FCommunity_anti-harassment%2FPolicy%3Fveaction%3Dedit&uselang=en)
This is an example community anti-harassment policy, particularly designed for use in communities that are primarily online.

If your community meets entirely in person, you may prefer the Right Term policy, which is designed for in-person events. We also suggest that even groups that have adopted a community policy have a conference policy for any events they run.

Contents
1	Anti-harassment policy text
1.1	Shorter version
1.2	Longer version
1.2.1	Reporting
1.2.2	Consequences
2	License and attribution
Anti-harassment policy text
Shorter version
COMMUNITY NAME is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, age, race, or religion. We do not tolerate harassment of participants in any form.

This code of conduct applies to all COMMUNITY NAME spaces, including [list, eg "our mailing lists and IRC channel"], both online and off. Anyone who violates this code of conduct may be sanctioned or expelled from these spaces at the discretion of the RESPONSE TEAM.

Some COMMUNITY NAME spaces may have additional rules in place, which will be made clearly available to participants. Participants are responsible for knowing and abiding by these rules.

Longer version
COMMUNITY NAME is dedicated to providing a harassment-free experience for everyone. We do not tolerate harassment of participants in any form.

This code of conduct applies to all COMMUNITY NAME spaces, including [give a list of your spaces, eg "our mailing lists and IRC channel"], both online and off. Anyone who violates this code of conduct may be sanctioned or expelled from these spaces at the discretion of the RESPONSE TEAM.

Some COMMUNITY NAME spaces may have additional rules in place, which will be made clearly available to participants. Participants are responsible for knowing and abiding by these rules.

Harassment includes:

Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, age, race, or religion.
Unwelcome comments regarding a person’s lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment.
Deliberate misgendering or use of ‘dead’ or rejected names.
Gratuitous or off-topic sexual images or behaviour  in spaces where they’re not appropriate.
Physical contact and simulated physical contact (eg, textual descriptions like “*hug*” or “*backrub*”) without consent or after a request to stop.
Threats of violence.
Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm.
Deliberate intimidation.
Stalking or following.
Harassing photography or recording, including logging online activity for harassment purposes.
Sustained disruption of discussion.
Unwelcome sexual attention.
Pattern of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others
Continued one-on-one communication after requests to cease.
Deliberate “outing” of any aspect of a person’s identity without their consent except as necessary to protect vulnerable people from intentional abuse.
Publication of non-harassing private communication.
COMMUNITY NAME prioritizes marginalized people’s safety over privileged people’s comfort. RESPONSE TEAM reserves the right not to act on complaints regarding:

‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’
Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you.”
Communicating in a ‘tone’ you don’t find congenial
Criticizing racist, sexist, cissexist, or otherwise oppressive behavior or assumptions
Reporting
If you are being harassed by a member of COMMUNITY NAME, notice that someone else is being harassed, or have any other concerns, please contact the RESPONSE TEAM at [email address or other contact point]. If the person who is harassing you is on the team, they will recuse themselves from handling your incident. We will respond as promptly as we can.

This code of conduct applies to COMMUNITY NAME spaces, but if you are being harassed by a member of COMMUNITY NAME outside our spaces, we still want to know about it. We will take all good-faith reports of harassment by COMMUNITY NAME members, especially LEADERSHIP TEAM, seriously. This includes harassment outside our spaces and harassment that took place at any point in time. The abuse team reserves the right to exclude people from COMMUNITY NAME based on their past behavior, including behavior outside COMMUNITY NAME spaces and behavior towards people who are not in COMMUNITY NAME.

In order to protect volunteers from abuse and burnout, we reserve the right to reject any report we believe to have been made in bad faith. Reports intended to silence legitimate criticism may be deleted without response.

We will respect confidentiality requ ok I'mests for the purpose of protecting victims of abuse. At our discretion, we may publicly name a person about whom we’ve received harassment complaints, or privately warn third parties about them, if we believe that doing so will increase the safety of COMMUNITY NAME members or the general public. We will not name harassment victims without their affirmative consent.

Consequences
Participants asked to stop any harassing behavior are expected to comply immediately.

If a participant engages in harassing behavior, RESPONSE TEAM may take any action they deem appropriate, up to and including expulsion from all COMMUNITY NAME spaces and identification of the participant as a harasser to other COMMUNITY NAME members or the general public.

License and attribution
This policy is licensed under the [Creative Commons Zero license](http://creativecommons.org/publicdomain/zero/1.0/) . It is public domain, no credit and no open licencing of your version is required.

If you would like to optionally attribute it, you could use the below text and link to [http://geekfeminism.wikia.com/wiki/Community_anti-harassment](https://geekfeminism.fandom.com/wiki/Community_anti-harassment):

This anti-harassment policy is based on the example policy from the Geek Feminism wiki, created by the Geek Feminism community.
The policy is based on the [conference anti-harassment policy](https://geekfeminism.fandom.com/wiki/Conference_anti-harassment/Policy), and is the work of Annalee Flower Horne with assistance from Valerie Aurora, Alex Skud Bayley, Tim Chevalier, and Mary Gardiner.

**Comment by janette** [comment]
@mgifford see https://dkan.readthedocs.io/en/latest/contributing/code_of_conduct.html

**Comment by mgifford** [comment]
Can we add a GitHub reference? Just a CODE_OF_CONDUCT.md with that link.

**Comment by janette** [comment]
Documentation updated
