### ISSUE TITLE
Use EntityTypeManagerInterface declaration instead of EntityTypeManager (Nitpick)

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#4296]
### Current Behavior

It seems more approriate to use EntityTypeManagerInterface as declaration type for the entityTypeManager property in Drupal\metastore\Nodewrapper\Data.

Otherwise for example the [call to new Data in _metastore_search_is_dataset](https://github.com/GetDKAN/dkan/blob/2.x/modules/metastore/modules/metastore_search/metastore_search.module#L20) is complaining about the declaration type.

This surely is a nitpick, but since IDE is constantly reminding me on this ...

### Expected Behavior

no complaining about declaration type anymore

### Steps To Reproduce

let your IDE check the [call to new Data in _metastore_search_is_dataset](https://github.com/GetDKAN/dkan/blob/2.x/modules/metastore/modules/metastore_search/metastore_search.module#L20)

**Comment by paul-m** [comment]
Great idea. Let's find other places where we type hint the concrete class into a service, and change that to use the interface if it exists. That's best practice anyway.

**Comment by paul-m** [comment]
Thanks.

I think your nitpick is 100% correct, and we should change that. We should also be nitpicky and fix `NodeDataFactory` in a similar way. (Inject interfaces instead of concrete classes.) Go ahead and add that to the PR if you'd like.

**Comment by stefan-korn** [comment]
Okay, added `NodeDataFactory` and some other places too.
