### ISSUE TITLE
Modifying the auto-generated .ddev/.webimageBuild/Dockerfile

### ISSUE THREAD

**Issue by t2wang** [GetDKAN/dkan#4301]
I apoloogized in advance if this is not the appropriate place to post this question. I'm a student and I'm beginner to this open source project.

I would like to change the the Dockerfile in the .ddev/.webimageBuild/ directory.

I understand that it is auto generated, and I need to change the config.yaml file.

My goal is to modify the config file so that the generated Dockerfile would have a **_CMD ["setsid" "python" "filter.py" "&"]_** line added, but I'm not sure how to do this.

I have attempted to achieve the same result using hooks and post_start, but for some reason the process does not persist even though I specify it to run in the background.

Anything possible work-around? Thanks in advance!

**Comment by stefan-korn** [comment]
Isn't this something that's related to [DDEV](https://ddev.com/)? Maybe look here: https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage

**Comment by t2wang** [comment]
> Isn't this something that's related to [DDEV](https://ddev.com/)? Maybe look here: https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/#adding-extra-dockerfiles-for-webimage-and-dbimage

Thank you! I will look into this!
