### ISSUE TITLE
Theme with comma inside title

### ISSUE THREAD

**Issue by pepeluca97** [GetDKAN/dkan#4309]
### Current Behavior

Creating a theme with a comma or commas, the search api return empty.

### Expected Behavior

The search shoud return the dataset connected

### Steps To Reproduce

Creating a theme with commas and try using search.

**Comment by stefan-korn** [comment]
Would probably need some more details here.

You cannot create a theme (topic) with comma via the default widget in the dataset I suppose, see also #4056 . If you add a comma the widget will automatically add the topic without the comma. So probably it is not intended to use comma in there.

But still you can maybe change the theme (topic) later and add a comma to it. Did you do it like this?

And then what exactly is the problem? You are using the React Frontend for searching, or something else? Maybe add a screenshot.

**Comment by dafeder** [comment]
Going to close this as we haven't heard more. I believe select2 can be customized to not treat `,` as a separator, but I don't know that we'd provide direct support for that. Willing to review a more specific suggestion or PR @pepeluca97 but would generally want to go along with how this widget usually works in Drupal.
