### ISSUE TITLE
Datastore MySQL import - Change some class members from private to protected

### ISSUE THREAD

**Issue by stefan-korn** [GetDKAN/dkan#4330]
### Feature Description

I am using and providing a [module to extend the Datastore MySQL import](https://www.drupal.org/project/dkan_datastore_import_tweak). This works by annotating the factory service from datastore_mysql_import. This would be easier if the private members of the factory class can be changed to protected.

### Detailed Feature Description

see feature description

### Problem and Motivation

see feature description

### Potential Benefits

see feature description

### Target Audience

- [ ] End Users
- [ ] Developers
- [X] Administrators
- [ ] Other

### Possible Implementation

PR will follow

**Comment by paul-m** [comment]
👍
