### ISSUE TITLE
Error while installing DKAN on existing drupal v10.3.6

### ISSUE THREAD

**Issue by lakhalhassan** [GetDKAN/dkan#4339]
### Current Behavior

While trying installing DKAN module on an existing Drupal 10.3.6 ; PHP Version 8.3  I got this error: 

The website encountered an unexpected error. Try again later.

Error: Interface "Contracts\FactoryInterface" not found in include() (line 13 of modules/contrib/dkan-2.x/modules/metastore/src/Storage/DataFactory.php).
Composer\Autoload\{closure}() (Line: 427)
Composer\Autoload\ClassLoader->loadClass() (Line: 261)
Drupal\Component\DependencyInjection\Container->createService() (Line: 179)
Drupal\Component\DependencyInjection\Container->get() (Line: 197)
Drupal::service() (Line: 91)
metastore_entity_is_valid_item() (Line: 72)
metastore_data_lifecycle() (Line: 19)
metastore_entity_load() (Line: 397)
Drupal\Core\Entity\EntityStorageBase->Drupal\Core\Entity\{closure}() (Line: 395)
Drupal\Core\Extension\ModuleHandler->invokeAllWith() (Line: 396)
Drupal\Core\Entity\EntityStorageBase->postLoad() (Line: 319)
Drupal\Core\Entity\EntityStorageBase->loadMultiple() (Line: 47)
Drupal\block_content\BlockContentPermissions->blockTypePermissions()
call_user_func() (Line: 166)
Drupal\user\PermissionHandler->buildPermissionsYaml() (Line: 125)
Drupal\user\PermissionHandler->getPermissions() (Line: 136)
Drupal\user\PermissionHandler->moduleProvidesPermissions() (Line: 293)
Drupal\system\Form\ModulesListForm->buildRow() (Line: 196)
Drupal\system\Form\ModulesListForm->buildForm()
call_user_func_array() (Line: 536)
Drupal\Core\Form\FormBuilder->retrieveForm() (Line: 284)
Drupal\Core\Form\FormBuilder->buildForm() (Line: 73)
Drupal\Core\Controller\FormController->getContentResult()
call_user_func_array() (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 638)
Drupal\Core\Render\Renderer->executeInRenderContext() (Line: 121)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext() (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw() (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle() (Line: 53)
Drupal\Core\StackMiddleware\Session->handle() (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle() (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle() (Line: 32)
Drupal\big_pipe\StackMiddleware\ContentLength->handle() (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass() (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle() (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle() (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle() (Line: 741)
Drupal\Core\DrupalKernel->handle() (Line: 19)

### Expected Behavior

Installed Module

### Steps To Reproduce

Install DKAN on existing drupal instatallation

**Comment by stefan-korn** [comment]
How did you install DKAN? `modules/contrib/dkan-2.x/modules/metastore/src` looks a bit like you did not install via composer and thus you might miss composer dependencies like getdkan/contracts.

**Comment by lakhalhassan** [comment]
Thank you for your feedback.

True, I didn't intall it using composer, I tryed installing it using the classical way I knew since durpal 7 ;), it's been a long time I didn't use drupal.

So, I'm trying now using composer, I installed XAMPP on window and installed composer, then tryed this command : 

D:\XAMPP\htdocs>composer create-project getdkan/recommended-project onedd

This is what I got:

Creating a "getdkan/recommended-project" project at "./onedd"

In CreateProjectCommand.php line 424:

  Could not find package getdkan/recommended-project with stability stable.


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]

I guess it didn't work, I'm still trying to figure out what is the issue

If you have any step by step to doing it please share it with me

**Comment by stefan-korn** [comment]
Yeah looks like you need to do:

`composer create-project getdkan/recommended-project --stability dev`

like https://github.com/GetDKAN/recommended-project says.

seems that [installation manual is not exactly correct here](https://dkan.readthedocs.io/en/latest/installation/index.html#starting-a-new-dkan-project)

You can also add DKAN to an existing project like [this](https://dkan.readthedocs.io/en/latest/installation/index.html#adding-dkan-into-an-existing-project).

**Comment by dafeder** [comment]
Thanks @stefan-korn - @lakhalhassan just try `composer require getdkan/dkan`. 

@stefan-korn sorry, what are you saying is incorrect in the docs?

**Comment by stefan-korn** [comment]
@dafeder I suppose just
`composer create-project getdkan/recommended-project`
does not work (currently).
But
`composer create-project getdkan/recommended-project --stability dev`
works.

First command is mentioned in the installation instructions, second in the repo's README.

TO tried to install from the project template.

**Comment by dafeder** [comment]
Ah you are correct, oops. Will correct the docs. We are always using create-project in scripts rather than running it manually in shell, so just never noticed this. We should probably do tags to avoid this problem.

**Comment by lakhalhassan** [comment]
Thank you @stefan-korn and @dafeder  for you help

I executed the commande:  
composer require getdkan/dkan:2.19.9

and still got this error :

D:\XAMPP\htdocs\onedd>composer require getdkan/dkan:2.19.9
./composer.json has been updated
Running composer update getdkan/dkan
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires getdkan/dkan 2.19.9 -> satisfiable by getdkan/dkan[2.19.9].
    - getdkan/dkan 2.19.9 requires drupal/facets ^3.0@beta -> found drupal/facets[dev-3.0.x, 3.0.0-beta1, 3.0.0-beta2, 3.0.0-beta3, 3.0.x-dev (alias of dev-3.0.x)] but it does not match your minimum-stability.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by dafeder** [comment]
@lakhalhassan can you try with `--stability beta`

This is something we should probably address, we did not anticipate it being such a long wait for facets to come out with a stable 3.x release. Ideally DKAN should be installable with stability=stable.

**Comment by lakhalhassan** [comment]
Thank you for your help

I changed stability to beta and it's working now.

While testing the module I encountred some small issues: 
for the Configure Header: Add dataset button in the DKAN Datasets view, I thing it will be beter to add [site:base-url] token to  the link
`<div class="form-actions"><a class="button button--primary" href="[site:base-url]/node/add/data">+ Add new dataset</a></div>`

and the same issue for the link  "Add new data dictionary"

**Comment by dafeder** [comment]
Thanks @lakhalhassan I am going to close this issue. We will take a look at that, and feel free to submit a PR for the change.
