### ISSUE TITLE
Make filtered datasets shareable

### ISSUE THREAD

**Issue by swirtSJW** [GetDKAN/dkan#4349]
### Feature Description

Currently datasets have a great tool to be able to filter the results and see them immediately.  However, they lack the ability to share a link to the filtered dataset.  As a result we must share an unfiltered link and then give directions on how to add the filters.   It would be nice to be able to apply filters and then have a way to share them through support of query parameters or other mechanism 
![image](https://github.com/user-attachments/assets/e68fdad3-e8db-415d-a198-557b3392904e)

### Detailed Feature Description

This solution is not trivial in that each filter has three parts the field, the value, and the operator (=, <, >...) and query parameters typically only support 2 parts (field and value).  There are a few possible solutions

- `?field=value&field_op=equals` (if no field_op specified, defaults to equals) this is the most specific, but gets long very fast
- `?field=value~op` less long and more readable. 

### Problem and Motivation

Communicating data requires a way to make sure everyone is seeing the same thing.  Walking through the settings for a specific filter is tedious to describe and leaves the possibility that what I see will be different from what the person I am sharing it with sees.

### Potential Benefits

People, can explore, filter and then share their findings in a specific or trackable way.

It also allows for revisiting the findings (from say a bookmark or a hyperlink) over time to see if anything changed.

### Target Audience

- [X] End Users
- [ ] Developers
- [ ] Administrators
- [ ] Other

### Additional Context

I am not sure if supporting query params opens up to large of dos attack vector.

**Comment by swirtSJW** [comment]
Disregard this.  Apparently this already exists.... just not in my local implementation.  Thank you for supporting this.

**Comment by dafeder** [comment]
For people happening upon this later, here is an explanation for making complex API queries against the datastore API: https://dkan.readthedocs.io/en/latest/user-guide/guide_api.html#how-to-run-a-simple-query-against-a-dataset
