### ISSUE TITLE
Recline should get rid of null values when graphing data

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#440]
(Note: This is not blocker, just an enhancement recommendation.)

This CSV contains a wide range of performance indicators for 14 public schools. 

In this screenshot, there are blank spaces for some schools within certain scoring columns:

![screen shot 2015-04-13 at 6 27 42 pm](https://cloud.githubusercontent.com/assets/9059428/7126836/d449ab9a-e20a-11e4-9b87-6652c3603d8f.png)

When uploaded, the blank spaces become "0" values:

![screen shot 2015-04-13 at 6 30 33 pm](https://cloud.githubusercontent.com/assets/9059428/7126884/4879ed22-e20b-11e4-9c60-2c650d2e087e.png)

When the data is graphed, it makes it look like those schools received scores of "0" and are failing -- when in fact, the schools didn't have any scores at all.

![screen shot 2015-04-13 at 6 31 03 pm](https://cloud.githubusercontent.com/assets/9059428/7126903/88f17c76-e20b-11e4-9856-38e7d1d12f14.png)

The solution would be for Recline to recognize null values instead of assigning them a "0" value, and to prevent rows that correspond with them from appearing when those columns are graphed.

Ideally, in this example, the schools with null score values would not even appear on the graph.

**Comment by kimwdavidson** [comment]
Need to confirm this is still an issue.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
