### ISSUE TITLE
Home is repeated in Breadcrumbs

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#475]
The "Home icon" and "Home" are both listed in the breadcrumbs:

![screen shot 2015-05-27 at 6 39 47 am](https://cloud.githubusercontent.com/assets/512243/7836860/35d057dc-0449-11e5-94b3-0df1b18244d2.png)

It should be: (no 'Home'):

![screen shot 2015-05-27 at 8 20 52 am](https://cloud.githubusercontent.com/assets/512243/7836875/5204e74c-0449-11e5-8cba-3bf8a7b36dab.png)

**Comment by dafeder** [comment]
It looks to me like the links have been lost - the breadcrumbs are now just plain text. You can even see this in the screenshot above.

**Comment by willieseabrook** [comment]
We have found some issues with this. Do not merge this, please wait for a new pull request

**Comment by willieseabrook** [comment]
All items should be clickable except the current title: 

E.G for [home icon] > Datasets > This is my dataset title

[home icon] and Datasets should be clickable

**Comment by acouch** [comment]
It looks like this needs to be rebased with the updated Behat version.

**Comment by janette** [comment]
@dafeder CIVIC-507 is marked as done but the PR was closed without merging
https://github.com/NuCivic/dkan/pull/484

**Comment by chilic** [comment]
5 years! Awesome!
