### ISSUE TITLE
Make the resource teaser in the dataset page more modular and easier to override

### ISSUE THREAD

**Issue by drkloc** [GetDKAN/dkan#531]
There could be scenarios where people have custom fields and want to alter the rendering for the dataset page and we currently don't have a way of providing an easier way than copying the whole set of code and overriding it.

I'm talking about this -> https://github.com/NuCivic/dkan_dataset/blob/7.x-1.x/dkan_dataset.theme.inc#L52

For instance, the download all function is expose throw this theme function.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
