### ISSUE TITLE
Write brief plain-language definition of "federated data", add as a sidebar block to datasets with federated data

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#556]
Write brief plain-language definition of "federated data", add as a sidebar block to datasets with federated data.

Cross-referenced to HHS (https://github.com/NuCivic/healthdata/issues/310) but relevant to all DKAN instances using federated data.

**Comment by janette** [comment]
@stefaniefgray is this a client request or a product enhancement? Can you provide the definition?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
