### ISSUE TITLE
Identifier for data.json should be unique URL with uuid not just uuid

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan#561]
https://project-open-data.cio.gov/v1.1/schema/#identifier

`indentifier` should be http://examplel.com/api/3/action/package_show?id=1b39ad70-02b7-42df-92b8-e6b950e10da0 instead of 1b39ad70-02b7-42df-92b8-e6b950e10da0

**Comment by susisiman** [comment]
This is just a recommendation. Since datasets often live on multiple catalogs, we will continue to use UUID only. Closed due to inactivity. Feel free to open!
