### ISSUE TITLE
Commenting system for datasets

### ISSUE THREAD

**Issue by paolomainardi** [GetDKAN/dkan#59]
I don't know if you already planned for the next DKAN release, but it would be nice to have a pluggable commenting system for datasets, with the support for Drupal standard and external systems like Disqus.

**Comment by dafeder** [comment]
This is still an open issue. You can always enable Drupal comments or add the Disqus module, but we would like a more thought-out feedback system for all DKAN data portals. There have been some initial attempts and this is still very much on the roadmap. Perhaps including a data _request_ function in addition to just feedback on existing datasets.

**Comment by jvitello** [comment]
When this is worked on or added, a robust captcha should be added.

**Comment by susisiman** [comment]
Our roadmap contains feedback feature. Closed due to inactivity. Feel free to open!
