### ISSUE TITLE
@font-your-face: UI/UX - When a font is enabled, it breaks table borders.

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#599]
See screenshot:

![screen shot 2015-07-28 at 8 32 52 pm](https://cloud.githubusercontent.com/assets/9059428/8947673/b4deedba-356b-11e5-8fb8-5e08619b97fa.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
