### ISSUE TITLE
Pivot table implementation

### ISSUE THREAD

**Issue by paolomainardi** [GetDKAN/dkan#60]
As requested here: https://github.com/okfn/recline/issues/364 but still not implemented on Recline side.

Would be nice to integrate one of this JS pivot table implementations:
http://rjackson.github.io/pivot.js/
https://github.com/nicolaskruchten/pivottable

We are available to take in charge the development of this feature.

**Comment by copystar** [comment]
I also would love to see pivot tables in DKAN. Thanks for considering it!

**Comment by dafeder** [comment]
A note to catch up on what the state of the art in the CKAN / frictionless-data world is around this stuff. It looks like there is not much momentum around support for this in recline and I'm not sure it would be worth the effort to build.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
