### ISSUE TITLE
Improve wording for custom logo selection

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#603]
"Use the default logo" should not be automatically checked; browse button should be automatically shown.

It is confusing to new DKAN users that unchecking "Use the default logo" is what triggers the "Browse" button to upload a new logo. 

The "Browse" button to upload a new logo should be automatically shown, not triggered via checkbox.

![screen shot 2015-07-23 at 6 47 20 pm](https://cloud.githubusercontent.com/assets/9059428/8948211/928c0764-3572-11e5-80e8-a0f3c9839807.png)

**Comment by janette** [comment]
I think it would be better to just change the instructions: "Uncheck this box if you want to upload a custom logo"

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
