### ISSUE TITLE
DKAN header and slogan text should be included in dropdown list of selectors

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#604]
When you change the font selectors for your site, you have to manually input ".site-slogan, .site-name" to change the site slogan and site name.

They should just be included in the dropdown list, because they are important to the site's design and this is confusing to users who don't know CSS.

![screen shot 2015-07-23 at 6 50 02 pm](https://cloud.githubusercontent.com/assets/9059428/8949137/70bedbb0-357d-11e5-9318-28f736b4d4ac.png)

![screen shot 2015-07-28 at 11 03 54 pm](https://cloud.githubusercontent.com/assets/9059428/8949121/40fd3f0c-357d-11e5-9df2-d800f75398dd.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
