### ISSUE TITLE
Enhancement: Hero unit color selector should have color drop-down

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#605]
Some users may not know the hex code for the color they want.

Input should be able to support basic HTML colors (i.e. "yellow," "maroon," "darkblue" -- see list at http://www.w3schools.com/html/html_colornames.asp)

Input should also have a basic color dropdown of colors that match our Colorizer themes. Otherwise, users would have to go into Colorizer, copy the hex code of the matching color, and then return to the hero unit customization box and paste it in.

Extremely low priority but handy for theming!

![screen shot 2015-07-23 at 6 51 07 pm](https://cloud.githubusercontent.com/assets/9059428/8958431/c4f636a6-35d2-11e5-8b09-cd306bf56d92.png)

**Comment by janette** [comment]
This is a good idea, I would say the alternate built in color-scheme options should be revised and better thought out as most of them are not very good but with some tweaking they could be nice options.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
