### ISSUE TITLE
Enhancement: Colorizer needs a 'Save Scheme' option

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#608]
When creating a custom color scheme in Colorizer, there's no way to save your settings in case something goes awry.

The locks next to each color in the list are helpful, but not if you want to test a new scheme and then return to the old one.

If you have a custom color scheme and want to test a new color scheme, you cannot save the custom scheme before testing others. Even if you select another Colorizer scheme from the dropdown menu (i.e. "Firehouse" or "Lagoon"), and go back to "Custom," it loses all of the colors you inputted.

Users need an option to save custom color schemes with their own names, such as "Stefanie's Custom Scheme" or "Gold Scheme," etc.

![colorizer](https://cloud.githubusercontent.com/assets/9059428/8958941/dde52836-35d5-11e5-86fe-8f066b455f15.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
