### ISSUE TITLE
Improve font discovery UX

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#610]
It's not clear that these fonts are sourced from Google Fonts, and if a user does not feel like browsing through an extremely long list of fonts, they should have the option to access Google Fonts externally. (https://www.google.com/fonts)

For designers, it would take a very long time to browse through every font. Users should have an external link to the Google Fonts library, which allows for sorting by font type (sans-serif, display, handwriting, etc.) and allows for real-time font previews.

Help text with an external Google Fonts link should be provided.

![screen shot 2015-07-23 at 6 38 01 pm](https://cloud.githubusercontent.com/assets/9059428/8959256/c47c7df2-35d7-11e5-9131-b284c23316aa.png)

**Comment by janette** [comment]
Or we could update the module to fix the built in filters...

![browse_fonts___dkan](https://user-images.githubusercontent.com/314172/28170680-bb3c30c2-67ab-11e7-8397-7812e8d31b5e.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
