### ISSUE TITLE
UI/UX: Site name and slogan font size should be listed under 'Appearance' options

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#612]
As a user interested in using a cursive font for my site's design, I am frustrated by how small the slogan is. It is difficult to read.

Users should have the option to increase or decrease the size of the site's name and slogan.

![screen shot 2015-07-23 at 7 32 42 pm](https://cloud.githubusercontent.com/assets/9059428/8959508/35c7a30a-35d9-11e5-8ef6-3365eb9428c1.png)

**Comment by kimwdavidson** [comment]
Still considering this

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
