### ISSUE TITLE
UI/UX: Users should have option to change header sizes

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#614]
See related ticket: #612 

As a user who wants to use a cursive font for headers as part of my site's theming, certain headers become very small and hard to read.

I would like to be able to enlarge the headers in order for my site's font to be legible.

![screen shot 2015-07-23 at 7 38 10 pm](https://cloud.githubusercontent.com/assets/9059428/8959708/5ead70fa-35da-11e5-9170-62bf28215676.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
