### ISSUE TITLE
Gravatar needs to be phased out; use User Photos

### ISSUE THREAD

**Issue by stefaniefgray** [GetDKAN/dkan#616]
On a design and theming call last month, @janette and I discussed Gravatar integration and decided that it was no longer necessary. 

It rarely loads, it hasn't been popular in years, and it mostly turns sites tacky with the huge colorful patterns.

On my QA site, as an Editor, I had no way of unchecking the option to use Gravatar. Even after uploading my user photo, it stayed checked.

When I returned to my profile page, there were still Gravatar icons shown in the side bar and navigation bar. Nothing had changed. There is no way to see my User Photo. It's as if I never uploaded it at all. 

There is also no way within DKAN for me to start using Gravatar and upload a photo to it even if I wanted to.

Gravatar should be phased out, and the User Photo should replace the Gravatar icons on the user profile sidebar and in the navigation bar.

(Note: This has been replicated on multiple sites.)

![screen shot 2015-07-29 at 5 44 54 pm](https://cloud.githubusercontent.com/assets/9059428/8970778/955a4404-3619-11e5-83d3-6a44fa4964c3.png)

![screen shot 2015-07-29 at 5 40 16 pm](https://cloud.githubusercontent.com/assets/9059428/8970851/fd591f12-3619-11e5-8166-29e8b1764d07.png)

**Comment by dafeder** [comment]
Low priority - if we're not able to fix this quickly, save for next release.

Whenever it gets worked on, make sure that an expected result happens if the user does not upload a picture - do we get any broken images anywhere or even uglier default images?

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
