### ISSUE TITLE
Audit DKAN for missing HTML <title>s and add them 

### ISSUE THREAD

**Issue by teosibileau** [GetDKAN/dkan#641]
https://www.drupal.org/project/page_title

We should implement for our content types:

```
hook_page_title_pattern_alter(&$pattern, &$types)
hook_page_title_alter(&$title)
hook_page_title_settings()
```

So people can override titles in their own modules.

**Comment by dafeder** [comment]
The page_title module has been deprecated, but the real issue here is that there are several areas of DKAN where page titles are missing. Let's use the metatags module or just existing config options where appropriate but do a full audit and fix for missing titles across the software.

**Comment by susisiman** [comment]
Closed due to inactivity. Feel free to open!
