### ISSUE TITLE
Update to geofield 2.x

### ISSUE THREAD

**Issue by jacintocapote** [GetDKAN/dkan#653]
The module leaflet draw widget has a lot changes from the version on d.o. On d.o exists a branch to work with geofield 2.x. Should try to merge with the branch and then update geofield to 2.x version. Related from https://github.com/NuCivic/data-northdakota/issues/18

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
