### ISSUE TITLE
CSS regions used for tests and theming should be cleaned up

### ISSUE THREAD

**Issue by frankcarey** [GetDKAN/dkan#810]
Right now, there are a bunch of CSS regions used for testing, but many of them end up using the same css identifiers (".content") is a popular one for instance...

If we're going to use CSS identifiers for testing, the DKAN team should consider implementing consistent classes/ids for things like a "user" page, or a "group" page, etc. While it would be good for testing for them to be more specific and semantic, it would also be more semantic and perhaps cut down on the styling complexity. It would also be wise to set some standards for theming (don't use the built in views and panels classes for instance)

CSS regions used in behat are at: https://github.com/NuCivic/dkan/blob/7.x-1.x/test/behat.yml#L51

**Comment by kimwdavidson** [comment]
No longer an issue. Closing. Thanks!
