### ISSUE TITLE
Honeypot is triggered by site managers (and other non-anon roles)

### ISSUE THREAD

**Issue by frankcarey** [GetDKAN/dkan#811]
Honeypot isn't currently configured it would seem?  The only form that's set to use is the register form, and that is technically the same used when a site manager adds a user. Right now the timelimit is 5 seconds. Solution might be to update permissions so more roles bypass honeypot protection, or to use the honeypot API to only trigger that form for anonymous users.

**Comment by kimwdavidson** [comment]
Permissions have been updated. No longer seems to be an issue. Please reopen if this is still an issue. Thanks!
