### ISSUE TITLE
Publish dataset URL as landingPage in data.json by default

### ISSUE THREAD

**Issue by jensr** [GetDKAN/dkan#856]
Hi guys

I'm pulling the data.json from our site into another drupal site via feeds. Previously, accessURL field pointed back to dataset URL, but now seems to be missing from data.json (v 1.1 on 7.x.-1.10)
While I can get the UUID and create an API back to the json, I would simply like to provide a URL back to the DKAN site for users - this seems no longer possible??
accessurl now seem to be reserved for resources rather than datasets - is this correct?

Thanks

**Comment by dafeder** [comment]
Hello @jensr - yes, the correct place to expose the URL you're talking about is in landingPage - see https://project-open-data.cio.gov/v1.1/schema/#landingPage

This is an optional field - we may change this in a future release but for now you will need to enable it yourself by going to `/admin/config/services/odsm/edit/data_json_1_1` and setting that to `[node:url]`

**Comment by dafeder** [comment]
I'm going to change the name of this issue and leave it open as a possible future enhancement.

**Comment by jensr** [comment]
Thank you & sorry for slow reply. I'll add the token as suggested for now.

**Comment by kimwdavidson** [comment]
This was fixed in #1975 and PR #2032. Closing.
