### ISSUE TITLE
add autologout module to DKAN

### ISSUE THREAD

**Issue by sheldonrampton** [GetDKAN/dkan#862]
## Description

Some DKAN customers have requested the ability to configure their websites so they log people out after a specified time period. This requires installing and enabling the autologout contrib module for Drupal:

https://www.drupal.org/project/autologout

Let's add the autologout module to the DKAN codebase but leave it disabled upon installation. It can be enabled and configure it for DKAN websites that want this feature but does not need to be enabled otherwise.
## User Story

As an _administrator_
I want to _configure my website to log people out after a specified period of inactivity_
so that _I can remove the security risk of having user accounts remain logged in indefinitely_.
## Tests

  Scenario: Enabling autologout feature
    Given I am logged in as a user with the "administrator" role
      And I am on "sites/all/modules"
      Then I should see "Auto Logout."
## Acceptance criteria

As an administrator of a DKAN website, I can visit admin/build/modules to enable and then configure the autologout module.

**Comment by sheldonrampton** [comment]
Note: This ticket is related to NuCivic support ticket NCS-4.

**Comment by dafeder** [comment]
Let's consider this for addition to dkan_starter.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
