### ISSUE TITLE
Support larger geojson files

### ISSUE THREAD

**Issue by ergonlogic** [GetDKAN/dkan#877]
There is a 10MB limit set on geojson files. When we tried removing that limit, we discovered the reason for it: memory exhaustion running `json_decode` on even relatively small (~13MB) geojson.

The failure we were seeing took the form of a 500 error with the following error in Apache's error log:

```
PHP Fatal error:  Allowed memory size of 205520896 bytes exhausted (tried to allocate 72 bytes) in .../geo_file_entity/modules/geo_file_entity_geojson_bundle/geo_file_entity_geojson_bundle.module on line 73, referer: http://.../admin/structure/entity-type/geo_file/geojson/add
```

This looks like a common-enough issue with how large the memory foot-prints of arrays that PHP expands a json strings into. Perhaps we could look at parsing the json ourselves to extract the objects we're looking for, and process those serially. I don't know the depth of the usual geojson objects, but a library such as https://github.com/janeklb/JSONCharInputReader might help in that regard.

**Comment by acouch** [comment]
> There is a 10MB limit set on geojson files. 

Think this was designed for geojson that would be displayed on a map in the browser so the 10MB limit was the highest possible bound and should most likely be lower. GeoJSON can be uploaded as a resource. There is a PR to include a preview of the GeoJSON https://github.com/NuCivic/dkan/issues/738 if that is helpful.

**Comment by ergonlogic** [comment]
[This post](https://www.mapbox.com/blog/introducing-geojson-vt/) suggests that much larger datasets (100MB+) can be supported with the addition of a library that couldbe integrated with Leaflet or d3.

That said, I'm not too familiar with mapping, so I could be off-base here.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
