### ISSUE TITLE
DB Error when using Search API with Postgres

### ISSUE THREAD

**Issue by Dylan-A** [GetDKAN/dkan#884]
Hi,

After installing fully made dkan distro from https://github.com/NuCivic/dkan-drops-7 using Postgres SQL (9.3.10) as database, Any search on default datasets gives:

**SQLSTATE[42702]: Ambiguous column: 7 ERROR: column reference "item_id" is ambiguous LINE 8: GROUP BY item_id, w0) subquery ^**

![error](https://cloud.githubusercontent.com/assets/16041976/12606695/5e89790c-c4f5-11e5-827e-20f464af91e8.PNG)

The search functionality when using MySQL as database does not give any error

**Comment by dafeder** [comment]
Hi Dylan - thanks for reporting this. We don't test the distro on Postgres often (all of our dev and  production environments use mysql) so it may take a while to get to debugging this. For now I would suggest going into the search API settings and disabling/enabling the dataset index and re-indexing everything. Check the index pages in general to see if you're getting any warnings there. 

Also, if you are able to run an Apache Solr server that will let you bypass this issue and probably have better performance in your search. See: http://docs.getdkan.com/dkan-documentation/dkan-developers/solr-search

**Comment by kimwdavidson** [comment]
Closing. Let us know if you'd like to reopen. Thanks!
