### ISSUE TITLE
DKAN misusing private flag

### ISSUE THREAD

**Issue by rossjones** [GetDKAN/dkan#950]
At the URL http://opendata.cambridgeshireinsight.org.uk/api/3/action/package_show?id=c2db7c89-827e-4d34-8cf0-95241dfd6a4c the dataset is shown as private=True - but it is still possible for anybody to view the dataset at http://opendata.cambridgeshireinsight.org.uk/dataset/empty-homes

This makes harvesting problematic as it means that this dataset, when harvested, will not be shown in a CKAN instance where the private flag is respected.

**Comment by susisiman** [comment]
Closed due to inactivity. Feel free to open!

**Comment by susisiman** [comment]
Closed due to inactivity. Feel free to open!
