### ISSUE TITLE
Add support for other character encodings and provide validation warnings when encodings are not supported

### ISSUE THREAD

**Issue by achraf-jeday** [GetDKAN/dkan#964]
## Description

When I create a new resource using a file that is not utf-8 encoded and I go to the preview page for that resource I see incorrect characters.
## Acceptance Criteria
- Add support for other character encodings.
- Provide validation warnings when encodings are not supported.

**Comment by achraf-jeday** [comment]
[test_Shift-JIS.csv](https://files.zenhub.io/56d7083b527eafdc4df2acd9)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
[test_ISO-Latin-1.csv](https://files.zenhub.io/56d7083b527eafdc4df2acda)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)


I attached two files, one that's encoded in Shift-JIS and the other is encoded in ISO-Latin-1.

**Comment by achraf-jeday** [comment]
![incorrect_002](https://cloud.githubusercontent.com/assets/4772404/13465560/83747b7e-e096-11e5-904b-67561fa48d36.png)
![incorrect_001](https://cloud.githubusercontent.com/assets/4772404/13465561/837862de-e096-11e5-8dfe-a1170f2d8347.png)

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
