### ISSUE TITLE
Uploading a Windows CSV File

### ISSUE THREAD

**Issue by chrisodva** [GetDKAN/dkan#987]
As a DKAN content creator, I would like a warning in the UI reminding me to not use the "Windows Comma Separated File" format in Excel, because it results in a blank row after every existing row in the spreadsheet, which causes display and formatting inconsistencies in DKAN charts. Or, DKAN automatically ignoring the extra line breaks from the file would be good too, although I'm assuming that would be a lot more work than simply reminding users to use a plain csv file.

**Comment by acouch** [comment]
Closing this ticket as it has not been updated recently and is not on our near-term roadmap. Please re-open if you would like to discuss further or are actively working on it.
